### ISSUE TITLE
Problem:Multi async would block each other

### ISSUE THREAD

**Issue by sj82516** [caolan/async#1004]
Hey all, 
currently I use async parallel to handle db request and render in node js. 
However, I execute async from several routing would block all together. 
Ex. I have A,B,C three page. A run async.parallel 1,2,3 function; B->4,5,6; C->7,8,9  
Then user request page A -> B -> C, then log show {1,2,3} -> {4,5,6} -> {7,8,9}. 
Response is in order even though {7,8,9} run in shortest time. 
Although Node Js would receive requests asynchronizely, but async.parallel seems to block together. 
Here is my pseudo code:  
A.js
<pre>
var async = require('async');
var express = require('express');
var dbrequest = require('../dbconnection');
var async = require('async');
router.get('/', function(req, res, next) {
    async.parallel([
        dbrequest.func1,
        dbrequest.func2,
        dbrequest.func3,
    ],function(err, results){
    res.render('appDetail', { 
        ans1:results[0],
        ans2:results[1],
        ans1:results[2]
    })
}

B.js and C.js are similar.

**Comment by aearly** [comment]
`async.parallel` will return the results in the order the functions are listed, regardless of which function called its callback first.  Is that what you are asking?

**Comment by sj82516** [comment]
My question is : A.js B.js C.js all use async.parallel. 
They suppose to run independently. 
However, theses three async.parallel would block each other. 
Only when previous request async parallel function finish , the next request async function could run. 
![1](https://cloud.githubusercontent.com/assets/6858460/12249481/fb50aa1e-b8fa-11e5-9f47-8c9116cc4324.png)

**Comment by sj82516** [comment]
Sorry I found out that's my mistake.
There is no problem in async. 
Please delete this issue. 
Thanks OTZ

**Comment by aearly** [comment]
What was your mistake?  (so others searching for a similar problem could get some help if they read this)

**Comment by sj82516** [comment]
I run async to execute mysql db request. 
The mistake is I use only one db connection so all request stuck in order. 
That's why I suspect async problem.(So stupid....) 
Thanks for your attention. :)
