### ISSUE TITLE
Simple async eachLimit example throws range error?

### ISSUE THREAD

**Issue by keatz55** [caolan/async#1009]
First of all just want to say amazing job with this package.

I have some simple code:
```
async.eachLimit(lines, 5, function iterator(line, complete) {
    console.log(line)
    complete(null);
}, function done(err) {
  if(err) throw err;
    console.log('done yo!');
});
```
However, I keep getting the following error:
```
RangeError: Maximum call stack size exceeded
```

**Comment by ex1st** [comment]
@keatz55 https://github.com/caolan/async#common-pitfalls-stackoverflow

**Comment by jonmackenzie** [comment]
url update:  https://caolan.github.io/async/

(it's pretty much right at the top, "Common Pitfalls")
