### ISSUE TITLE
Shouldn't `iterator` be called something else – e.g. `operation`?

### ISSUE THREAD

**Issue by behrangsa** [caolan/async#1011]
In:

### each(arr, iterator, [callback])

The second argument is not the iterator. `each` itself is the iterator. The second argument is an operation that the iterator perform on each and every member of the passed array, `arr`.

Am I missing something here?

**Comment by aearly** [comment]
Our nomenclature is a bit weird.  All these examples predate the official iterator spec.  It's hard to pick a better word --- `taskFn`, `operation`, `asyncFn`, `iteratingFn`, etc...

To make things more confusing, we're going to add support for ES6 iterators in addition to plain arrays for functions like `each`.   And then there's the `async function () {}` syntax on the horizon...

**Comment by megawac** [comment]
[`iteratee`](https://en.wikipedia.org/wiki/Iteratee) is the technically correct term

**Comment by aearly** [comment]
The benefits of having a contributor who still remembers his CS!  Should we change the docs across the board to use `iteratee`?

**Comment by behrangsa** [comment]
I would say yes, let's use `iteratee`.

**Comment by crispen-smith** [comment]
For what its worth +1, Aldo please let me know if I can help with this change.

**Comment by megawac** [comment]
@crispen-smith make the pull request if interested otherwise me or Alex will whenever we have some spare time

**Comment by crispen-smith** [comment]
I'll submit in the next few days.

**Comment by crispen-smith** [comment]
PR Submitted.

**Comment by aearly** [comment]
Closed via #1021
