### ISSUE TITLE
async.asyncify doesn't work as a task to async.auto

### ISSUE THREAD

**Issue by myaskevich** [caolan/async#1013]
async version `1.5.2`

I've been trying to make the following code work:

```javascript
return async.auto({
  userObject: async.asyncify(function () {
    return userService.get(userId);     // returns a Promise
  }),
  emailAddress: function (done, results) {
    ...
  }
}, function (done, results) {
  ...
});
```

I get this error:

```
Unhandled rejection TypeError: callback is not a function
    at /home/myaskevich/Projects/paralect/timeraven/node_modules/async/lib/async.js:1242:21

```

It should work for `async.waterfall`, `async.compose`. Does it also make sense to make it work for `async.auto` as well?

Thanks for your reply.

**Comment by ex1st** [comment]
Because asyncify await callback as a last argument, but in auto "task" it a first argument and last - result.

**Comment by aearly** [comment]
Yeah, we're going to fix the order of the args for `auto` tasks in the next major release.  `asyncify`ed functions should work then.
