### ISSUE TITLE
Is it possible to know how many of the supplied functions got successfully executed.

### ISSUE THREAD

**Issue by GolfRider** [caolan/async#1014]
Hi,

Is there a way to know how many of the supplied functions got executed successfully in waterfall/parallel method ?  

For ex:
async.parallel([
    function1(){ ... },
    function2(){ ... },
    function3(){ ... }
], callback);

If function3 fails, is it possible to know only the first 2 functions got executed successfully...?

Thanks

**Comment by Gobie** [comment]
use some kind of state, which all functions have access to or use https://github.com/davepacheco/node-vasync

**Comment by aearly** [comment]
Yeah, you'd have to keep track of that state yourself.  However, I would challenge you to structure your program so that kind of state doesn't matter whenever possible.

Related: #749
