### ISSUE TITLE
Elephant in the room: the upcoming async keyword

### ISSUE THREAD

**Issue by devinus** [caolan/async#1017]
Any thoughts on what example code using async is going to look like after the `async` keyword is universal?

**Comment by aearly** [comment]
This was discussed a bit in #956 .  I think we're going to aim for interop with functions that return promises (e.g. what async functions implicitly do).  You'd be able to use an `async` function in place of a regular callback-using function.  Async would then be useful in bridging the gap between async/await/Promise-style code and callback-style code.

**Comment by aearly** [comment]
This is a bit clunky, but it would work today, since `asyncify` adapts functions that return promises:

```js
async.map(someArray, async.asyncify(async function doSomething(item) {
  var foo = await something(item);
  foo.bar = "whatever";
  return foo;
}), callback)
```
