### ISSUE TITLE
Event handlers getting removed in some situations?

### ISSUE THREAD

**Issue by bgSosh** [caolan/async#1024]
Hi, 

I'm not sure what's going on here, so if anyone could explain I'd be very appreciative. I noticed that in some situations when using async with streams and error event handers, I'd get unhandled errors being thrown, as the error event handlers didn't seem to be registered.

I've tried to reduce it to the minimal scenario.  It seems to be when using async.series, if there is a synchronously-called-back function, followed by a function which nests it's code in a setImmediate (or ensureAsync), then the error handlers are ignored.  E.g.

```
   var dummyReadStream = fs.createReadStream('doesNotExist.txt');

   async.series([

           function(cb) {  //Synchronous series function
               cb();
           },
        
          function(cb) {
               setImmediate(function(){  //process.nextTick does not cause the problem
                   doSomethingWithStreamThatInvolvesErrorEvents(dummyReadStream, function(err) {
                       cb(err);
                   });
               });
           }

       ],
       function(err) {
           if(err) { logger.error(err);}
           process.exit(0);
       }
   );



   function doSomethingWithStreamThatInvolvesErrorEvents(readStream, callback) {

       readStream.on('error',  function(err){ callback(err); });

       var writeStream = fs.createWriteStream('test.txt');
       writeStream.on('finish', function(){ callback(); });
       writeStream.on('error',  function(err){ callback(err); });
       readStream.pipe(writeStream);
   }
```

This results in an unhandled global error (that the source file doesn't exist).  Remove either the first series function, or the setImmediate, and the error handlers work (and no unhandled error is thrown).

Can someone please explain this behaviour?

Thank you.

**Comment by aearly** [comment]
The error is happening before you attach the handler in `doSomethingWithStreamThatInvolvesErrorEvents`.  `nextTick` and sync execution are fast enough that the handler is attached in time.
