### ISSUE TITLE
facility to ignore second firing of second callback

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1026]
say we are using a async.parallel call like so:

```js
async.parallel({
 'a': function(cb){

        var client = require('socket.io-client')('http://localhost:3000');
        client.on('connect', cb);
        client.on('error', cb);

  }
}, function complete(err){

});
```

TMK, if there on 'error' callback gets called after the connect cb, async will throw a real error, saying double callback etc. But surely there is a usecase for ignoring the second callback. Is there an option or setting with async to ignore the second callback just use the result of the first for any async.parallel task etc?

thanks

**Comment by aearly** [comment]
In cases like these I use [`_.once`](https://lodash.com/docs/#once) :

```js
async.parallel({
 'a': function(cb){
        cb = _.once(cb)

        var client = require('socket.io-client')('http://localhost:3000');
        client.on('connect',cb);
        client.on('error',cb);

  }
}, function complete(err){

});
```

**Comment by ORESoftware** [comment]
thanks, unfortunately that won't work for me, because I am creating a library where the users of the lib will be inputting the callback functions

the way I have it now, is mapping each callback to a promise, but that means I have to use Promise.all instead async.parallel

I do think there should be an option for this! I am a big fan of this lib, but I think there should be an alternative to using _.once, really

**Comment by aearly** [comment]
Why wouldn't it work?  `_.once` wraps the supplied callback and creates a new function -- it doesn't modify the passed callback.

**Comment by ORESoftware** [comment]
yeah, but I cannot rely on the users of my lib to not forget to use _.once or similar

**Comment by aearly** [comment]
Wouldn't you use `_.once` internally in your lib?  I'm a bit unclear as to why you can't wrap user-supplied callbacks.

**Comment by ORESoftware** [comment]
I guess you're right I can just wrap the user supplied callbacks :)
