### ISSUE TITLE
async.eachSeries go back one iteration?

### ISSUE THREAD

**Issue by tyronedougherty** [caolan/async#1031]
My current project requires an async loop that occasionally must go back to the previous iteration and perform it again. Basically what I'm asking is if there is a way to do the opposite of nextLoop(), something like a previousLoop() function?

Would appreciate it if someone knows if this is possible. Thanks!

Code example:
```
async.eachSeries(array, function(val, nextLoop, previousLoop){
   if(val==='something') nextLoop();
   else previousLoop(); //Is it possible to do this somehow?
}, function(){
   console.log('Completed');
});
```

**Comment by aearly** [comment]
We don't offer anything like that currently.  The closest thing is `async.retry`.  It is a bit of non-standard control flow.
