### ISSUE TITLE
Question Async Series, Object Sequence Nodejs

### ISSUE THREAD

**Issue by 360disrupt** [caolan/async#1032]
Regarding:
https://github.com/caolan/async#seriestasks-callback

1) It runs in series if it is an array:
`Run the functions in the tasks array in series, each one running once the previous function has completed.`
2) Objects don't have a specified order
`The mechanics and order of enumerating the properties is not specified.`
3) It is possible to user `series`with an `object`
`It is also possible to use an object instead of an array.`

On my tests it always runs in the same sequence as I declare the functions in the object. 

# Question:

1) Does it reliably run in sequence if the functions are defined in an object (instead of an array)? Because I need a reliable order, but I want to keep the nice formatted callbacks.
2) If not what is the use case, because than it would be a slower version of async.parallel?

**Comment by aearly** [comment]
If an object is passed to `series`, it will just use whatever order is returned by `Object.keys`.  In node/v8, this is fairly stable -- it's usually the same as the order defined in the object literal, up to about 30 items.  Other JS engines may vary.  If you really need to rely on the order, use an array.  The order of keys is technically undefined behavior in Javascript.

Allowing using an object in `series` is really just an artifact of the implementation.  In most cases, you'd want to use an array, or something like `waterfall` or `auto`.

**Comment by 360disrupt** [comment]
Ok, thx, good to know.
