### ISSUE TITLE
Transform and Reduce argument order

### ISSUE THREAD

**Issue by megawac** [caolan/async#1043]
See https://github.com/caolan/async/pull/892 for context

I am for `async.reduce(arr, iteratee, [accumulator,] callback)`

/cc @aearly @qsona @suguru03

**Comment by qsona** [comment]
I'm +1 for `async.reduce(arr, iteratee, [accumulator,] callback)`. :100:

**Comment by suguru03** [comment]
+1
I agree. Thank you for notification!

**Comment by megawac** [comment]
I'm having second thoughts as I started writing test cases.

It's more logical I think to write

```js
var arr = [....]

async.transform(arr, {}, function(memo, v, k) {
   memo[k] = v;
    cb();
}, function() {
    ....
}
```

then

```js
var arr = [....]

async.transform(arr, function(memo, v, k) {
   memo[k] = v;
    cb();
}, {}, function() {
    ....
}
```

**Comment by aearly** [comment]
Yeah, the way it is now is easier to parse visually when you have an inline iteratee.  I'm not sure what we should do here.

**Comment by megawac** [comment]
I think we should err on the side of no breaking changes honestly

**Comment by aearly** [comment]
Ok, then maybe we should keep the args ordering for `transform` and `reduce` as-is.
