### ISSUE TITLE
Detect iteratee callback function does not take an error parameter

### ISSUE THREAD

**Issue by meuserj** [caolan/async#1044]
The documentation indicates that the callback function parameter to the iteratee function is expecting an error as the first parameter and the truth value as the second function. After banging my head trying to figure out why it wasn't finding the obviously correct value, I discovered that it is actually expecting the first parameter to be the truth value.

**Comment by meuserj** [comment]
Oh, the overall callback also does not have an error field passed into it.

**Comment by megawac** [comment]
Yeah, we're working on fixing this inconsistency in the next version (see https://github.com/caolan/async/pull/774)

**Comment by megawac** [comment]
Fixed in https://github.com/caolan/async/pull/1028
