### ISSUE TITLE
Feature request: run all function for "each" even theres an error

### ISSUE THREAD

**Issue by benhk2005** [caolan/async#1046]
I would like to have an "each" function will loop through the the array passed in the "each" and run though all of them even though there are error in one/more of the functions array. Thanks :smile:

**Comment by aearly** [comment]
We're going to add something similar to this in #1012 .  You'll be able to do something like:

```js
async.map(arr, async.reflect(iteratee), function (err, results) {
  // results[0].value is the results
  // results[1].error is the error, if it occurred
});
```
