### ISSUE TITLE
Using callback only to indicate wait-state, not passing anything as result

### ISSUE THREAD

**Issue by akoskm** [caolan/async#1056]
Hello!

I've asked this on SO but this might be more appropriate place to search for answers. I feel like I'm abusing the callback function only to indicate that there is a wait state:

```js
var calls = [];
var projects = _.each(projects, function (p) {
  calls.push(function (callback) {
    // find the list of phases associated with this project
    Phase.find({ project: p._id }, function (err, doc) { 
      if (err) {
        callback(err);
      } else {
        p.phases = doc;
        callback();
      }
    });
  })
});
```
As you can see, I'm assigning the result of the lookup directly to `p` instead of passing it to `callback()`. In this case, the `parallel` code is simple as:

```js
async.parallel(calls, function (err) {
  workflow.outcome.projects = projects;
  return workflow.emit('response');
});
```

If I would pass the `phase` to every callback then in `parallel` I would have a list of phases without projects. So I should iterate over them and over projects to find the appropriate project for every phase. Which obviously seems much more complicated then this solution.

Is there something wrong with this approach?

**Comment by aearly** [comment]
There's nothing "wrong" with your approach, it will work fine.  There is room for improvement, though.

Whenever you're using `_.each` and just pushing to an array at the end, it's screaming to be refactored in to `_.map`:

```js
var calls = _.map(projects, function (project) {
  return function (callback) {
    // find the list of phases associated with this project
    Phase.find({ project: project._id }, function (err, doc) { 
      if (err) {
        callback(err);
      } else {
        project.phases = doc;
        callback();
      }
    });
  };
});
```

But then, seeing as you're creating a list of functions to pass to `parallel`, you can just use `async.map` directly:

```js
async.map(projects, function (project, callback) {
  // find the list of phases associated with this project
  Phase.find({ project: project._id }, function (err, doc) { 
    if (err) {
      callback(err);
    } else {
      project.phases = doc;
      callback(null, project); // <-- have to callback with the value here
    }
  });
}, function (err, projectsWithPhases) {
  workflow.outcome.projects = projectsWithPhases;
  return workflow.emit('response');
});
```

A bit more concise,  and following with the spirit of async more.

**Comment by akoskm** [comment]
Thanks for the explanation and the examples. I'll leave the link to the SO discussion here because it contains an answer which solves my problem + greatly optimizes the whole lookup process http://stackoverflow.com/a/35929075/407466.
