### ISSUE TITLE
Timeout individually for each request

### ISSUE THREAD

**Issue by rcdiaz** [caolan/async#1059]
I  want to make several requests with a web scraper and want you if you do not return within the time limit returns {}
as you can do this with the timeout?

My code is:

```js
async.parallel(listTask,function(err, results){
            if (results){
                res.send(results);
            }
        });
```

Thanks

**Comment by aearly** [comment]
Yeah, you should be able to do this with `timeout` once 2.0 lands:

```js
async.parallel(async.timeout(60 * 1000, listTask), function(err, results){
    if (results){
        res.send(results);
    }
});
```

**Comment by rcdiaz** [comment]
ah ok, thanks!!
