### ISSUE TITLE
Feature Request: untilLimit

### ISSUE THREAD

**Issue by AminaG** [caolan/async#1063]
- Repeatedly call `fn`  x times in parallel, until a condition meet.

**Comment by cbou** [comment]
+1 and whilstLimit

**Comment by aearly** [comment]
Hmnn, I'm not sure if I like the idea.  What happens if you're running 5 tasks in parallel, and the first one that calls its callback, satisfies the condition?  Then you get 4 other callbacks calls that may or may not satisfy the condition whose results are ignored.  Sounds pretty inefficient, and seems like it will cause bugs wherever it's used.  What would be the concrete uses for this?

**Comment by AminaG** [comment]
I want to do a heavy task on the DB. and run millions of queries.
The input came by stream (I don't know in the beginning how many queries should be).
The DB can handle 10 queries in the same time.

I want to run the task maximum 10 times in parallel. Every time on task finish, our task start. until a condition meet, and no new tasks will start.

**Comment by aearly** [comment]
So, say you have this timeline with a theoretical `untiLimit`:

1. Kick off 10 DB queries
2. 5 queries finish, the condition is not met
3.  5 new queries are started
4. The 6th query to respond, calls-back with a result set that satisfies the `untilLimit` condition
5. The main `untilLimit` callback is called
6. The 7th through 15th queries respond, with result sets that are discarded.

So it took you 6 queries, to get the result you wanted, but, in total, you kicked off 15 queries.  60% of your DB queries were wasted.

Now imagine you weren't doing queries, but inserts or updates.  Now you have data being added (or deleted) that isn't obviously reflected in your control flow.

Is this what you want?

**Comment by AminaG** [comment]
So what you suggest?​

**Comment by aearly** [comment]
Just using `until` or `whilst`, which execute 1 step at a time.

**Comment by AminaG** [comment]
it will be much slower, if I can run 10 at the same time, why run 1 at a time

On Mon, Mar 21, 2016 at 11:18 PM, Alex Early < notifications@github.com > wrote:
Just using until or whilst , which execute 1 step at a time.

**Comment by aearly** [comment]
I think I already outlined why you would would want to run 1 at a time.
Would it really be faster to run 10 at a time if you're polling for some
condition?

**Comment by AminaG** [comment]
I still sure that IT will be useful in some cases.

Here another example:

I want to send for example email to all my users (2M). My sever give me the result one by one by using Stream.  The email server limit me to 10 emails per second.

```
connection.query('select email from users')
.pipe()
.stream(Stream.Transform({
objectMode:true,
transform:function(object,info,callback){
    // I want to run the sendEmailToAsync, and do not wait until it finish.
   // The callback will run, when `sendEmailTo` will START.
   // This is sign to the Stream that we can continue to get the next email.
  //  Every time I start sending an email we pooling another email.
  //  If there are more than 10 emails sent in background, do not start to send new emails.
    sendEmalToAsync(object.email,callback)
})

sendEmailTo=function(destination,callback){
    var success=doSomeThingHeave();
    // When we finish, another email can be sent.
    callback()
}

// Run the function again and again. maximum 10 times in parallel. 
sendEmailToAsync=require('async').untilLimit(sendEmailTo,10)
```

**Comment by AminaG** [comment]
Maybe the `queue` is good place for it.
The problem is that I don't want to push 1M functions to the `queue`. I want to push new tasks, only when previous tasks finished.

**Comment by aearly** [comment]
`mapLimit`/`eachLimit` would also be an option in that case, in addition to `queue`.

**Comment by AminaG** [comment]
eachLimit not.
eachLimit get an array in the begining of all the items.
In my case, I don't have an array.
And I don't want to hold in array all the items, it can be millions.
It similar to eachLimit, but it should work in array that items added to it
on-the-fly

**Comment by aearly** [comment]
That is the canonical use-case for a `queue`, then.

**Comment by AminaG** [comment]
But if I use `queue`, the `queue` will hold all the functions in its
memory.

**Comment by aearly** [comment]
No it wont -- it re-uses the worker function, and splices items out of the task list array as they are processed.

**Comment by AminaG** [comment]
I talk before they process.
The MySQL server, gives me records.
I want to get 10 records, and send them to `queue`
Every time a process complete, I get a new record from the db and send to
queue.

Using this method. My app will keep in memory only 10 records at the same
time.
I will use async to process 10 records at once.

In your idea, the `queue` need to keep in memory millions of records until
they processed

**Comment by aearly** [comment]
No -- a queue will begin to process items as soon as they are pushed to it, and remove references to them as soon as they are finished processing.

At any rate, I don't think there is a good use case for `untilLimit`, and there are some fundamental flaws with the idea.

You are welcome to experiment with your own control flow outside of Async.

**Comment by dtruel** [comment]
@aearly I am dealing with this same issue.  It looks like your concern with implementing it is that the 5 operations you run may somehow change the outcome of the continue test function.  However in many cases this just doesn't happen.  As @Aminadav says, this is not the case for a function that handles db records.  The reason is the truth test would simply return whether there was another item in the DB cursor to process.  It will process up to X at a time.  Processing database records isn't going to affect the number of records in the cursor.

Queue just doesn't seem like the right structure for this because it will empty quickly before all records have been inserted.  Then you have to keep track of how many times drain has been called.

**Comment by dtruel** [comment]
I ended up writing the following code.  Hopefully it helps somebody

```javascript
var usersCursor = Users.find({},{_id:1});
var numInProgress = 0;

function doRecord(next){
    usersCursor.next().then((user) => {
        console.log("record is ", user);
        exec(`/usr/bin/php do-script --id=${user._id}`, (e, stdout, stderr)=> {
            if (e instanceof Error) {
                console.error(e);
                throw e;
            }
            console.log('stdout ', stdout);
            console.log('stderr ', stderr);
            next();
        });

    });
}

function checkIfNextRecord(next){
    usersCursor.hasNext(function(err, result) {
        if(err){
            next(null, true);
        }
        next(null, !result);
    })
}

function start(action,testFunc,done, concurrency){
    var self = this;
    var numInProgress = 0;
    var stop = false;

    function next(err){
        if(err){
            throw err;
        }
        itemComplete();
    }
    function itemComplete(){
        --numInProgress;
        testFunc(testFuncComplete);
    }
    function testFuncComplete(err, finished){
        if(finished){
            stop = true;
            if(numInProgress == 0){
                console.log("done")
                done();
            }
            return;
        }
        processItem();
    }
    function processItem(){
        setTimeout(() => {
            ++numInProgress;
            action.call(self,next);
        },0)
    }
    for(var i = 0; i < concurrency; ++i){
        processItem();
    }
}

start(doRecord,checkIfNextRecord,function(){
    db.close();
},2);
```
