### ISSUE TITLE
A solution for stoping a flow after an early exit

### ISSUE THREAD

**Issue by Herobs** [caolan/async#1064]
There are a strong requirement that stop a flow normally instead of call callback with a fake err. I find a solution from [restify](http://restify.com/):

> You can pass in false to not error, but to stop the handler chain.

So only `null` to indicate a error, and `false` for normal terminal.

`callback(false)` will stop the flow, but won't active error handle like `if (err) console.log(err)`.

**Comment by aearly** [comment]
Hmnn, this is very intriguing!  I like that there is precedent in restify.  It also seems like `false` might be a good to use -- most people pass `null` or `undefined`.  There is a bit of symmetry with how returning `false` in `_.each` also breaks the iteration.

**Comment by aearly** [comment]
@megawac What do you think about this?

**Comment by megawac** [comment]
Works for me (in a major bump) - would be nice for the `createTester`
implementation as it will have an improved method of terminating `*Series`
and `*Limit` based iteration

**Comment by aearly** [comment]
Yeah, I agree, we should save it for the next major.  The breaking change we made with predicate-style functions (e.g. `some`, `filter`) would make this change cause extra confusion as people migrate since people would be passing `false` as the first arg.

**Comment by wjagodfrey** [comment]
Not having this is very inconvenient. I support the use of `cb(false)` - it's what I had expected to exist when first using this module.

**Comment by megawac** [comment]
Think I will be hammering on some of these breaking changes over the weekend.

@hargasinski @aearly any thoughts on a 3.0 timeline? December perhaps?

**Comment by aearly** [comment]
Do we have any stats on how widely used v2 is? I wouldn't want to have more breaking changes for people to evaluate while most people still haven't upgraded.

**Comment by hargasinski** [comment]
We should probably do a minor 2.1 release with the changes applied in #1261 and a non-breaking fix for #1293 before 3.0. The docs will also get updated with the changes in PRs, such as #1263, #1271, and #1280, which will be helpful.

@aearly, that's good point. 2.0 will have been released for 6 months in December. Should we assume that will be enough time for most users to update? We could use the changelog to write a migration guide in the Wiki for 1.5 to 3.0.

**Comment by megawac** [comment]
This is now somewhat possible with `2.1.1` by returning `async/internal/breakLoop`

**Comment by stephent** [comment]
@megawac is there a link to any documentation for this (async/internal/breakLoop)? Not seeing anything on the site so far.

**Comment by aearly** [comment]
I'd be hesitant to use it, as we are not fully decided that this is how we want to handle early exits.  We could change this later,  breaking your code.

**Comment by aearly** [comment]
<libraries.io> has some great version stats: https://libraries.io/npm/async/usage

I broke down the percent of `<`/`>` v2.x  [here 📈 ](https://docs.google.com/spreadsheets/d/1pQ3k4SDAuSBoifWCOkj7zz1YNSJlpECSHFDDKhwdFxQ/edit?usp=sharing)

20% of dependents are v2.0+.  (v1.5.2 is our most widely used version, though, ~22%).  v2.0 has been in the wild for a year.  I think we can start thinking about v3.
