### ISSUE TITLE
How use async in Angular

### ISSUE THREAD

**Issue by jairoGilC** [caolan/async#1065]
Hi I want use this library in Angular but I'm not sure if it's possible because I can find Angular dependency to inject

**Comment by aearly** [comment]
How are you loading other libraries in your project?

Async is available on npm, bower, as a standalone script, and many other package managers.

**Comment by skeet** [comment]
@jairoGilC If you include the async lib it will be available on the $window object:

```
$window.async.each(things, function(thing, callback) {
   // Do stuff
   callback();
}, function(err) {
   // Do more stuff
});
```

**Comment by aearly** [comment]
This seems to be more of an Angular question than an Async question.
