### ISSUE TITLE
`AutoInject` has some problems

### ISSUE THREAD

**Issue by suguru03** [caolan/async#1068]
`autoInject` is very wonderful and interesting!
But I found some problems about it when I use array tasks.

```js
async.autoInject({
    task1: function(cb) {
        cb(null, 1);
    },
    task2: ['task3', function(task3, cb) {
        console.log(task3); // 3
        cb(null, 2);
    }],
    // 1
    task2_1: ['task3', function(cb) {
        console.log(cb); // 3
        console.log(arguments[1]); // [function]
        cb();
    }],
    // 2
    task2_2: function(task3, cb) {
        console.log(task3); // 3
        cb();
    },
    // 3
    task2_3: ['task1', 'task3', function(task3, task1, cb) {
      　console.log(task3, task1); // 1, 3
        cb();
    }],
    // 3'
    task2_4: ['task3', function(task1, cb) {
        console.log(task1); // 3
        cb();
    }],
    task3: function (cb) {
        cb(null, 3);
    }
}, done);
```
First,  `task2_1` doesn’t work. Because, if you want to use array tasks, you have to use a function which the argument length is same as task length.

Second, `task2` and `task2_2` give same results. If you want to get result like `task2`, you don’t have to use array tasks. You will use `task2_2` in reality.

Third, `task2_3` doesn’t inject it. I might use injection even if I use array tasks, like `task2_4`.

I changed [`autoInject`](https://github.com/suguru03/neo-async/blob/master/test/controlFlow/test.autoInject.js#L112-L166) to inject even if I use array tasks because I want to solve those problems.
How do you think about it?

**Comment by aearly** [comment]
I would call `task2_1` an error -- the number of string args needs to match the number of parameters in the task function (plus the callback).  Otherwise, there's no way to tell which argument is the actual callback.

`task2` and `task2_2` will work as expected -- you can use the array-style task form, even if you don't need to.

`task2_3` will pass the args as in `task1`, `task3` order, even though the function signature is contradictory.

BTW, there are some differences in how we've implemented `autoInject` versus how its implemented in `neo-async`.  We already support array-style tasks.

**Comment by suguru03** [comment]
Thank you for your reply.
Firstly, I expected the callback function is always injected.
Does it mean that the callback function is injected when the task is just a function?

**Comment by aearly** [comment]
I think you misunderstood `task2_1` a little bit.  Of course you would still always pass a callback to the task function.  The problem becomes that there's no good way to tell which of the args passed *to the task function* is the callback.  The dependency on `task3` contradicts that the task function only takes in a single argument.

**Comment by qsona** [comment]
@suguru03 I don't know whether `async.autoInject` need to support array-style tasks (because `async.auto` already exists), but I think `async.autoInject` should not do name-based injection if the arg is passed as array. If we do it, supporting array-style is almost meaningless.

**Comment by qsona** [comment]
And I feel supporting array-style tasks is natural because it is same as AngularJS style. 

Consider the following case. We may want to use both an injecting style and an array-arg style.

```
// a common function
function anAsyncFn(arg, cb) {
  console.log(arg);
  cb();
}

async.autoInject({
    task1: function(cb) {
        cb(null, 1);
    },
    task2: function(task1, cb) {
        console.log(task1); // 1
        cb(null, 2);
    },
    task3: ['task2', anAsyncFn], // logged '2'
```

**Comment by suguru03** [comment]
Certainly, I understood.
Thank you very much!

**Comment by aearly** [comment]
Yeah, I also think the array-style task is also important if you want to use partially-applied  or otherwise wrapped task functions:

```js
async.auto({
  task1: function (cb) { ... },
  task2: ["task1", async.retryable(5, function (arg1, cb) {
    //..
  }]
},done);
```

It's also essential if you're going to be minifying your code for the browser (the main reason Angular supports array-style DI).
