### ISSUE TITLE
async.queue with maximum number of total jobs

### ISSUE THREAD

**Issue by kelthuzad** [caolan/async#1069]
I have the following requirements that I cannot implement directly with a simple async.queue:

- I need an async.queue because I want to execute jobs that will be created from different asynchronous modules at different times
- I know the number of jobs that will eventually be pushed to the queue
- I need a callback that is called after all jobs in the queue are executed, but queue's empty/drain hooks are no help because the queue can run empty multiple times, as jobs are added asynchronously. I want a callback that is only called after all jobs are done.

=> I need a queue that accepts the number of jobs that will be pushed to the queue as additional parameter, keeps track of the number of completed jobs and calls a queue-complete-callback when the required number of jobs were completed.

I implemented my own solution based on async.queue, but it would be nice to have this as an official async feature.

Would you be interested in having this feature or do you consider it a too special case?

**Comment by aearly** [comment]
Sounds a bit niche to me.  It's a bit odd that the queue would know beforehand how many items it would run.

**Comment by kelthuzad** [comment]
This is probably really a niche requirement.. 
Although I did not think my requirement was that uncommon: I want to run a bunch of tasks which are created by different asynchronous functions and have a callback that will be called if all tasks are finished. 
Any alternative solutions to achieve this would be greatly appreciated.

**Comment by aearly** [comment]
Sounds like a use-case for `auto`.
