### ISSUE TITLE
async.detect result is undefined

### ISSUE THREAD

**Issue by colingoldberg** [caolan/async#1072]
Hi,

I tried the async.detect example 'out of the box' - placing an existing file as the first (and second) item in the array. But the result was 'undefined'.

[Both 'test_async.js','lok.json' exist, 'file3' does not]

```js
async.detect(['test_async.js','lok.json','file3'], function(filePath, callback) {
  fs.access(filePath, function(err) {
    callback(null, !err)
  });
}, function(err, result){
    // result now equals the first file in the list that exists 
    if (err) console.log('err:'+err);
    else console.log(result);
});
```

I actually would like to use detectSeries, but first 'detect' should work.

Thanks

Colin Goldberg

**Comment by aearly** [comment]
What version of Async are you using?

**Comment by colingoldberg** [comment]
# v1.5.2 as per changelog and package.json

**Comment by aearly** [comment]
Check the docs for 1.5.2, the args in the iteratee callback have changed:

https://github.com/caolan/async/blob/v1.5.2/README.md

**Comment by colingoldberg** [comment]
Thanks.
