### ISSUE TITLE
Allow to use streams of objects

### ISSUE THREAD

**Issue by piranna** [caolan/async#1076]
The same way that's possible to use Arrays and it will be added support for Iterable objects, add support for streams on objectMode. Both arrays are streams are similar in concept, only that array split data in space while streams split it in time, and both of them can be read sequentially.

**Comment by aearly** [comment]
Streams are a bit out of scope for this library. There is Highland.js for dealing with streams, as well as RxJS and other FRP libraries.  You could also use something like `concat-stream` to convert the stream to an array, and then pass it to an Async method.
