### ISSUE TITLE
Docs say `async.setImmediate` is `nextTick` on Node, but it's not?

### ISSUE THREAD

**Issue by stnever** [caolan/async#1079]
Hello! I'm a bit confused by the docs at:

https://github.com/caolan/async/blob/master/README.md#nexttickcallback-args-setimmediatecallback-args

> In Node.js this just calls process.nextTick; in the browser it falls back to setImmediate(callback)

But in `lib/internal/setImmediate.js`, it seems it will pick up `setImmediate` in Node as well:

```
var _setImmediate = typeof setImmediate === 'function' && setImmediate;

var _defer;
if (_setImmediate) {
    _defer = _setImmediate;
} else if (typeof process === 'object' && typeof process.nextTick === 'function') {
    _defer = process.nextTick;
} else {
    _defer = function(fn) {
        setTimeout(fn, 0);
    };
}
```

Is there any Node flavor where setImmediate does not exist? (I understand browsers may not have it, but then they wouldn't have `process` either... would they?)

**Comment by aearly** [comment]
The docs are wrong -- it always favor the native `setImmediate`.  The cases where it would fall back to `nextTick` are in browser-builds that provide a `nextTick` implementation (e.g. Browserify).
