### ISSUE TITLE
Async.detect not working properly, or documentation problem

### ISSUE THREAD

**Issue by Martinlck** [caolan/async#1080]
Hello there, I've been trying to use async.detect and this is a code snippet I did for testing : 
```javascript
var a = [1,2,3,4,5];
        async.detect(a, function (element, cb) {
            cb(null, element === 3);
        }, function (err, res) {
            console.log("RES ", res, "Err" , err);
        })
```
Both res and err are undefined on this example. So either I should call cb(element===3) or the documentation (https://github.com/caolan/async#detect) that explains detect is wrong. Let me know I will gladly submit a PR to fix this.

**Comment by megawac** [comment]
You are probably reading v2 documentation but using the v1 implementation
