### ISSUE TITLE
filterSeries documentation error

### ISSUE THREAD

**Issue by uptownhr** [caolan/async#1081]
When using collection.filterSeries the iteratee callback does not accept err. It only accepts TrueValue. However, the documentations for filter shows that it should accept an err. Same goes for the finished callback - the 3rd parameter callback does not have (err, result) but is just (result) 

##current
```
async.filter(['file1','file2','file3'], function(filePath, callback) {
  fs.access(filePath, function(err) {
    callback(null, !err)
  });
}, function(err, results){
    // results now equals an array of the existing files
});
```

##should be
```
async.filter(['file1','file2','file3'], function(filePath, callback) {
  fs.access(filePath, function(err) {
    callback(!err)
  });
}, function(results){
    // results now equals an array of the existing files
});
```

It may be that I'm doing something wrong as well. In that case, please advise as to why callback(null, !err) is not working for me.

**Comment by aearly** [comment]
Sounds like you're reading the 2.0 docs, but using v1.x.  See the note at the top of the readme.

**Comment by uptownhr** [comment]
Ah you are correct. How come npm installs 1.5 by default? 2.0 not released yet?

**Comment by aearly** [comment]
Yep, still in RC status while we kick the tires.  You can manually install the new version, if you want.

**Comment by uptownhr** [comment]
thanks for the help.
