### ISSUE TITLE
series Interval speed

### ISSUE THREAD

**Issue by uptownhr** [caolan/async#1082]
I know this is pretty trivial and can easily be done with setTimeout but it would be so nice and clean, if an optional interval parameter can be sent for the series methods. Just a thought :)

**Comment by aearly** [comment]
Yeah, it is pretty simple with `setTimeout`, also a bit niche.  There are talks of similar ideas in #1020 and #943.  I think there's some demand for some sort of throttled-queue-style behavior, but I think it would best exist as a standalone module outside of Async.  You're welcome to implement your own `seriesInterval` function -- seems like an interesting little project.
