### ISSUE TITLE
async.detect not working according to documentation

### ISSUE THREAD

**Issue by lbrucher** [caolan/async#1085]
According to the documentation (https://github.com/caolan/async#detectcoll-iteratee-callback):

> async.detect(coll, function(item, callback), function(err,result)), callback=function(err, truthValue)

In reality it seems that the implementation works this way:
> async.detect(coll, function(item,callback), function(result)), callback=function(truthValue)

For instance, the following code:
```
async.detect([1,2,3,4], function(item, cb){
	console.log("item=",item);
	cb(null, item>=2);
},
function(err, result){
	console.log("end: ", err, result);
});
```
shows the following output:
```
item= 1
item= 2
item= 3
item= 4
end:  undefined undefined
```

Instead, the following seem to work:
```
async.detect([1,2,3,4], function(item, cb){
	console.log("item=",item);
	cb(item>=2);
},
function(result){
	console.log("end: ", result);
});
```
With the output:
```
item= 1
item= 2
end:  2
```

Also, I did not see any test case for this method so could not verify the proper usage.

**Comment by ex1st** [comment]
You are reading docs for version 2.0RC, but using version 1.5. 
Right version - https://github.com/caolan/async/blob/v1.5.2/README.md

**Comment by lbrucher** [comment]
doh, nice catch, thanks!
