### ISSUE TITLE
Using async with Promises

### ISSUE THREAD

**Issue by RayKahn** [caolan/async#1086]
Any idea if this is possible or on the way? 

Thanks in advance.

**Comment by aearly** [comment]
You can wrap any function that returns a Promise with `ensureAsync` and the returned function can then be used like any-other callback-style async function. (e.g. passed to `map`, `waterfall`, etc..)

**Comment by megawac** [comment]
See #956 for discussion

**Comment by demian85** [comment]
Is there a way to make async control flow functions to return a promise instead of passing a callback node-style?
For example, the following code:
```
exports.getUser = function (userId) {
  return new Promise((resolve, reject) => {
    db.collection('users').findOne({ _id: userId }).then((user) => {
      async.map(user.contacts, (contactId, cb) => {
        db.collection('users').findOne({ _id: contactId }, { name: 1, email: 1 }).then(callbackify(cb));
      }, (err, contacts) => {
        if (err) return reject(err);
        getTeams(userId).then((teams) => {
          const output = Object.assign(user, { contacts, teams });
          resolve(output);
        }).catch(reject);
      });
    }).catch(reject);
  }).catch(handleError);
};
```
 can be changed to:
```
exports.getUser = function (userId) {
  return db.collection('users').findOne({ _id: userId }).then((user) => {
    return async.map(user.contacts, (contactId, cb) => {
      db.collection('users').findOne({ _id: contactId }, { name: 1, email: 1 }).then(callbackify(cb));
    }).then((contacts) {
      getTeams(userId).then((teams) => {
        return Object.assign(user, { contacts, teams });
      })
    })
  }).catch(handleError);
};
```
Am I wrong? It's not cool mixing callbacks and promises, I just want to use promises and async controls utilities without much boilerplate.

**Comment by megawac** [comment]
@demian85 consider using https://github.com/Kikobeats/promise-async or https://github.com/eladnava/koa-async

**Comment by demian85** [comment]
Sure, but it should be pretty straightforward to return a promise for all
async utility functions if no callback is provided.
Perhaps it's in the roadmap? Maybe I can help.

**Comment by aearly** [comment]
See the discussion in #956 .  We still support envs where there aren't native promises.  Use something like [`pify`](http://npm.im/pify) and you can manage it yourself.

**Comment by Enelar** [comment]
https://www.npmjs.com/package/google-spreadsheet use that in doc, took me a while to understand there is no promises involved lmao, have a great day everyone
