### ISSUE TITLE
applyEach doc is outdated

### ISSUE THREAD

**Issue by piranna** [caolan/async#1087]
`applyEach` accept an object as iterable running over all its properties instead of only Arrays, while the doc doesn't say anything about this. I think this should be added since if not it seems mostly an easter egg :-P but if the iterables are run over in an homogenous way by all functions, then this info should be shown at the top of the doc instead of just only some functions like `parallel`.

**Comment by aearly** [comment]
You're right -- `applyEach` can accept any collection type for the list of tasks.
