### ISSUE TITLE
applyEach return undefined

### ISSUE THREAD

**Issue by piranna** [caolan/async#1088]
`applyEach` function return always undefined instead of an array or an object with the results of the operations, as it happens with `map` or `parallel`. Doing so it would also make `parallel` equivalent to `applyEach` when it's called without arguments, so maybe also the code gets simpler...

**Comment by aearly** [comment]
You make a good point -- `applyEach` would be much more useful if it called the callback with the results of each task.

**Comment by piranna** [comment]
Thank you :-)

**Comment by piranna** [comment]
Cool, thank you! :-D When will this be available on npm?

**Comment by aearly** [comment]
Should be in 2.0.0 rc3.
