### ISSUE TITLE
Allow to set `thisArg`

### ISSUE THREAD

**Issue by piranna** [caolan/async#1089]
Some Javascript Array functions (and others) allow to define a `thisArg` argument that allow to define the `this` object when the function gets executed, and it's specially useful to give them a context where to execute without needing to create new Function objects with `.bind()` but using instead `.apply()`, earning some memory and cpu.

**Comment by aearly** [comment]
It was a deliberate design decision back in the day to leave `thisArg` management to the user.  Leaving it out definitely simplifies Async's internals.

In practice, there is negligible performance difference between using `.bind()`, `.apply()`, or using a closure.  While `.apply()` is slightly faster, any performance gain would probably be obviated by having to juggle around a `thisArg`.

**Comment by piranna** [comment]
> While .apply() is slightly faster, any performance gain would probably be obviated by having to juggle around a thisArg

It's both a performance and memory issue, but this is a good point against adding support for `thisArg`. I don't know `async.js` internals (and two times I tried to go into didn't understand anything), but could it be considered (again)? The main problem I find is from an API point due to optional final callback, but maybe in some cases it could be added...

**Comment by aearly** [comment]
Ah, I hadn't even thought about how it complicates the call signatures of most methods.

If you had something like `async.each(arr, taskMethod, arg)`, there would be no clear-cut way to determine whether the last `arg` was the callback, or a `this` binding and an omitted callback.  I think it's a non-starter because of that.  `.bind()` is the way to go.

**Comment by Igor10k** [comment]
@aearly 
Why is there this `async.apply()` method at all when there's a native `bind()` function that can do the same. Did you do any performance tests? It's hard to believe the converting arguments to an array and using native `.apply()` method is faster than just passing params using `.bind()` with `null` as a `this` context.

**Comment by aearly** [comment]
`async.apply`  is more akin to `_.partial` than the native `Function#apply`.  It doesn't apply a `this`-binding.  It's just a hold-over from the early days of Async.  If you need `this` context, just use `Function#bind`.

**Comment by Igor10k** [comment]
Or just always use `bind` and pass `null` when context is of no importance. Thanks for the answer :)
