### ISSUE TITLE
cyclic dependencies

### ISSUE THREAD

**Issue by zahreelay** [caolan/async#1092]
if we have an object like : 
         obj  =      {
			a : ['c',a],
			b : ['a',b],
			c : ['b',c]
		},
where a,b,c are names of functions, shouldn't this throw cyclic depenedency error if passed to async.auto ?

**Comment by aearly** [comment]
Our cyclic dependency checking isn't that robust.  It will only detect direct cycles, e.g. `a: ["b": a], b: ["a", b]`.

**Comment by aearly** [comment]
A PR that fixes this would be welcome...
