### ISSUE TITLE
ensureAsync overrides "this" binding

### ISSUE THREAD

**Issue by bspates** [caolan/async#1093]
Not sure if this is on purpose or not but a "this" is passed into fn.apply inside of ensureAsync which overrides any previous binding of the the function to another context. https://github.com/caolan/async/blob/master/lib/ensureAsync.js#L19.

**Comment by aearly** [comment]
The `this` there doesn't matter -- the "this"-binding is already lost by passing the function by reference.  Make sure you `.bind()` functions you pass around, if you need a "this"-binding

**Comment by bspates** [comment]
Sorry bout that, was thinking apply would override a .bind() call. Looks like that is not the issue. The problem is I cannot wrap a function with ensureAsync and then bind a context to the returned function and have that context be available as this in the original function. For example: 
```javascript
var async = require('async');

var foo = function(one) {
  console.log(this);
};

foo = async.ensureAsync(foo);
foo = foo.bind("bar");

foo(); // prints global node object
```

**Comment by aearly** [comment]
Yeah, that order of operation isn't possible, at least not without over-complicating Async's internals.

**Comment by bspates** [comment]
Wouldn't adding a `fn = fn.bind(this);` above this line https://github.com/caolan/async/blob/master/lib/internal/initialParams.js#L6 
fix it? 
So: 
```javascript
import rest from 'lodash/rest';

export default function (fn) {
    return rest(function (args/*..., callback*/) {
        var callback = args.pop();
        fn = fn.bind(this);
        fn(args, callback);
    });
}
```
If this is an acceptable change I can make a pr.

**Comment by aearly** [comment]
That would work!

You can make it simpler:

```js
        var callback = args.pop();
        fn.call(this, args, callback);
```
