### ISSUE TITLE
async.some not running without optional callback

### ISSUE THREAD

**Issue by caliber01** [caolan/async#1096]
I've ran into an issue with some, It simply doesn't run if i don't provide the optional final callback:

`async.some([1, 2, 3], (i, cb) => {console.log(i); cb()})`
prints nothing
`async.some([1, 2, 3], (i, cb) => {console.log(i); cb()}, () => {})`
prints "1 2 3"

I found the same issue with async.find function

**Comment by aearly** [comment]
Good catch.  Although I wonder why someone would use `some` or `detect` and then discard the result....
