### ISSUE TITLE
breaking the waterfall chain without throwing an error

### ISSUE THREAD

**Issue by ghost** [caolan/async#11]
I was told I need to refactor my code that is using async waterfall. I used it primarily because I had several chained functions that were going too deep, and I wanted to reuse a function, etc. There is a condition at one point down the chain that is not strictly an error condition, but that I don't want to pass down the rest of the waterfall chain, because it's useless - say for example I did a query and there are no results, and that's not an error, I don't want to propagate all the way down with no results. If I were doing this without async, I guess I would have a "final" callback and which could be called to break out of the chain without explicitly throwing an error. This functionality doesn't seem to be present in waterfall. Is there a way to do this cleanly? The only way I can see to do it is to throw a special error and then handle that on the final callback so as to return a non error.

**Comment by digitaljohn** [comment]
Personally I find myself needing functionality like this and think it should be added to the core library.

Here is my helper workaround if anyone is interested...

```
exports.breakWaterfall = function(tasks, callback){
    async.waterfall(tasks, function(){
        if(arguments[0] === 'break'){
            arguments[0] = null;
        }
        callback.apply(null, arguments);
    });
}
```

If you need to break to the last function within a task just call the callback like this: `done('break', other, arguments);`.

The helper just detects the `'break'` and mutates the arguments so it does not look like an error to the rest of your code.
