### ISSUE TITLE
doWhilst documentation

### ISSUE THREAD

**Issue by DominicBoettger** [caolan/async#1107]
Hello,

i had the problem that i was not able to use the current element in doWhilst following the API documentation.

Then i tried the following:

````
js
async.doWhilst((callback) => {
  let res = execHandler.next();
  callback(null, res);
}, (res) => {
  return !res.done;
}, (err) => {
  if (err) {
    console.log(err);
  }
});
````

And it worked very well. Is this allowed? Because the API documentation says that there is no input element in the test function.....

Best regards
Dominic

**Comment by aearly** [comment]
Sounds like a doc mistake.
