### ISSUE TITLE
Invalid async@2.0.0-rc.3?

### ISSUE THREAD

**Issue by Nic2012** [caolan/async#1109]
I have upgraded node from 0.10 upto 4.4 and updated npm packages.
With the latest async I am getting by node ls:
```
npm WARN unmet dependency /home/.../node_modules/get-pixels/node_modules/request/node_modules/form-data requires async@'^1.5.2' but will load
npm WARN unmet dependency /home/.../node_modules/async,
npm WARN unmet dependency which is version 2.0.0-rc.3
/home/...
├── async@2.0.0-rc.3 invalid
```
and finally at the end
```
npm ERR! invalid: async@2.0.0-rc.3 /home/../node_modules/async
```

Is that serious?

**Comment by megawac** [comment]
What version range did you set for async. It shouldn't be an issue for form-data as `parallel` (the only function they use) hasn't changed between async@^1 and 2.0

**Comment by Nic2012** [comment]
I havent set anything, i do not know how. Currently I dont use async, but in my next projects.
I would like to help y to find any serious bugs, I have mentioned it in ticket.
So no negative side effect by these errors? I can use async now?

**Comment by megawac** [comment]
Its hard to say with the information provided. I'd probably just recomend reinstalling your ndoe modules

http://stackoverflow.com/questions/25696584/npm-list-giving-npm-err-invalid-output

**Comment by aearly** [comment]
Also, how did you update node? You might have an out of date npm. `npm update -g npm` can fix that.
