### ISSUE TITLE
Question: doUntil() vs doWhilst()

### ISSUE THREAD

**Issue by boustanihani** [caolan/async#1115]
Could anyone please explain the difference between the post-check functions ```doUntil()``` & ```doWhilst()``` ??
- ```doUntil(fn, test, callback)``` https://www.npmjs.com/package/async#doUntil
- ```doWhilst(fn, test, callback)``` https://www.npmjs.com/package/async#doWhilst

According to the docs, ```doUntil()``` is like ```doWhilst()```, except **the test is inverted**. Note the argument ordering differs from until. What does "the test is inverted" mean? Both functions have same arguments ordering!!

**Comment by megawac** [comment]
Yeah, that probably needs a better explanation. The difference is that to continue running the tasks with `doUntil` you pass `false` to the test function and it keeps running until `true` is received, whereas `doWhilst` continue as long is a truthy value is received and breaks when false is passed.

**Comment by aearly** [comment]
"do until the test passes"

"do whilst the test passes"

That's how I remember it.
