### ISSUE TITLE
sourceMappingURL in minified build is not correct

### ISSUE THREAD

**Issue by joostdebruijn** [caolan/async#1117]
In `async.min.js` there is a reference to the sourcemap:

`//# sourceMappingURL=dist/async.min.map`

However, this reference is not correct: because `async.min.js` is also in the dist-folder. This causes errors when using the script in a browser for example. The sourceMappingURL should be:

`//# sourceMappingURL=async.min.map`

I guess this URL is generated somewhere in a buildscript, but I was not able to find and fix it in a PR.

**Comment by hargasinski** [comment]
This is an error in the [options](https://github.com/caolan/async/blob/master/Makefile#L64) passed to `Uglify` in the `Makefile`. When `--source-map` is passed without `--source-map-url`, the source map URL is set to value passed in with `--source-map`. Passing a value with `--source-map-url` fixes the issue. See [the Uglify options](https://github.com/mishoo/UglifyJS2#user-content-usage) for more details. PR #1119.

**Comment by megawac** [comment]
Thanks for the report and fix
