### ISSUE TITLE
Feature request - async.forEachOf results in callback

### ISSUE THREAD

**Issue by hatimk** [caolan/async#1124]
Hi,

I am using `async.forEachOf()` quite often and I think this is a very handy tool for task parallelization over an array. However - and correct me if I am wrong - it seems like there is no way to get the different threads' results in the final callback (I am obliged to create a results array outside of the forEachOf and to populate it with the results inside the iteratee function). Wouldn't it be better if the callback is of the form `callback(err, results)` where `results` is an array of responses corresponding to all the threads, like it is the case for `async.parallel`?

Kind regards,

**Comment by aearly** [comment]
Just use `async.map()` instead.
