### ISSUE TITLE
The difference of unsaturated between Queue and PriorityQueue

### ISSUE THREAD

**Issue by suguru03** [caolan/async#1131]
I have a question about `priorityQueue.unsaturated`.

I wonder the reason why it is different from `queue`.
https://github.com/caolan/async/blob/master/mocha_test/priorityQueue.js#L151-L153
https://github.com/caolan/async/blob/master/mocha_test/queue.js#L639-L655
Are both correct?

**Comment by aearly** [comment]
Ah, I was fixing the timing for queues, but failed to also update `priorityQueue`.  This should be corrected.

**Comment by suguru03** [comment]
I see, thanks!

**Comment by aearly** [comment]
Closed by #1132!
