### ISSUE TITLE
Add forMapOf like forEachOf

### ISSUE THREAD

**Issue by alinex** [caolan/async#1133]
I would like to have a async.map method working on objects like the async.forEachOf does. As a working wrapper I currently use (as coffeescript):

```coffeescript
    forMapOf = (obj, iterator, cb) ->
      # check the object
      return cb new Error "mapOf only works on objects" unless typeof obj is 'object'
      # map over object keys
      keys = Object.keys obj
      async.map keys, (key, cb) ->
        # call iterator with value and key
        iterator obj[key], key, cb
      , (err, results) ->
        return cb err if err
        # combine the results into an object again
        map = {}
        for num in [0..keys.length-1]
          map[keys[num]] = results[num]
        cb null, map
```

Is it possible to integrate such functionality directly with it's limit and series partners?

**Comment by aearly** [comment]
I think you're better off using `eachOf` and family if you need the key.  The other option would be to use something like `_.pairs(obj)` and then `_.zip`ing the result back up when you're done.

Also note that `map` already works with objects, it just doesn't give you access to the key in the iteratee.

**Comment by aearly** [comment]
I think we're going to separate out object functionality in to `mapValues` and `mapKeys`.  See #1157

**Comment by megawac** [comment]
Brings the questions of whether the key+value should be accessible for those implementations and whether we should keep a unary version (each vs eachOf, map vs mapOf)

**Comment by aearly** [comment]
I think we should pass `(value, key, cb)` to both, not worry about the unary case.

**Comment by alinex** [comment]
I could work perfectly with the behaviour in v2.0.0-rc.5, there i step over object keys without access to the key name but since v2.0.0-rc.6 i give an object and get an array back, that won't work.
