### ISSUE TITLE
async queue never triggers drain but only sometimes

### ISSUE THREAD

**Issue by atrhacker** [caolan/async#1136]
Hello Async Usersy,

I'm continuing to play around with nodejs. So below is a brief summary of my launch.js app

```js
var counter = 0;
var queue = async.queue(function(objectWithVariousProperties, callback) {
    methodDoingVariousAsynchronousStuff(objectWithVariousProperties.link, function(err,result) 
        counter++;
        callback();
    });
}, 20);

queue.drain = function() {
    log.debug("Finished Queue", {
        "Objects processed" : counter
    });
};
//TO various iterations over several array and construct some object and then push them in the queue via 
queue.push(media_object)
```
My issue is that 80% of the time the process works. the application launch via the shell command nodejs launch.js , process the queue, when queue is finished it displays the 'Finished Queue' then back to shell.

However, sometimes the drain event is never triggered but the application finished and back to the shell without any exception. I inspected during several hours my code to find if there was a missing callback, but it does not seems so.

Any idea which can explain this strange random behaviour ? 
Or any tools which would help to find the leaking code or the missing callback if any ?

As I said, sometimes, the queue process more than 5000 objects without any problem and sometimes when I launch it, it process somestuff, but stop randomly,  it just does not trigger the drain event but the process stop (again without any exception or error or anything, just a normal stop)

I spent a couple of evenings trying to figure out why, so if you guys had any ideas it would be gladly welcomed.

Thanks in advance for your feedbacks and I wish you a very nice day,

Anselme

**Comment by aearly** [comment]
Impossible to know without knowing more of your code?  What happens when you replace `methodDoingVariousAsynchronousStuff` with just a simple `setTimeout`?

**Comment by atrhacker** [comment]
hey Aerly, Thank a lot for your feedback. Unfortunately behind this method there is a lot of logic and asynchronous call, whihc would be impossible to copy/paste. The thing is it could be a callback never returned sometimes but is there a debugging tool allowing to capture every event not fired or something like this ? I will try with the setTimeout and keep you in touch.
