### ISSUE TITLE
async nesting loop with forEachSeries and whilst together

### ISSUE THREAD

**Issue by vvsuperman** [caolan/async#1143]
because my query is complex, so I use forEachSeries and whilst together, with code like that:

     async.forEachSeries(BJRegion,function (region, key, callback){

    var count = 0;

    async.whilst(
        function () { return count < 10; },
        function (cb) {
           sth....
        }
        ,
        function (err, count) {             
            console.log("err...........",err,count);                                
        }
    ); //whilst
    });//for eachof
but it seems like that when the first while is done the whole loop is end, the outer foreach do not go to the next element. without while everything is ok, forEach can get ever element in the var BJRegion,

**Comment by megawac** [comment]
I think you just have to call your forEachSeries callback in the done callback of whilst

```js
async.whilst(
    function () { },
    function (cb) {} ,
    function (err, count) {             
        // call the forEachSeries Callback                       
      callback(null, data); 
   }
);
```

**Comment by vvsuperman** [comment]
first I need to get some data in BJRegion which is an array, for example, I get some name like john, mike.....then I have to loop about 100 times according to each name.  So, I need to 

async.forEachSeries 
    some loop.....
    async.whilst
        some loop......

do you have any opinion ?

**Comment by megawac** [comment]
does your `whilst` loop have to be asynchronous? Otherwise it'd probably be better to do a normal for/while loop there. Also any reason you use a series `forEach` rather than doing it in parallel? Anyway, I think your solution is fine

**Comment by vvsuperman** [comment]
but It's can not work....  the foreach run once,  just get the first element. when whilst end then the whole forEachSeries end. so, my question is that can the foreach and whilst use together? if not, how could I do .

**Comment by megawac** [comment]
Yes, they are interoperable. You just have to be sure to call the iterator
callbacks for both `forEachSeries` and `whilst`
