### ISSUE TITLE
Throwing an error in callback results in "Unhandled rejection Error: Callback was already called."

### ISSUE THREAD

**Issue by patrykziem** [caolan/async#1150]
Throwing an error in callback results in "Unhandled rejection Error: Callback was already called."
This prevents user from seeing actual error message, created by assertions in tests. 
This hasn't been happening in 2.0.0-rc3. Is this expected behaviour in rc4?

Here's the example code

```js
async.waterfall([
  (next) => {
    apiClient
      .post('/some-url')
      .send({prop: 'value'})
      .expect(200)
      .end(next);
  }
], (err) => {
  assert.ifError(err);
  throw new Error('Some Error');
});
```

**Comment by aearly** [comment]
Looks like there's a Promise inside your `apiClient` thats catching the error you're trying to throw, and calling the `.end()` callback twice.

**Comment by patrykziem** [comment]
ApiClient is a regular SuperAgent client. How would it even be possible for a function in waterfall, which is executed previously to catch error thrown in callback?

**Comment by aearly** [comment]
It's a common pitfall with continuation-passing style.  Consider this:

```
function someAsyncFn(arg, callback) {
  try {
    var foo = doSomething(arg);
    callback(null, foo);
  } catch (e) {
    callback(e);
  }
}

someAsyncFn(1, function(err, val) {
  throw new Error();
})
```

The error thrown in the callback will be caught by `someAsyncFn`, which will then call the callback again.  Promises wrap their resolved/rejected handlers in a try/catch, so this comes up often.  There's a promise somewhere in your code handling the error.

**Comment by patrykziem** [comment]
You of course have been right. Pushing it down the loop with nextTick does seem to make it work.
Thank you for pointing it out, I falsely assumed that this was already happening with callback.

Is there a better way to do it instead of adding additional flow function every time?

I mean this:

async.waterfall([
  (next) => {
    apiClient
      .post('/some-url')
      .send({prop: 'value'})
      .expect(200)
      .end(next);
  },
  (res, next) => async.nextTick(next, null, res)
], (err) => {
  assert.ifError(err);
  throw new Error('Some Error');
});
