### ISSUE TITLE
async.detect docs are wrong v2

### ISSUE THREAD

**Issue by emps** [caolan/async#1151]
i notice docs not so much correct for example 
i use now async v2 and reading main docs that are for v2
and tring 

Not working:
```
async.detect(pictures, (picture, callback) => {
	callback(null, picture._id === data.pictureId);
}, (err, result) => {
	result.likesCount = data.likesCount;
});

```

Wokring:
```
async.detect(pictures, (picture, callback) => {
	callback(picture._id === data.pictureId);
}, (result) => {
	result.likesCount = data.likesCount;
});
```

while docs says use callback(null to catch the err in second callback.. (err, result

**Comment by emps** [comment]
docs are incorrect or detect function is bad implemented ? i think some more collection methods are same problem such as .filter same story

**Comment by aearly** [comment]
Are you sure you're using one of the  v2.0 RCs?  We have a whole suite of tests that show it working as documented. https://github.com/caolan/async/blob/master/mocha_test/detect.js

**Comment by emps** [comment]
yes im using rc4

**Comment by aearly** [comment]
Can you provide a full failing test case?

**Comment by emps** [comment]
yes i will do today thanks

**Comment by megawac** [comment]
Any update @emps?

**Comment by emps** [comment]
sorry i was very busy.. can u run the code i wrote ?

**Comment by aearly** [comment]
Nope, need the array you're using.

**Comment by emps** [comment]
hii, i see with rc5 problem gone :+1:  this issue gone
