### ISSUE TITLE
missing documentation for async.transform

### ISSUE THREAD

**Issue by EndangeredMassa** [caolan/async#1154]
The outline lists `async.transform`, but it doesn't have its own section describing what it does.

Outline for collections: https://github.com/caolan/async#collections

Bad outline link: https://github.com/caolan/async#transform

Code: https://github.com/caolan/async/blob/master/lib/transform.js#L7

**Comment by aearly** [comment]
We're about to migrate away from the readme to a dedicated docs site, so there's no reason to duplicate the docs right now.
