### ISSUE TITLE
A buffering wrapper for async functions

### ISSUE THREAD

**Issue by seriousManual** [caolan/async#1155]
I just ran into the following use-case and was wondering if something like this is already possible with async or if it might be considered useful for async.

Consider a async function that takes some time (e.g. because of IO). When the function gets called multiple times this expensive tasks will be executed multiple times (possibly clogging the CPU, network ...).
Here it would be sensible if all subsequent calls that come after the first call would be buffered and than resolved when the result of the first call returns.

Example code explain the illustrate the above:
```javascript
function expensiveGen(callback) {
    setTimeout(_ => callback(null, Math.random()), 1000)
}

const expensiveGenWrapped = bufferingAsyncWrapper(expensiveGen)

//the following five calls to `expensiveGenWrapped` will receive the same result as they are done while the task is "busy" for 1000ms
expensiveGenWrapped((error, result) => console.log('1_' + result))
expensiveGenWrapped((error, result) => console.log('2_' + result))
expensiveGenWrapped((error, result) => console.log('3_' + result))
expensiveGenWrapped((error, result) => console.log('4_' + result))
expensiveGenWrapped((error, result) => console.log('5_' + result))

//the following call to `expensiveGenWrapped` will receive a result that differs from the above results
setTimeout(_ => expensiveGenWrapped((error, result) => console.log('stuff' + result)), 2000)
```

An examplary implementation could look like this: https://github.com/seriousManual/bufferingAsyncWrapper/blob/master/index.js

Let my know what you think!

**Comment by aearly** [comment]
Unless I'm mistaken, it sounds just like `async.memoize`.

**Comment by seriousManual** [comment]
not quite, `async.memoize` is a cache that returns the same value for a certain input every time.
in contrast the describe buffering wrapper queues up all calls that happen _while_ the wrapped function is computing/generating the result. when the computation is finished all queud up calls get answered by the result.
when the expensive function gets called again after that it will start the computation a new.

**Comment by aearly** [comment]
This might be useful as its own npm package, but it has too much overlap with `memoize` for me to include it with Async proper.
