### ISSUE TITLE
Loading fails with TypeError in Firefox

### ISSUE THREAD

**Issue by andrenarchy** [caolan/async#1158]
Loading async `2.0.0-rc.4` in Firefox (tested with 38 and 42) via
```html
<!doctype html>

<html>
  <body>
    <script src="node_modules/async/dist/async.js"></script>
  </body>
</html>
```
fails with the following error:
```
TypeError: Function.prototype.toString called on incompatible object (async.js:1425:31)
```
[This](https://github.com/caolan/async/blob/a684c1b75645068559516d2fd295e0da342e6b51/dist/async.js#L1425) is the corresponding line.

**Comment by jdalton** [comment]
This has been fixed since v4.8.0 (current version is 4.12.0)

**Comment by jdalton** [comment]
Make sure you build with a fresh `npm i` of lodash.

**Comment by andrenarchy** [comment]
Oh, `dist/async.js` includes lodash functions? These functions seem to be outdated. Can someone please update them for providing a quick solution to the problem?

**Comment by megawac** [comment]
@aearly can you update the npm dist build

**Comment by andrenarchy** [comment]
Thanks a lot! :+1: 

I wonder why the npm version also uses `dist/async.js` and thus does not benefit from updates to the `dependencies` in `package.json` (shouldn't they be `devDependencies` at the moment?). Instead, you always need to update async when lodash pushes an update – and we all know how busy @jdalton is with getting new updates out! :) Do you have any references where this decision is explained?

**Comment by megawac** [comment]
The discussion is kinda scattered through #996. The main reason is to minimize import time so npm doesn't have to load so many files. The reason it's a dependency still is so you can import specific methods (`require('async/each')`) and have it look up the lodash methods properly.

**Comment by andrenarchy** [comment]
I'll look into the referenced issue, thanks!

**Comment by megawac** [comment]
@andrenarchy search for `main` and you should be able to jump through the relevant discussion (core of it https://github.com/caolan/async/pull/996#issuecomment-185866749)
