### ISSUE TITLE
Best Practices and Coding Style with async.js

### ISSUE THREAD

**Issue by cyberjoac** [caolan/async#1159]
Hi, 

Can you recommend any project that use async.js methods in production that I could use to learn best practices and coding style guidelines with it?

Particularly, what's the best way to stucture the code inside the function(callback). 
Is it considered good practice to put the whole method inside the function(callback) {...} code or better to extract methods from inside of it.
```
async.series([
    function(callback){
       doSomething(callback);
    },
    function(callback){
        doSomething2(callback);
    }
],
```

Thanks a lot for your help.

**Comment by megawac** [comment]
> Can you recommend any project that use async.js methods in production that I could use to learn best practices and coding style guidelines with it?

For a reference project using async I'd highly recommend checking out [waterline](https://github.com/balderdashy/waterline) [(1)](https://github.com/balderdashy/waterline/blob/fb0f03d413d84f6f71d46ad0fde346a4aa37e540/lib/waterline.js) [(2)](https://github.com/balderdashy/waterline/search?utf8=%E2%9C%93&q=require%28%27async%27%29) for excellent use of async.

I'm not aware of any true coding style guide for async in particular. It could be interesting to make some eslint rules for async in the future.

> Is it considered good practice to put the whole method inside the function(callback) {...} code or better to extract methods from inside of it.

This is really just preference based. You'll see it mixed in the documentation and code examples. I think I prefer methods extracted out in most cases for readability, but I don't have strong attachments.
