### ISSUE TITLE
"Callback was already called," yet it doesn't seem possible that it would have been called twice

### ISSUE THREAD

**Issue by mtchllbrrn** [caolan/async#1162]
```
// Open the DDP connection
async.retry({ times: 20, interval: 2000 }, (cb) => {
  ddp.connect((err) => {
    console.log(err);
    if (err) {
      cb(err, null);
    } else {
      cb(null, 'succeeded');
    }
  });
}, err => {
  if (err) throw err;
  const { JOB_USER, JOB_PASS } = process.env;
  DDPlogin.loginWithUsername(ddp, JOB_USER, JOB_PASS, err2 => {
    if (err2) throw err2;
    Job.processJobs('jobs', 'fooJob', (job, cb) => {
      // This will only be called if a fooJob job is obtained
      console.log(job.data); /* eslint no-console: 0 */
      job.done();
      cb();
    });
  });
});
```

emits the following:

```
Network error: ws://127.0.0.1:3000/websocket: connect ECONNREFUSED 127.0.0.1:3000
/Users/mitchell/work/src/blendata/node_modules/async/dist/async.js:839
            if (fn === null) throw new Error("Callback was already called.");
                             ^
Error: Callback was already called.
    at /Users/mitchell/work/src/blendata/node_modules/async/dist/async.js:839:36
    at /Users/mitchell/work/src/blendata/node_modules/async/dist/async.js:5218:17
    at /Users/mitchell/work/src/blendata/node_modules/async/dist/async.js:339:31
    at /Users/mitchell/work/src/blendata/node_modules/async/dist/async.js:5999:21
    at ddp.connect (/Users/mitchell/work/src/blendata/.workers/fooWorker.js:26:7)
    at .<anonymous> (/Users/mitchell/work/src/blendata/node_modules/ddp/lib/ddp-client.js:320:7)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/mitchell/work/src/blendata/node_modules/ddp/lib/ddp-client.js:83:12)
    at emitOne (events.js:101:20)
```

I've looked through similar issues, and it seems in most cases that people had written their code such that the callback *was* called twice. For instance, they omitted an `else`:

```
if (err) cb(err);
cb(null, 'success');
```

Best I can tell, that's not the case for me.

**Comment by megawac** [comment]
Any chance your callback passed to `ddp.connect` was called twice?

**Comment by megawac** [comment]
I think what might of happened reading ddp-client [1] is

1) failed to connect, callback was called
2) on a retry you successfully connected/failed to connect and your callback was called again.
3) because you called the callback twice async threw an error 

[1] https://github.com/oortcloud/node-ddp-client/blob/master/lib/ddp-client.js#L303

**Comment by vsivsi** [comment]
Right. It seems that trying to use both ddp-client's `autoReconnect: true` (default) option, and `async.retry()` simultaneously leads to this interaction. Turning off `autoReconnect` and explicitly handling disconnection events seems to be a resonable solution.

**Comment by mtchllbrrn** [comment]
Good catch @vsivsi. I'll come back to this when I get a chance and see if that solves it.

**Comment by jatinkumarrao** [comment]
var doc = new GoogleSpreadsheet('1UVjq5xhgw');
var sheet;
async.series([
  function setAuth(step) {
    // see notes below for authentication instructions!
    var creds = require('./data-3c155f5283bc.json');
    // OR, if you cannot save the file locally (like on heroku)
    var creds_json = {
      client_email: 'snt.com',
      private_key: '-------END PRIVATE KEY-----\n',
    }
 
    doc.useServiceAccountAuth(creds, step);
  },
  
  function getInfoAndWorksheets(step) {
    app.get('/', function (req, res) {
    doc.getInfo(function(err, info) {
    
      console.log('Loaded doc: '+info.title+' by '+info.author.email);
    
      sheet = info.worksheets[0];
       res.json(sheet)
        //step(new Error(sheet));
      // console.log(sheet.title)
      //console.log('sheet name: '+sheet.title+' '+sheet.rowCount+'x'+sheet.colCount);
    step();
   
    }); 

  })
    
  }
  ])
call back error
