### ISSUE TITLE
Passing param to async.map() with bind iteror

### ISSUE THREAD

**Issue by romain-nio** [caolan/async#1165]
Hi,

I want to apply a function on each element of my array and returing this array with all items modified.

I want to use **async.map()** but it's not possible to natively add arguments to it. I read that it's possible to pass extra params to **async.map()** with the **bind()** iterator (cf http://stackoverflow.com/questions/20882892/pass-extra-argument-to-async-map)

I tried the fowollowing code without any success. My extra param "bucket" is set to "undefined" :
```
async.map(sources, function(item, callback) {

        getFileContentFromS3(this.bucket, item, callback);

    }.bind({

        bucket: bucket

    }), function(err, sources) {

        callback(null, sources)

    });
```

**Comment by ex1st** [comment]
Why not just?

```javasciprt
async.map(sources, function(item, callback) {
        getFileContentFromS3(bucket, item, callback);
 }, function(err, sources) {
        callback(null, sources)
});
```

**Comment by romain-nio** [comment]
thanks ex1st  ! :) :+1: I don't why I tried to do a complex code.. 

Thanks !

**Comment by romain-nio** [comment]
Hi @ex1st, I reponed the issue because I test your code again and it's not working. My param "bucket" is empty in my function (getFileContentFromS3). I checked that this parameter is not empty before be passing to the function as first argument.

I also try with static string variable and it's failed too :
```
async.map(sources, function(item, callback) {
        getFileContentFromS3("test", item, callback);
 }, function(err, sources) {
        callback(null, sources)
});
```

Thanks for you help :)

**Comment by megawac** [comment]
Hi @romain-nio, @ex1st should work for your case assuming `getFileContentFromS3` doesn't modify bucket. It's hard to help you without enough code and data to reproduce your issue.

**Comment by romain-nio** [comment]
hi @megawac, thanks for your answer :)

"Bucket" param  is not modify in the function "`getFileContentFromS3`". It seems that without using `bind`, it's not working (cf http://stackoverflow.com/questions/20882892/pass-extra-argument-to-async-map)

Can you tell me what is the normal behavior?

Regards,
Romain.

**Comment by megawac** [comment]
So the code in the original post with bind works?

**Comment by romain-nio** [comment]
Hi @megawac, no it's not working

**Comment by aearly** [comment]
It sounds like the issue is in your `getFileContentFromS3` function.  Impossible for us to debug further without more code, but it's also out of Async's scope.
