### ISSUE TITLE
es6 is implicitly in strict mode no need for 'use strict' directives.

### ISSUE THREAD

**Issue by jdalton** [caolan/async#1168]
ES6 modules are implicitly [in strict mode](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-code) so there's no need for 'use strict' directives in the ES6 module source, it's redundant. The strict mode directive is added by babel when transpiled to ES5/3. Would you all dig a PR?

Related https://github.com/eslint/eslint/issues/1956.

**Comment by jdalton** [comment]
Related https://github.com/eslint/eslint/issues/1956.

**Comment by megawac** [comment]
Sure, always cool with killing some boilerplate

**Comment by jdalton** [comment]
Moved to #1174.
