### ISSUE TITLE
filter result not an array

### ISSUE THREAD

**Issue by Luncher** [caolan/async#1169]
**What version of async are you using?**
version: 2.0.0-rc.5  

**Which environment did the issue occur in (Node version/browser version)**
node v 6.2.0

**What did you do? Please include a minimal reproducable case illustrating issue.**  
```javascript  
const fs = require('fs');  
const async = require('async');

async.filter(['f1', 'f2', 'f3'], fs.exists, function(ret) {
    console.log(ret);
});
```  

[luncher@localhost async]$ node app.js 
true
[luncher@localhost async]$ 

**What did you expect to happen?**
expect result must be an array 

**What was the actual result?**
a Boolean equal true

**Comment by Luncher** [comment]
[luncher@localhost async]$ ls
app.js  f1  f2  f3  node_modules  package.json
[luncher@localhost async]$

**Comment by megawac** [comment]
Hi @Luncher in version 2 of async the result function for filter is in the format `function(err, ret)` instead of `function(ret)`

**Comment by Luncher** [comment]
thanks, but the wiki  not updated

**Comment by aearly** [comment]
Which wiki? The current docs are accurate.
