### ISSUE TITLE
Cleanup package managers.

### ISSUE THREAD

**Issue by jdalton** [caolan/async#1175]
I noticed async has a lot of package manager scaffolding which could be removed or simplified.
For example component, jam, spmjs, volo could be dropped as they're either no longer maintained or have minuscule usage. The bower.json could be simplified as well. If you all are up for a PR, I'll send one over.

**Comment by aearly** [comment]
Sounds good.  Seems only Bower is the only package manager still kickin' aside from NPM.  Not too familiar with `bower.json1 properties -- what could we remove?

**Comment by jdalton** [comment]
Moved to #1176.
