### ISSUE TITLE
Ambiguity when async.auto provides an array

### ISSUE THREAD

**Issue by jbergknoff** [caolan/async#1178]
When step A in an `async.auto` calls back with more than two arguments, a subsequent step B is shown an array as the result of step A. As far as I can tell, there is no way to distinguish (1) step A calling back in the usual way with an array, and (2) step A calling back with more than two arguments.

For example:

``` js
async.auto(
  {
    "stepA": function(cb) {
      cb(null, 1, 2);
    },
    "stepB": [
      "stepA",
      function(cb, result) {
        console.log(result.stepA); // [1, 2]
      }
    ]
  }
);
```

``` js
async.auto(
  {
    "stepA": function(cb) {
      cb(null, [1, 2]);
    },
    "stepB": [
      "stepA",
      function(cb, result) {
        console.log(result.stepA); // [1, 2]
      }
    ]
  }
);
```

If your `auto` step normally calls back with an array, but the oddball third argument is optional, I'm not sure there's a robust way to tell if the third argument is present.

It does seem natural for `auto` to deal with more than one argument by providing an array, but maybe it should do something to resolve this ambiguity. For example, it could tag the array with a special property.

I realize that 2.0 has some changes to `auto` but, as far as I could tell, this particular issue is still present.

**Comment by aearly** [comment]
This is a pattern we follow in a couple Async.  When combining results from a callback function, if there's only 1 result argument, we use it directly, but otherwise, we use an array of the results.

We don't follow this consistently -- for example, in `parallel` we'll use an array of all results, but in `map` we only use the first result arg.  I'm not sure what the correct thing to do here is.

**Comment by aearly** [comment]
BTW, I'm leaning towards having `auto` only use the first result argument, discarding any extras, similar to `map`.

It would be easy to write a wrapper function for tasks that gathers extra args into an array.

**Comment by CodeMan99** [comment]
Would the best solution to return a sliced version of the arguments object?

```javascript
var args = Array.prototype.slice.call(arguments, 1);
var len = args.length;
var obj = Object.assign({}, args);

Object.defineProperty(obj, 'length', {get: () => len, enumerable: false});
```

Users can then treat the object like a normal Array, test that is *not* an Array with `Array.isArray`, and convert the object into an Array for connivence with `Array.from`.

I your argument for being a helper is a valid one as well. To me `auto` is suppose to have a "sync" feel, so it is a bit strange to "return" multiple times. Here is the original example again, but without writing the sync function with a callback.

```javascript
async.auto({
  stepA: async.asyncify(function() {
    return [1, 2]; // an actual array... alternatively, you might return an object
  }),
  stepB: ['stepA', function(callback, d) {
    console.log(d);
  }]
});
```

**Comment by CodeMan99** [comment]
After some thinking, I realized the helper is extremely easy to write using `Array.shift`.

```javascript
function multiValueCallback(cb) {
  return funtion() {
    var err = Array.prototype.shift.call(arguments);
    cb(err, arguments);
  };
}
```

For completeness, a simple example.

```javascript
async.auto({
  page: callback => request('http://www.google.com', multiValueCallback(callback)),
  save: ['page', (callback, d) => fs.writeFile(d.page[1], 'utf8', callback);
});
```

**Comment by rduenasf** [comment]
@aearly have you guys got any conclusion on this topic?

**Comment by aearly** [comment]
@rduenasf No, we didn't.  What do you think is the correct thing to do here?

**Comment by CodeMan99** [comment]
Is this really an issue worth entertaining? Namely I am thinking about how destructuring will affect usage of multiple-value returns.

**Comment by aearly** [comment]
I'm inclined to leave things as they are.  While I think it's more "correct" to only use the first value passed to the callback (like in `map`), I'm not sure its worth the breaking change to do so.

**Comment by aearly** [comment]
I think we can rely on newer language features to smooth this over:

```js
async.auto({
  task1: (cb) => {
    cb(null, 1, 2);
  },
  task2: ['task1', (results, cb) => {
    let [a, b] = results.task1;
    //....
  }]
}, done);
```
