### ISSUE TITLE
Change the name `async` to other candidate early? (Prepare for ES7)

### ISSUE THREAD

**Issue by zixia** [caolan/async#1179]
as we know, `async` & `await` will be the language reserved keyword in ES7.

so how about consider to change the name of this module earlier so we will be well prepared? :)

**Comment by megawac** [comment]
> async & await will be the language reserved keyword

They will not be language reserved, unless (and I'm not 100% on this) if you use the features in that file. I think the spec says the parser should detect whether `async`/`await` are used as keywords. w3c would not allow a new spec to break existing code

> change the name of this module earlier

There is nothing stopping you from importing with a different name (except in global namespace I assume)

```js
var asyncJs = require('async')
import A from 'async'
```

**Comment by megawac** [comment]
I'm going to close as won't fix, agree @aearly & @Kikobeats?

**Comment by SiegfriedEhret** [comment]
Just a small note: async functions are not part of ES7. They are in stage 3 (as of today), and they need to be worked on before reaching the final stage of the recommendation.

The status of the [proposal](https://tc39.github.io/ecmascript-asyncawait/) contains:

> This proposal was accepted into Stage 3 ("Candidate") of the ECMAScript spec process in September 2015. The champion intends for this proposal to be accepted into Stage 4 ("Finished") by the end of November.

And we are not here yet.

Finally, even the TC39 is [not yet sure of the syntax](https://github.com/tc39/ecmascript-asyncawait):

> Instead of `async function`/`await`, the following are options:
- `function^`/`await`
- `function!`/`yield`
- `function!`/`await`
- `function^`/`yield`

Let's keep async for now.

**Comment by aearly** [comment]
Yeah, I think the hassle and confusion of changing the name of this library would be greater than the hassle and confusion of colliding with a future `async` keyword.  Especcialy since `async` most likely won't be a reserved word.

In the meantime, I use "Async", "async", and "`async`" to disambiguate the library, concept, and function-type/keyword accordingly.
