### ISSUE TITLE
Memory leak when using Async.js

### ISSUE THREAD

**Issue by anhldbk** [caolan/async#1184]
**What version of async are you using?** 
^2.0.0-rc.5

**Which environment did the issue occur in (Node version/browser version)** 
v5.4.1

**What did you do? Please include a minimal reproducable case illustrating issue.**
Would you pls tell me what causes memory leak in the following code? The code is a simplified version of my server. I've desperately searched for leaks & solutions in nodejs, but I've found none. 

```js
'use strict'
const async = require('async')

function validate(x, y, callback){
  var validateX = function(cb){
    x ++
    if(cb) cb(null)
  }

  var validateY = function(cb){
    y +=2
    if(cb) cb()
  }

  async.waterfall(
    [validateX, validateY],
    function(err, result){
      validateY = null
      validateX = null
      callback(err, result)
    }
  )
}

async.forever(
  function(next){
    validate(0, 0, function(err, result){
      if(err){
        return next(err)
      }
      setTimeout(next, 5)
    })
  },
  function(err){}
)
```

**What did you expect to happen?**
The program runs without any memory leak

**What was the actual result?**
Its memory usage gradually increases

**Comment by aearly** [comment]
Have you played around with Node Inspector?  Do you know what objects or closures aren't being cleaned up?

**Comment by anhldbk** [comment]
@aearly I'm terribly sorry. After thorough profiling, there's no leak at all. So I close the issue now.
