### ISSUE TITLE
Object collection transformed to array

### ISSUE THREAD

**Issue by kumavis** [caolan/async#1188]
**What version of async are you using?**
`2.0.0-rc.6`
**Which environment did the issue occur in (Node version/browser version)**
`node v4.2.3`
**What did you do? Please include a minimal reproducible case illustrating issue.**
```js
var objCollection = { a: 1, b: 2 }
async.map(objCollection, asyncNoop, logResults)
function asyncNoop(item, cb){
  cb(null,item)
}
function logResults(err, results){
  console.log(results)
}
```
**What did you expect to happen?**
I expected to get an object as the result

**What was the actual result?**
I got an array as the result

**Comment by ex1st** [comment]
It a normal behavior for version v2 #1157

**Comment by kumavis** [comment]
@ex1st thanks

but also meh

**Comment by RobertWHurst** [comment]
Why? Am I suppose to have to write extra code now to map the results to an object?
