### ISSUE TITLE
First result of parallel not passed properly

### ISSUE THREAD

**Issue by Vinno97** [caolan/async#1196]
**What version of async are you using?**
I am using async 2.0.0-rc.6, but this also happened on 1.5.1

**Which environment did the issue occur in (Node version/browser version)**
My node version is 4.4.2 and I am running it in a cloud9.io docker.

**What did you do? Please include a minimal reproducable case illustrating issue.**
* db.getLinkedPlayers returns an array of objects.
* db.checkPlayerUsername returns a single object or undefined (in this example undefined).

I have the following code:
```javascript
async.parallel([db.getLinkedPlayers.bind(this, username), db.checkPlayerUsername.bind(this, username)], function (err, results) {
```
I expect result to be
```javascript
[
    [
        {"string", number},
        {"string", number}
    ],
    undefined
]
```
but instead I get:

```javascript
[
    [],
    undefined
]
```
At first I tought that my function was wrong, but then I tried this
```javascript
function noop(callback){
    process.nextTick(callback);
}

async.parallel([noop, db.getLinkedPlayers.bind(this, username), db.checkPlayerUsername.bind(this, username)], function (err, results) {
```
And I got.
```javascript
[
    undefined,
    [
        {"string", number},
        {"string", number}
    ],
    undefined
]
```
While this does work for me, I am fairly certain that this is not how it is intended to work. Or am I missing something obvious?

**Comment by aearly** [comment]
Does your db function callback with multiple args, or an array as the first non-error argument?

**Comment by aearly** [comment]
Does your db function callback with multiple args, or an array as the first non-error argument?

**Comment by Vinno97** [comment]
It only has the array as the first non-error argument.

The code that calls the callback basically comes down to this:

```javascript
function(err, result) {
    if (err) {
        (...)
        return callback(err);
    }
    (...)
    callback(null, result);
}
```

When I was debugging, I placed a breakpoint on line `723` and `726` in `async.js` and saw that the variable `result` got set in the first iteration, but was gone the second time. I didn't look into it any further, so it could be that I misobserved.

**Comment by aearly** [comment]
Could this be an intermittent failure of your `db.getLinkedPlayers` function?

**Comment by Vinno97** [comment]
My apologies for only reacting so late. I was quite preoccupied this weekend.

I was sure that there was no error on my side, but it appears that I was wrong. For some reason, the debugger shows the result as an empty array (even the REPL console), but when I later use the variable in my code, it appears to be correct.

I do not know why this happens, but this is also probably why I only now found out about it. Anyway, this is not a problem with `async`, but probably one of cloud9
