### ISSUE TITLE
Error using async.eachSeries

### ISSUE THREAD

**Issue by hermannlang** [caolan/async#1200]
I tried to use the example for async.eachSeries and got an error "Uncaught ReferenceError: inCache is not defined".
How can I fix it?

**Comment by megawac** [comment]
Lets say `cache` is a map... `cache = new Map`, `inCache` could be defined as follows

```js
function inCache(item) {
  return cache.has(item)
}
```

That example is only supposed to be describing a pattern. Lets say hugeArray has 5 million elements, if all the items are in the cache already we will be doing 5 million operations synchronously.
