### ISSUE TITLE
Script exits silently when using async.each instead of async.eachSeries

### ISSUE THREAD

**Issue by giacecco** [caolan/async#1201]
This is not necessarily a bug, but it may be. I am using version 2.0.0-rc.6 installed using npm on node 4.4.6.

I have a relatively complex script using async extensively. At some point in development, it started exiting silently and I have no idea why and where in the code it quits. 

By chance, I thought I could change [one point in the code](https://github.com/Digital-Contraptions-Imaginarium/twitter2rss/blob/master/twitter2rss.js#L311) where I was using _async.each_ into _async.forEach_, and I haven't had the problem since.

Of course there may be many reasons for this to happen that have nothing to do with async. Can you please suggest how you would debug the issue to understand what is happening, or any hints from your past experience with async? Thanks.

**Comment by aearly** [comment]
Sounds like you might have a race condition somewhere in your code -- relying on an asynchronous result without explicitly waiting for it.  Changing `each` to `forEach` shouldn't matter, they're the exact same function.

**Comment by megawac** [comment]
I'd suggest stepping through your code (with node inspector or iron-node) and identifying where your module fails. Not much we can suggest from our end.

https://github.com/s-a/iron-node
http://www.html5rocks.com/en/tutorials/developertools/async-call-stack/
