### ISSUE TITLE
Throw error inside series callback

### ISSUE THREAD

**Issue by electerious** [caolan/async#1211]
**What version of async are you using?**

2.0.0-rc.6

**Which environment did the issue occur in (Node version/browser version)**

v6.2.0

**What did you do? Please include a minimal reproducable case illustrating issue.**

I'm trying to throw an error inside the series callback, but the error gets caught for some reason.

The following works fine:

```js
throw new Error('throw_0') // => Node stops here

async.series([

	(next) => clean(distPath, next),
	(next) => copy(routes, srcPath, distPath, opts, next),
	(next) => run(routes, srcPath, distPath, next)

], (err) => {

	throw new Error('throw_1')

})
```

While throwing an error inside the series callback doesn't.

```js
// throw new Error('throw_0')

async.series([

	(next) => clean(distPath, next),
	(next) => copy(routes, srcPath, distPath, opts, next),
	(next) => run(routes, srcPath, distPath, next)

], (err) => {

	throw new Error('throw_1') // Node stops here, but the error gets caught somehow and never shows up

})
```

**What was the actual result?**

Node continues to execute. No error visible.

**What did you expect to happen?**

I expect that the error gets thrown and my node app crashes because of `throw_1 `.

**Comment by aearly** [comment]
Are there any try/catch blocks inside your functions that night be catching the error in the callback?

**Comment by electerious** [comment]
I'm not aware of a try..catch block that might catch the error.

The shown example is a slightly modified version from [here](https://github.com/electerious/Rosid/blob/master/src/compile.js#L48). Instead of using `next` for the callback I'm using a function to throw an error explicitly. Just to ensure that it's not a problem with `next`. As you can see, there's no try catch around it.

Walking up the call stack doesn't show a try..catch either:
https://github.com/electerious/Rosid/blob/master/src/index.js#L16 => The module that exports the compile module
https://github.com/electerious/Rosid/blob/master/bin/rosid#L52 => Where the module gets executed

**Comment by electerious** [comment]
Adding a try..catch around async.series also shows that the error doesn't even leave the module:

```js
try {

	async.series([

		(next) => clean(distPath, next),
		(next) => copy(routes, srcPath, distPath, opts, next),
		(next) => run(routes, srcPath, distPath, next)

	], (err) => {

		console.log('1')
		throw new Error('throw_1')
		console.log('2')

	})

} catch(e) {

	console.log('error', e)

}
```

Output:

```
1
```

**Comment by electerious** [comment]
I've found the problem. There's a promise deeply hidden in the `run` function. Somehow—and I've no idea why—catches all the errors, even those thrown in the async.series callback :-/

**Comment by aearly** [comment]
Yeah, a promise would catch any errors in the callstack -- including in the callbacks.  You can defer calling the callback  (e.g. `setImmediate(callback, null, results)`)  to work around that.
