### ISSUE TITLE
async.applyEach callback is not working

### ISSUE THREAD

**Issue by thatisuday** [caolan/async#1215]
I am using v2.2.0 of async.js and I am using it on client side.

I am trying basic example of async.applyEach

```
var enableSearch = function(string){
  console.info(string);
};
var updateSchema = function(string){
  console.warn(string);
};

async.applyEach([enableSearch, updateSchema], 'New msg', function(){
  console.log('It is done...');
});
```

I suppose I should expect results to be...
```
New msg
New msg
It is done
```

but some reason I am not getting `It is done`. That means callback is no firing. Anything I am doing wrong here...

**Comment by thatisuday** [comment]
And `async.applyEachSeries` calls only first function in the stack with no callback. i.e. `enableSearch`

**Comment by aearly** [comment]
Your `enableSearch` and `updateSchema` functions don't actually call any callback, so the final callback will never be called.

**Comment by thatisuday** [comment]
@aearly Oops... sorry about that.

**Comment by anusree-mmlab** [comment]
I have 2 callbacks on each enableSearch and updateSchema.
But the  final callback is called with the enableSearch callback.
