### ISSUE TITLE
async.during iteratee callback do not support optional parameter

### ISSUE THREAD

**Issue by thatisuday** [caolan/async#1217]
I am using v2.0.0 on client side.

In async.during example, if we pass a optional value in callback of iterate, javascript show error of `callback is not a function` in truthy functon.

```
var count = 0;

async.during(
    function (callback) {
        console.warn(arguments);
        return callback(null, count < 5);
    },
    function (callback) {
        count++;
        setTimeout(function(){
          callback(null, count);
        }, 1000);
    },
    function (err, res) {
        console.info(res); // 5 seconds have passed
    }
);
```

Is there anything I am doing wrong? I guess this is also mentioned in documentation that *`callback` will be passed an error and any arguments passed to the final `fn`'s callback*

**Comment by thatisuday** [comment]
This does same with `doDuring`

**Comment by aearly** [comment]
Which 2.0.0 RC version are you using?

**Comment by thatisuday** [comment]
@aearly 6

**Comment by megawac** [comment]
Any arguments you pass to callback will be passed to the predicate. Your code can be changed as follows,

```js
var count = 0;

async.during(
    function (_count, callback) {
        console.log(arguments);
        return callback(null, _count < 5);
    },
    function (callback) {
        count++;
        setTimeout(function(){
          callback(null, count);
        }, 1000);
    },
    function (err) {
        // 5 seconds have passed
        console.log("done")
    }
);
```

This probably should be documented, if you're interested send a pull request

**Comment by megawac** [comment]
There is also a bug for falsy arguments (which will cause example above not to work)

**Comment by megawac** [comment]
@aearly do we want to just remove optional parameters passed to during test functions? Doesn't seem so useful as async won't pass it in on the first call anyway

**Comment by aearly** [comment]
`whilst` and `until` also have the same weird behavior where args from the async callback are only applied on the second `test` call.  I think if you're using args from the `fn`'s callback in the `test`, you're going to be using `do(Whilst|Until|During)` instead anyway.  We should clarify the docs.

**Comment by megawac** [comment]
I think we should just remove this behaviour

**Comment by aearly** [comment]
Should we also remove the behavior for `whilst` and `until`?  (e.g. not pass any args from the async `fn`'s callback, whether its the first or later call of the test function?)

**Comment by megawac** [comment]
I think so (never found it anything but weird) but I'd like to hear anyones
opinion that uses this functionality
