### ISSUE TITLE
2.0.0 ready to go?

### ISSUE THREAD

**Issue by aearly** [caolan/async#1220]
I think its time.  Everything in the milestone is complete, and the docs site is up and running. (except for the `during` inconsistency issue, which I think is just a docs fix)

I think 2.0.0 is ready for to be released into the wild! 

cc @megawac

**Comment by megawac** [comment]
I agree after we close #1217

**Comment by gemox94** [comment]
Hi. I'm starting with node so I was following a tuto where uses async.parallel. So when I wanted to run the app it throws me an error in async module and the error was that async couldn´t  find applyEach module:
"Error: Cannot find module './applyEach'"
And I saw that the version of async was 2.0.0, so I decided to install an older version, specifically the version is 1.5.2 and the error disappeared.

**Comment by megawac** [comment]
Ohhh, thats a good point @aearly we should test all the modules after we run the compile step. Can we configure the `index.js` file mocha uses to test?

**Comment by megawac** [comment]
@gemox94 I actually can't reproduce this. Can you provide code to reproduce this issue?

**Comment by aearly** [comment]
Well, last issue closed!  I say we wait until Monday to release.  It would be bad to inadvertently cause some issues when most people are off for the weekend.

**Comment by megawac** [comment]
Sure, lets review the changelog and make sure its prepared

**Comment by tekwiz** [comment]
I just added an issue that I think should be resolved before v2 is released: #1225. I don't give a significant amount of weight to code-coverage results without a great deal of investigation into their configuration, but I feel this should be resolved before a major release.

That said, as a non-owner, I can say I am still 100% comfortable using the v2 release without code-coverage test results, so it may be more efficient to simply remove the Coveralls badge and circle back to resolve it afterwards.

**Comment by aearly** [comment]
Coverage not working isn't a showstopper.  We can fix this later.  I don't know it it has worked at all since modularization.

**Comment by megawac** [comment]
I think the issue is ES6 imports

**Comment by megawac** [comment]
@aearly lets release tomorrow@noon (est), sound good?

**Comment by aearly** [comment]
How about 1pm EST?  (9am PST is a bit early)

**Comment by 131** [comment]
It's time, it's time !

**Comment by megawac** [comment]
Hehe, a couple issues got opened last night @131, we have to triage them before release

**Comment by megawac** [comment]
https://github.com/caolan/async/milestone/1 for reference

**Comment by megawac** [comment]
Some final things I noticed giving the jsdoc a final look over:

1) document inserting multiple items into queue/cargo. Array form not documented.
2) lib/iterator isn't used at all internally. Does this even deserve to live in async any longer? I'd say kill it in favour of ES-2015 iterators which natively support arrays.
3) race to support iterables? (maybe 2.1)
4) waterfall to support iterables? (maybe 2.1)

**Comment by aearly** [comment]
3) and 4) can wait for 2.1 .  I also think Array literals are way more useful for those functions.  Supporting generic iterables could lead to some interesting control flow options I haven't foreseen though.  `race` could also support objects.

**Comment by aearly** [comment]
I :clap: Think :clap: We're :clap: Ready :clap: To :clap: Go :open_mouth:

**Comment by megawac** [comment]
![](https://media.giphy.com/media/wJEeKGplvQwr6/giphy.gif)

**Comment by aearly** [comment]
2.0.0 is live! https://www.npmjs.com/package/async

**Comment by aearly** [comment]
Now we wait for the inevitable bug reports... :dizzy_face: :sweat_smile:

**Comment by megawac** [comment]
Do you have some unstaged changes to docs @aearly? Generating the docs on my machine don't turn out the same as gh-pages?

**Comment by aearly** [comment]
Nope, everything is up to date on my end.  What's different?
