### ISSUE TITLE
reduce callback isn't really optional

### ISSUE THREAD

**Issue by asquared** [caolan/async#1223]
**What version of async are you using?**
1.5.2 (but the offending code seems to still exist in master)

**Which environment did the issue occur in (Node version/browser version)**
node v0.10.29

**What did you do? Please include a minimal reproducable case illustrating issue.**
The documentation says the callback is optional, so I should be able to do:
```
const async = require('async');

var array = [1, 2, 3];
function reducer(memo, item, callback) {
        memo += item;
        console.log("sum is %d", memo);
        setImmediate(callback, null, memo);
}

async.reduce(array, 0, reducer);
```

**What did you expect to happen?**
```
sum is 1
sum is 3
sum is 6
```

**What was the actual result?**
```
sum is 1
sum is 3
sum is 6

.../node_modules/async/lib/async.js:380
            callback(err, memo);
            ^
TypeError: undefined is not a function
    at .../node_modules/async/lib/async.js:380:13
    at .../node_modules/async/lib/async.js:52:16
    at .../node_modules/async/lib/async.js:269:32
    at .../node_modules/async/lib/async.js:44:16
    at Object.<anonymous> (.../node_modules/async/lib/async.js:377:17)
    at Object.immediate._onImmediate (timers.js:354:16)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by megawac** [comment]
Yeah, actually looking into this a lot of methods are documented to have optional callbacks when they are clearly required

(filter, map, etc)

**Comment by megawac** [comment]
Should these be optional or not @aearly

**Comment by asquared** [comment]
In my case it's helpful if they're optional. At each step of the reduce I
can delete a file until a certain amount of data has been removed. The
total bytes remaining to be deleted are passed along in the memo. I don't
care about the final result - just the side effect of files getting deleted
- so I'm using an empty callback.

**Comment by aearly** [comment]
Yeah, they should all be optional.  I do think it's odd that you would use `map` or `filter` and then ignore the result, but we should make the callback optional for consistency with other methods.

**Comment by megawac** [comment]
I think `sortBy` should be the only one required -- any objection @aearly?

**Comment by aearly** [comment]
Yeah, there'd be no reason to use `sortBy` and ignore the result.
