### ISSUE TITLE
Coveralls code-coverage out of date

### ISSUE THREAD

**Issue by tekwiz** [caolan/async#1225]
It appears that the code-coverage results are out of date (invalid?).  The most recent build was on March 31, and it appears that only `karma.conf.js` was evaluated (https://coveralls.io/github/caolan/async).

**Comment by megawac** [comment]
Nevermind that fix didn't work
https://travis-ci.org/caolan/async/jobs/143901451#L1984

**Comment by tekwiz** [comment]
@megawac There were some errors when the tests were run under nyc.  I've submitted #1234 to fix that.  I believe that is the underlying problem with the Coveralls report.

**Comment by tekwiz** [comment]
Bingo! The coveralls report ran after npm coveralls script line fix https://github.com/caolan/async/pull/1234/commits/00f12da45d6df7b9e5115996d5071ae759531e1e
https://coveralls.io/builds/6972426
