### ISSUE TITLE
retry: unable to log "Retrying in x minutes"

### ISSUE THREAD

**Issue by djensen47** [caolan/async#1226]
When using `retry` or `retryable`, I would like to log that the retry will happen in _x_ milliseconds/seconds/minutes.

For instance,
```
[Jul 11, 2016 14:25:37] This API key has reached their API limit for the hour. Please wait before making another call.
[Jul 11, 2016 14:25:37] Retrying in 5 minutes.
```

If I try to log this in the interval function, it does not work because the interval function precomputes the intervals and pops them into another async method.

The task callback function doesn't make sense because that happens _after_ the interval has elapsed and I don't know anything about the retry interval (nor should I). 

Maybe there should be another callback that can be invoked prior to waiting on the interval time period?

**What version of async are you using?**
2.0.0-rc6

**Which environment did the issue occur in (Node version/browser version)**
Node 6.2.1

**Comment by megawac** [comment]
+1 I don't see why these intervals should be precomputed, /cc @aearly

**Comment by djensen47** [comment]
💯  Thanks and the code looks cleaner too!
