### ISSUE TITLE
applyEach arguments position

### ISSUE THREAD

**Issue by jamiebuilds** [caolan/async#1228]
Currently the `applyEach` and `applyEachSeries` functions have the following type signature:

``` js
async.applyEach(fns, ...args?, callback?)
```

Having a rest parameter in the middle of the arguments list is very difficult to write a type annotation for. It's currently not possible in either Flow or TypeScript, which is why you see stuff [like this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/async/async.d.ts#L132-L133) (I'm writing a similar type definition for Flow right now).

Would it be okay to switch the argument order around and make callback nullable so it is like this?

``` js
async.applyEach(fns, callback | null, ...args?)
```

Or use an array instead of a rest parameter?

``` js
async.applyEach(fns, args?: Array<any>, callback?)
```

**Comment by megawac** [comment]
`doDuring`'s test function also has that constructor definition. I think @aearly will have some feedback as its fresh in his mind (#1217)

**Comment by aearly** [comment]
I'd really prefer to always have a callback be the last arg of any async function, as per node's style.  I think using an array for the args would be a good compromise.  It also has more symmetry with the native `Function.apply`.

```js
async.applyEach(fns, args?: Array<any>, callback?)
```

Also, the problem here is `function (arg1, ...args, arg2)` right?  `function(...args, callback)` is type-able in TypeScript/Flow?  There are many functions in Async that have the latter signature -- `waterfall` tasks, `doDuring`'s test function, `autoInject` tasks...

**Comment by thejameskyle** [comment]
> Also, the problem here is `function (arg1, ...args, arg2)` right? `function(...args, callback)` is type-able in TypeScript/Flow?

I'm afraid not, in both type systems rest params are only allowed as the final param.

> `doDuring`'s test function also has that type of function definition.

I don't understand. [According to the docs](http://caolan.github.io/async/docs.html#.doDuring), it doesn't appear to have anything similar.

**Comment by megawac** [comment]
The test function is of the syntax `function test(err, ...args, callback)`

**Comment by aearly** [comment]
Nah, it's `(...args, callback)` like many others: https://github.com/caolan/async/blob/master/lib/doDuring.js#L29

**Comment by thejameskyle** [comment]
Wait, I'm sorry, I'm so confused...

Do you mean like this?

```js
async.doDuring(fn, function test(...args, callback) {
  // ...
}, callback);
```

or this?

```js
async.doDuring(fn, function test(callback) {
  callback(...args, function() { /* ... */ });
}, callback);
```

or something else?

**Comment by aearly** [comment]
The first one.  This was recently updated; it's not released yet so the docs are a bit inaccurate.

**Comment by thejameskyle** [comment]
Ah, okay. That's the source of my confusion.

From the perspective of authoring type definitions I'd advise against an api like that. But if it adds a lot of value I guess it might be worth it.

**Comment by aearly** [comment]
Yeah, I understand.  Unfortunately, "function(...args, callback) {}" describes every node-style async function, so it's an API we have to support.

Do you think TypeScript might be enhanced to allow that form?  Or would it lead to ambiguities?

**Comment by thejameskyle** [comment]
I don't know what the TypeScript team does and does not want to do. I'll ask some others on the Flow team what their thoughts are.

**Comment by aearly** [comment]
BTW, I'm :+1: for having the `args` be an array in the case of `applyEach`.  Having an optional param after a rest param will always lead to ambiguities.

**Comment by megawac** [comment]
@aearly lets make this a v3 feature to consider

**Comment by aearly** [comment]
Agreed.  It's also possible that Flow and TS might be augmented in the interim.

**Comment by thejameskyle** [comment]
So current status about having rest parameters in a type system:

It might be possible to have within library definitions without ambiguity. However, because rest parameters aren't allowed at the start/middle of a parameter list, it would be impossible to write a type definition within the normal syntax.

```js
function method(a, ...b, c) { } // can't be turned into valid es6 without a syntax transform.
```

**Comment by aearly** [comment]
Yeah, I understand that.  It's a bit tricky, since we have a scenario where the rest params are untyped, except for the last one.  We basically implement it like this:

```
function foo(...args) {
  var callback = args.pop();
  ///...
}
```

So while the actual argument syntax can't be directly implemented in ES6, we have a situation where there's the possibility for extra type information on top of what ES6 allows.

**Comment by thejameskyle** [comment]
I've proposed allowing the usage of spread elements within tuples to solve this case:

```js
function method(...args: [string, ...number, boolean]) {}
```

**Comment by aearly** [comment]
I'm revisiting this, and I'm not sure there's any way to satisfy TypeScript. 

The proposal is to change `applyEach` to use an array for the initially applied args.

```typescript
async.applyEach(fns, args?: Array<any>, callback?)
``` 

However, both `args`, and `callback` are optional.  When they are both omited, a function is returned with the signature (invalid typescript):

```typescript
appliedFn(...args: Array<any>, callback?)
```
This is designed to be slotted into `waterfall` and similar.

We could change those `args` to be an array, but that severely limits the usefulness of the method, having to combine arguments into an array.  The `each` example in the docs becomes pretty clunky:

```js
async.each(
    buckets.map(bucket => [bucket]), // have to turn each item of the array into an array
    async.applyEach([enableSearch, updateSchema]),
    callback
);
```

------

Another posibility is to deprecate the partial application feature of `applyEach`.  With arrows being available basically everywhere now, the above example could become:

```js
async.each(
    buckets,
    (bucket, next) => async.applyEach([enableSearch, updateSchema], [bucket], next),
    callback
);
```

A bit more clear, and less magic involved.

**Comment by aearly** [comment]
Another option:

Make the args required, don't accept a callback, and return a function that only takes a callback.  This turns it into a wrapper method that hooks two or more functions together.

```typescript
async.applyEach(fns, ...args: Array<any>)
```

Which returns a function of the type:

```typescript
fn(callback?: Function)
```

The example in the docs would become:

```js
async.each(
    buckets,
    (bucket, next) => async.applyEach([enableSearch, updateSchema], bucket)(next),
    callback
);
```

Or to be even more clever:

```js
async.each(
    buckets,
    async bucket => async.applyEach([enableSearch, updateSchema], bucket)(), // the returned function could be made awaitable
    callback
);
```
