### ISSUE TITLE
PriorityQueue execution order

### ISSUE THREAD

**Issue by suguru03** [caolan/async#1229]
**What version of async are you using?**
v2.0.0-rc.6, master

**Which environment did the issue occur in (Node version/browser version)**
Node

**What did you do? Please include a minimal reproducable case illustrating issue.**
https://github.com/caolan/async/blob/master/mocha_test/queue.js#L405-L431
If I changed `queue` to `priorityQueue`, the order is reversed.

```js
var call_order = [];
var q = async.priorityQueue(function (task, callback) {
    if (task.isLongRunning) {
        q.pause();
        setTimeout(function () {
            call_order.push(task.id);
            q.resume();
            callback();
        }, 50);
    }
    else {
        call_order.push(task.id);
        setTimeout(callback, 10);
    }
}, 10);

q.push({ id: 1, isLongRunning: true});
q.push({ id: 2 });
q.push({ id: 3 });
q.push({ id: 4 });
q.push({ id: 5 });

q.drain = function () {
    expect(call_order).to.eql([1, 2, 3, 4, 5]); // [5, 4, 3, 2, 1]
    done();
};
```

**What did you expect to happen?**
I think first task should be executed at first if priority wasn't defined.

**What was the actual result?**
`[ 5, 4, 3, 2, 1 ]`

**Comment by aearly** [comment]
@megawac probabaly related to the DLL changes.
