### ISSUE TITLE
reduceRight docs say takes object|array; only supports array

### ISSUE THREAD

**Issue by megawac** [caolan/async#1232]
Because `reduceRight` calls `Array.prototype.slice` on the passed in collection it only supports `Arrays`

This begs the question, is reversing an object really a good pattern? How about an iterator? If yes, should implement `eachRight`, `eachOfRight` and friends?

Also should we document `Iterable` support on all methods supporting iterators? Currently we only state we support `Array | Object` in these cases.

**Comment by aearly** [comment]
If you were using an iterator with `reduceRight`, you'd have to expand it into an array, e.g. `async.reduceRight([...iterator], iteratee, cb)`.  If your collection offered some sort of reverse iterator, you'd use that instead.  Reversing the keys of an Object is mostly meaningless.  I think it's fine if `reduceRight` only works with arrays.

**Comment by megawac** [comment]
Okay, second part. Should `each*`, `eachOf`, `map*`, `filter*`, etc be documented to take Iterables?

**Comment by aearly** [comment]
Ah, yes.
