### ISSUE TITLE
To kill async.iterator or not to kill

### ISSUE THREAD

**Issue by megawac** [caolan/async#1237]
As far as I can tell, `async.iterator` is not used internally despite being documented as an exposed internal method. As mentioned in #1220, I think it's time we leave this method in the dust in favour of ES2015 iterator protocol (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) which natively supports arrays

**Comment by aearly** [comment]
Yeah, I think we can kill it.  It used to be used internally in `waterfall`, and I think caolan just exposed it in case anyone found it useful.  It's been superseded by native iterator support.
