### ISSUE TITLE
Browserify async require

### ISSUE THREAD

**Issue by seonixx** [caolan/async#1240]
Excuse my lack of indepth knowledge on the subject, but I'm trying to use async in the browser with NPM/browserify, rather than bower.

However the async module is not being attached to the window, in the same way that libraries like lodash do.

Is this expected behaviour? Is the bower package the only package that will attach to window on load?

**Comment by aearly** [comment]
Yeah, one of Browserify's goals is to not attach extra properties to `window`.  Standard practice with is to browserify any code that needs access to a npm module, with `var foo = require("foo")` at the top.

If you really need async as a global, just put `window.async = require("async")` somewhere.

**Comment by megawac** [comment]
We don't expose async to the window if you load it up with require. If you want it to be exposed globally you can do it manually

Lodash being exported to the window when imported with browserify is a bug imo (https://github.com/lodash/lodash/issues/1852, https://github.com/lodash/lodash/issues/2251, lodash/lodash#1798, etc)
