### ISSUE TITLE
How to sort an async queue?

### ISSUE THREAD

**Issue by sandromartis** [caolan/async#1243]
Hey there

Before version 2.0.0 of async I was using the `queue.tasks` array to manually re-sort the queue after the items have already been pushed to the queue.
I just used `array.sort` and it was working perfectly fine for my use case.

The switch to Doubly Linked Lists in v2.0.0 unfortunately broke my implementation.
Now my question: Is there an easy way to sort an `async.queue` on the fly?

Of course I could always drain the queue, sort everything and pump it back into the queue, but it would be nice if there was some way to directly sort on the async queue.

If this is indeed not built into `async.queue` yet, I could try to implement it.
It could imagine something like `queue.sort(compareFunction)` that accepts a `compareFunction` similar to `array.sort`.

```
var points = [40, 100, 1, 5, 25, 10];
points.sort(function(a, b){return a-b});
```

Unfortunately I don't really know how easy that would be with Doubly Linked Lists, since I'm not very familiar with those.

Best,
Sandro

**Comment by megawac** [comment]
Can you not use a priorityQueue if you care about order? 

Don't know how big your queues are but a bubble sort is extremely straightforward for dlls - otherwise you can look into other sort methods

http://stackoverflow.com/questions/15048327/bubble-sort-on-double-linked-list

**Comment by sandromartis** [comment]
The priorityQueue does not really solve this for me since I need to give the item a priority as I push it to the queue. And there seems to be no easy way to change the priority afterwards.
(Please correct me if I'm wrong here)

But for my use case I need to be able to re-sort the queue after all the items have been added and while the workers are already working on the queue.
My queues are usually 5000 - 30'000 items and I need to be able to sort them every couple of seconds based on some euclidian distance.

I was just wondering if some kind of sort method on the queue would be something you guys (or some users) are interested in. If so, I would be happy to give it a shot and contribute.
If not, I will just stick with v2.0.0-rc.6 for now or implement my own queuing system.

**Comment by aearly** [comment]
A really hacky, may-break-in-the-future solution would be to:

```js
var q = async.queue(worker);
q._tasks = [];
```

This would cause the queue to use an array internally, and your sort would work again.

I'm not thrilled about adding a sort method to the queue.  An O(n^2) bubble sort gets ugly, especially when n = 30,000.

But honestly, what you're doing is pretty unique, and pushing the limits of our queue.  Since you're constantly re-sorting,  you might be better off in the long run having your app own that logic.

**Comment by sandromartis** [comment]
Allright, thank you for the feedback.

I guess I will look around for some other solution or implement my own thing.

Best,
Sandro

**Comment by megawac** [comment]
@sandromartis if you're interested I think this would make a good third part extension. You should be able to implement quick or merge sort for DDLs (http://stackoverflow.com/a/6065792/1517919) however it gets tricky.

Using @aearly's solution is a fine work around IMO as we intentionally are using array compatible apis for everything but priority queue

**Comment by megawac** [comment]
By the way, related reference http://jonisalonen.com/2013/sorting-a-linked-list/

**Comment by megawac** [comment]
@aearly I'd be open to supporting this btw, though if we did we would probably not want to use a doubly linked list and instead use a heap (which would have a couple other benefits, especially for priorityQueue). I think I'll play around with this tonight

**Comment by aearly** [comment]
So we would use a heap for `priorityQueue` s only?  I don't see how a heap would benefit an ordinary queue.

A heap also wouldn't help @sandromartis 's use case much.  He'd get O(nlogn) sorts, but he's still have to resort manually.

**Comment by megawac** [comment]
Yeah, I don't think this makes sense to belong in async. I don't think the tradeoffs are worth it. It would be awesome if someone implemented a heap that was compatible with our queue (so you could do 

```
var q = async.queue(worker);
q._tasks = new Heap();
```
