### ISSUE TITLE
eachOfLimit with limit < 1 should error

### ISSUE THREAD

**Issue by megawac** [caolan/async#1249]
Currently instantly resolves. I think this should be a case we throw an error in.

**Comment by aearly** [comment]
I agree, a limit of 0 or less would certainly be a programmer error.

It's weird that we have a test for the old behavior.  I'm not sure how limit 0 would be useful to anyone.

**Comment by vkstack** [comment]
Definitely throw an error.

**Comment by mikael-entefy** [comment]
Please also throw on undefined.
That would have made finding my `async.eachLimit(list, config.propWithType, fn)` bug way easier.
