### ISSUE TITLE
Async.each / Async.eachSeries

### ISSUE THREAD

**Issue by zevero** [caolan/async#1250]
**What version of async are you using?**
upgrade from v1.5.2 to v2.0.0 

**Which environment did the issue occur in (Node version/browser version)**
linux node 6.2.2

**What did you do? Please include a minimal reproducable case illustrating issue.**
async.each(addresses, function(address){ async db query / or lookup via google api})
addresses has 8000 entries.

**What did you expect to happen?**
It worked in v1.5.2 but did not work anymore in v2.0.0

**What was the actual result?**
Error: Maximum call stack size exceeded
I tried to change for async.eachSeries ... but it did not help.
I tried to set --max-stack-size=100000 or --stack-size=100000 but I use it via gulp ... so I am not sure if gulp really passes this on to node.

I just downgraded to v1.5.2 for now.
Thought it may be of interest to you since 2.0.0 just came out ...

**Comment by ex1st** [comment]
Pleas check this - https://github.com/caolan/async/pull/604

**Comment by zevero** [comment]
yeah ... this seems to have been corrected in v1.
I did not manage to understand the code for v2 ... but I suspect, that this setImmediate() trick was not used ...

**Comment by zevero** [comment]
Thank you. This was very helpful.
Just for the record - here is how I solved my situation: 

    complete_addresses  = [];
    async.each(addresses,function(address, cb) {
        db.address.getCoordsOrGeolookup(address, function(err,coords){
          if (err) throw new Error(err.message);
          complete_adresses.push({coords:coords, address:address);
          cb();
        });
      }, cb_all_done);

I can use v2 now by replacing 3rd line with

     setImmediate(db.address.getCoordsOrGeolookup, address, function(err,coors){...})

Hurray!
