### ISSUE TITLE
How to make a synchronous call from a Promise?

### ISSUE THREAD

**Issue by arjungowdaa** [caolan/async#1259]
Hi, I have implemented REST API in NodeJS with Promise. I have 3 Promises. From one of the promise am calling a module which is in different module file. However by the time I get response from the module the flow in Promise is moving ahead. How can I make this module call synchronous?

I could have added another Promise but I don't want to include that module code within this API. Any suggestions? Will async library help me to achieve this?

Am using v4.4.2 version of Node.

Regards, AG.

**Comment by megawac** [comment]
Consider using [`async.asyncify`](http://caolan.github.io/async/docs.html#.asyncify) which will transform both promise returning functions and synchronous functions to our expected callback format
