### ISSUE TITLE
Using with non async code

### ISSUE THREAD

**Issue by Brakkar** [caolan/async#1260]
Hi I really like how this package allows to structure code, for example the waterfall way.
Does it make any sense to use it to structure non async code ? Like create functional style waterfall with non async code ? Anybody does this kind of usage ?
Or is it too much overhead in therms of performance ?

**Comment by megawac** [comment]
It can often be useful to reason about code with the assumption that its always asynchronous. This has the benefit of avoiding some race condition scenarios.

However, of course it will generally be faster to execute code synchronously. I would generally not worry about it as async attempts to be very well optimized and attempts to minimize overhead in general. Also, do note that asyncjs does not gaurentee that callbacks are async. For instance in the example below, the done callback is called synchrnously

```js
function done() { }
function instantResolver(val, cb) {
   cb();
}

async.each([1], instantResolver, done);
```

Let me know if you need clarification on any of these points, feel like I didn't explain it all so well.
```
