### ISSUE TITLE
async/queue: iterates pending tasks

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [caolan/async#1262]
I use async/queue, while adding task to queue,   I keep resolve and reject functions returned from promise as attributes in task. async/queue doesn't call application specific callback during kill if any pending task related activities to be handled by application.

Before closing down serial port, I should reject pending requests in the task queue. Right now, I made my cleanup function this way.

```
    //PATCH: Fixme, request feature from async/queue
    //mercyKill takes callback for each task cleanup 

    //this is expected to go inside async/queue
   //or   modify existing async/queue kill to achive similar results

    queue.mercyKill = function(callback) {
        if (!callback) 
            return this.kill();

        while ( this._tasks.length > 0){
            var node  = this._tasks.shift();
            callback(node.data);
        }
    }

    //my application
    queue.mercyKill(function(task){
        console.log("Cleaning task ", task.id);

        if (task && task.reject) {
            task.reject("serial port closed");
        }
    });
```

I searched APIs in async documentation, I could not get any. I can do pull request with right fix inside async/queue if you approve API.

**Comment by megawac** [comment]
Where is that callback coming from?

Anyway, right now you can implement this as below. I'm not sure I'm a fan of exposing something like "mercyKill" (definitely needs a better name at least ;) but I'll give it some more thought

```js
queue.kill = function() {
  var node;
  while (node = this._tasks.shift()) {
    callback(node.data);
  }
}
```

**Comment by gopalakrishnan-subramani** [comment]
mercyKill is a sudo name. The proposal is to modify https://github.com/caolan/async/blob/master/lib/internal/queue.js implemented as given below. Since application creates tasks, then adds to queue, during kill/emptying queue, application need to cleanup the resources. In my case, I store promise's resolve and reject, I have 100 of them in each serial and tcp ports queued. 


Original Code: https://github.com/caolan/async/blob/master/lib/internal/queue.js

```

var q = {
        _tasks: new DLL(),
        
        ...
         
        kill: function () {
            q.drain = noop;
            q._tasks.empty();
        }
}
```

Proposal


```
var q = {
    _tasks: new DLL(),
    
    ...
     
    kill: function (callback) {
        q.drain = noop;
        if (!callback) {
            q._tasks.empty();
            return;
        }

        //call callback to clean-up task created by application
        var node;
        while (node = q._tasks.shift()) {
            callback(node.data);
        }
    }
}
```

Below is my library source code, each task has reject, resolve, I need to call promise reject before closing serial port.  

```
this.requestQueue.kill(function(task){
    if (task && task.reject) {
        task.reject("serial port closed");
        task.reject = null;
        task.resolve = null;
    }
});
```

**Comment by aearly** [comment]
I feel this is a bit niche to add to Async core.  It looks like you have a good workaround that fits your specific use case.
