### ISSUE TITLE
async.timeout

### ISSUE THREAD

**Issue by jan-osch** [caolan/async#1264]
Could you please provide some examples how to use `async.timeout`? I can't understand how to  pass parameters and non-timeout errors to the `wrapped` function.

**Comment by hargasinski** [comment]
Hi @jan-osch, thanks for question!

The `wrapped` function returned by `async.timeout` is invoked the same way as the `asyncFn` you pass in, assuming it follow the node convention of having a callback as the last argument. The only difference is that if it takes longer than the  `milliseconds` passed in when wrapping it, the callback will be passed an error with the code `ETIMEDOUT`.

For example, if this is the function you want to wrap:
```js
// your async function you want to timeout after a certain amount of time, e.g. 500 ms
function apiMethod(req, callback) {
    api.getData(req, function(err, data) {
        // pass any errors the same way you would normally
        if (err) return callback(err);

        // do your processing on data
         
        // pass results to the callback as you normally would
        return callback(null, data);
    )
}
```

and you normally call `apiMethod`:

```js
apiMethod({ foo: 'foo' }, function(err, data) {
    if (err) return handleError(err); // your error handler 
    
    // the rest of your code
});
```

Then to wrap it in `async.timeout`, you would just do:

```js
var wrappedApiMethod = async.timeout(apiMethod, 500);

// now you can invoke it exactly the same way as apiMethod
wrappedApiMethod({ foo: 'foo' }, function(err, data) {
    // if the method takes more than 500 ms to execute err will have the
    // code `ETIMEDOUT`
    if (err) return handleError(err);
    
    // the rest of your code
});
```

I'll update the [timeout docs](http://caolan.github.io/async/docs.html#.timeout) to hopefully make this a little more clear.

**Comment by jan-osch** [comment]
@hargasinski Thank you for explanation!  Now I get it, updating the docs is a good idea, the example you showed is excellent.
