### ISSUE TITLE
Allow to continue after failure

### ISSUE THREAD

**Issue by piranna** [caolan/async#1269]
Async APIs calls to their callback function as soon as there's a failure. I propose to add an option to do just the oposite: if there's an error, continue with the other tasks until they finish, and only in that moment call to the callback with the error (or errors). This can be useful for example with `parallel` to finish all the tasks instead of left some of them unfinished.

**Comment by aearly** [comment]
You raise an interesting point.  Currently we callback immediately out of simplicity.  One argument would be that this is the correct thing to do -- you are notified of the error immediately.  The state of the pending tasks might be irrelevant in that case.

On the other hand, if you needed to do some cleanup in response to that error, it would be nice to know there are no pending tasks still running.   Waiting for pending tasks to complete in the event of an error would complicate our code a bit.   I'm also not sure what the api would look like to make it optional either.

**Comment by piranna** [comment]
The solution I'm doing is to wrap my async functions and in case they fail, store the error in an array and call the Async.js callback as "success", and later check the errors array to see if something went wrong. This way I only call directly the Async.js callback with an error in case of really critical ones. You can see the code at https://github.com/piranna/download-manager/blob/master/index.js

**Comment by aearly** [comment]
Have you also seen `reflect`/`reflectAll`?  They make every async task complete successfully, and wraps the result down to a `{error, result}` object you can then inspect.

**Comment by piranna** [comment]
> Have you also seen reflect/reflectAll? They make every async task complete successfully, and wraps the result down to a {error, result} object you can then inspect.

Didn't know about them, good to now.

**Comment by aearly** [comment]
I think this use case is well-handled by `reflect`/`reflectAll`.
