### ISSUE TITLE
Feature Request: async.if

### ISSUE THREAD

**Issue by mafrides** [caolan/async#1272]
I have been using async for game dev, and I often run into this use case: 

in async series or waterfall, I want to conditionally run some of the steps.

Currently, I use a construct like this:

async.series([
  test ? callback : async.constant(null),...

I would like to be able to write the following:

async.series([
  async.if(test, callback),...

and have it do the same as above

if this is something that would fit with the library, I'd love to try implementing it.  Would be my first open source contribution.

Thanks,
Michael

**Comment by hargasinski** [comment]
Hi Michael,

Thanks for the suggest! We've had a couple of similar suggestions in the past (see #1212, #949), but historically async has been against logic helpers. You seem to have a conditional that works fine.

If you want this as a function, have a look at @aearly's [provided](https://www.npmjs.com/package/acomb#provided). I think it provides the functionality you need. Thanks.
