### ISSUE TITLE
Upgrade guide for 1.5.x to 2.0.x

### ISSUE THREAD

**Issue by akarshsatija** [caolan/async#1273]
Is there any upgrade guide for upgrading? Or is the newer version 2.0.x compatible with 1.5.x?

**Comment by hargasinski** [comment]
There have been a few breaking changes from 1.5.x to 2.0.x that could have an impact on your code. They're all listed under the [Breaking Changes](https://github.com/caolan/async/blob/master/CHANGELOG.md#breaking-changes) section of v2.0.0 in the [changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md). You should read those first, but for the most part, you shouldn't have any major problems upgrading.
