### ISSUE TITLE
"autoInject task functions require explicit parameters." error when using async.constant()

### ISSUE THREAD

**Issue by zatziky** [caolan/async#1276]
**What version of async are you using?**
2.0.1

**Which environment did the issue occur in (Node version/browser version)**
Node v. 6.2.2

**What did you do? Please include a minimal reproducable case illustrating issue.**
```
async.autoInject({
            hostname: async.constant("xxx"),
}, callback);
```

**What did you expect to happen?**
That the autoInject passes without issues an error.

**What was the actual result?**
error - "autoInject task functions require explicit parameters."

**More Details**
The same piece of code works well with `auto()`.

```
async.auto({
            hostname: async.constant("xxx"),
}, callback);

```

In order to make it working with `autoInject()` I had to wrap the method a function with a param.

`hostname: callback => async.constant("xxx"),`

It seems that function return by `async.constant()` does not work well with `autoInject`.

**Comment by megawac** [comment]
yeah, `autoInject` parses the function signature (i.e. usings `function.toString()` which is kind of hacky and not resilient to things like this case). `constant` creates a function with a wrapper which `autoInject` can't understand.

Consider this a limitation of `autoInject`, personally I recommend using `auto` over `autoInject`
