### ISSUE TITLE
Error "Callback was already called." even when was not called.

### ISSUE THREAD

**Issue by adambisek** [caolan/async#1279]
Error "Callback was already called." occurs when is no callback called. Look at my code, it looks like some overloading issue.

Test case:

```
  const listJobs = (next) => {
    next(null, {
        queued: {},
        running: {},
        done:{},
    });
    return null;
  };

  const getSystemInfo = (next) => usage.lookup(process.pid, next);

  async.parallel([
    getSystemInfo, // its function, calls callback "(err, next)"
    listJobs, // its function, calls callback "(err, next)"
  ], (err, result) => {
    if (err) {
      return;
    }
    result[0].queued = 1; // HERE is the problem. it looks like overloading issue
  });
```

Async version: 2.0.1, Node.js v 6.2.2, Babel transpiler for ES6.

Expected: Assign variable to object property. Yes, it is for 100% an object.

Actual: 
/Users/webserver-nodejs/spider-crawler/node_modules/async/dist/async.js:844
            if (fn === null) throw new Error("Callback was already called.");                             ^

Error: Callback was already called.
    at /Users/webserver-nodejs/spider-crawler/node_modules/async/dist/async.js:844:36
    at /Users/webserver-nodejs/spider-crawler/node_modules/async/dist/async.js:3676:17
    at /Users/webserver-nodejs/spider-crawler/node_modules/async/dist/async.js:339:31
    at /Users/webserver-nodejs/spider-crawler/node_modules/usage/lib/providers/ps.js:21:9
    at ChildProcess.exithandler (child_process.js:198:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)

**Comment by adambisek** [comment]
Just now, I get rid of this problem.
The problem was maybe in 3rd party library, but still I can't understand, how can it occur on mentioned line, when assigning to a property.

**Comment by hargasinski** [comment]
Thanks for the report! `async.parallel` is expected to throw an error if one of the `tasks` calls `callback` (or `next` in this case) more than once. I tried running the test case, both transpiled and not, and it ran without an error, so like you said, it's probably another library you're using calling it multiple times.  

Also, what makes you say that it is the assignment causing the error? If removing a library removed the error, and since the error stack doesn't mention anything about it, could the cause of error be something else?

**Comment by haozxuan** [comment]
i have this problem too, and i can reappear it. 

test code

    var MongodbClient = require('mongodb').MongoClient,
        dbStack = {};

    function createConnect(mongodbInfo, next) {
        var ip = mongodbInfo.ip,
            port = mongodbInfo.port,
            name = mongodbInfo.dbName,
            connectId = ip + port + name,
            username = mongodbInfo.username,
            password = mongodbInfo.password,
            auth = encodeURIComponent(username) + ":" + encodeURIComponent(password) + "@";

        if (!username || !password) auth = '';

        dbStack[connectId] = dbStack[connectId] || {};

        if (dbStack[connectId].sta === "OK") {
            next(null, dbStack[connectId].connect);
        } else {
            dbStack[connectId].next = dbStack[connectId].next || [];
            dbStack[connectId].next.push(next);

            if (dbStack[connectId].sta !== "BUSY") {
                dbStack[connectId].sta = "BUSY";

                var url = "mongodb://" + auth + "127.0.0.1:27017/table";

                MongodbClient.connect(url, function (err, db) {
                    if (err) {
                        console.error("mongodb connect %s false, err is ", connectId, err);
                        delete dbStack[connectId].sta;
                        return next(err);
                    }

                    dbStack[connectId].connect = db;
                    dbStack[connectId].sta = "OK";
                    for (var i in dbStack[connectId].next) {
                        dbStack[connectId].next[i](null, db);
                    }
                    dbStack[connectId].next = [];

                    db.on('close', function (reason) {
                        console.error('mongodb connection %s is closed. reason is ', connectId, reason);
                        delete dbStack[connectId].sta;
                        delete dbStack[connectId].connect;
                        return next(reason);
                    });

                    db.on('error', function (reason) {
                        console.error('mongodb connection %s err. reason is ', connectId, reason);
                    });

                    db.on('parseError', function (reason) {
                        console.error('mongodb connection %s err. the driver detects illegal or corrupt BSON being received from the server. reason is ', connectId, reason);
                    });

                    db.on('reconnect', function (info) {
                        console.error('mongodb connection %s has reconnected and re-authenticated. information is ', connectId, info);
                    });

                    db.on('timeout', function (err) {
                        console.error('mongodb connection %s timeout. please check mongodb connect num. err is ', connectId, err);
                    })
                })
            }
        }
    }

    var conf = {
        ip  : "localhost",
        port: 27017,
        name: 'table'
    };

    function Foo(next) {
        createConnect(conf, function (err, db) {
            if (err) {
                console.log('err is ', err);
                return next(err);
            }

            db.collection('objects').find({}).limit(1).next(function (err, res) {
                if (err) {
                    console.log('get err is ', err);
                    return next(err);
                }
                console.log('hello world', res);
            })
        })
    }

    var async = require('async');

    setInterval(function () {
        async.each([1,2,3], function (item, next) {
            Foo(next);
        }, function (err, res) {
            console.log('err res is ', err, res);
        })
    }, 1000)

when u run this code,   it work well, but when stop mongodb server, this demo will keep alive with   some error message, and restart mongodb server, this demo stdout well, important is that. when you second stop mongodb server, this demo will crash by "Error: Callback was already called." this is confuse me so much. and i change factor by not use async,  looks like that:

    setInterval(function () {
        Foo(function (err) {
            console.log('Foo err is ', err);
        })
    }, 1000)

 this demo work well. so i think maybe async do something  effect that;

**Comment by adambisek** [comment]
What is the conclusion please?

**Comment by hargasinski** [comment]
`async.parallel` is behaving as expected, it throws an error if `callback` is called more than once. See the **Multiple Callbacks** section of the [docs intro](http://caolan.github.io/async/) for a little more information. Since you were able to get rid of the error after removing the third party library, the library was most likely calling it multiple times and causing `async` to throw the error.

**Comment by adambisek** [comment]
Thanks for reply, I am gonna check that out.

Note: I am still using the library, what was problematical (I am importing only one except the async), but I have rewritten it this way, and it works - but I really cant see, where was the problem. Maybe you could see(?), maybe it would be helpful for someone other.

```
const listJobs = (next) => {
    next(null, {
        queued: {},
        running: {},
        done:{},
    });
    return null;
  };

const getSystemInfo = (next: Function) => {
  usage.lookup(process.pid, (err, result) => {
    if (err) {
      return next(err);
    }
    const ret = result;
    ret.memoryFormatted = `${Math.round(ret.memory / 1024 / 1024)}M`;
    return next(null, ret);
  });
};

export const status = (req: Object, res: Object) => {
  async.parallel({
    systemInfo: getSystemInfo,
    jobsList: listJobs,
  }, (err, result) => {
    if (err) {
      return res.send({ err });
    }
    const ret = result;
    async.eachOf(ret.jobsList.running, (data, url, next) => {
      ret.jobsList.running[url].tail = `${req.protocol}://${req.get('host')}/tail/${encodeURIComponent(url)}`;
      return next();
    }, (err) => {
      if (err) {
        return res.send({ err });
      }
      return res.send(ret);
    });
    return null;
  });
};
```

**Comment by mandaputtra** [comment]
I also getting callback "already called error" but since its an error from this lib, I hardly can track any of that error.. Maybe there is a way that I should avoid what, when got this problem?

**Comment by ddzyan** [comment]
I also getting callback "already called error"
