### ISSUE TITLE
waterfall callback twice error

### ISSUE THREAD

**Issue by ltfyxkfh** [caolan/async#1284]
``` javascript
var async = require('async');
var task1 = function (callback) {
        console.log('--i will callback times');
        callback();
        callback();
    },
    task2 = function (callback) {
        console.log('--i should not repeat');
        callback();
    },
    task3 = function (callback) {
        console.log('---i should not repeat too');
        callback();
    };
async.waterfall([
    task1,
    task2,
    task3
], function () {
    console.log('done');
});
```
result:
>--i will callback times
>--i should not repeat
>--i should not repeat
>---i should not repeat too
>---i should not repeat too
>done

**Comment by hargasinski** [comment]
Thanks for the report! What version of async are you using? In the latest version, 2.0.1, this will throw an error. See the [Multiple Callbacks](http://caolan.github.io/async/) section of the docs. 

My guess as to what's happening is that whenever `task1` calls `callback`, `waterfall` automatically calls the next task in the list. It's doesn't guard against this, as it is an unexpected use case of async.

**Comment by ltfyxkfh** [comment]
thks!My version is 1.2.1,it's time to upgrade.
