### ISSUE TITLE
TypeScript Cannot find module 'async'

### ISSUE THREAD

**Issue by QJesus** [caolan/async#1285]
**What version of async are you using?**
async@2.0.1
**Which environment did the issue occur in (Node version/browser version)**
node: v6.6.0  typescript: Version 1.8.10
**What did you do? Please include a minimal reproducable case illustrating issue.**
I want to use async in typescript by coding:  import {parallel, waterfall} from 'async'; 
but occured an compile error: [ts] Cannot find module 'async'

my tsconfig.json as below:
"compilerOptions": {
    "target": "es2015",
    "module": "umd",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noEmitOnError": true,
    "removeComments": false,
    "moduleResolution": "node",
    "sourceMap": false
  }
**What did you expect to happen?**

**What was the actual result?**

can you help me ?

**Comment by aearly** [comment]
I am not familiar with how TypeScript bundles, but I have 2 questions:

Do other modules from NPM bundle properly?

Have you tried using `async-es`, which is published as an ES module rather than a CommonJS module?
