### ISSUE TITLE
processing highland stream chunks using async

### ISSUE THREAD

**Issue by carlskii** [caolan/async#1291]
I'm using highland.js to process a file using a stream to read the contents between two delimiters. I'm also using async.js to run a series of http requests in sequence.

Ideally I would like to pass the output x from highland as the first function to the async series (chain) so that the HTTP requests get executed for each chunk extracted from the stream.

Is this possible? If so, how can this be achieved?

```javascript
var async = require('async');
var _ = require('highland');


_(fs.createReadStream(files[0], { encoding: 'utf8' }))
        .splitBy('-----BEGIN-----\n')
        .splitBy('\n-----END-----\n')
        .filter(chunk => chunk !== '')
        .each(function (x) {
        }).done(function () {

    async.series([
        function(callback) {
            setTimeout(function() {
                console.log('Task 1');
                callback(null, 1);
            }, 300);
        },
        function(callback) {
            setTimeout(function() {
                console.log('Task 2');
                callback(null, 2);
            }, 200);
        },
    ], function(error, results) {
        console.log(results);
    });

});;
```

**Comment by megawac** [comment]
Instead of `.done()` I think you want `toArray()`

so it would be

`_(stream)
  <do highland stuff>
  .toArray(function(hlResults) {
   <do async stuff with results
});
