### ISSUE TITLE
Queue worker farm

### ISSUE THREAD

**Issue by tillkruss** [caolan/async#1292]
We'd like to use `async` for our queue worker farm on a single machine. All they do is make HTTP requests and wait for the responses, no computations. We're doing 200 req/s.

Right now we're using Node's cluster API to spin up a dozen workers. Could someone give an example of how to best implement a queue worker (in that cluster):
- to execute multiple functions simultaneously that poll SQS for jobs
- call a function when a job is available 
- and call themselves again once their finished

I appreciate any input or clues and apologize if this isn't the right place for support requests.

**Comment by megawac** [comment]
`async.auto` is a good place to start. If you have trouble implementing your own solution you can respond here or file a stackoverflow question. I'd rather not solve such a problem for you without solid requirements (similar to stackoverflow policy).
Sorry for the slow response, wasn't sure how I wanted to answer this.
