### ISSUE TITLE
async.timeout: add context parameter

### ISSUE THREAD

**Issue by nodo** [caolan/async#1294]
Hi,

I would like to propose adding a `context` parameter to `timeout` (http://caolan.github.io/async/timeout.js.html). 

The change would be quite simple: instead of applying the asynchronous  function with `null` context, the uses can pass its own (https://github.com/caolan/async/blob/master/lib/timeout.js#L71). Of course, the context parameter should be optional.

What do you think?

**Comment by megawac** [comment]
I think I would prefer the user call [`.bind()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) on their function instead of an API change.
