### ISSUE TITLE
Nested Async Functions Not Firing Parent Done Function

### ISSUE THREAD

**Issue by adamrabie** [caolan/async#1299]
**What version of async are you using?**
2.0.1
**Which environment did the issue occur in (Node version/browser version)**
5.12
**What did you do? Please include a minimal reproducable case illustrating issue.**
```
var runLogic = function() {
  var deferred = Q.defer()

  async.eachOf(obj, function(val, key, cb) {

    async.each(val, function(arr, innerCbOne) {

      async.each(arr, function(item, innerCbTwo) {

        ajaxRequest().then(function() {
          return innerCbTwo()
        })

      }, function() {
        return innerCbOne()
      })
    }, function() {
      // This is the last place it prints before hanging
      return cb()
    })

  }, function() {
    // I'm not getting here sometimes!
    return deferred.resolve()
  })
  return deferred.promise  
}
```

**What did you expect to happen?**
I expected the deferred.resolve to fire 
**What was the actual result?**
Script hangs :(

**Comment by megawac** [comment]
It works for me (on the asyncjs site). Ran this code

```js
var obj = {
  x: [[1]]
}

var deferred = $.Deferred()

async.eachOf(obj, function(val, key, cb) {

  async.each(val, function(arr, innerCbOne) {

    async.each(arr, function(item, innerCbTwo) {

      innerCbTwo();

    }, function() {
      return innerCbOne()
    })
  }, function() {
    // This is the last place it prints before hanging
    return cb()
  })

}, function() {
  // I'm not getting here sometimes!
  return deferred.resolve()
})

deferred.then(function() {
  console.log('done');
})
```

Make sure you're not getting an ajax error or something

**Comment by adamrabie** [comment]
@megawac 

Thanks for quick reply. I updated my example slightly in a couple places as i noticed i wasn't reflecting exactly what I was doing.

In any case I do call the callback in the catch function of the async and that's not where it is hanging. Both the inner .each function are completing and i'm getting a hang just before the line cb(). I can even console.log(cb) and it prints [Function] but that is the last thing I see.

**Comment by megawac** [comment]
Does the code example I gave above work for you @adamrabie?

**Comment by adamrabie** [comment]
@megawac 

It does.

I can't fathom what might be happening though in my fuller code. I know the ajax request seems like the culprit but it's direct parent async callbacks and done function is firing, its only the main parent cb() that isn't firing which doesn't have any request behaviour inside other than the dependency on its inner async functions, both of which are completing. Hope this makes sense.

**Comment by megawac** [comment]
It's really hard for me to suggest anything without a reproducible case I can run... If details are sensitive you can email me with further details.
