### ISSUE TITLE
CITGM test failing on s390

### ISSUE THREAD

**Issue by GeorgeAdams95** [caolan/async#1303]
Async: v2.0.1
Linux-s390
Node: 6.7.0
`npm install -g citgm` and then `citgm-all`

```
# 342 passing (15s)
# 1 failing
# 1) retry retry with interval when all attempts fail:
# Uncaught AssertionError: did not include interval
# + expected - actual
# -false
# +true
# 
# at mocha_test/retry.js:71:13
# at lib/retry.js:116:26
# at fn (mocha_test/retry.js:65:13)
# at Timeout.retryAttempt [as _onTimeout] (lib/retry.js:112:9)
# (node:13672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: error in callback
# npm ERR! Linux 3.10.0-327.13.1.el7.s390x
# npm ERR! argv "/dev/shm/usenode.jenkins0/node-v6.7.0-linux-s390/bin/node" "/dev/shm/usenode.jenkins0/node-v6.7.0-linux-s390/bin/npm" "run" "mocha-node-test"
# npm ERR! node v6.7.0
# npm ERR! npm  v3.10.3
# npm ERR! code ELIFECYCLE
# npm ERR! async@2.0.1 mocha-node-test: `mocha mocha_test/ --compilers js:babel-core/register`
# npm ERR! Exit status 1
# npm ERR! 
# npm ERR! Failed at the async@2.0.1 mocha-node-test script 'mocha mocha_test/ --compilers js:babel-core/register'.
# npm ERR! Make sure you have the latest version of node.js and npm installed.
# npm ERR! If you do, this is most likely a problem with the async package,
# npm ERR! not with npm itself.
# npm ERR! Tell the author that this fails on your system:
# npm ERR!     mocha mocha_test/ --compilers js:babel-core/register
# npm ERR! You can get information on how to open an issue for this project with:
# npm ERR!     npm bugs async
# npm ERR! Or if that isn't available, you can get their info via:
# npm ERR!     npm owner ls async
# npm ERR! There is likely additional logging output above.
# npm ERR! Please include the following file with any support request:
# npm ERR!     /tmp/cfe46f24-dc8c-47ad-9d01-3c641d5ac65c/async/npm-debug.log
# npm ERR! Test failed.  See above for more details.
```

**Comment by megawac** [comment]
Thats a flakey test which fails every once and a while (#1152)

**Comment by ferdian26** [comment]
> Async: v2.0.1 
> Linux-s390 
> Node: 6.7.0 
> `npm install -g citgm`dan kemudian`citgm-all`
> 
> ```
> #342 passing (15s)
> #1 failing
> #1) retry retry with interval when all attempts fail:
> # Uncaught AssertionError: did not include interval
> # + expected - actual
> # -false
> # +true
> # 
> # at mocha_test/retry.js:71:13
> # at lib/retry.js:116:26
> # at fn (mocha_test/retry.js:65:13)
> # at Timeout.retryAttempt [as _onTimeout] (lib/retry.js:112:9)
> # (node:13672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: error in callback
> # npm ERR! Linux 3.10.0-327.13.1.el7.s390x
> # npm ERR! argv "/dev/shm/usenode.jenkins0/node-v6.7.0-linux-s390/bin/node" "/dev/shm/usenode.jenkins0/node-v6.7.0-linux-s390/bin/npm" "run" "mocha-node-test"
> # npm ERR! node v6.7.0
> # npm ERR! npm  v3.10.3
> # npm ERR! code ELIFECYCLE
> # npm ERR! async@2.0.1 mocha-node-test: `mocha mocha_test/ --compilers js:babel-core/register`
> # npm ERR! Exit status 1
> # npm ERR! 
> # npm ERR! Failed at the async@2.0.1 mocha-node-test script 'mocha mocha_test/ --compilers js:babel-core/register'.
> # npm ERR! Make sure you have the latest version of node.js and npm installed.
> # npm ERR! If you do, this is most likely a problem with the async package,
> # npm ERR! not with npm itself.
> # npm ERR! Tell the author that this fails on your system:
> # npm ERR!     mocha mocha_test/ --compilers js:babel-core/register
> # npm ERR! You can get information on how to open an issue for this project with:
> # npm ERR!     npm bugs async
> # npm ERR! Or if that isn't available, you can get their info via:
> # npm ERR!     npm owner ls async
> # npm ERR! There is likely additional logging output above.
> # npm ERR! Please include the following file with any support request:
> # npm ERR!     /tmp/cfe46f24-dc8c-47ad-9d01-3c641d5ac65c/async/npm-debug.log
> # npm ERR! Test failed.  See above for more details.
> ```
