### ISSUE TITLE
mapLimit with n/sec limit

### ISSUE THREAD

**Issue by mvalletta** [caolan/async#1314]
Is possible to limit parallel execution to a number/sec?
This is necessary for those services, like Google Sheet API Limits and Quotas  (see https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas) , that limit the number of queries per second (QPS) per IP.
Thanks!

**Comment by aearly** [comment]
Similar features have been asked about before.  ( #1113 #1082 #1020 #942 #37 )  There is demand for some sort of "throttled queue" functionality, but managing that kind of construct properly is a hard problem.

**Comment by megawac** [comment]
tl;dr you/async would need some sort of smoothing function to do this. If we were to do this we would probably implement [an exponential smoothing function](https://en.wikipedia.org/wiki/Exponential_smoothing)

**Comment by JohnLelii-CMCST** [comment]
OP: maybe you've already solved this.....I've used another NPM package to implement rate limiting using leakybucket or token bucket models.  https://www.npmjs.com/package/limiter  This has worked well for me in the past.  To create a rate limited mapper function, just do something like this.  Your mapper function is directly used with async.

`var RateLimiter = require("limiter").RateLimiter;
var limiter = new RateLimiter(2, "second");
var async = require('async');

function rateLimitedMapper(item, callback)
{
  limiter.removeTokens(1, function(err, remainingRequests) {
    console.log("working on item: " + item);
    callback(null, item.length);
  });
}

async.map(input, rateLimitedMapper, function(err, results) {
  // do something with results
 });
`

**Comment by aearly** [comment]
That seems like a lib we should mention in our readme.  Seems to do exactly what we wanted to build.

**Comment by megawac** [comment]
Yep, it's using a token bucket under the hood which is the same approach I was taking. I'd be quite fine deferring rate limitting to external libraries :)

**Comment by aearly** [comment]
Yeah, honestly I'm not thrilled with having to support something like that within Async.  There are so many gotchas when doing rate limiting.

**Comment by aearly** [comment]
Changing the tags on this to signify that we need a place in the docs for other libraries that extend Async.

**Comment by manoharreddyporeddy** [comment]
Another way to do this using Promise.all and promise-throttle:

https://stackoverflow.com/questions/20253425/throttle-and-queue-up-api-requests-due-to-per-second-cap/47627820#47627820
