### ISSUE TITLE
Function should abort, but continues on error

### ISSUE THREAD

**Issue by GRIM2D** [caolan/async#1316]
**What version of async are you using?**
2.1.2

**Which environment did the issue occur in (Node version/browser version)**
browser, installed via npm, compiled using webpack

**What did you do? Please include a minimal reproducable case illustrating issue.**
Providing error on callback, doesn't abort the function. Result callback called with proper error and no results, but iteratee function called

https://runkit.com/58170f651dbdbd0014bb8b5f/58170f651dbdbd0014bb8b60
```javascript
const async = require("async")
async.map([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], (item, callback) => {
    console.log(item);
    if (item == 3) {
        callback(true);
    } else {
        callback(null, item);
    }
}, (err, results) => {
    if (err) {
        console.error("err", err);
    } else {
        console.log("Results", results);
    }
});
```

**What did you expect to happen?**
Iteratee functions shouldn't called after error occured, it should immediately call result callback

**What was the actual result?**
Iteratee functions called till array isn't enumerated

**Comment by megawac** [comment]
The base `map`/`each` just spin up all the callbacks and waits for them all to either resolve or error. We don't bother to attempt not call the iteratee for a value as the only way this would ever occur is if the iteratee was **synchronous and errored** (edge case). Do you have a use case where this behaviour is important?

FYI both `parallel` and `series` will exit immediately in the case.

**Comment by GRIM2D** [comment]
I'm switched to async because of largeness of arrays. `map` and `each` is should break if error occurs like does native implementations. 

```javascript
[0, 1, 2, 3, 4, 5].map(int => {
    if (int == 3) {
        throw new Error();
    }
    console.log(int);
    return int;
});

/* Output:
0
1
2
Uncaught Error
*/
```

Async should provide effective system of aborting/breaking functions, as it's primary goal is working with Big arrays (IMHO). If one could do same tasks in native implementations with small affect on UI, he wouldn't switch to async

**Comment by megawac** [comment]
Anyway, `async.mapLimit(arr, Infinity)` covers this case for now.

Changing this behaviour would require profiling as it will slow down the primary usecase (asynchronous iteratees). The main reason I was considering implementing a solution for this was for the `some`/`every`/`find` use cases with sync callbacks. Again it depends on how much sync support we want to provide

**Comment by GRIM2D** [comment]
Thanks for response and for this great library, I successfully changed `map` to `mapSeries` and it's working like expected. 

After seeing sources, finally figured how this library works. 
As problem was misunderstanding how it works, I'm closing this issue.

**Comment by megawac** [comment]
Thanks for the report, it made me question how this case should be supported
