### ISSUE TITLE
how to - async.parallel / async.each / async.map but maximum concurrency of 5 or so

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1319]
I have been using this lib to great effect for years - and been through the docs enough to be pretty sure I have never seen how to use 

`async.parallel` or `async.each` with a maximum concurrency. Say I have 100 tasks and I want them to run in parallel but no more than 5 or 10 or whatever, running at the same time.

Is that possible with this lib? thanks

**Comment by ORESoftware** [comment]
ahh, I remember seeing parallelLimit, mapLimit, but not fully realizing what they were for,

I think I found my answer - http://caolan.github.io/async/docs.html#parallelLimit

**Comment by megawac** [comment]
Yep, you want the `*Limit` versions of these functions :D

**Comment by ORESoftware** [comment]
Thanks! :) Actually I think there is a bug!

I have this:

// (bash is an array with at least 40 elements)

// no error gets logged in the final callback, yet the final callback is called after only the first 3 iterations, any idea how this could happen? The first 3 iterations do run as normal, outputing the expected output.

```js
     async.eachLimit(bash, 3, function (item, cb) {

        console.log('item => ', item);
        const n = cp.spawn(executable, item, {});

        n.stdout.setEncoding('utf8');
        n.stderr.setEncoding('utf8');

        n.stdout.on('data', function (d) {
          console.log(d);
        });

        n.stderr.on('data', function (d) {
          console.log(d);
        });

        n.on('close', cb);

      }, function(err){
         if(err){
           console.error(err.stack || err);
         }
         cb(null);
      });
```

**Comment by ORESoftware** [comment]
Thought there was a bug in this lib, but there was a small chance of that, thanks for your help!!

**Comment by megawac** [comment]
Haha, always good to hear that we didn't break it :)
