### ISSUE TITLE
detectSeries not accepting the truth value

### ISSUE THREAD

**Issue by danielgindi** [caolan/async#1324]
When doing:

```
var items = [1, 2, 3, 4, 5];
Async.detectSeries(items, function (item, foundItem) {
  console.log(item);
  foundItem(null, true);
}, function (err, item) {
  console.log('found', item);
});
```

The output is:

```
1
2
3
4
5
found undefined
```

According to the docs, it should be:
```
1
found 1
```

**Comment by megawac** [comment]
Based on the behaviour youre seeing I think you're using async 1.5

In `1.5` the `foundItme` callback did not take an error argument (https://github.com/caolan/async/blob/v1.5.2/README.md#detect)

**Comment by danielgindi** [comment]
Yes, thank you. I didn't notice that you moved to 2.*, so my `npm update` did not actually update.
