### ISSUE TITLE
Version 2.1.2 doesn't work in IE8 (Object doesn't support this action)

### ISSUE THREAD

**Issue by yurevichcv** [caolan/async#1325]
**What version of async are you using?**
2.1.2 (for previous version everything works well)

**Which environment did the issue occur in (Node version/browser version)**
IE8

**What did you do? Please include a minimal reproducable case illustrating issue.**
Used async.asyncify and async.nextTick with Babel with "es2015-loose" preset and ES5 Shim in IE8.
In previous version (even in 2.1.1) everything worked well.

**What did you expect to happen?**
Expected not to have error in IE8 :)

**What was the actual result?**
Error: Object doesn't support this action (fails for Object.getProperty)

**Comment by megawac** [comment]
In 2.x we started depending on lodash 4, which started to rely on ES5 features.

If you provide a shim for ES5 in your environment it should work. I would suggest using either https://github.com/es-shims/es5-shim or https://github.com/zloirock/core-js
