### ISSUE TITLE
Async in Browser

### ISSUE THREAD

**Issue by frankred** [caolan/async#1329]
I installed async in my webproject with
`
npm install --save async
`

Now I bind it to my frontend
```
app.use('/js/async.js', express.static(path.join(__dirname, 'node_modules/async/index.js')));
```
And use it on my `index.html` page.

But this leads to an error:
```
async.js:3 Uncaught ReferenceError: exports is not defined(…)
```

 But in the readme it says it can also be used directly in the browser.

**Comment by hargasinski** [comment]
Thanks for the question. The `index.js` file is mainly for Node. The files in the `dist` are built using UMD, and should work almost everywhere. So in your case, it would be:
```js
app.use('/js/async.js', express.static(path.join(__dirname, 'node_modules/async/dist/async.js')));
```
or preferably,
```js
app.use('/js/async.js', express.static(path.join(__dirname, 'node_modules/async/dist/async.min.js')));
```
You should also look into [Browserify](http://browserify.org/articles.html) or [Webpack](http://webpack.github.io/docs/what-is-webpack.html). They'll let you `require` directly in the browser like you would with Node.

**Comment by frankred** [comment]
Thank you !!! Maybe this should be documented somewhere 👍

**Comment by megawac** [comment]
Yeah having this documented would be great in the intro (https://github.com/caolan/async/blob/master/intro.md). Should also probably include cdn links for async (http://www.jsdelivr.com/projects/async)

**Comment by hargasinski** [comment]
I just added it to the intro. Thanks for the suggestion :smile:
