### ISSUE TITLE
save on performance by omitting unnecessary array

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1332]
I was looking at the code just to see how the new system worked

looking at this file

https://github.com/caolan/async/blob/master/lib/internal/applyEach.js

I see this:

```js
fn.apply(that, args.concat([cb]));
```

You should be able to do this instead:
```js
fn.apply(that, args.concat(cb));
```

e.g.:

```js
const arr = [1,2,3];
console.log(arr.concat(4));
```

Not sure how often this type of call is made in the lib, but hopefully can save an iota of performance by removing unnecessary array :)

**Comment by megawac** [comment]
Sure, cb is gaurenteed not to be an array as its passed by the eachfn. Feel free to pull request this

**Comment by megawac** [comment]
Going to close this, feel free to open a  pull request

**Comment by ORESoftware** [comment]
Sure thing, is there a contribution guideline, how to build + test after making changes to ES6 modules?

**Comment by hargasinski** [comment]
@ORESoftware you don't have to rebuild after making changes, our publishing script will take care of that. You can just make your changes to the `lib` folder, in this case to `lib/internal/applyEach.js`, and then run `npm test`. `npm test` takes care of linting and testing `lib`. The actual tests are found in `mocha_test`. Thanks for taking a look at this.

**Comment by ORESoftware** [comment]
I guess it's weird that you don't test the dist after the dist is built? or do you?

anyway, here's what I did

https://github.com/caolan/async/pull/1333

**Comment by megawac** [comment]
We run a subset of the tests on the dist bundles
