### ISSUE TITLE
How to kill an async queue with SIGINT

### ISSUE THREAD

**Issue by gdams** [caolan/async#1335]
I am trying to kill and async queue when I run `process.kill('SIGINT');`

Here is my code:

```
function launch() {
  var collection = _.reduce(lookup, filterLookup, []);

  var q = async.queue(runTask, app.parallel);
  q.push(collection);
  q.drain = function done () {
    q.drain = null;
    reporter.logger(log, modules);
    process.exit(reporter.util.hasFailures(modules));
  };

  function abort() {
    q.kill();
    process.removeListener('SIGINT', abort);
    process.removeListener('SIGHUP', abort);
    process.removeListener('SIGBREAK', abort);
    process.setMaxListeners(process.getMaxListeners() - app.parallel || process.getMaxListeners());
  }
  process.setMaxListeners(process.getMaxListeners() + app.parallel || process.getMaxListeners());
  process.on('SIGINT', abort);
  process.on('SIGHUP', abort);
  process.on('SIGBREAK', abort);
}
```
I know that it is definitely calling the abort function so for some reason that function can't seem to run `q.kill();` 

Thanks in advance!

**Comment by megawac** [comment]
Why do you think the queue is not getting killed? It's hard to offer advice without a complete repro case

**Comment by GeorgeAdams95** [comment]
here is my code: https://github.com/GeorgeAdams95/citgm/commit/246fc11ed5bdabdf95a455eaea294600ec9328f1 I can tell that it's not getting killed because there are still processes left lying around

**Comment by megawac** [comment]
Is the queue being used to call asynchronous code in citgm? All `kill` really does is remove all any items remaining, it doesn't try to manage in flight processes as we can't really force your code to immediately resolve

You can try something like 04102b3, but even that won't be able to abort in flight callbacks

**Comment by ORESoftware** [comment]
@megawac it sounds like `q.kill()` and `q.empty()` are the same, then?
