### ISSUE TITLE
async.each callback not called when long process.

### ISSUE THREAD

**Issue by namtn** [caolan/async#1336]
Hi all,
I have a list of files need to download and I used async.each to loop the array as below:

```js
async.each(urls, function(url, callbackEach) {
            console.log('Starting download :  ' + url )
            download(url, url.substring(url.lastIndexOf('/'), url.length), function () {
              console.log('Download completed:  ' + url )
             callbackEach();
            })
    }, function(err) {
        if( err ) {
          console.log('A file failed to process');
        } else {
          console.log('Download Slide completed ---------------------')
        }
    })
```

It worked perfectly for all image files. However, if has a video file in list and download process take a long time then function callback never called.

Anyone can help me? I'm using Async version 2.1.2
Thanks,

**Comment by megawac** [comment]
Are you sure the download isn't erring? What happens if the download fails?

**Comment by namtn** [comment]
Hi @megawac 
I'm sure all file downloaded without any error because the line code:
 `console.log('Download completed:  ' + url )
` always run correctly and if any error occur this line will execute:
`          console.log('A file failed to process');
`

Thanks,

**Comment by megawac** [comment]
You're not calling the `callbackEach` callback in the case where the download errs

**Comment by namtn** [comment]
Hi @megawac ,
I have update code for error handling as below:
Download function:

`var download = function (uri, filename, callback) {
  request.head(uri, function (err, res, body) {
    console.log('content-type:', res.headers['content-type'])
    console.log('content-length:', res.headers['content-length'])
    request(uri).on('error', function (err) {
      callback(err)
    }).pipe(fs.createWriteStream(__dirname + '/public/download/' + filename))
      .on('close', callback)
  })
}`

And call download function inside async.each:

`    async.each(urls, function (url, callbackEach) {
      var url = url.replace(');', '')
      if (url.startsWith('http://smartschool.edu.vn/')) {
        console.log('Starting download :  ' + url)
        download(url, url.substring(url.lastIndexOf('/'), url.length), function (error) {
          console.log('Download completed:  ' + url)
          if (error) {
            callbackEach(error)
          } else {
            callbackEach()
          }
        })
      }
    }, function (err) {
      if (err) {
        console.log('A file failed to process')
      } else {
        console.log('Download completed ---------------------')
        res.send('OK!')
      }
    })`

If has a video file ~ 20Mb and view the console log, just log for download completed and downloaded file already in my computer but callback function not call.

Thanks,

**Comment by megawac** [comment]
Is there a set of urls (or an ssh endpoint I can connect to) I can test this with to try and repro? I can't really offer advice without a repro case

**Comment by namtn** [comment]
Hi @megawac ,

Problem solved.
Actually, There is a one file in the list never downloaded so the callback function not complete call for all elements.
My mistake.

Thanks @megawac.
