### ISSUE TITLE
Control Flow times - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mcmartins** [caolan/async#1337]
Async v2.1.4 / Node v4.1.1

Running the code from the documentation with a large n (1500) for **times(n, iteratee, callback)**:

```javascript
var async = require('async');

// Pretend this is some complicated async factory
var createUser = function(id, callback) {
    callback(null, {
        id: 'user' + id
    });
};

// generate 5 users
async.times(1500, function(n, next) {
    createUser(n, function(err, user) {
        next(err, user);
    });
}, function(err, users) {
    console.log(users.length)
});
```

I get:

```bash
RangeError: Maximum call stack size exceeded
      at forEach (test/disk-test.js:49:7)
      at node_modules/async/dist/async.js:1008:9
      at replenish (node_modules/async/dist/async.js:882:17)
      at iterateeCallback (node_modules/async/dist/async.js:867:17)
      at node_modules/async/dist/async.js:840:16
      at node_modules/async/dist/async.js:1010:13
```

Before in version v1.5.x, I was able to create testing arrays of 250K but with this version I can only create max 1400.

Is there a better way to do it?

**Comment by aearly** [comment]
That error happens when you don't defer your callback.  Either use something like `setImmediate`, or perhaps Lodash's `_.times`.  It appears you don't need Async at all.

**Comment by mcmartins** [comment]
Thank you for looking into this.

I'll just use setImmediate which fixes it, don't want to include more dependencies in the project.

Thanks.
