### ISSUE TITLE
Run task with condition

### ISSUE THREAD

**Issue by dominhhai** [caolan/async#1338]
For some reasons it's nice if we can start run a task with specific condition.

For example: Using priority queue for running task with `time` priority. If we add new job with `time` before an other running tasks, this new job will wait until a running task finished. Oh, task `10:00:00` has to wait task `11:00:00`!

IMO, it's not difficult and small break the current code, so should be added to the task flow.

**Comment by aearly** [comment]
I'm not sure what your asking for here exactly.  It sounds like you're trying to use a `priorityQueue` as a scheduler.

**Comment by dominhhai** [comment]
@aearly I'm trying to use `priority queue` as a scheduler.

**Comment by aearly** [comment]
I wouldn't recommend that.  I'm sure there's a more focused node library for that, or heck, even `cron`.
