### ISSUE TITLE
idea for errbacks

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1342]
I have a few case of code like so:

```js
async.series({

 one: function(cb){
    async.parallel({a:fn1,b:fn2}, cb);
},

two: function(cb){
   async.parallel({c:fn3,d:fn4}, cb);
}

}, function(err,results){


});
```

I really like that you can do

`const foo = results.one.a`

or

`const bar = results.two.d;`

etc.

however, I am wondering if it is possible to do something like this with the async library:

```js
async.series({

 one: async.parallel({a:fn1,b:fn2})

 two: async.parallel({c:fn3,d:fn4})

}, function(err,results){


});
```

maybe if async.parallel returned a function which takes a single callback param?

**Comment by hargasinski** [comment]
Hi @ORESoftware,

Right now, I don't think it would be possible to correctly handle `async.parallel` returning a function, as the `callback` parameter is optional. However, you can achieve what you're looking for using `async.apply`. Essentially, your code would just change to:
```js
async.series({
 one: async.apply(async.parallel, {a:fn1,b:fn2}),
 two: async.apply(async.parallel, {c:fn3,d:fn4})
}, function(err,results) {

});
```
I hope that helps, you can read more about `apply` in the [docs](https://caolan.github.io/async/docs.html#apply). The example shows a similar use case. Thanks for the suggestion!
