### ISSUE TITLE
[Question] Where can I see the code of  this page ? http://caolan.github.io/async/ 

### ISSUE THREAD

**Issue by imvetri** [caolan/async#1345]
I was exploring this repo for source for the page, and I couldn't succeed. Could someone help me out?

**Comment by megawac** [comment]
Its hosted on https://github.com/caolan/async/tree/gh-pages

This page is generated by our jsdoc scripts. If you want to try download the package and run, `make doc` or `npm run jsdoc`, the docs will be in the `docs/` folder. Open `docs/index.html`

**Comment by hargasinski** [comment]
Just to add to what @megawac said, the homepage is generated from `intro.md` and the jsdoc scripts are located in `support/jsdoc`.

**Comment by imvetri** [comment]
Thanks a lot.
