### ISSUE TITLE
Feature Request: Partition

### ISSUE THREAD

**Issue by goughy000** [caolan/async#1348]
Would be good to have a new collections method for "partition"

Here's a description of how the method works in Ruby:
Returns two arrays, the first containing the elements of enum for which the block evaluates to true, the second containing the rest.

So it's a bit like a filter/reject combo.

If others are interested and I get time then I'll have a go at implementing but it won't be for a few weeks at least but I thought I would put the idea here in case someone else has time

**Comment by megawac** [comment]
I'm not sure how I feel about adding partition to async but I would be open to a [`groupBy`](https://lodash.com/docs/4.17.4#groupBy) which could be used to fill almost the same need. The reason I'm not a big fan of supporting partition as its slightly too specific of a use case and for methods like this we have to add `partition`, `partionLimit` and `partionSeries`

**Comment by goughy000** [comment]
@megawac that makes perfect sense to me!

**Comment by hargasinski** [comment]
👍 for supporting `groupBy`.

**Comment by hargasinski** [comment]
Fixed in #1364.
