### ISSUE TITLE
Feature Request: queue with array of workers

### ISSUE THREAD

**Issue by Maarethyu** [caolan/async#1350]
A really useful thing would be to be able to have not only one worker function, but an array of workers, and obviously a way for a worker to register to the workers list.

Exactly like async.queue() but the queued tasks could be processed by any worker whose concurrency limit is not reached.

Maybe there is a way to do it with async.queue() and some additional code but i cant figure it out.

**Comment by aearly** [comment]
What do you mean by "any worker whose concurrency limit is not reached"?  A "worker" in the context of  `queue` is just a function that can be called.  You can already control the concurrency of how many parallel calls to that function there can be.

**Comment by Maarethyu** [comment]
By "worker" I mean a function that will process the tasks.
In `queue` you can only pass a unique function that will process the tasks, it would be usefull to have multiple functions that would process tasks.

See it as some sort of load balancing, `queue` is the load balancer and the worker functions are the servers: they all do the same thing, but with their own environment.

![image](https://cloud.githubusercontent.com/assets/11776438/22261737/689f8246-e26e-11e6-92c5-5cea3fddc74e.png)

**Comment by aearly** [comment]
How would the workers get their own environments?

**Comment by Maarethyu** [comment]
Not actual environment sorry, I meant instance of a worker for example.

**Comment by aearly** [comment]
What does "instance of a worker" mean for you?  A worker is just a function.

**Comment by aearly** [comment]
Maybe you can show me some example code of what this feature would look like.

**Comment by Maarethyu** [comment]
Syntax would look like: 
`async.registerQueue(defaultWorker)`
defaultWorker is the function used if no other worker function has been registered.

`queue.register(worker)`
`queue.register([worker1, worker2])`
`queue.register({foo: worker1, bar: worker2})`
Register a single, array or object of functions, that will be used to process new tasks. It can be used multiple times to register new workers (You need to provide an object to be able to unregister workers).

`queue.unregister(workerName)`
`queue.unregister([foo, bar])`
Remove a single or an array of previously registered named workers.

`queue.push(task)`
Add a task to the queue.
If there is no worker registered, use the defaultWorker.
Else use any registerd worker whose concurency limit is not hit.

_(I've not specified how to pass concurency limit that's up to you)_

Example: [(pastebin)](http://pastebin.com/PMgD9RFY)

![screenshot_1](https://cloud.githubusercontent.com/assets/11776438/22273198/6dc93fd8-e29f-11e6-9345-d2dacb0ef794.png)

**Comment by hargasinski** [comment]
@aearly, from my understanding, a potential use case of this would if you have more than one API key for an API. You could have a `worker` function for each key, and once one `worker` saturates, the `async.registerQueue` starts executing tasks using the next one until it reaches it's concurrency limit (and so on) or one of the previous `workers` unsaturates. That being said, even though I could see the benefit of this, I don't know if this is a common enough of a use case in practice for us to support it. 

If we do decide to experiment with this, with regards to the API, I would be favour of something like `queue.register(worker, concurrency)`, and if `worker` is a collection, each one is assigned the same `concurrency` (similar to how `push` handles it for a priorityQueue). When creating the queue, the signature should be similar to `cargo`, `queue`, and `priorityQueue`, although there might be a better name than `registerQueue`.

**Comment by Maarethyu** [comment]
You got it, that's exactly what I meant!
I knew it would be a rare use case, that's just a problem I ran into without being able to code one myself without a large amount of code.
I'll leave the idea here, the decision to implement it is up to you.

**Comment by aearly** [comment]
I'm :-1: on this.  I don't think  using Async as a load balancer is a common use case.  Also, if we did support load balancing, there are so many ways to load balance (round robin, LRU, concurrency-based, etc..) that it would lead to a lot of feature creep.

It wouldn't be too hard for you to implement load balancing yourself.  The queue worker function would become a function that defers to a list of workers, e.g.:

```js
var workers = [
  //...  create your list of workers;
];

var q = async.queue(function(task, done) {
  const worker = getAvailableWorker(workers); // <--- this is where you put the load balancing logic,
 // the logic will be unique to your application
  worker.run(task, done);
}, totalConcurrency);
```

**Comment by Maarethyu** [comment]
I feel kinda bad for not having though of a solution as simple as this.
Since it's so simple to implement it yourself, probably no one is gonna need it implemented in Async.
