### ISSUE TITLE
Could not import waterfall from async-es/waterfall (ES6 syntax)

### ISSUE THREAD

**Issue by Tiendq** [caolan/async#1351]
**What version of async are you using?**
2.1.4

**Which environment did the issue occur in (Node version/browser version)**
7.4.0, Chrome 55

**What did you do? Please include a minimal reproducable case illustrating issue.**
Using `waterfall` in a module with ES6 syntax, my module is transpiled well with `babel`/`webpack`.

```javascript
import waterfall from 'async-es/waterfall';
```

**What did you expect to happen?**
No error.

`babel-loader` needs only to handle my code, not modules in `node_modules` folder.

**What was the actual result?**
Chrome reports following error at line 2 in `waterfall.js`:

Uncaught SyntaxError: Unexpected token import

```javascript
import isArray from 'lodash-es/isArray';
```

**Comment by megawac** [comment]
You have to add `async-es` and `lodash-es` to the list of modules to be transpiled (https://github.com/babel/babel-loader/issues/171#issuecomment-163385201) as these modules use some ES2015 syntax

**Comment by Tiendq** [comment]
@megawac 

`exclude: /node_modules\/(?![async\-es|lodash\-es])/` works for me.

I wish this tip is included in the `async` ES6 version instruction since excluding `node_modules` is likely default `babel-loader` configuration.

Thanks,

**Comment by megawac** [comment]
@aearly ^ thoughts

**Comment by aearly** [comment]
Does the babel-loader respect the `esnext:main` prop (or something similar) in the package.json?  If so, we should add it.

Otherwise, it's definitely worth a line in the readme.

**Comment by AndersDJohnson** [comment]
@Tiendq @megawac @aearly I've created a webpack helper to automatically detect dependencies such as this one that may require Babel transpilation. See https://github.com/andersdjohnson/webpack-babel-env-deps.

For it to work in its current form, this module would have to indicate `engines` in its `package.json` with the minimum Node version that supports any features required by its `async-es` build. FYI @caolan.
