### ISSUE TITLE
"Cannot find module 'lodash/_overRest'"

### ISSUE THREAD

**Issue by diasdavid** [caolan/async#1352]
**What version of async are you using?**
2.1.4

**Which environment did the issue occur in (Node version/browser version)**
Only in circle-ci (travis-ci is ok, Mac OS X is ok too)

**What did you do? Please include a minimal reproducable case illustrating issue.**
Only need to 'rerun' circle-ci tests here: https://circleci.com/gh/libp2p/js-libp2p-webrtc-star/224

**What did you expect to happen?**
At first I would expect it to run just fine, but second, I would expect to be able to find a reference of what is `lodash/_overRest`, but I've been scavaging through lodash and issues on the web, and it seems no one else is hitting this problem or has a reference where this module exists.

**What was the actual result?**
```
Message:
    Cannot find module 'lodash/_overRest'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'lodash/_overRest'
```

**Comment by megawac** [comment]
What version of lodash are you seeing this with (that circle-ci thing isn't openning for me). I tried installing `4.17.4` and I see `_overRest` in my node_modules. Can you check that `node_modules/lodash/_overRest.js` exists

**Comment by diasdavid** [comment]
Installing it as a dev dependency of the top module solved the issue in CI, although it should have been a dep of async. 

I'm still unsure why this only happens in Circle

**Comment by megawac** [comment]
Hmm, it shows up in my dependencies when I npm install

```
  "author": {
    "name": "Caolan McMahon"
  },
  "bugs": {
    "url": "https://github.com/caolan/async/issues"
  },
  "dependencies": {
    "lodash": "^4.14.0"
  },
  "description": "Higher-order functions and common patterns for asynchronous code",

```

Going to close as I can't reproduce

**Comment by dignifiedquire** [comment]
Maybe there is some weird caching going on on circleci which causes this issue?

**Comment by megawac** [comment]
Couldn't say, let us know if you encounter it again or isolate the issue

**Comment by maxlath** [comment]
I encountered the same issue (async version: 2.1.4 / env: Ubuntu 16.04)
And I think the reason is that `package.json` requires `{ lodash: '^4.14.0' }`, which is matched by the latest `lodash 4.15.0`, in which [`_overRest.js` was removed](https://github.com/lodash/lodash/commit/aacfefc7524e1c647b39efa605f1eca1f6da80d5#diff-3ff90820579038354b09377bf2b481e6)

**Comment by aearly** [comment]
I wonder how @jdalton 's work on making webpack-lodash-plugin work with rollup is going.  If we had a tool like that, we wouldn't have to rely on lodash internals.

**Comment by megawac** [comment]
@maxlath `_overRest` was removed for lodash version 5, not the version 4 release track. We'll look into this again when lodash 5 is out.

**Comment by maxlath** [comment]
@megawac so how come we got this error? I'm confused oO

**Comment by amandeepmittal** [comment]
I am encountering this error and I am not use async module directly.  In my app, these are the modules I am using:
```json
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "1.16.1",
    "cookie-parser": "1.4.3",
    "express": "4.14.1",
    "express-session": "1.15.1",
    "module-log": "1.0.0",
    "mongoose": "4.8.5",
    "morgan": "1.8.1"
```

I am using latest `npm` and nodejs LTS versions.

**Comment by chenfanggm** [comment]
I'm encounter the same issue now.
And in lodash 4.17.4, there's no _overRest.js in the module

**Comment by nicolasbonnici** [comment]
@amandeepmittal Same problem here caused by Lodash mongoose dependency, tried the last mongoose release 4.11.3 with still the same result.

**Comment by amandeepmittal** [comment]
@nicolasbonnici I haven't tried the module in sometime. Let me test and get back to you. It certainly is a dependency issue.

**Comment by hargasinski** [comment]
@nicolasbonnici upgrading to the latest version of `async` should resolve the issue, as the `lodash/_overRest` dependency was removed in `v2.4.0`.

@megawac to reproduce:
```bash
$ npm install lodash@4.14.0 --save # another dependency depends on lodash ~4.14.0 or ~4.15.0
$ npm install async@2.3.0 --save

$ npm ls lodash
├─┬ async@2.3.0
│ └── lodash@4.14.0  deduped
└── lodash@4.14.0
```

```js
// index.js

// throws an error as `_overRest` wasn't added until lodash `v4.16.0`
var waterfall = require('async/waterfall');
```

However, this has been inadvertently fixed since, so I don't think there's anything we need to do.
