### ISSUE TITLE
[Question] How to enforce a timeout on async.series function

### ISSUE THREAD

**Issue by himanshu0503** [caolan/async#1353]
**Scenario**
I want to run some functions in an async.series loop and would like to end (similar to a process.exit) the async.series function after a certain timeout. I've used async.timeout but that basically tells me if the timeout event occurred, it doesn't really kill the async.series function. I want to know if it is possible to do that?

**What version of async are you using?**
2.0.0

**Which environment did the issue occur in (Node version/browser version)**
0.12.18

**What did you do? Please include a minimal reproducable case illustrating issue.**
```javascript
function main() {
  async.series([
    _functionA, //makes call to some API /expected response time in 500ms
    _functionB //makes call to another API /expected response time is 2000ms
    ...
    ],
    function(err) {
      return callback(err);
    }
  );
}
```

**What did you expect to happen?**
Trying to exit the async.series after a timeout (example 2000ms).

**What was the actual result?**

**Comment by aearly** [comment]
How about:

```js
const timeoutSeries = async.timeout(async.series, 2000);

timeoutSeries([
  _functionA,
  _functionB,
  //...
] done);
```

**Comment by himanshu0503** [comment]
Tried out with https://gist.github.com/himanshu0503/dea89024f96f28f48882b8c8aff7348d, but that didn't help. Is there a way to kill the running async.series by passing a signal?

**Comment by aearly** [comment]
There's no way to cancel an async function, all you can do is ignore the result.

**Comment by megawac** [comment]
Async itself has no way of cancelling the execution of functions being started through async. There is no decent way of doing that comprehensively in Javascript -- a lot of asynchronous code may simply not be abortable.
