### ISSUE TITLE
async.map, but with an index like async.eachOf

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1354]
Hey all

Looking through the docs, I am looking for `async.map`, but with the index of the iteratee passed to the callback.
With `async.each`, the analogue is `async.eachOf`. But I don't see `async.mapOf` or what not.

Is there such a thing? Let me know if you need more info, thanks!

**Comment by jpalala** [comment]
Hey :)  Is what you need similar to this answer - http://stackoverflow.com/a/31821896 . Maybe you can create an alias/copy method that just calls `async.forEachOf` whenever you call `async.mapOf`, if you find that name more fitting.

**Comment by ORESoftware** [comment]
@jpalala  what's up Joe! let me give that a shot, how are things going?

**Comment by ORESoftware** [comment]
does async.forEachOf pass data to the final callback like async.map?

**Comment by jpalala** [comment]
We're ok 👍  Anyway here's what i tried to get the data back:

```
var async = require('async');

async.forEachOf(['a', 'b', 'c'], function () {

  console.log(arguments[1]);
});
```

**Comment by aearly** [comment]
`forEachOf` and family don't pass the results to the callback.  If you want the key, you could do something like:

```js
async.forEach(_.entries(obj), ( [key, value], next ) => {
  // do whatever
}, done);
```

Keep in mind, this will return an array, and the  order will not be guaranteed.  You'd have to build a result object manually.

**Comment by ex1st** [comment]
why not mapValues?
```javascript
async.mapValues( (val, key, next) => {
    // do whatever
}, (err, obj) => {
    let result = _.toArray(obj);
});
```

**Comment by ORESoftware** [comment]
@ex1st huh that might work!

**Comment by aearly** [comment]
Yeah, disregard what I said, `mapValues` is exactly what you want.
