### ISSUE TITLE
Question - What about adding a libhive badge for real code examples ?

### ISSUE THREAD

**Issue by libHive** [caolan/async#1362]
Libhive is a site that shows how packages are used by other packages.
There are currently around 25k examples of how async is used.
We have a nice badge that can link to this -

[![libhive badge](https://www.libhive.com/providers/npm/packages/async/examples/badge.svg)](https://www.libhive.com/providers/npm/packages/async)

What do you think about adding this to the Readme ?
Thanks

**Comment by megawac** [comment]
How are the examples sorted, because the first 4 examples did not look great

**Comment by megawac** [comment]
Anyway, I'd be fine with adding the badge. Feel free to PR it.

**Comment by libHive** [comment]
Thanks :tophat: @megawac 
I've made some changes to the sorting algorithm so the top examples should be better now.
I've also opened https://github.com/caolan/async/pull/1370
