### ISSUE TITLE
Add a util to limit the numbers of arguments passed

### ISSUE THREAD

**Issue by ravenjohn** [caolan/async#1366]
Some libraries provide multiple arguments in their callback and most of the time I only need the first two, the error and the success data.

Instead of doing this to reduce the arguments:
```js
thirdPartyLib.foo((err, what_i_need) => cb(err, what_i_need));
```

I will just:

```js
thirdPartyLib.foo(async.nargs(cb, 2));
// or the default would be 2, so it will be just async.nargs(cb)
```

This is very useful on `async.waterfall` since the next function should know exactly how many arguments the previous one will pass to properly identify the callback function.

note: `nargs` might not be the best function name for this 😆

**Comment by ravenjohn** [comment]
lodash actually has a function like this: https://lodash.com/docs/4.17.4#ary but I think it's better if it would also be implemented here.

**Comment by aearly** [comment]
I'd be :+1: for keeping this in Lodash.    Literally all we would do is `async.nargs = _.ary`, (with tons of documentation overhead).

**Comment by megawac** [comment]
Yeah, I'd prefer to defer to lodash's implementation on this one. Thanks for the request though!
