### ISSUE TITLE
feature request - import only one function a la Lodash

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1372]
Hey all
Maybe this already exists, maybe not, sorry if this is a dupe.  I am looking to only use one async function in my project.

Is there a way to do something like:

```js
// package.json

"dependencies": {
  "async.mapseries": "x.y.z"
}
```

Does something like this exist with async? thanks

**Comment by aearly** [comment]
We nixed this idea back in the 2.0 planning stages due to the overhead in creating and maintaining all the modules.  Lodash did (does?) this, and sees very little use.

You can still require individual functions: `require('async/mapSeries')`.

**Comment by ORESoftware** [comment]
Thanks yeah when I import lodash.x it still seems to load all of lodash so
I don't know what's up.
