### ISSUE TITLE
Add GitHub topics to the repo

### ISSUE THREAD

**Issue by hargasinski** [caolan/async#1373]
GitHub recently added [topics](https://github.com/blog/2309-introducing-topics) to 

> create subject-based connections between GitHub repositories and let you explore projects by type, technology, and more.

It might be useful to add these to the repo. We could use something along the lines of the npm keywords + `javascript`.

**Comment by aearly** [comment]
This seems like a simple thing to do.  Unfortunately, only the repo owner can add them, it seems. Ping @caolan

**Comment by caolan** [comment]
I added `javascript`, `async`, `callbacks` to the topics - let me know if you think we should add any others

**Comment by hargasinski** [comment]
Awesome, thanks!
