### ISSUE TITLE
whilst() throws exception on deep iteration

### ISSUE THREAD

**Issue by stevenhankin** [caolan/async#1375]
# Background
I'm using Async.whilst() to wait for all multiple database callbacks to complete at the end of a CSV Parsing stream before committing and closing the connection.  One workaround is to wrap the iteration callback in a short timeout, but this feels kludgy.

# Description
**What version of async are you using?**
Version 2.1.5

**Which environment did the issue occur in (Node version/browser version)**
Any

**What did you do? Please include a minimal reproducable case illustrating issue.**
```javascript
/* Simple case */
let pending = 10000;

async.whilst (
    () => { return pending > 0 },
    (cb) => { pending-- ; cb() },
    (err) => { }
);
```

**What did you expect to happen?**
Should complete without exception.  

**What was the actual result?**
```javascript
RangeError: Maximum call stack size exceeded
```

**Suggestion**
Implement [trampolining](https://en.wikipedia.org/wiki/Tail_recursion#Through_trampolining)

**Comment by aearly** [comment]
This is expected behavior when using a synchronous iteration function.  We removed internal deferrals for performance reasons.  If you want to use a sync function with whilst, either defer the callback with `process.nextTick` or wrap it in `ensureAsync`.

**Comment by aearly** [comment]
And we would love to implement trampolining, but unfortunately it doesn't work with an asynchronous recursive function.  You still need some form of async while loop, which you can't do without recursion (in ES5, at least, and an ES2017 `async/await` implementation would have built-in deferrals behind the scenes... ).
