### ISSUE TITLE
lodash dep

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1376]
```
 leg@xps:~/WebstormProjects/oresoftware/sumanjs/suman$ npm la lodash
 suman@1.1.512218
 │ /home/oleg/WebstormProjects/oresoftware/sumanjs/suman
 │ Suman is an advanced, singular, Node.js test runner designed to supercede Mocha and rival AVA
 │ git+https://github.com/sumanjs/suman.git
 │ https://github.com/sumanjs/suman#readme
 ├─┬ node-check-fast@0.0.1006
 │ │ Run node -c as fast as possible on .js files in a project
 │ │ git+https://github.com/ORESoftware/node-check-fast.git
 │ │ https://github.com/ORESoftware/node-check-fast#readme
 │ └─┬ async@2.1.5
 │   │ Higher-order functions and common patterns for asynchronous code
 │   │ git+https://github.com/caolan/async.git
 │   │ https://github.com/caolan/async#readme
 │   └── lodash@4.17.4
 │       Lodash modular utilities.
 │       git+https://github.com/lodash/lodash.git
 │       https://lodash.com/
 └─┬ suman-utils@0.0.73099
   │ Shared module within the Suman test runner ecosystem
   │ git+https://github.com/ORESoftware/suman-utils.git
   │ https://github.com/ORESoftware/suman-utils#readme
   ├─┬ async@2.1.5   !!! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< !!!  here
   │ │ Higher-order functions and common patterns for asynchronous code
   │ │ git+https://github.com/caolan/async.git
   │ │ https://github.com/caolan/async#readme
   │ └── lodash@4.17.4
   │     Lodash modular utilities.
   │     git+https://github.com/lodash/lodash.git
   │     https://lodash.com/
   └── lodash@4.17.4
       Lodash modular utilities.
       git+https://github.com/lodash/lodash.git
       https://lodash.com/
```

looks like a recent version of async depends on lodash. For backend projects, I found that lodash takes up around 5000 kbs on disk. 

My concern is - if async uses lodash - does installing async usually incur a 5000kb disk penalty if a project was not already using lodash?

Has async found a way to split up lodash for backend projects, so that only needed functions are imported?

For example, import 'lodash.merge' instead of all of lodash?

Please advise. I'd like to reduce any dependency on lodash while keeping a dependency on async.

**Comment by ORESoftware** [comment]
I'd have to look through the codebase, but, do you really need lodash for this (wonderful) project?

**Comment by ORESoftware** [comment]
IMO - please please please - lodash is OSS. Please take the functions you need from lodash and copy them to async if possible. TMK I am importing all of lodash when I import async (for backend projects), and that is bad.

**Comment by megawac** [comment]
You're not importing all of lodash when you use async, but you are installing lodash by NPM. In async we're importing only the methods we use. Perhaps we can create a npm repo with only the distributables @aearly (i.e. no npm dependencies)

**Comment by aearly** [comment]
I don't think we need another "just async.js" package.  If you're not using Lodash anywhere else in your project, you can just `rm node_modules/lodash` before you upload to your server/container/etc..

**Comment by ORESoftware** [comment]
@aearly I am importing async to a library, which I in turn publish to NPM, which other people need to install. I'd rather not have unnecessary 5000kbs in my library - this forces everyone who uses my lib to install lodash.

I am concerned about the footprint of my module/library for the use of other - I am not very concerned about footprint of my applications.

Does that make sense?

**Comment by aearly** [comment]
I wouldn't sweat it too much.  It is likely that consumers of your library will also be using Lodash somehow, and it will be de-duped.  If you are really concerned, you could copy and use Async's single-file `dist/` version in your lib.

You could also use `async-es` and use a tool like Rollup to compile a single JS file for your lib with all the dependencies baked in, only including the parts of Async/Lodash you actually use.

**Comment by ORESoftware** [comment]
@aearly yeah, thanks - I think using the /dist dir would be too much hassle as it would making versioning with async too hard. 

Why not make lodash a devDep in your project? if users ultimately require /dist instead of all your code?

**Comment by ORESoftware** [comment]
Yeah, looking at the code, looks like you guys could simply move lodash into a dev dep! does that make sense?

**Comment by aearly** [comment]
We support requiring individual Async functions (e.g. `require('async/waterfall')`), which in turn requires whatever individual Lodash functions that are needed, so we can't remove it as a normal dependency.

**Comment by ORESoftware** [comment]
Ok, understood, could you publish async-dist in the NPM repo with only the dist directory? Or is that what you were suggesting that I do?
