### ISSUE TITLE
Is async.eachSeries compatible with ES6 Promises ?

### ISSUE THREAD

**Issue by anacicconi** [caolan/async#1378]
I ran into a problem where I have to apply a chain of Promises for an array of elements. This Promises have to be done in the order they are defined. I tried to use async.eachSeries. However, I'm not able to make it work as expected. Is this a limitation of the module or am I missing something?

With eachSeries, all the items are passed to the loop. Even if there's an error, the loop keeps going on to the next item thanks to next(err). However, when we try it with a chain of promises inside, if there's an error in one of the Promises for one of the items, the loop stops. Here's an example:     

     var items = ['a', 'b', 'c'];

     return new Promise((resolve, reject) => {

        async.eachSeries(items, (item, next) => {

            function1(item)
                .then(function2)
                .then(function3)
                .then(
                    function() {
                        console.log('no, error');
                        next();
                    })
                .catch(
                    function(err) {
                        console.log('error found');
                        next(err);
                    });

        }, (err) => {
            console.log('final error', err);
            if (err) {
                reject(err); // --> I would like to stop it if there's an error
            } else {
                resolve();
            }
        });
    });

In this case, if there's an error on item 'b' the item 'c' will never pass on the loop. 

The only solution I found for that is to stop using next(err) on the catch() and uses next() like if there was no error. The problem with this workaround is that in the end of the loop, I mean in the second part of the async.eachSeries, I'm not able to identify an error and reject the promise. 

Here's an example:

    var items = ['a', 'b', 'c'];

     return new Promise((resolve, reject) => {

        async.eachSeries(items, (item, next) => {

            function1(item)
                .then(function2)
                .then(function3)
                .then(
                    function() {
                        console.log('no, error');
                        next();
                    })
                .catch(
                    function(err) {
                        console.log('error found');
                        next();
                    });

        }, (err) => {
            console.log('final error', err);
            if (err) {
                reject(err); // --> It will never stop here as we use next() on the catch without passing the error
            } else {
                resolve();
            }
        });
    });

**Comment by aearly** [comment]
> With eachSeries, all the items are passed to the loop. Even if there's an error, the loop keeps going on to the next item thanks to next(err).

This isn't true.  `eachSeries` should exit the iteration when an error is encountered.  It should be no different if you're using promises under the hood.

**Comment by anacicconi** [comment]
Oh, I must have missed something during my tests. Thanks for you answer @aearly.
