### ISSUE TITLE
feature request - variation of async apply - A wrapper function

### ISSUE THREAD

**Issue by alexjv89** [caolan/async#1384]
When writing modular async functions that return a value, it would most likely be written as 
`function(arg1,arg2..., function(err,results))` these functions are difficult to use in async.series and async.parallel. 

Say, I had an implementation logic that involves 3 async function called one inside another using the data retrieved from the earlier function, we could argue that async.waterfall is the best logic to use.

However the problem with async.waterfall is that 2nd function gets the values of the 1st function, and the 3rd function gets the value of the 2nd function. If for some reason, I need to change the order of execution of the function, I will most likely need to refactor the functions also as they are heavily dependant on each other.

Ideally I would want to write independant functions, that I can call in async.series or async.parallel and can order them in async.series in such a way that it gives me some application logic. 

to do this I end up writing generic functions as such:
`function(arg1,arg2..., function(err,results))`

and in async.series I write a wrapper for these functions so that they can be used
```
var e_var={}; // some execution variable
e_var.results=[]; // results will come here
async.series([
  function(callback){ // this is the wrapper function
    a(1,2,function(err,result){ // actual modularized code
      e_var.results=result;
    })
  },
],function(err,results){
})
```
Using the execution variable, I can have a bunch of async.series or async.parallel logic running with modularized code. 

Writing the wrapper function again and again is fine if the series is like 5 steps. Anything more than that it becomes difficult to read the code. 
Because function `a` is returning value via the callback, the function `a` cant be called via async.apply also. 

So I wrote this generic wrapper function
```
/**
 * This is a wrapper function that makes it possible for using regular function that returns values via callbacks 
 * to be used in async.series and async.parallel. The return value is assigned to a value of your choice
 * @param  {Function} 			fn 			Wraps this function
 * @param  {Array}   			args		Arguments for the inner function
 * @param  {Object or Array}	assign_to 	The results from the inner fuction is assigned to this value
 * @return {Function}             			function that can be used in async series or parallel
 */
apply:function(fn,args,assign_to){
	var ret=function(callback){
		args.push(function(err,result){ // adding the callback function which assigns the return to a variable
			_.forEach(result,function(value,key){ // this works if the return is an array or an object
				assign_to[key]=value;
			});
			callback(err);
		});
		// var args=[1,2]
		fn.apply(null,args);
	};
	return ret;
},
```

and here is how I use it (above wrapper function is called as `GeneralService.apply` in the code below)

```
async.series([
	getAllBookTags,
	// getting influencer books from redis
	GeneralService.apply(RedisService.getMultipleKVsFromRedis,['books_by_influencer:',filter.influencers,'redis_search'],a.i_values),
	// getting books with tag from redis
	// async.apply(RedisService.getMultipleKVsFromRedis,'books_with_tag:',filter.book_tags,'redis_search',a.t_values),
	GeneralService.apply(RedisService.getMultipleKVsFromRedis,['books_with_tag:',filter.book_tags,'redis_search'],a.t_values),
	// entire filter logic
	findRelevantBooks,
	findDynamicScoreOfBooks,
	getASetOfFullBookObject,
	
	// get all influencers
	// async.apply(User.getAllInfluencers,pg.influencers),
	GeneralService.apply(User.getAllInfluencers,[],pg.influencers),
	// get all the reviews favorited by the user
	getAllReviewsFavoritedByUser,
	// adding influencer info in reviews
	addInfluencerInfoIntoReviews,

],function(err,result){
	.....
});	
```
The above controller loads  - [this page](https://www.highlyreco.com/s?influencers=3,4,8,9,12,17,18,20,21,22,23,26,27,28,63,468,469,472,477,483,491,493,495,496,497,498,499,500,503,511,516,517,519,533,555&book_tags=all)

With the wrapper function, the code is clean and more readable. 

I would love to know if there is a better way to do this. If this makes sense, maybe it can be added to async.

**Comment by aearly** [comment]
Have you checked out `auto`?  It might be more in line with what you want.
