### ISSUE TITLE
How can use implicit args in auto and autoinject 

### ISSUE THREAD

**Issue by mjafarpour** [caolan/async#1387]
Hi,
How can i use implicit args list for auto and autoinject.
I use async 2.1.5 and nodeJs 4.2.6

eg:

var args = [ 'arg1', 'arg2', 'arg3' ] ,
      funcList = {
                 arg1: function(cb){ cb(null,'xyz')  },
                 arg2: function(cb){ cb(null,'xyz')  },
                 arg3: function(cb){ cb(null,'xyz')  }
            }

funcList[ 'arg4' ] = [args, function( r, cb ){
     // use or change  r[ args[0] ] or r[ args[1] ] ...
}]

async.auto(funcList, callback);

at the run time i get Error: async.auto task `arg4` has a non-existent dependency `arg1, arg2, arg3` in arg1, arg2, arg3

**Comment by aearly** [comment]
Change it to:

```js
funcList[ 'arg4' ] = args.concat(function( r, cb ){
  // use or change r[ args[0] ] or r[ args[1] ] ...
})
```

**Comment by mjafarpour** [comment]
Thanks, it's worked with auto method but can use it for autoinject?

**Comment by aearly** [comment]
You can't have dynamic args in autoInject.  All args have to be explicit in the function definition.
