### ISSUE TITLE
Please update the description website link

### ISSUE THREAD

**Issue by andmeics** [caolan/async#1388]
The http form link can not be support ,so http://caolan.github.io/async/ can not be reach,please update the link into https://caolan.github.io/async/ , think you.

**Comment by aearly** [comment]
Which link exactly?

**Comment by andmeics** [comment]
https://caolan.github.io/async/

**Comment by aearly** [comment]
No, where is this link?

**Comment by andmeics** [comment]
<img width="720" alt="screen shot 2017-03-20 at 15 52 00" src="https://cloud.githubusercontent.com/assets/6023090/24091783/2e51d34a-0d85-11e7-84fe-811bfd5b9632.png">

**Comment by aearly** [comment]
Ah.  That would be on @caolan to update.

Out of curiosity, why does it have to be https?  The current http link works fine.

**Comment by andmeics** [comment]
Yes,why it works fine today,but yesterday doesn't? I don't know what happened,so I thought it because GitHub not allowed
