### ISSUE TITLE
fork child process in async.each or async.eachSeries results in the loop end after the first function done

### ISSUE THREAD

**Issue by MarcCaesars** [caolan/async#1389]
i've tried 2.1.5 and 1.5.x version, both repeat this problem.

```javascript
// an example of the function which has child process
cp.exec('some cmd', function(err) {
  if(err) {
    throw err;
  } else {
    cp.fork(moduleNeedToRun, [params], function(err, stdout, stderr) {})
  }
});
```

when i push an array of the example function above into async.eachSeries, the loop ends after the very first function completion.

is there any problem in my code? or the each/eachSeries exit when child process returns a success signal?

**Comment by aearly** [comment]
What was the underlying issue?  (So that others might benefit)
