### ISSUE TITLE
queue.remove() with filter function

### ISSUE THREAD

**Issue by robsch** [caolan/async#1391]
I'm currently finding a way to remove certain unprocessed entries in a queue/priorityQueue. I don't know how to do it, so I would appreciate if anyone could give me a hint.

**Feature suggestion**: add another method with which entries gets removed like that:

    var q = async.queue(function (task, callback) {
        callback();
    });
    q.push({some: 'thing'});
    q.remove(function (task) {
        return task.some === 'thing'; // remove task if return value is true
    });

Or with the priority queue: 

    var q = async.priorityQueue(function (task, callback) {
        callback();
    }, 3);
    q.push({some: 'thing'}, 100);
    q.remove(function (task, priority) {
        return task.some === 'thing'; // remove task if return value is true
        or
        return priority === 100; // remove task with certain priority
    });

**Comment by aearly** [comment]
We expose the underlying tasks as `q._tasks`.  It is a linked list, rather than an array, however.

@megawac what do you think is the best solution for removing an item from the queue?  Add a `filter` function to the `DLL`?

**Comment by megawac** [comment]
I think this is reasonable, I prefer the name `remove` than `filter` as remove implies destructiveness

**Comment by robsch** [comment]
Now, I've done it with collecting the tasks first and then remove them in a second step. I wasn't sure what would happen if I remove them immediately.

You could implement both: _filter_ and _remove_, though I needed only the remove function.

Compared to the _kill_ function I wouldn't remove the _drain_ function when remove is called.
