### ISSUE TITLE
Pass arguments to the first function in waterfall?

### ISSUE THREAD

**Issue by ghost** [caolan/async#14]
It doesn't seem to be possible to pass arguments to the first function in waterfall.

Could this be done in other ways because I really need the first one to get some variables.

**Comment by marcolino** [comment]
Hmmm... Great hacks, really... I too was puzzled by not being able to pass parameters to first waterfall function... But, shouldn't this be post to module author (caolan) as a bug/inconsistency ?

**Comment by megawac** [comment]
This is the intended use of these methods. async.apply was added mainly for this use case AFAIK

The documentation does give examples of using waterfall with a function, however, if anyone wants to amend the readme to show using waterfall with apply that would be fantastic

**Comment by jingles** [comment]
:+1: @adisos apply is great!  i've only been using this library a little while and I am continually impressed.

**Comment by ssrballin** [comment]
if anyone still has this issue, the constant function works very well.

```
async.waterfall([
    async.constant(42),
    function (value, next) {
        // value === 42
    },
], callback);
```

For more info, check out http://caolan.github.io/async/docs.html#.constant
