### ISSUE TITLE
Converting async.js usage into async/await

### ISSUE THREAD

**Issue by bf** [caolan/async#1401]
I wonder what your thoughts are on converting a legacy async.js-based control flow (mostly utilizing async.waterfall / async.series) to the Node 7.x async/await pattern.

Has anybody done it before and is it worth it?

My major gripe with async in recent years has been that the stack traces are meaningless in some scenarios, because it doesn't print out the actual place where an exception is throw. From switching to async/await I hope this issue is solved.

**Comment by bf** [comment]
when switching to `neo-async` I get proper stacktraces :(

**Comment by bf** [comment]
Fixed by using neo-async

**Comment by aearly** [comment]
Do you have an example that shows an improper stack trace?
