### ISSUE TITLE
Question - async.series / async.parallel - but no data accumulation

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1410]
Are there equivalents to async.series / async.parallel, but which do not accumulate data

e.g., we have

`async.series([] | {}, function(err, results){});`

I am looking for

`async.seriesX([] | {}, function(err){});`

I assume this might save a small amount of memory, by avoiding creating an object in the async library behind the scenes.

**Comment by ex1st** [comment]
```javascript
async.eachSeries(arr, (fn, cb) => { fn(cb); }, function(err){});
```

**Comment by aearly** [comment]
Yep, `each` and family work with objects, too.  Series uses `eachLimit`  in its implementation.

**Comment by ORESoftware** [comment]
Ummm, async.eachSeries does not have the same signature as async.series


```
async.series([


], function(err,results){

});
```
and

```
async.eachSeries([], function(item,cb){

}, function(err){

});
```

I am looking for

```js
async.seriesX([


], function(err){   // no results passed

});
```

**Comment by ex1st** [comment]
@ORESoftware 
Nope, eachSeries is best solution. Just try.

**Comment by ORESoftware** [comment]
I don't think it will work, because I have this style:

```js
async.series([
   function(cb){

  },
  function(cb){

  },
  function(cb}{

 }
], function(err,results){


});
```

I don't need to map the functions, I just need to run the functions in series.

**Comment by ex1st** [comment]
You can add your method:
```javascript
async.seriesX = function (fns, cb) {
  async.eachOfSeries(fns, (fn, key, cb) => { fn(cb); }, cb);
}

async.seriesX([] | {}, function(err){});
```

**Comment by ORESoftware** [comment]
Ok let me give it a shot, thanks
