### ISSUE TITLE
add index to map function

### ISSUE THREAD

**Issue by jeffersoncarpenter** [caolan/async#1411]
It's true that `indexOf` and `Object.keys` can be used, but it would be highly convenient if the index were passed to the iterator function.  The API is not easy for me to imagine, though.  It would be easy to pass it to the iterator after the callback.

**Comment by ex1st** [comment]
http://caolan.github.io/async/docs.html#mapValues

**Comment by megawac** [comment]
See #669, #321, #594 and some others for some background
