### ISSUE TITLE
How to return something in callback when the overall task is completed ?

### ISSUE THREAD

**Issue by goelatul00** [caolan/async#1413]
**What version of async are you using?**

**Which environment did the issue occur in (Node version/browser version)**

**What did you do? Please include a minimal reproducable case illustrating issue.**

**What did you expect to happen?**

**What was the actual result?**

**Comment by megawac** [comment]
This question isn't clear enough to give you a better answer. Please clarify the async method you're using and provide an example of what you're trying to do. 

Anyway, typically you do not return things in the callbacks. You call the callback `callback(err, result)`

**Comment by goelatul00** [comment]
Dear I want to return something from callback after completing my
operation(s). You are requested to provide some way to do this. You can
find sample code from attachment.

You will be very very thankful for any kind of support.

**Comment by megawac** [comment]
I don't see an attachment but

1) what async methods are you using
2) what do you want to return
3) how do you expect this returned value to be used.

I would encourage you to look at the documentation. For most cases you shouldn't be returning anything, you call the `iteratee` callback with what you would otherwise be returning.

**Comment by goelatul00** [comment]
Dear, I am using async library for long time. There are some cases where I
want to return final outcome / result from async like from *waterfall* (
where callback function have final outcome as second argument ). How would
I do such task Or I want to return success object after completion of *each*
or *eachSeries*, How would I do this. You will be thankful for support.

**Comment by aearly** [comment]
A code example of what you are looking for would be very helpful here.  It is hard to understand what you are asking for.
