### ISSUE TITLE
Add backoff option to retry

### ISSUE THREAD

**Issue by martinambrus** [caolan/async#1415]
It would be great if the retry() method had a backoff option. If set, it would increase interval by such factor between attempts. Also, a max_interval option would be nice alongside to tell up to what interval we should keep on increasing.

**Comment by aearly** [comment]
We already support this - `interval` can be a function. There's an example of exponential back-office in the docs:http://caolan.github.io/async/docs.html#retry

**Comment by martinambrus** [comment]
Ah, I see. The docs confused me a bit and I didn't see that, sorry about this.
