### ISSUE TITLE
Should `queue` support falsy values for `q.drain`, `q.empty`, etc...?

### ISSUE THREAD

**Issue by hargasinski** [caolan/async#1423]
It might be useful for `queue` to support falsy values for functions that are assigned by the user.

The two primary use cases for this would be: libraries that accept an optional function as a callback:
```js
function foo(/*other args*/, callback) {
  if (callback) {
    q.drain = callback;
  }
}

// could be simplified to
function foo(/*other args*/, callback) {
  q.drain = callback;
}
```
and removing the callbacks:
```js
// remove `drain` callback
q.drain = (() => {});

// could be simplified to
// remove `drain` callback
q.drain = null;
```
These are mainly style preferences though. The downside is that it would quiet a bit of additional checks on our side, such as `if (q.idle() && q.drain)` [here](https://github.com/caolan/async/blob/master/lib/internal/queue.js#L74).

The idea for this came from a downstream issue [remote-sync](https://github.com/yongkangchen/remote-sync/pull/402/files) was having with [fs-plus](https://github.com/atom/fs-plus) library where they weren't passing in a [required callback](https://github.com/atom/fs-plus/blob/master/src/fs-plus.coffee#L429). Thought it might be interesting to see if this should be a supported use case in general.

**Comment by aearly** [comment]
I see two options here (really 3):

1. Support falsy values, and use `q.drain && q.drain()` where we need to.  This muddies the queue  logic a bit.
2. Change `drain` to be a getter/setter, that returns `noop` if `drain` is falsy.  This will make creating queue instances slightly slower.
3. Keep it as is.

All of these have their tradeoffs.  Inertia leads me to option 3. Also, if we do this to `drain`, it might make sense to do this with other queue callbacks.

**Comment by hargasinski** [comment]
After thinking about it some more, I'm leaning towards the third option too. Considering no one has actually requested this yet, there isn't much of a point in cluttering the logic preemptively (at least with the first option). Thanks.
