### ISSUE TITLE
Elusive `concatLimit` 

### ISSUE THREAD

**Issue by elmigranto** [caolan/async#1426]
Some issues and PRs (#973 #847) mention `concatLimit` but it's nowhere to be found in actual API and docs. Would be neat to have it, or is there a reason it is not provided? (I haven't been able to find anyting in changelog or otherwise myself.)

Thanks!

**Comment by aearly** [comment]
This is a bizarre omission, but you're the first to notice!  (I don't think `concat` and family have many users.)  A PR to add this would be welcome.
