### ISSUE TITLE
Final callback not executed!!

### ISSUE THREAD

**Issue by djkwagala** [caolan/async#1431]
Version: 2.4.1

Environment: Browser

**What did you do? Please include a minimal reproducable case illustrating issue.**
```ts
async.each(seriesArray, (series1: SeriesConfig) => {
                    this.dataStore.series[series1.name] = this.setSerieData(series1);               
            }, (error?: Error) => {
                if(error) console.error(error.message);
                this.setState({ dataStore: this.dataStore, isLoaded: true });
            });
```
The final callback is not executed!
``` ts
           (error?: Error) => {
                // tslint:disable-next-line no-console
                if(error) console.error(error.message);
                this.setState({ dataStore: this.dataStore, isLoaded: true });
            });
```

**What did you expect to happen?**
I expected the state to be updated with new dataStore
**What was the actual result?**
The final callback is never executed

**Comment by aearly** [comment]
You're missing a callback in your iteratee function.

**Comment by djkwagala** [comment]
Thanks, this can be closed. you need to indicate this clearly on the documentation. 
I had thought that the callback on the iterator is the one executed for each and every item. and the 3rd Parameter( finalCallback) would be auto executed without needing to indicate callback() in the iterator.
Thanks once again.
