### ISSUE TITLE
TypeError: wrapAsync(...) is not a function with node 8.0.0

### ISSUE THREAD

**Issue by tlbtlbtlb** [caolan/async#1433]
**What version of async are you using?**

2.4.1

**Which environment did the issue occur in (Node version/browser version)**

node 8.0.0

**What did you do? Please include a minimal reproducable case illustrating issue.**

```javascript
async=require('async')
_=require('underscore')
async.parallel(_.range(10), function(iter, cb) { cb(null); }, function(err) { console.log(err); })
```

**What did you expect to happen?**

should print null.

**What was the actual result?**
```
TypeError: wrapAsync(...) is not a function
    at /usr/local/lib/node_modules/async/dist/async.js:3830:24
    at eachOfArrayLike (/usr/local/lib/node_modules/async/dist/async.js:1003:9)
    at eachOf (/usr/local/lib/node_modules/async/dist/async.js:1051:5)
    at _parallel (/usr/local/lib/node_modules/async/dist/async.js:3829:5)
    at Object.parallelLimit [as parallel] (/usr/local/lib/node_modules/async/dist/async.js:3912:5)
    at repl:1:7
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
```

**Comment by tlbtlbtlb** [comment]
Oops, my mistake.

**Comment by andre0799** [comment]
Could you please share your mistake @tlbtlbtlb ? That would be helpful to others that get the same error.

**Comment by emberdyn** [comment]
@tlbtlbtlb What was the solution to this error?  I am getting the same error.  Thanks.

**Comment by TheRationalizer** [comment]
"Oops, my mistake" - That helped me solve the problem too, thanks for elaborating.

**Comment by Hunchmun** [comment]
@tlbtlbtlb would you still care to elaborate? Thanks

**Comment by tlbtlbtlb** [comment]
`async.parallel` takes an array of functions. I was calling it like `async.each`.

**Comment by TheRationalizer** [comment]
Thanks 👍

**Comment by likping** [comment]
How to solve TypeError: wrapAsync(...) is not a function

**Comment by aearly** [comment]
You're passing an undefined function as an iteratee, e.g. `async.map(array, undefined, callback)`.  Check your code in the call stack.
