### ISSUE TITLE
Guarantee that parallelLimit(1) will run functions in order

### ISSUE THREAD

**Issue by the1mills** [caolan/async#1434]
say we have

```js
async.series([
  function one(cb){},
  function two(cb){},
  function three(cb){}
]);
```

for some important genericism in my program, I'd like to convert the above to:

```js
async.parallelLimit(1, [
  function one(cb){},
  function two(cb){},
  function three(cb){}
]);
```

my question is rightly, can I be guaranteed the same order of operation (one,two, then three) when using parallelLimit(1) instead of async.series?

**Comment by the1mills** [comment]
I have the same question for

`async.eachSeries`

and 

`async.eachLimit(1)`

**Comment by megawac** [comment]
Yes, `parallelLimit(1)` and `series()` and `eachLimit(1)` and `eachSeries()` are equivalent and [actually implemented as such](https://github.com/caolan/async/blob/master/lib/eachSeries.js#L23)
