### ISSUE TITLE
TypeScript support question

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1435]
I am on async version 2.4.1

I have this question on SO:
https://stackoverflow.com/questions/44479657/pass-array-to-async-library-eachseries-expects-dictionary

any answers will be upvoted, thanks!

**Comment by aearly** [comment]
Sounds like an issue with the typescript definition.

**Comment by the1mills** [comment]
Ok I guess I will file an issue with TypeScript on our collective behalf...I figured y'all authored the .d.ts for this lib
