### ISSUE TITLE
How is Async going to support concat functions?

### ISSUE THREAD

**Issue by suguru03** [caolan/async#1437]
**What version of async are you using?**
v2.4.1

**Which environment did the issue occur in (Node version/browser version)**
Node v8.0.0

**What did you do? Please include a minimal reproducable case illustrating issue.**
```js
async.concat([1, 2, 3], (val, next) => {
  next(null, val % 2 ? val : 0);
}, (err, result) => {
  console.log(result); // [1, 3]
});
```

**What did you expect to happen?**
If the function has the same functionality as `Array.prototype.concat`, it should be `[1, 0, 3]`.

**What was the actual result?**
`[1, 3]`

Also I realized,
```js
[].concat(0); // [0]
[].concat(); // []
[].concat(undefined); // [undefined]
```
I would like to know how Async is going to support the functions. Thanks :)

**Comment by aearly** [comment]
Looks like we're just doing a truthy check here, when we should actually do `y == null`:

https://github.com/caolan/async/blob/master/lib/internal/concat.js#L5

**Comment by suguru03** [comment]
Sure, I'll follow the PR changes, thanks :)
