### ISSUE TITLE
queue stop processing after first batch

### ISSUE THREAD

**Issue by huyntsgs** [caolan/async#1439]
I have implemented a simple queue, but it only works with first batch. And then stop without drain calling.
in console, there are only 4 lines printed.

[2017-06-23 09:35:52.013] [INFO] console - http://mysite/getuserinfo/0
[2017-06-23 09:35:52.013] [INFO] console - http://mysite/getuserinfo/1
[2017-06-23 09:35:52.014] [INFO] console - http://mysite/getuserinfo/2
[2017-06-23 09:35:52.014] [INFO] console - http://mysite/getuserinfo/3

    var queueSize = 4;
    var taskHandler = function(task, done) {
      console.log(task.url);     
    };    

  var aqueue = async.queue(taskHandler, queueSize);

    aqueue.drain = function() {
      console.log("All the work has been done.");
    }

    for(var i = 0; i < 50; i++) {
      aqueue.push({ id: i, url: "http://mysite/getuserinfo/"+i });
    }

**Comment by hargasinski** [comment]
Hi @huyntsgs, thanks for the question!

It looks like you're not calling `done` in `taskHandler`. You need to call it, so `queue` knows you're done processing the current item, and it can run the next one. i.e. `taskHandler` should be along the lines of 
```js
var taskHandler = function(task, done) {
  console.log(task.url);
  done();
}; 
```

`aqueue.drain` is never called, as if you don't call `done`, the `queue` will never finishing processing all of it's items. See the [`queue`](http://caolan.github.io/async/docs.html#queue) and [`QueueObject`](http://caolan.github.io/async/docs.html#QueueObject) docs for more info.

**Comment by huyntsgs** [comment]
Thanks @hargasinski, it worked :)
