### ISSUE TITLE
TypeScript support question - signature for final callbacks

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1440]
I have this code, and I need to figure out which TS type def to use for "WhatIsThis".
Everything else seems to be taken care of by the async type defs, since I have installed

`@types/async`

But it seems that I need to import 

`import {WhatIsThis} from '@types/async';`

I just don't know what `WhatIsThis` is :)

```typescript
export const transpileAll = function (transformPaths: Array<string>, cb: WhatIsThis) {

  async.mapLimit(transformPaths, 5, function (t, cb) {
      // yadda yadda
        process.nextTick(cb);
    });

  }, cb);

};
```

I looked as `@types/async` and I didn't see it. I am also looking for WhatIsThis for async.each as well as async.mapLimit.

Please advise.

**Comment by ORESoftware** [comment]
For the sake of an example, let's say my code looks like this:

```typescript
  async.mapLimit(transformPaths, 5, function (t, cb) {
      // yadda yadda
        process.nextTick(cb, {
           foo: true,
           bar: 'rolo'
       });
    });

  }, cb);

```

so somehow I have replace the generic T with an interface like so:

```
interface IMapItem{
    foo: boolean,
    bar: string
}
```

So it would be `WhatIsThis<T>`  => `WhatIsThis<IMapItem>`

but how does this actually work with async lib?

**Comment by aearly** [comment]
Sorry, we don't maintain the `@types` for Async, and I'm not familiar with TS's type system.

Maybe its `AsyncResultArrayCallback`?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/async/index.d.ts#L113
