### ISSUE TITLE
Canceling an `async.retry`

### ISSUE THREAD

**Issue by gabegorelick** [caolan/async#1442]
There doesn't seem to be a way to cancel an outstanding `async.retry` task:

```js
var _task = wrapAsync(task);
var attempt = 1;
function retryAttempt() {
        _task(function(err) {
            if (err && attempt++ < options.times &&
                (typeof options.errorFilter != 'function' ||
                    options.errorFilter(err))) {
                
                // not returned to caller, so no way to `clearTimeout`
                setTimeout(retryAttempt, options.intervalFunc(attempt));

            } else {
                callback.apply(null, arguments);
            }
        });
}
retryAttempt();
```

Instead, you have to add logic to an `errorFilter` function to check if the task has been canceled. But that's not the same since you have to wait for the timeout to expire before your `errorFilter` will run.

**Comment by aearly** [comment]
Doing this at in the `errorFilter` will be as good as it gets.  There is no agreed-upon way to cancel an async request. Every Async method cannot be canceled -- all you can do is ignore the result.

**Comment by gabegorelick** [comment]
Totally understand if you don't want to implement this since there's no consensus in the community for how to do this, but one way would be to use an EventEmitter to output the timeout IDs. Something like
```js
export default function retry(opts, task, callback) {
   // ...snip

   const emitter = new EventEmitter(); 

    var _task = wrapAsync(task);

    var attempt = 1;
    function retryAttempt() {
        _task(function(err) {
            if (err && attempt++ < options.times &&
                (typeof options.errorFilter != 'function' ||
                    options.errorFilter(err))) {
                const timeoutID = setTimeout(retryAttempt, options.intervalFunc(attempt));
                emitter.emit('retry', timeoutID);
            } else {
                callback.apply(null, arguments);
            }
        });
    }

    // would have to ensure this is called on nextTick if wrapAsync doesn't already do that
    retryAttempt();
    
    return emitter;
}
```

**Comment by aearly** [comment]
The event emitter is a clever solution to your use-case.  It's a bit un-Async-ey though.  Mixing event emitters and callbacks always tends to get confusing control-flow wise.

Also, we have Plans™ for the currently-unused/implemented return value for Async functions...
