### ISSUE TITLE
asyncify release zalgo with synchronous functions

### ISSUE THREAD

**Issue by olegabyst** [caolan/async#1446]
```js
const async = require('async');

function foo(x) { return x + x };
async function bar(x) { return x + x };

var afoo = async.asyncify(foo);
var abar = async.asyncify(bar);

afoo(3, (err, r) => console.log(r));
abar(5, (err, r) => console.log(r));

console.log('Current cycle');
```
this produce such output:
```
6
Current cycle
10
```
I think it's inconsistent behavior.

**Comment by aearly** [comment]
Async deliberately doesn't protect you from Zalgo as much as possible, for performance reasons.   We do have `ensureAsync`, which is a Zalgo-containing wrapper, e.g.:

```js
var afoo = async.ensureAsync(async.asyncify(foo));
```

**Comment by olegabyst** [comment]
@aearly oh, such tradeoff makes sense

**Comment by isaacs** [comment]
One way to look at this is that async is not zalgo-introducing as much as it is zalgo-preserving.

The foo function returns immediately, and so its callback runs immediately.  The bar function returns a promise, and so its callback runs when the promise resolves.  In both cases, async is running the function right away.

It's a valid approach.  Now, if `async.asyncify()` ran the main function immediately in some cases, and on next tick in other cases (say, depending on whether a list had elements or was empty, etc.) then that would be introducing new zalgo into the system, surely resulting in a nezperdian hive mind of abject terror.

**Comment by eliranmal** [comment]
what's *zalgo*, if i may?

**Comment by eliranmal** [comment]
oh ok, i just saw [this][1] :)


[1]: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by ORESoftware** [comment]
I think ideally (in a future version of async) async could detect if the user fired the callback in the same tick, and then use process.nextTick internally. But how to detect if user fired callback in the same tick? That's the question.
