### ISSUE TITLE
async NPM module not executing setTimeout for each item in the array

### ISSUE THREAD

**Issue by rahul-desai3** [caolan/async#1447]
Following is the program I have written:

```
var async = require('async');

var arr = [1,2,3,4];

async.each(arr, function (item) {
  setTimeout(function () {
    console.log('item: ', item);
  }, 1000);
}, function (error) {
  console.log('error', error);
});
```

I expected the console log to show up after every 1 sec but it shows all the logs at once after 1 sec.

How do I fix this?

[I have also posted this on StackOverflow.](https://stackoverflow.com/questions/44972862/async-library-not-executing-settimeout-for-each-item-in-the-array)

**Comment by ex1st** [comment]
```javascript
async.eachSeries(arr, function (item, cb) {
  setTimeout(function () {
    console.log('item: ', item);
    cb();
  }, 1000);
}, function (error) {
  console.log('error', error);
});
```

**Comment by rahul-desai3** [comment]
@ex1st I am getting the following output:
```
item:  1
item:  2
item:  3
item:  4
error null
```

Not sure why the last one is `error null`.

If I remove the `cb` completely, all I get is:
`item:  1`

How do I fix this?

**Comment by ex1st** [comment]
@rahul-desai3 fix what? I don't understand what you mean.

**Comment by rahul-desai3** [comment]
@ex1st What should I modify in the code so that it doesn't give `error null` at the end?
Looks like the `cb()` needs to be executed for the node.js to process the next element in the array. What could be a sample `cb` funtion here?

**Comment by ex1st** [comment]
You can do: 
```javascript
if (error)
    console.log('error', error);
```
Also, `cb` needs for async's iterator, not for nodejs. It's a classic asynchronous JavaScript with callbacks.

**Comment by rahul-desai3** [comment]
@ex1st Thank you!
