### ISSUE TITLE
async in control flow

### ISSUE THREAD

**Issue by danielb2** [caolan/async#1450]
**What version of async are you using?**

2.5.0

**Which environment did the issue occur in (Node version/browser version)**

6.9.1

**What did you do? Please include a minimal reproducable case illustrating issue.**

``` javascript
Async.waterfall([
    function (next) {

        return next(null, 3);
    },
    Async.retry(3, (three, next) => {

        return next(null, three);
    })], (err, res) => {

        console.log(res);
});
```

**What did you expect to happen?**

I expected to see `3` printed  based on the [documentation for retry](http://caolan.github.io/async/docs.html#retry)

``` javascript
// It can also be embedded within other control flow functions to retry
// individual methods that are not as reliable, like this:
async.auto({
    users: api.getUsers.bind(api),
    payments: async.retryable(3, api.getPayments.bind(api))
}, function(err, results) {
    // do something with the results
});
```

If it doesn't work for all control flow functions, I think the documentation should be clear about that and list the ones which do work.

**What was the actual result?**

` TypeError: next is not a function`

**Comment by hargasinski** [comment]
Hi @danielb2, thanks for the question!

For use with flow control function, use [`async.retryable`](http://caolan.github.io/async/docs.html#retryable) as opposed to [`async.retry`](http://caolan.github.io/async/docs.html#retry). `retry` will immediately invoke the `task` function, while `retryable` returns a function you can call.

**Comment by danielb2** [comment]
oh I misread. it does say retryable in the example. 😳  Thank you

**Comment by aearly** [comment]
This seems like a mistake in our docs -- we should remove that example and call out `retyable` more.
