### ISSUE TITLE
Doc for someSeries callback appears incorrect

### ISSUE THREAD

**Issue by radcapitalist** [caolan/async#1451]
Hey - The documentation for someSeries() appears to incorrectly specify the "done" callback:

callback | function <optional> | A callback which is called as soon as any iteratee returns true, or after all the iteratee functions have finished. Result will be either true or false depending on the values of the async tests. **Invoked with (err, result)**.

However, my experience (still at v. 2.4.1) is that callback is invoked just with (result) (which makes sense, because the iteratee has no way to report an error, just true or false).

Thanks,

Eric

**Comment by megawac** [comment]
Yeah, the documentation appears confusing. The callback passed to the iteratee should be resolved with `callback(error, result)` and the final callback receives `err, result`.

For example
```
async.some(['file1','file2','file3'], function(filePath, callback) {
    callback(null, filePath)
}, function(err, result) {
    console.log(err, result)
});
```
Logs `null`, `true`.

**Comment by aearly** [comment]
Docs appear to be correct.
