### ISSUE TITLE
"sourceMappingURL" not built with "npm install"

### ISSUE THREAD

**Issue by jbelien** [caolan/async#1452]
**What version of async are you using?**
2.5.0

**Which environment did the issue occur in (Node version/browser version)**
Node.js v6.10.3 & npm 5.3.0

**What did you do? Please include a minimal reproducable case illustrating issue.**
I just run `npm install --save async` as described in the documentation.

**What did you expect to happen?**
Expect to have a `async.min.map` file build in `dist` folder.

**What was the actual result?**
No `async.min.map` file build in `dist` folder but `//# sourceMappingURL=async.min.map` at the end of `async.min.js` file.

**Comment by hargasinski** [comment]
Hi @jbelien. Thanks for the report! This will be fixed shortly.
