### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lmyzzu** [caolan/async#1457]
**What version of async are you using?**
2.4.1
**Which environment did the issue occur in (Node version/browser version)**
Maximum call stack size exceeded

**What did you do? Please include a minimal reproducable case illustrating issue.**
async.timesLimit(30000, 1, function (n, cb) {
	cb("", n);
}, function (errs, results) {
	console.log(errs, results);
});

**What did you expect to happen?**
no error

**What was the actual result?**
            callback(err);
            ^
RangeError: Maximum call stack size exceeded

**It's ok as follow (wondering):** 

async.timesLimit(30000, 1, function (n, cb) {
	process.nextTick(function () {
		cb("", n);
	});
}, function (errs, results) {
	console.log(errs, results);
});

**Comment by lmyzzu** [comment]
Who can explain to me ？ I’m much obliged.

**Comment by JohnLelii-CMCST** [comment]
You are not providing an async function when invoking timesLimit().  A synchronous function as you've provide can exceed the stack.
http://caolan.github.io/async/global.html

You can fix with setImmediate() or http://caolan.github.io/async/docs.html#ensureAsync

**Comment by lmyzzu** [comment]
@JohnLelii-CMCST Thanks for you guide, I'm understand this rule:
Wrap an async function and ensure it calls its callback on a later tick of the event loop. If the function already calls its callback on a next tick, no extra deferral is added.
