### ISSUE TITLE
question: check an async.queue to see if a matching task has already been inserted?

### ISSUE THREAD

**Issue by PsyTae** [caolan/async#1459]
Is there anyway to look at the tasks of a current queue to determine if the task you are about to put in might already match a task currently in the queue?

**Comment by aearly** [comment]
There is no officially sanctioned way to iterate the queue.  There is a `q._tasks` property that exposes the underlying linked list for the queue.  You can either iterate the linked list, or call `q._tasks.toArray().find(...)` to see if your task already exists.

This is an implementation detail, so it is not documented.  It might break in the future if we change how the queue works internally.

**Comment by aearly** [comment]
Although, as an enhancement to the queue, we could expose a `q[Symbol.iterator]` property for exposing an implementation-agnostic way to iterate the current items of the queue.

**Comment by OfekA** [comment]
I would also like this feature, many other Queues have this feature.
q.contains(task) would be very useful!
