### ISSUE TITLE
Doc for auto is wrong

### ISSUE THREAD

**Issue by SHocker-Yu** [caolan/async#1461]
https://caolan.github.io/async/docs.html#auto
In this example:
`write_file: ['get_data', 'make_folder', function(results, callback) { }`// The two parameter positions should be swapped
AND
`email_link: ['write_file', function(results, callback) { }`

**Comment by aearly** [comment]
> What version of Async are you using?

Sounds like you're using v1.x or earlier.

**Comment by SHocker-Yu** [comment]
@aearly yeah,you are right, thanks.
