### ISSUE TITLE
Support question - what to use in place of process.nextTick in browser

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1462]
Can't remember if I asked this before or not. To avoid Zalgo with this library, should we simply use

`setTimeout(x, 0);`

on the front-end, in place of

`process.nextTick(x);`

on the backend? I have an isomorphic library and need to make things work on both front-end and back-end.

thanks

**Comment by aearly** [comment]
http://caolan.github.io/async/docs.html#nextTick

**Comment by ORESoftware** [comment]
Thanks, I remember seeing that now. Yeah I have to use Webpack to replace `process.nextTick` in more than one place, maybe I can just use async's fill.

**Comment by aearly** [comment]
IIRC, there's a feature in Webpack that gives you a `process` object with a `nextTick` polyfill.  Might be getting confused with Browserify though...

**Comment by ORESoftware** [comment]
@aearly yeah I think both Webpack and Browserify have that
