### ISSUE TITLE
Async Waterfall - doesn't complete callback when exception occurs.

### ISSUE THREAD

**Issue by swateek** [caolan/async#1463]
**What version of async are you using?**
1.5.0

**Which environment did the issue occur in (Node version/browser version)**
NodeJS 4.4.4

**What did you do? Please include a minimal reproducable case illustrating issue.**

```js
var async = require('async');
var ftp = require('jsftp');

async.waterfall([
    function(callback){
        console.log("Step 1");
        // fetch data from DB
        callback(null);
    },
    function(callback){
        console.log("Step 2");
        // FTP to remote location using a third party library
        ftp.put(fileName, remoteLocation, function(err) {
        if (!err){
          callback(null, "File transferred successfully!")
        }else {
          callback(err, null)
        }
    });
}],
function(err, result){
    if(err){
        console.log("Step 2.5")
        console.log(err);
    }else{
        console.log("Step 3");
    }
    callback(err, result);
});


```

**What did you expect to happen?**

Expected the async waterfall to catch any error from the FTP function. In my case the server was down, it showed up a ECONNRESET error and it didn't move to further to the final block of waterfall.

**What was the actual result?**

No callback was returned.

**Comment by aearly** [comment]
It's impossible for Async to catch asynchronous errors.  It would be the job of the `jsftp` library to handle any errors and pass them to the callback.

**Comment by swateek** [comment]
Ah, thank you. I just realised that after posting.

Is there any work around to this? Or should I promisify?


Swateek Jena
about.me/swateek
[image: Swateek Jena on about.me]
  <http://about.me/swateek>Ph:+91-9900056958

**Comment by swateek** [comment]
Well, thank you. I used an event module for listening to on "error" and could successfully complete the task.

Here's the Stackoverflow question that helped me - [stackoverflow.com](https://stackoverflow.com/questions/45652672/nodejs-async-loop-doesnt-reach-final-error-block)
