### ISSUE TITLE
Migration from 1.x

### ISSUE THREAD

**Issue by AlesMenzel** [caolan/async#1464]
**What version of async are you using?**
2.5.0

**Which environment did the issue occur in (Node version/browser version)**
Node: 8.1.4

**What did you do? Please include a minimal reproducable case illustrating issue.**
```
async = require 'async'

data = Array(2000).fill().map (_, key) -> key

async.reduce data, [], (memo, item, next) ->
    return next null, memo if item % 2 is 0
    memo.push item
    next null, memo
, (err, res) ->
    console.log err, res
```

**What did you expect to happen?**
To see output of array of even numbers.

**What was the actual result?**
Error was thrown: `Maximum call stack size exceeded`
But with the 1.x version it was able to handle this amount of data.

**Comment by megawac** [comment]
You aren't using any async control flow doing this as your next callbacks are called synchronously. This is causing the callbacks to be called recursively at a rate that hits your environments stackoverflow recurssion caps. A simple fix would be to call `next` with a `setImmediate` or `setTimeout(f, 0)`

```js
var data = Array(2000).fill().map((v, i) => i);

async.reduce(data, [], (memo, item, next) => {
    if (item % 2 !== 0) {
    	memo.push(item)
    }
    setTimeout(next, 0, null, memo);
}, console.log.bind(console))
```
