### ISSUE TITLE
map incorrectly iterates object values instead of keys

### ISSUE THREAD

**Issue by hongkongkiwi** [caolan/async#1467]
**What version of async are you using?**
2.5.0
**Which environment did the issue occur in (Node version/browser version)**
Node.js v8.1.2
**What did you do? Please include a minimal reproducable case illustrating issue.**
```
async = require('async');

const obj = {
  'title1': 'value1',
  'title2': 'value2'
}

async.map(obj, (item, cb) => {
  console.log(item);
  cb(null, item);
});
```
**What did you expect to happen?**
title1
title2
**What was the actual result?**
value1
value2

It looks like when an object is passed to map, it incorrectly iterates through the values. But actually, it should iterate through keys as in the documentation.

The function mapValues should iterate through the values of an object.

**Comment by hargasinski** [comment]
Hi @hongkongkiwi, thanks for the report!

`map` is expected to iterate over the values of an object, as from the [docs](https://caolan.github.io/async/docs.html#map):

> Produces a new collection of values by mapping each value in coll through the iteratee function.

It will always return an array, even if you pass in an object. If you need access to the keys of the object, you could use lodash's [`_.entries`](https://lodash.com/docs/4.17.4#toPairs):

```js
const async = require('async');
const _ = require('lodash');

const obj = {
  'title1': 'value1',
  'title2': 'value2'
};

async.map(_.entries(obj), (item, cb) => {
  // item[0] is the key
  // item[1] is the value
  console.log(item);
  cb(null, item);
});
```

If there's an error in the documentation somewhere (or it's unclear), let us know or feel free to open a PR to fix/clarify it. Thanks!

**Comment by aearly** [comment]
`mapValues` is also an option.  Or `async.map(Object.keys(obj), (key, cb) => {...})`

**Comment by aguyinmontreal** [comment]
@aearly  @hargasinski   `async.mapValues` and lodash's `_.entries` only work with _Objects_ (at the opposite of `async.eachOf` and `async.map` which accept all types of collections)

How can we access the keys when using `map.async` for simple Arrays ?

**Comment by hargasinski** [comment]
@aguyinmontreal Lodash's `_.entries` works for arrays as well as objects. ES2015 also added [`Array.prototype.entries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/entries), which does the same thing.

```js
let arr = ['foo', 'bar', 'baz'];

async.map(arr.entries(), ([key, val], cb) => {
  // ...
}, callback);
```

As @aearly mentioned, you could also use [`Object.keys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys).

```js
async.map(Object.keys(arr), (key, cb) => {
  const val = arr[key];
  // ...
}, callback);
```

Hope that helps.
