### ISSUE TITLE
npm install is not working.

### ISSUE THREAD

**Issue by ashoksahoo** [caolan/async#1470]
**What version of async are you using?**
"async": "^2.5.0",

**Which environment did the issue occur in (Node version/browser version)**
Node - v8.4.0
Npm - 5.3.0
macOS Sierra - 10.12.6(16G29)

**What did you do? Please include a minimal reproducible case illustrating issue.**
 npm install async 

**What did you expect to happen?**
async to be installed.

**What was the actual result?**
Async install fails.
➜ npm install async 
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg== integrity checksum failed when using sha512: wanted sha512-kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg== but got sha1-iTMSr2myEj3vcfV4iQAWce6yyFM=. (8851 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-4AH6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ== integrity checksum failed when using sha512: wanted sha512-4AH6Z5fzNNBcH+6XDMfA/BTt87skxqJlO0lAh3Dker5zThcAxG6mKz+iGu308UKoPPQ8Dcqx/4JhujzltRa+hQ== but got sha1-D8Z9fBQYJd6UKC3VNr7GubzoYKs=. (4142 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== integrity checksum failed when using sha512: wanted sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== but got sha1-No8lEtefnUb9/HE0mueHi7weuVw=. (25587 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN turbo@1.0.0 No repository field.
npm WARN turbo@1.0.0 No license field.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ashok/.npm/_logs/2017-09-11T10_14_45_259Z-debug.log

**Comment by ashoksahoo** [comment]
It got fixed after clearing the cache. https://github.com/npm/npm/issues/17146

**Comment by Tapudp** [comment]
How do I clear the cache for npm

**Comment by ashoksahoo** [comment]
Check in stackiverflow. I don’t remember exactly.

**Comment by Sammylukorito23** [comment]
npm cache clean --force saved the day #npm
