### ISSUE TITLE
Aside question about packaging front-end code

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1473]
Hey async authors, I have the following question about packaging front-end distribution code with an NPM package

https://stackoverflow.com/questions/46335800/conditionally-include-dist-directory-with-npm-module

I think the async footprint is much smaller than my lib, and I get the feeling that async includes the front-end build whenever you install the NPM package, or is it different than that?

**Comment by aearly** [comment]
I think it's fine to include both node and browser builds in the same package. In Async's case, it's only 15kb more, of a 100kb tarball.  The extra size is not worth the pain of having to know to use a separate package in the browser.  

React is another library that does this, even though it is much larger, and it includes several front-end only distributions.
