### ISSUE TITLE
async.reflect -> error.message is undefined

### ISSUE THREAD

**Issue by AlexZeitler** [caolan/async#1474]
**What version of async are you using?**
2.5.0

**Which environment did the issue occur in (Node version/browser version)**
Node 6.11.1

**What did you do? Please include a minimal reproducable case illustrating issue.**
```
async.series([
    async.reflect(callback => callback(null, 'one')),
    async.reflect(callback => callback(new Error('bad stuff happened'))),
    async.reflect(callback => callback(null, 'two'))
  ],
  (err, results) => {
    console.log(results[1].message)
  });
```

**What did you expect to happen?**
output should be `bad stuff happened`

**What was the actual result?**
output is `undefined`

async without `async.reflect`:

```
async.series([
    callback => callback(null, 'one'),
    callback => callback(new Error('bad stuff happened')),
    callback => callback(null, 'two')
  ],
  (err, results) => {
    console.log(err.message)
  });
```
Output contains `bad stuff happened`

**Comment by aearly** [comment]
You should be looking for `results[1].error.message`, not `results[1].message`.  `reflect` makes the wrapped function callback with `{ error: error }` or `{ value: value }`

**Comment by AlexZeitler** [comment]
Thanks, `results[1].error.message` did the trick.
