### ISSUE TITLE
   node using async.parallel there is a strange phenomenon

### ISSUE THREAD

**Issue by wang-weifeng** [caolan/async#1476]
node using async.parallel there is a strange phenomenon, I used in the seven, and then restart the project in Linux when the first access to the data, troubleshooting a lot of places did not find the reasons, then I print in the 7 function Order mark, found 7 did not complete the end of the time, into the final function (err, result), and then in the final implementation of the async.parallel one of them. So I replaced promise-async-await, I found that the procedure did not have this problem, so I guess is not async.parallel this will happen, thank you

**Comment by aearly** [comment]
It's hard to understand what the issue is.  Do you have some example code?

**Comment by megawac** [comment]
I'm going to close this as there isn't enough information for us to act on. Feel free to add more info and ping me.
