### ISSUE TITLE
document and best practice request

### ISSUE THREAD

**Issue by ktravelet** [caolan/async#1477]
First of all, thanks so much for this great library.  I use this all over the place in my node applications mainly for flow control but the queue and limiters get used a lot as well. 

My issue is that I have a few files with 10-20 series methods and the entire file is just way to long.  I'd like to modularize the code a little bit and have each series entry in a separate file.  Hopefully you can point me to some examples like this with industry standard best practices.  

Most basic example is something like below.  This works but I'm just wondering if this is how it _should_ be done.  Should I handle the errors within the modules (like module one) or should the modules pass callback(err) (like module two) if it encounters an error?  I'm thinking the later to keep everything the callback way.  

Thanks!

File oneModule.js
```
module.exports =  function one(callback) {
    console.log('one!');
    /*
        do stuff
    */
    if (err) {
        throw new Error('Error from doing stuff');
    }
    callback();        
};
```
File twoModule.js
```
module.exports =  function two(callback) {
    console.log('two!');
    /*
        do stuff
    */
    if (err) {
        return callback('Error doing some stuff');
    }
    callback();
         
};
```
File main.js
```
var oneRequired = require('./one');
var twoRequired = require('./two');

async.series([oneRequired, twoRequired], function done(err, results) {
    console.log('done!', err, results);
});
```

**Comment by aearly** [comment]
If your `series` flows are getting too complicated, I recommend looking at `waterfall` or `auto`.

As far as how to separate functions across source files, there really is no "best practice" there -- it's entirely up to you. I like to break things up when theres more than ~200 lines in a file, some function will be re-used in several places, the function will be likely be changed or swapped out with something else, or I want to be able to test a function in isolation.
