### ISSUE TITLE
async.waterfall breaks when given an async function (node 8)

### ISSUE THREAD

**Issue by sjungwirth** [caolan/async#1480]
**What version of async are you using?**
2.5.0

**Which environment did the issue occur in (Node version/browser version)**
Node 8

**What did you do? Please include a minimal reproducable case illustrating issue.**
```
async=require('async')

async function myFirstFunction(callback) {
     callback(null, 'one', 'two');
}

function mySecondFunction(arg1, arg2, callback) {
     // arg1 now equals 'one' and arg2 now equals 'two'
     callback(null, 'three');
}

async function myLastFunction(arg1, callback) {
     // arg1 now equals 'three'
     callback(null, 'done');
}
 
async.waterfall([
     myFirstFunction,
     mySecondFunction,
     myLastFunction,
], function (err, result) {
     // result now equals 'done'
     console.log(err, result)
});
```

**What did you expect to happen?**
to not have an exception

**What was the actual result?**
```
> TypeError: callback is not a function
    at myFirstFunction (repl:2:5)
    at /Users/scott/node_modules/async/dist/async.js:143:27
    at /Users/scott/node_modules/async/dist/async.js:21:12
    at nextTask (/Users/scott/node_modules/async/dist/async.js:5297:14)
    at Object.waterfall (/Users/scott/node_modules/async/dist/async.js:5307:5)
    at repl:1:7
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12) undefined
```

**Comment by aearly** [comment]
Callbacks are not passed to `async` functions, instead, simply return a value.

**Comment by sjungwirth** [comment]
In the case of the first function above, where more than one argument is passed to `callback` in `myFirstFunction`, should we instead return an array? And If so, if I actually want one argument, but for it to be an array, should I wrap in another array?

**Comment by aearly** [comment]
Yeah, you could do something like:

```js
async.waterfall([
  // ...
  async function (arg1, arg2) {
    //...
    const arg3 = await foo()
    return [arg1, arg2, arg2]
  },
  function ([arg1, arg2, arg3], callback) {
    //...
  }
```

**Comment by chak774** [comment]
Then how to return error?

**Comment by josefanostylus** [comment]
Any answers to the above question? I believe to bail when encountered an error in a async function , you still need to call the "next" callback

**Comment by pravynandas** [comment]
How about this? 
```javascript
async.waterfall([
  // ...
  async function (arg1, arg2, callback) {
    //...
    try {
      const arg3 = await foo()
      return [arg1, arg2, arg3]
    } catch (err) {
      callback('An error occured:' + err.message);
    }
  },
  function ([arg1, arg2, arg3], callback) {
    //...
  }
```

**Comment by aearly** [comment]
`async` functions don't get passed callbacks.  Just `throw` an error.

**Comment by pravynandas** [comment]
Thanks.

**Comment by aearly** [comment]
> IIFE can be helpful here. Here is how i used it.
> 
> ```
> function doSomethingAsynchronously(_callback) {
>     ;(async () => {
>         await callAnAsyncFunction();
>     })()
>     _callback(null)
>   }
> ```

This wont do what you expect.  The `_callback` will be called before the async function returns.  Moving the callback inside the async IIFE will work, though.

**Comment by smartron1** [comment]
b

**Comment by haayhappen** [comment]
c
