### ISSUE TITLE
Which difference?

### ISSUE THREAD

**Issue by aleks63** [caolan/async#1482]
Which difference?

```
tasks = [ fn, fn, ... ]
async.parallel(tasks)
```

or
```
async test () {
tasks = [ fn, fn, ... ]
await tasks
}
```
I do not understand, why I should use async.js instead simple async/await?

**Comment by wartab** [comment]
Support for roughly 25% of browsers?

**Comment by aleks63** [comment]
No, for node.js only

**Comment by aearly** [comment]
One uses callbacks, the other uses promises.  It comes down to personal preference and what type of libraries you'll be interfacing with.

Also note it should be:

```js
async test () {
  tasks = [ fn, fn, ... ]
  await Promise.all(tasks)
}
```
