### ISSUE TITLE
support question - hooking into async queue events

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1484]
Regarding async versions >=  `"async": "^2.4.1"`

Is there a way to hook into the queue, to find out which items are running and which items are enqueued? For example, if I add 100 items to the queue with a concurrency of 5..there should be 95 enqueued items, is there a way for me to find out which ones those are?

I see the saturated and unsaturated callbacks - I am looking to see if I can access the items that are enqueued, when those callbacks fire.

**Comment by ORESoftware** [comment]
Also, as an aside, I am looking for a way to pause or empty all items from a queue. For example, if there is an error in the program I want to "kill" all items in the queue before exiting (because my exit routine is asynchronous).

**Comment by ORESoftware** [comment]
Lastly, to determine if a queue is completely empty (nothing enqueued and nothing running), this is the check I am using:

```js
  let allDone = function (q: Object) {
      return q.length() < 1 && q.running() < 1;
    };

```
is that correct?

**Comment by aearly** [comment]
`q.idle()` is what you're looking for: http://caolan.github.io/async/docs.html#QueueObject

`q.workersList()` will also return the list of items currently being processed.
