### ISSUE TITLE
get error using async/await in async.series callback

### ISSUE THREAD

**Issue by goyzhang** [caolan/async#1485]
**What version of async are you using?**
2.5
**Which environment did the issue occur in (Node version/browser version)**
node V8.4.0  windows 10
**What did you do? Please include a minimal reproducable case illustrating issue.**
```
async.series([
    async function(callback) {
        // do some stuff ...
        console.log('one')
        await doSomething() //this line executed as desired
        callback(null, 'one');
    },
    function(callback) {
        // do some more stuff ...
        console.log('two')
        callback(null, 'two');
    }
],
// optional callback
function(err, results) {
    if(err)
    console.log(err)
    // results is now equal to ['one', 'two']
});
```
->
one
TypeError: callback is not a function

**What did you expect to happen?**
codes run as async/await mechanism
**What was the actual result?**
get "TypeError: callback is not a function"

**Comment by aearly** [comment]
`async` functions do not get passed a callback.  Instead, simply return a value.
