### ISSUE TITLE
Can you use async.series with async / await?

### ISSUE THREAD

**Issue by dauledk** [caolan/async#1491]
Can you use async await inside the async.series function?

I did some simple experiments, but they did not work as expected.

**Comment by aearly** [comment]
Yes, you can!  But instead of using a callback, just return a value or throw an error.  http://caolan.github.io/async/global.html

**Comment by dauledk** [comment]
Ok - please forgive me If I misunderstod something 😄  Like this? 

    const result = await async.each(openFiles, async (file) => {
        try: {
            await asyncOperation(file);
            return null
        } catch(err) {
            return err
        }
    })

**Comment by aearly** [comment]
Since `async` functions automatically convert errors into rejections, unless you wanted to do something special with the error, you example could be reduced to: 

```
    const result = await async.each(openFiles, async (file) => {
        await asyncOperation(file);
    })
```

**Comment by dauledk** [comment]
Thank you for the improved snippet. It seems to work in a simple scenario, but in the following setting I can't get it to work:

    for (const tasks of fileTasks) {
        const result = await async.each(tasks, async (file) => {
            await asyncOperation(file);
        })
    }

I was of the understanding that the for-of loop would allow asynchronous operations?

**Comment by aearly** [comment]
Since `async.each` doesn't return a Promise, you can't `await` it.

**Comment by dauledk** [comment]
Ahh ok. So using the for-of async/await option is not a good pattern with async. Do you now if this is on the roadmap for async?

**Comment by aearly** [comment]
There is some mad science planned. 😉

**Comment by tritoanst** [comment]
This is my solution:
`
function makeAsync() {
  if (arguments.length < 3) return;
  let fixParams = {};
  let paramLength = arguments.length;
  let method = arguments[0];
  for (let i = 1; i < arguments.length; i++) {
    fixParams[(i - 1)] = arguments[i];
  }
  return new Promise((resolve, reject) => {
    const callback = (err, result) => {
      if (err) return reject(err);
      return resolve(result);
    };
    
    fixParams[paramLength - 1] = callback;
    fixParams.length = paramLength;
    method.apply(null, fixParams);
  });
}

await makeAsync(async.each, openFiles, async (file) => {
        await asyncOperation(file);
    });
`

**Comment by tritoanst** [comment]
`  // convert to async method
  function makeAsync() {
    if (arguments.length < 3) return;
    let fixParams = {};
    let paramLength = arguments.length;
    let method = arguments[0];
    for (let i = 1; i < arguments.length; i++) {
      fixParams[(i - 1)] = arguments[i];
    }
    return new Promise((resolve, reject) => {
      const callback = (err, result) => {
        if (err) return reject(err);
        return resolve(result);
      };
      
      fixParams[paramLength - 1] = callback;
      fixParams.length = paramLength;
      method.apply(null, fixParams);
    });
  }
  // call async method with method above
  await makeAsync(async.each, openFiles, async (file) => {
    await asyncOperation(file);
  });`

**Comment by tritoanst** [comment]
Create a convert method:
```javascript
const makeAsync = method => {
  return (...args) => {
    return new Promise((resolve, reject) => {
      args.push((error, result) => {
        if (error) return reject(error);
        resolve(result);
      });
      method.apply(this, args);
    });
  };
};
```
ex:
```javascript
    const result = await makeAsync(async.each)(openFiles, async (file) => {
        await asyncOperation(file);
    });
```

**Comment by aearly** [comment]
Or [`util.promisify()`](https://nodejs.org/api/util.html#util_util_promisify_original) 😉 

(or [`pify()`](https://www.npmjs.com/package/pify))

**Comment by oznekenzo** [comment]
Why does this go from a question about `async.series` to `async.each`?

**Comment by LKTPD** [comment]
```
const _async = require('async');

public doSomething = async(num) : Promise<any> => {
     return num*num + 1;
} 

public async getResults() {
    let results = new Array<any>();
    let tasks = [];

    try {
      const list = [1,2,3,4,5,6,7,8,9,10];

      list.forEach((item) => {
        tasks.push((callback) => {
          this.doSomething(item.then(
            (res) => {
              results.push(res);
              callback(null, res);
            }
          );
        })
      })

      results = await new Promise((resolve) => {
        _async.series(tasks, (err, res) => {
          console.log(res);
          if (err) {
            results.push(err);
          }
          resolve(results);
        })
      });
    } catch (err) {
      results.push(err.message);
      console.log(err);
    }

    return _.join(results, '\r\n');
  }



```

**Comment by anhdiepmmk** [comment]
@aearly Hey fen could you please tell me which extracly version support async/await ? 
I'm using caolan/async version 2.6.0
