### ISSUE TITLE
Not able to use the iterable functions map, each, etc.

### ISSUE THREAD

**Issue by ErreMalote** [caolan/async#1492]
**What version of async are you using?**
2.15.0

**Which environment did the issue occur in (Node version/browser version)**
node 7.10.0
**What did you do? Please include a minimal reproducable case illustrating issue.**
```js
async.map(prototypeCollection, (proto, callback) => {
                    proto.load()
                        .then( (response) => {
                            debugger
                            let typeTriple = proto.graph.match(proto.subject, "http://www.w3.org/1999/02/22-rdf-syntax-ns#type", typeOf);
                            if (typeTriple.length > 0) {
                                return loadPrototypeSuccess({prototype: proto.subject.valueOf()});
                            }
                        })
                        .catch ( (error) => {
                            console.log("error: " + error);
                        }) 
                })
```

**What did you expect to happen?**
be able to call the function inside my iterator "proto.load()"

**What was the actual result?**
`proto` comes out as undefined. maybe the object is not supported as a collection?
the object looks like this: `Container {subject: NamedNode, graph: TripletGraph, _serviceConfiguration: ServiceConfiguration, patchDocument: PatchDocument}
`
and it has a length of 22 so it is totally iterable.

**Comment by aearly** [comment]
Which version of Async are you using?  There is no version `2.15.0`.  To use an iterable, you need `2.0.0` or later, and it must have a `[Symbol.iterator]` method.

(I also notice you are not calling the `callback` in the iteratee function)

**Comment by ErreMalote** [comment]
It is the 2.5.0 it was a typo. Ans what is that Symbol.iterator. Also, is
the callback required? I just wanted to execute a couple of fetch's
asynchronously.

**Comment by aearly** [comment]
Iteratable protocol: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols

If you want to simply fire-and-forget a few fetches without having a `done` callback, a `for` loop will have the same effect as `async.map`.

**Comment by ErreMalote** [comment]
I just ended up using a forEach with an async function inside object.forEach( async () => {  my code}). for the Iterator I just needed the default that objects use I don't know why it wasn't working with the iterators from the library. Thanks anyway!
