### ISSUE TITLE
How can I remove a task from the queue after a certain time?

### ISSUE THREAD

**Issue by kodchi** [caolan/async#1493]
Hi,

I'd like to remove a task from the queue after a certain time, but for some reason the `remove` method of the `Queue` object is never called. Here's my code:

```js
const Queue = require('async/queue');

const q = new Queue((data, callback) => {
    setTimeout(() => {
        console.log('working');
        callback();
    }, 3000);
}, 1);

let data = {id: 1};

q.push(data, () => {
    console.log('inside callback');
});

// works -- the task is removed from the queue
// q.remove((worker) => {
//     console.log('inside worker test', worker.data.id);
//     if (worker.data.id == 1) {
//         console.log('removing 1');
//         return true;
//     }
//     return false;
// });

// doesn't work -- the test function never gets executed
setTimeout(() => {
    console.log('inside setTimeout');
    q.remove((worker) => {
        console.log('inside worker test', worker.data.id);
        if (worker.data.id == 1) {
            console.log('removing 1');
            return true;
        }
        return false;
    });
}, 1);
```

As you can see above, `q.remove` is never called when it's inside a timeout, but works fine when it's outside. Is it because the worker has already started and cannot be removed even though the callback hasn't been called yet?

My node version is 8.8.1 and async version is 2.5.0.

**Comment by aearly** [comment]
`q.remove()` only works for items that are in the queue, not items that are running.  In this example, your item would have been shifted off and be processing after the delay -- the queue is checked for processing on the next tick after a `q.push()`.  After the timeout, the queue is empty, with one task running.

**Comment by kodchi** [comment]
OK, thank you!
