### ISSUE TITLE
Working with Map()<k,v>

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1495]
Just wondering if async can work with Map where the signature is `<string,Function>`

something like this:

```js
const m = new Map() as Map<string, Function>;
m.set('foo', function(cb){ process.nextTick(cb)}
async.map(m, function(err,results){
   // results must be a plain object though
});
```

I don't think async works like this, but just curious if it could.

**Comment by aearly** [comment]
http://caolan.github.io/async/docs.html#map

A `Map` is considered an 'Iterable', so, yes, you can `map` over `Map` s.

**Comment by ORESoftware** [comment]
Crap, my bad, what I mean was this instead:

`async.series` not `async.map`

does a `Map` work with `async.series` is my question

**Comment by aearly** [comment]
http://caolan.github.io/async/docs.html#series
