### ISSUE TITLE
Allow for callbacks with async functions

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1496]
Feature request - I just discovered today how the async lib works with async functions, like so:

```js
async.series({
    a: async function () {
      return Promise.delay(500).then(v => 'zzz');
    },
    b: async function (){
      let c = await Promise.delay(500).then(v => 2);
      return c*2;
    }
  },
  function (err, results) {
    if (err) throw err;
    console.log('results => ', results);
    process.exit(0);
  });
```

the above is cool, but what if we actually want to mix `async` functions with callbacks, which is perfectly reasonable, something like this:

```js
async.series({
    a: async function (cb) {
      let z = await Promise.delay(500).then(v => 'zzz');
      doSomethingCallbacky(z, cb);
    },
    b: async function (cb) {
      let c = await Promise.delay(500).then(v => 2);
      doSomethingElseCallbacky(c, cb);
    }
  },
  function (err, results) {
    if (err) throw err;
    console.log('results => ', results);
    process.exit(0);
  });
```

currently it looks like the async lib detects if the function is an async function and if so, does not pass the callback. But why not just use  `Function.prototype.length` ?

that seems to be the most performant... if fn.length === 0, don't pass a callback, if it's 1, pass a callback, something like that. Should near-zero performance hits, since fn.length is already available.

**Comment by aearly** [comment]
I am very 👎 on mixing callbacks with `async` functions.  I'd rather people `util.promisify` node-style callback functions and `await` them inside an `async` function.

**Comment by ORESoftware** [comment]
eh, agree to disagree on this one, I think mixing callbacks with async/await is very intuitive and totally normal. Like I said, all you would have to do is read `fn.length` which is already available free of charge.
