### ISSUE TITLE
recursive call of callback says : Callback was already called

### ISSUE THREAD

**Issue by ahadyekta** [caolan/async#1497]
Hi people , I use waterfall method for a series of async functions . Inside the first function I want to repeat the process after all process reaches end. So I pass a finalCallback from the first function to each one to be called in the end. It goes well for the first loop , but it throws an exception of : Callback was already called.
However, I need to recall it with new input data . How can I do?

**What version of async are you using?**
newest
**Which environment did the issue occur in (Node version/browser version)**
node
**What did you do? Please include a minimal reproducable case illustrating issue.**
recursive calling a function containing callback function
**What did you expect to happen?**
to repeat the callback with new data
**What was the actual result?**
Callback was already called

**Comment by aearly** [comment]
We don't support calling callbacks multiple times -- it leads to bugs and confusing control flow. If you need to run through part of a waterfall multiple times, break out that part into another function, and then use something like `eachSeries` or `doWhilst` to run it multiple times.
