### ISSUE TITLE
Can't import async in an ES6 module in the browser

### ISSUE THREAD

**Issue by dpk** [caolan/async#1499]
**What version of async are you using?**

2.6.0

**Which environment did the issue occur in (Node version/browser version)**

Browser (Safari, Firefox, Chrome) supporting ES6 modules natively

**What did you do? Please include a minimal reproducable case illustrating issue.**

```js
import * as async from "./async.js";
```

**What did you expect to happen?**

To import async

**What was the actual result?**

```
TypeError: undefined is not an object (evaluating 'global.async')
```
from line 4.

**Comment by aearly** [comment]
Try using [`async-es`](https://www.npmjs.com/package/async-es).

**Comment by dpk** [comment]
That returns a load of 404 errors because the imports don't have `.js` at the ends of the filenames.

**Comment by aearly** [comment]
Ah, good point.  The current ES implementation assumes a node-style loader.

**Comment by aearly** [comment]
Even I fix the `.js` problem, I also realize it will choke on `import foo from 'lodash/foo'`.   I can easily rollup a monolithic ES `index.js` that does no other imports (so you could `import async from './async-es/index.js'`).  But `import map from './async-es/map.js'` will choke until there is better tooling, or a loader spec for the browser.

**Comment by aearly** [comment]
This will get better when we drop lodash a a dependency in 3.0, but resolving npm ES modules in the browser without a build step is still a largely unsolved problem.

I do know that Node is actively working on the problem at the moment, and I am eagerly waiting for a resolution so I can implement it here.
