### ISSUE TITLE
async.retry with a asynchronous function inside errorFilter

### ISSUE THREAD

**Issue by teebu** [caolan/async#1500]
**What version of async are you using?**

2.6 

**Which environment did the issue occur in (Node version/browser version)**

nodejs 6.10

**What did you do? Please include a minimal reproducable case illustrating issue.**

trying to use async retry with asynchronous function inside errorFilter.

https://repl.it/repls/UnfitScalyAlpinegoat

This is more of a question then a bug. 

I want to send an error report, and I figured placing it inside the errorFilter would work nicely. It's a asynchronous function, so calling it inside and returning true inside isn't working. 

What's a good solution for this? errorFilter would need a callback for what I'm trying to do. Maybe some kind of additonal onError function?

**Comment by aearly** [comment]
Looks like you can just fire-and-forget the error report in the sync errorFilter, no need to wait for its callback.

**Comment by teebu** [comment]
That's what I did, but I am doing this inside AWS Lambda. They don't like to wait for things to finish, they will just end the process on the last callback.
