### ISSUE TITLE
applyEach should surface results from the input functions

### ISSUE THREAD

**Issue by hhowe29** [caolan/async#1501]
I could utilize `applyEach` more often if it provided a way to collect results from each input function. Please allow me to write code link this:

```
async.applyEach([func0, func1, ... funcN], 'foo', 29, (error, results) => {
   if(error) {
     console.log('guess you are out of luck');
   }   
  else {
    // results == array of N+1 result values
    console.log('func0(foo, 29) returned ' + results[0]);
    console.log('func1(foo, 29) returned ' + results[1]);
    ...
  }
});
```
This is similar `map`, but inverted from SIMD to MISD.

**Comment by hargasinski** [comment]
Hi @hhowe29,

Thanks for the question! `applyEach` behaves the same way as `map` in this regard (it's actually [implemented using `map`](https://github.com/caolan/async/blob/master/lib/applyEach.js#L37) internally) so you can already do that. The documentation for it is just missing right now.

```js
const func0 = (foo, bar, cb) => { cb(null, 'foo'); };
const func1 = (foo, bar, cb) => { cb(null, 'bar'); };

async.applyEach([func0, func1], 'foo', 29, (err, results) => {
  if (err) {
    // handle err
  }
  // results is ['foo', 'bar']
});
```

If you have an idea for including this in the [docs](http://caolan.github.io/async/docs.html#applyEach), a PR would be awesome!
