### ISSUE TITLE
Missing proper map over Object

### ISSUE THREAD

**Issue by mafiosso** [caolan/async#1502]
**2.6.0**

**Missing functionality for mapping over Object preserving Object structure e.g. key: value.**

**I have expected such a functionality in .map function.**

**The .map function should respond with object with the same keys**

**Function .map returns Array for Objects.**

I have developed small workaround.

```
async.obj_map = function( objs , apply_fn, cb ){
  var fns = [];

  var rets = {};
  var errs = [];

  for( let o in objs ){
    let obj = objs[o];
    fns.push(
      function(par_cb){
          apply_fn( obj, o,
                    function( err, val ){
                      if( err ){ errs.push(err); return; }
                      rets[o] = val;
                      par_cb( null );
                    });                  
      }
    );
  }

  async.parallel( fns, function(err, dta){
    if( err ){ errs.push(err); }
    cb( (errs.length > 0 ? errs : null), rets );
  });
};

```

**Comment by ex1st** [comment]
Hello @mafiosso, what about [mapValues](https://caolan.github.io/async/docs.html#mapValues)?

**Comment by mafiosso** [comment]
Ok its a solution i 've missed mapValues. Thanks.
