### ISSUE TITLE
Question: how to paginate with token? (or recursively call async function and pass through parameters)

### ISSUE THREAD

**Issue by tommedema** [caolan/async#1503]
AWS API calls typically respond with a [pagination token](http://docs.aws.amazon.com/acm/latest/APIReference/API_ListCertificates.html#ACM-ListCertificates-request-NextToken). When present, another call to the same API should be made with that token, until a token is no longer supplied. This is typically done using recursion.

I would like to use `async` (or another library) to simplify this approach. I had imagined the following psuedo code:

```
  await paginate(async (lastToken, recurse, page) => {
    const { certificates, token } = await listCertificates({nextToken: lastToken})
    handleCertificates(certificates)
    token && recurse(token)
  })
```

This illustrates how something as complicated as token based pagination could be accomplished with a few lines of code. I've looked into async and saw some relevant functions (e.g. `until`), but have not found a way to recursively pass the output of one call to the next (i.e. pass in the token to the next call).

Is this possible with `async`? Or is there a library that's more suitable for this?

**Comment by tommedema** [comment]
After scanning through the documentation once again, I believe this should do it.

```
async.forever(
    function(next, lastToken) {
        const { certificates, token } = await listCertificates({ nextToken: lastToken })
        handleCertificates(certificates)
        token && next(null, token)
    }
)
```

Is this indeed the most suitable approach to achieve pagination with a token?

**Comment by tommedema** [comment]
Ultimately this worked but it's a little bit ugly. What do you think?

```
import foreverSync from 'async.forever'

const forever = promisify(foreverSync, { errorFirst: false })

let lastToken
const result = await forever(next => {
    const { certificates, token: lastToken } = await listCertificates({nextToken: lastToken})
    handleCertificates(certificates)
    next(lastToken ? null : true)
})

```

**Comment by Seojiwoong** [comment]
How about using whilst instead of forever?
https://caolan.github.io/async/docs.html#whilst

**Comment by Seojiwoong** [comment]
How about making recursive function? 
I think that it doesn't need async.js....

**Comment by tommedema** [comment]
@Seojiwoong this would result in quite some boilerplate, whereas the above is cleaner with `forever`

**Comment by aearly** [comment]
`doWhilst` is good for this kind of thing.

```
let results = []
let nextToken
doWhilst(
  (next) => {
    getPage(url, nextToken, (err, body) => {
      if (err) return next(err);
      nextToken= body.nextToken
      results = results.concat(body.objects)
      next()
    })
  },
  () => nextToken,
  (err) => {
    // results now has all pages
  })
```

**Comment by tommedema** [comment]
@aearly I like how async/await makes something like do/while so simple to read again; thanks!
