### ISSUE TITLE
Execute _subtasks_ in a shared execution queue?

### ISSUE THREAD

**Issue by sergiogiogio** [caolan/async#1509]
Is there a way to execute _subtasks_ in a _shared_ execution queue and get a notification (callback) when all the subtasks are completed?

Concrete example: a function computing the size of a directory, with the constraint to limit file IO to maximum 2 parallel operations.
Few considerations:

1- Without the constraint, the function can simply `fs.readdir` the target directory and `fs.stat` individual files, however this will in theory lead to many parallel IOs (note: I am aware the VM will also put a limit on the number of parallel IOs, however I would like this limit to be explict in JS). (code below)
2- One mitigation is to use async.eachLimit to set a maximum number of parallel IOs. However if the directory contains subdirectories, there will be multiple calls to async.eachLimit at each subdirectory so overall the number of parallel IOs will not be in check.
3- Ideally the function would queue individual `fs.stat` in a shared queue that controls the parallelism. Is there such a facility available in async?

```javascript
const fs = require('fs')
const async = require('async')

var dirsize = function(path, cb) {
	var sizesum = 0;
	fs.readdir(path, function(err, files) {
		async.each(files,
			function(file, cb) {
				fs.stat(path + "/" + file, function(err, stats) {
					if (stats.isDirectory()) {
						dirsize(path + "/" + file, function(err, size) {
							sizesum += size;
							cb(null);
						})
					} else {
						sizesum += stats.size
						cb(null);
					}
				})
			},
			function() {
				return cb(null, sizesum);
			}
		)
	})
}

dirsize(".", function(err, size) {
	console.log("dirsize = " + size);
})
```

**Comment by aearly** [comment]
`async.queue` is what you want  here.  As you process a directory, push any sub-directories to the queue.   You can easily control the concurrency of a queue.

**Comment by sergiogiogio** [comment]
Thanks - the concurrency should ideally be at the level of "stat" command. Here's a version with a queue (stat_queue can here be shared by multiple functions and will always only execute 2 operations at the same time). It works - but it is tedious and feels like essentially implementing a queue within a queue, which is why I wanted to check whether there exist better solutions.

Essentially I am looking for a feature that would enable me to 1) execute a set of tasks on a queue and 2) notify me when the set of tasks has completed. 1) is addressed by Async/queue but 2) does not seem to have a canonical solution.

```javascript
var stat_queue = async.queue( function(path, cb) { fs.stat(path, cb) }, 2 ); 

var dirsize2 = function(path, cb) {
	var sizesum = 0;
	fs.readdir(path, function(err, files) {
		var pending = files.length;
		var ret_err = null;
		for(var i = 0; i < files.length ; ++i) { (function(i) {
			stat_queue.push(path + "/" + files[i], function(err, stats) {
				ret_err = ret_err || err;
				if(err) console.log(err);
				if(!ret_err) {
					if (stats.isDirectory()) {
						dirsize2(path + "/" + files[i], function(err, size) {
							sizesum += size;
							if(--pending == 0) {
								cb(ret_err, sizesum);
							}
						})
					} else {
						sizesum += stats.size
						if(--pending == 0) {
							cb(ret_err, sizesum);
						}
					}
				}
			})
		})(i) }
	})
}

dirsize2(".", function(err, size) {
	console.log("dirsize2 = " + size);
})
```

For completeness' sake - here is a variation with a Joiner class intended to "hide" the counter. Is such a facility already available in async?

``` javascript
var Joiner = function(count) {
	this.count = count;
	this.cbCalled = false;
	this.err = null;
}
Joiner.prototype.then = function(cb) {
	this.cb = cb
}
Joiner.prototype.fun = function(err) {
	if(err) if(!this.err) this.err = err;
	if(this.err) {
		if(!this.cbCalled) { this.cbCalled = true; return this.cb(this.err) }
	}
	if(--this.count === 0) if(!this.cbCalled) { this.cbCalled = true; return this.cb(this.err) }
}

var dirsize3 = function(path, cb) {
	var sizesum = 0;
	fs.readdir(path, function(err, files) {
		var join = new Joiner(files.length);
		for(var i = 0; i < files.length ; ++i) { (function(i) {
			stat_queue.push(path + "/" + files[i], function(err, stats) {
				if (err) join.fun(err);
				if (join.err) return;
				if (stats.isDirectory()) {
					dirsize3(path + "/" + files[i], function(err, size) {
						sizesum += size;
						join.fun(null);
					})
				} else {
					sizesum += stats.size
					join.fun(null);
				}
			})
		})(i) }
		join.then( function(err) { cb(err, sizesum) });
	})
}

dirsize3(".", function(err, size) {
	console.log("dirsize3 = " + size);
})

```

**Comment by aearly** [comment]
The `drain` callback of a `queue` will tell you `2)`.  It's called when a task completes and the queue is empty -- typically when the queue is done.

**Comment by sergiogiogio** [comment]
I can't use queue.drain because the queue is shared between multiple tasks/processes. I would need a way to explicitly designate a number of _subtasks_ and have the queue tell me when the specific set of subtasks has completed.

**Comment by aearly** [comment]
I misunderstood what you were attempting to do in your code.  I think you were using queue in the wrong way, trying to use it as an accessory to control flow, rather than the main source of control flow.  Here's a simpler way to accomplish what you want:

```js
function dirsize (dir, cb) {
  let size = 0
  const q = async.queue((file, taskCb) => {
    fs.stat(file, (err, stats) => {
      if (stats.isDirectory()) {
        fs.readdir(file, (err, files) => {
          q.push(files.map(f => path.join(file, f)))
          taskCb()
        })
      }
      size += stats.size
      taskCb()
    })
  }, 2)

  q.push(dir)

  q.drain = () => {
    cb(null, size)
  }
}
```
