### ISSUE TITLE
Does doWhilst execute tasks sequentially?

### ISSUE THREAD

**Issue by sebto** [caolan/async#1512]
Sorry, I'm new to Async package. I need a function to execute unknown tasks sequentially. 
I found doWhilst is suitable to do unlimited number of tasks but I'm not sure it executes tasks in sequence. I didn't find it clearly in documentations.

It seems because test function will be called just after each iteration is completed, tasks will be executed seuqntially.

**Comment by hargasinski** [comment]
Hi @sebto,

Thanks for the question! Yes, for [`doWhilst`](http://caolan.github.io/async/docs.html#doWhilst), and related functions such as [`doUntil`](http://caolan.github.io/async/docs.html#doUntil) and [`doDuring`](http://caolan.github.io/async/docs.html#doDuring), the calls to the task will be sequential. So, for `doWhilst`, the task will be run, once it finishes (calls it's callback), the test will function be run, and after it returns, the task will be run again, and so on.

If you need to run a function an unlimited number of times, you should look into [`forever`](http://caolan.github.io/async/docs.html#forever). Also, if you just need to run functions sequentially, you could look into [`waterfall`](http://caolan.github.io/async/docs.html#waterfall), or [`series`](http://caolan.github.io/async/docs.html#series), but you would need to know the number of tasks beforehand.
