### ISSUE TITLE
Async.waterfall is super slow. How I can optimize it?

### ISSUE THREAD

**Issue by juliemobile5** [caolan/async#1513]
I am trying to implement serverless lambda function that writes text on image. However the whole function is taking on average 5 secs and sometimes up to 10 seconds to implement. I can't understand how to optimise code. 

Here is the editImage function which implements async.waterfall, where source image from s3 bucket is downloaded. And then it puts text on downloaded image and then uploads result to destination key.

    exports.editImage = function(event, context, callback) {
     // init and assign vars
     async.waterfall([
       async.apply(download, srcBucket, srcKey),
       async.apply(editAsset, text),
       async.apply(upload, dstBucket, dstKey)
     ], function (err) {
          if (err) console.log('Unable to transform image');
         
          callback(null, {statusCode: 200, body: JSON.stringify({ key: dstKey})
           });
         }
       );
    };

    function download(srcBucket, srcKey, callback) {
      var params = {Bucket: srcBucket, Key: srcKey};  
      s3.getObject(params, callback);
    };

    function editAsset(text, response, callback) {
       var img = gm(response.Body);
       img.size(function (err, { height }){
          img.drawText(0, height / 2 - 40, text.toUpperCase(), 'center');
          img.toBuffer('png', function (err, buffer) {
          if (err) console.log(err);
          callback(null, response, buffer);
       });
     });
    }

    function upload(dstBucket, dstKey, response, buffer, callback) {
      s3.putObject({
          Bucket: dstBucket,
          Key: dstKey,
          Body: buffer,
          ContentType: response.ContentType
      }, function(err, data) {
      if (err) {
          console.log(err, err.stack);
      }else{
          callback(null, response, buffer);
      }
     });
    }

The code works. But I can't understand what is causing more delays. async.waterfall or graphicsmagic operations. Can I get any advice on how to improve performance

**Comment by harry1064** [comment]
From my point of view, all your function take their respective time like downloading image, edition image using graphics magic and upload image which add to give you total time to complete your whole task. 

I think variation in time only depend in downloading and uploading image.

**Comment by ecasilla** [comment]
use `console.time` to trace which one of your function is causing the latency
