### ISSUE TITLE
async.mapLimit  support cancel?

### ISSUE THREAD

**Issue by binghaiwang** [caolan/async#1518]
if async.mapLimit is running,  support cancel?

**Comment by hargasinski** [comment]
Hi @binghaiwang, thanks for the question!

You cannot cancel a running task (see #1487, #1353). However, we do have plans for exiting early, i.e. exiting out of a method, such as `mapLimit`, before the running tasks finish (ignoring their result), and without starting any of remaining tasks. See #1064 for information about that.
