### ISSUE TITLE
Question: collection functions with retry callback?

### ISSUE THREAD

**Issue by gakada** [caolan/async#1520]
Hello. I'm looking if what I'm trying to do is already there somewhere. To give an example, `eachLimit` has this signature:
```
elements : Collection<T>
limit : Number
onElement : (element : T, next : Error? -> *) -> *
done : Error? -> *
```
now, `onElement` can be generalized to
```
onElement : (element : T, next : Error? -> *, retry : T? -> *) -> *
```
that is, if `retry` is called in `onElement`, `onElement` action will be repeated for that (or specified) element. Possible implementation is something like this:
```js
const eachLimit = (elements, limit, onElement, done) => {
  const loop = elements => {
    const retryElements = []
    async.eachLimit(elements, limit, (element, next) =>
      onElement(element, next, retryElement => {
        retryElements.push(retryElement || element)
        next()
      }),
    error => {
      if (!error && retryElements.length > 0) {
        loop(retryElements)
      } else {
        typeof done === 'function' && done(error)
      }
    })
  }
  loop(elements)
}

// e.g.
eachLimit([0, 1, 2, 3], 2, (e, next, retry) => {
  console.log(e)
  if (e % 2 === 0) {
    retry(e + 1)
  } else {
    next()
  }
})
/*
will print
0
1
2
3
1
3
*/
```
So my questions, is there a better way to do this? Is there already a way to do something like this in async (or another library), or I should write such wrappers if I need it.

**Comment by hargasinski** [comment]
To retry `onElement` when an error occurs, you could wrap it in [`async.retryable`](https://caolan.github.io/async/docs.html#retryable). By default, it will retry `onElement` 5 times. However, it won't let you know specify the element to retry `onElement` on. 

```js
eachLimit([0, 1, 2, 3], 2, async.retryable((e, next)=> {
  console.log(e)
  // this will not print 3, as the `onElement` for 0 will end up passing an error 
  // to `next` before eachLimit calls `onElement` on 3
  next( e % 2 === 0 ? new Error('foo') : null );
}))
/*
will print
0
1
2
0
2
0
2
0
2
0
2
 */
```

If you need to specify the element, you could use [`async.retry`](https://caolan.github.io/async/docs.html#retry). Something along the lines of:
```js
eachLimit([0, 1, 2, 3], 2, (e, next) => {
  let currentElem = e
  retry((cb) => {
    console.log(currentElem)
    if (currentElem % 2 === 0) {
      currentElem += 1
      cb(new Error())
    } else {
      cb()
    }
  }, next)
})
/*
will print
0
1
2
1
3
3
 */
```

**Comment by gakada** [comment]
Thanks for clarifying this for me :)

I knew those two exist, but somehow was stuck with the idea of doing multiple passes, instead of retrying on tasks (which is probably more modular). My real use case is `eachLimit`/etc. over some network requests (that are not expected to fail) with some concurrency, and so far `retryable` seems to work fine as well.
