### ISSUE TITLE
times uses too much memory for large values

### ISSUE THREAD

**Issue by jazzzz** [caolan/async#1521]
**What version of async are you using?**

2.6.0

**Which environment did the issue occur in (Node version/browser version)**

Any.

**What did you do? Please include a minimal reproducable case illustrating issue.**

```js
async.times(1e9, (n, next)=>next(), err=>{})
```

**What did you expect to happen?**

My iteratee should be called instantaneously and it should use nearly no memory.

**What was the actual result?**

It take gigs of memory and several seconds before the iteratee is first called (when the process does not crash with OOM).

**Comment by hargasinski** [comment]
Thanks for the report! 

I haven't done any profiling, but this is mostly likely due to the `range(0, count, 1)` call in our [`times` implementation](https://github.com/caolan/async/blob/master/lib/timesLimit.js).

**Comment by aearly** [comment]
`times` will always be problematic with large values, because it will still create a `1e9` sized results array.  If you really need a billion iterations, do something like:

```js
function * iter(n) {
  for (let i = 0; i < n; i++) yield i
}

async.each(iter(1e9), (n, next)=>next(), err=>{})
```

`each` and family don't create `results` arrays.

**Comment by jazzzz** [comment]
@aearly it makes sense, I didn't see that `times` returned a `results` array.
