### ISSUE TITLE
Concurrency option for async whilst

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1522]
I am on async version:  `"async": "^2.6.0"`

I have this code:

```js
import http = require('http');
import async = require('async');

let finished = false;
const to = setTimeout(function () {
  finished = true;
}, 20000);

const errors = [] as Array<any>;

const check = function () {
  return finished === false && errors.length < 1;
};

async.whilst(check,
  function (cb: Function) {
     // I would like to run these task functions in parallel, but with a concurrency limit  
  },
  
  function () {
    
    if (errors.length < 1) {
      console.log('test passed.');
      process.exit(0);
    }
    
    console.error('test failed.');
    errors.forEach(function (e) {
      console.error(e.message || e);
    });
    
  });
```

is there a way to use a concurrency limit with async whilst? I didn't see it in the docs, something like this:

`async.whilst(check, concurrencyValue, taskExecutor, finalCallback);`

of course the default for the `concurrencyValue` is 1

**Comment by hargasinski** [comment]
Right now, there isn't a way to specify a concurrency limit for `whilst` or any of the related function. However, you could mick the required behaviour using a generator and `eachLimit`:

```
function* gen() {
  while (check()) {
    yield true;
  }
}

async.eachLimit(gen(), 15, function (cb) {
  // your iteratee function
}, function () {
  // your final callback
})
```

I'd be hesitant to add something like `whilstLimit` to `async`. Since the same `iteratee` is called each time, with the same arguments, the number of use cases for it to run concurrently seems low. I could be convinced otherwise though.

**Comment by ORESoftware** [comment]
@hargasinski  `mapLimit` and friends also has the same iteratee called each time, but has a concurrency option.

In my case the iteratee has  a `if / elseif / else` pattern, so there is some branching for each iteratee. But if there was no branching, it still might be useful to run the same task, 2 or 3 at a time or what not.

**Comment by aearly** [comment]
I think `whilst` with concurrency is kind of a footgun.  Say you're running `whilst` with concurrency 5, and  have 5 requests running.  The first of those 5 finishes, and then the `test` function returns false.  Should you have run the other 4 requests?

I can't think of a good use case for this, where you'd want to concurrently poll for a condition.

**Comment by ORESoftware** [comment]
@aearly I agree with that
