### ISSUE TITLE
callback undefined error when switching from es6 to es2017

### ISSUE THREAD

**Issue by farzher** [caolan/async#1524]
just putting this here as a landing page for all the inevitable bugs caused by the bad decision to have magic behavior when using async/await

when using typescript/babel and compiling to es6 or lower, this code works.
when updating to es2017, it breaks because callback is undefined.

```js
async.each(['a','b','c'], async (item, callback) => {
  await Promise.resolve()
  callback()
}, (err) => {
  err // ? TypeError: callback is not a function
})
```

1. you should not check `fn.constructor.name === 'AsyncFunction'`, because any function that returns a promise is an async function.
2. you should not magically decide to not give a callback function

*sorry i may be a bit frustrated after trying to debug this*

**Comment by aearly** [comment]
If you're using an `async` function, simply return a value, rather than use a callback.

If you're also transpiling, wrap the function with `asyncify`, because otherwise we won't be able to know beforehand if the function returns a Promise or not.
