### ISSUE TITLE
Different operation between v1.5.2 and v2.6.1

### ISSUE THREAD

**Issue by KunHwanAhn** [caolan/async#1535]
**What version of async are you using?**
v2.6.1

**Which environment did the issue occur in (Node version/browser version)**
node.js 4.8.3

**What did you do? Please include a minimal reproducable case illustrating issue.**
I upgraded the version from `v1.5.2` to `v2.6.1`, and I tested the changed methods.

And I found different operation of some functions(e.g. `async.detect`, `async.every` etc..) between v.1.5.2 and v2.6.1.

But another operation of a function, `async.detectSeries` is same, even though `detect`  and `detectSeries` are included in the same family.

Following is my sample code lines to reproduce my issue.

```Javascript
'use strict';

const _ = require('lodash');
const async = require('async');

let range = _.range(0, 100);

function doDetect(cb) {
  async.detect(
    range,
    (value, next) => {
      console.log('[async.detect][PROCESS] value:', value, new Date().getTime());

      if (value === 50) {
        next(null, true);
      } else {
        next(null, false);
      }
    },
    (err, result) => {
      console.log('[async.detect][DONE] err:', err);
      console.log('[async.detect][DONE] result:', result);

      return cb && cb();
    }
  );
}
```

**What did you expect to happen?**
The operation of some functions is not same.

**What was the actual result?**
At v1.5.2, async.detect stop using the rest data of collection, but, at v2.6.1, it uses them.

If you intended this, please close this issue.

Thanks
Conan

**Comment by aearly** [comment]
If I'm understanding you correctly, it's true, we changed `every`/`detect`/et al to be parallel, but included the `everySeries`/`detectSeries` to be sequential, to match how other Async methods worked.  Use the `*Series` versions in 2.x.

We also changed it so the iteratee callback takes in `next(err, bool)` rather than just `next(bool)`.
