### ISSUE TITLE
Asynchronous whilst test function

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1537]
I believe this is the current API for async.whilst:

```js
var count = 0;
async.whilst(
    function () { return count < 5; },
    function (cb) {
        count++;
        setTimeout(cb, 1000);
    },
    function (err) {
        // 5 seconds have passed
    }
);
```

I am looking for an asynchronous test function, like so:

```js
async.whilst(
    function (cb) { 
        setTimeout(function(){
               cb(null, true);
       })
   },
    function (cb) {
        count++;
        setTimeout(cb, 1000);
    },
    function (err) {
        // 5 seconds have passed
    }
);
```

does that exist in some form?
I can't think of a clean workaround unfortunately.

**Comment by hargasinski** [comment]
Yes, it does. Take a look at [`during`](https://caolan.github.io/async/docs.html#during) and [`doDuring`](https://caolan.github.io/async/docs.html#doDuring).

**Comment by ORESoftware** [comment]
oh nice thanks
