### ISSUE TITLE
async queue example should show how to handle errors

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1539]
Looking at the docs for async.queue
https://caolan.github.io/async/docs.html#queue

```js
// create a queue object with concurrency 2
var q = async.queue(function(task, callback) {
    console.log('hello ' + task.name);
    callback();
}, 2);

// assign a callback
q.drain = function() {
    console.log('all items have been processed');
};
```

is there an 

```js
q.onError = function(err){

}
```
 handler that we can use?

I don't think `q.drain` is an error-first callback, and I don't want to pass a callback for each `q.push` or `q.unshift` call, I just want to use one error-first callback.

This should exist and be in the docs, right?

**Comment by aearly** [comment]
https://caolan.github.io/async/docs.html#QueueObject

`q.error` exists, and there is an optional callback you can pass to `q.push()`.

**Comment by ORESoftware** [comment]
@aearly  it needs to be documented in the example, that is the bug. How can I add it to the example? How do I make a PR for the docs?

**Comment by aearly** [comment]
The example is in the JSDoc comment in the `queue` source.

**Comment by ORESoftware** [comment]
https://github.com/caolan/async/pull/1540

sounds good
