### ISSUE TITLE
Separate async methods (to use with Lambda functions)

### ISSUE THREAD

**Issue by efortes** [caolan/async#1545]
First of all thank you for maintaining this project. 
Recently I start using AWS nodejs lambda functions for my applications. I use the serverless framework to deploy multiple functions.
I don't use the async package as its to big for my project. Deploying lambda functions has a max package size at AWS.

**Question**  
Is it possible to also deploy the methods separate on npm? I don't want to introduce webpack to my small projects just to include some packages.

**Package example**
@caolanAsync/retry
@caolanAsync/series
@caolanAsync/parallel

**Comment by hargasinski** [comment]
I believe this option was explored in #984, but decided it was best to keep everything in one package for simplicity. We'll be dropping `lodash` in `v3` (the PR is already merged, see #1528), which should decrease the package size quiet a bit. Will that solve the issue?

**Comment by efortes** [comment]
@hargasinski thank you for the answer. For the case I had I solved the problem without using async. 
But if I really want this I could use webpack to minimize the size. 
Thank you.
