### ISSUE TITLE
async queue to process backpressure problem

### ISSUE THREAD

**Issue by homerzhou** [caolan/async#1546]
Hi:
    I want to use `async.queue` to process backpressure problem, But it have not max queue size just `only the practical limits of a JS array`. so I have to do like this:
```
let q = async.queue(function(tasks, callback) {
    .......
    callback()
});

q.drain = function() {
    some_readable_stream.resume()
}

some_readable_stream.on("data", function(data) {
    q.push(data);
    some_readable_stream.pause();
});
```
This example is not great, I have to `get one, process one, and again`; If I have the `highWaterLevel` like `readable-stream in Node.js`, That will be great.
```
let q = async.queue(function(tasks, callback) {
    .......
    callback()
}, highWaterLevel);

q.drain = function() {
    some_readable_stream.resume()
}

some_readable_stream.on("data", function(data) {
    if (q.push(data) == false) {
        some_readable_stream.pause();
    }
});
```
I'm not sure why not have the `highWaterLevel` in `asyc.queue` like `readable-stream in Node.js`

**Comment by hargasinski** [comment]
`queue` accepts a `concurrency` parameter that specifies the maximum number of tasks to process in parallel. When the number of tasks being processed hits the concurrency limit, new tasks will be queued until they can be processed. When this happens, it will call the `saturated` callback. Would that work for your use case?

```js
let q = async.queue(function(tasks, callback) {
  // ...
  callback()
}, 4);

q.drain = function() {
  some_readable_stream.resume()
}

q.saturated = function() {
  some_readable_stream.pause();
}

some_readable_stream.on("data", function(data) {
  q.push(data);
});
```

Also, side note, `q.unsaturated` might work better than `q.drain` for this case. See the [`queue` docs](https://caolan.github.io/async/docs.html#queue) for more info.

**Comment by homerzhou** [comment]
Sorry, I not want `saturated`, I want the `stream model`.
I think `highWaterLevel` in `readable-stream in Node.js` is what I want.
Ths.

**Comment by aearly** [comment]
If you need to manage backpressure, a Transform stream in object mode is a better  fit for your control flow.
