### ISSUE TITLE
Support q - get number of processed jobs for async queue?

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1549]
I have this question on SO:
https://stackoverflow.com/questions/51016938/async-queue-get-number-of-processed-tasks-jobs

no answers yet so moving here unfortunately.

Say we have a simple async queue:

```js
import async = require('async');
const q = async.queue((task, cb) => task(cb));

q.push(cb => {

});

q.push(cb => {

});

// ...

q.push(cb => {

});
```

is there a way to get the number of tasks that have completed?
`q.running()` yields a count of running jobs.

**So the question is - is there a call that returns the number of processed/completed jobs/tasks?**

`q.processed() => number?`
or maybe
`q.completed() => number?`

a completely different question that I also have on SO that is unanswered is this one:
https://stackoverflow.com/questions/51032271/provide-task-type-for-async-queue-using-generics

**Comment by hargasinski** [comment]
No, right now we do not keep track of the number of tasks completed. See the second code snippet of [this answer](https://github.com/caolan/async/issues/1547#issuecomment-400888578) for a way to implement it yourself.

I'm not too familiar with TypeScript, so I unfortunately can't answer the second question.

**Comment by ORESoftware** [comment]
@hargasinski thanks since you answer the other question, I will close this one.
