### ISSUE TITLE
Alpha/beta test an NPM publishing tool

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1550]
As maintainers of async know, I love async and have used it for 100s of projects. I trust your opinions and need your input for a project I am working on. Let me know if you want me to move this issue/ticket elsewhere.

I am in the process of getting this ready for use by other people:
https://github.com/ORESoftware/r2g

for anyone writing NPM libs/OSS this should be useful.

The first thing you could help me with, is letting me know if anything in the README is unclear or unexplained. Also, if you have any more feature ideas, lmk.

Hope it's clear how r2g works and why I wrote it. Thanks!

**Comment by aearly** [comment]
Seems like a cool project, but doesn't really seem applicable to Async, as we already have an involved build/test process, and no dependencies to accidentally become devDependencies.
