### ISSUE TITLE
TypeError: conn.executeMany is not a function

### ISSUE THREAD

**Issue by Shubhangi-yadav** [caolan/async#1561]
Hello ,I am getting this error while using async.waterfall .Please help.
[test.zip](https://github.com/caolan/async/files/2183677/test.zip)

**Comment by hargasinski** [comment]
Hi @Shubhangi-yadav, thanks for the question!

You appear to have an extra argument, `a`, at the beginning of your `doinsert2` function. Changing the signature from
```js
var doinsert2 = function ( a,conn, cb) {
```
to
```js
var doinsert2 = function (conn, cb) {
```
should fix the issue.

`waterfall` does not pass the first parameter passed to the task callback, the error, onto the next task. So when you call `return  cb(null, conn);` in `doinsert`, only the second parameter, `conn`, is passed onto `doinsert2`. See the [`waterfall` docs](http://caolan.github.io/async/docs.html#waterfall) for more info.
