### ISSUE TITLE
Concat order preservation: implemented or not?

### ISSUE THREAD

**Issue by alexandercerutti** [caolan/async#1563]
Hello everybody, I have a doubt about concat function order preservation. I found a [merged pull request](https://github.com/caolan/async/pull/1436) which introduces this change but the [documentation](http://caolan.github.io/async/docs.html#concat) still report this

> There is no guarantee that the results array will be returned in the original order of `coll` passed to the `iteratee` function.

So what should I refer to? Does the function keep the order of `coll`?
I suppose it is preserved since it seems got introduced in v2.5.0 while we are at v2.6.0.
Thank you.

**Comment by aearly** [comment]
The order should be preserved now, but it looks like our docs are out of date!

**Comment by alexandercerutti** [comment]
That's what I supposed. Is the repository of the website available? I may do a pull request with this correction.

**Comment by aearly** [comment]
The docs website is built from the JSDoc comments of each source file.

**Comment by alexandercerutti** [comment]
Okay. I'm going to do pull request, okay?

**Comment by aearly** [comment]
![make it so](https://i.stack.imgur.com/MNeE7.jpg)

**Comment by alexandercerutti** [comment]
[Done](https://github.com/caolan/async/pull/1564) 😄.
I'm closing this.
