### ISSUE TITLE
 How to Create a Parameter Query with many arrays? (multiple INSERT statements)

### ISSUE THREAD

**Issue by mzambo** [caolan/async#1565]
Hi my name is Marco.
I use mysql and I have the parameters  in different arrays , and my question is 
what is the right async collection to use in this case?
(all the arrays have the same length)

                for (let i = 0; i < cbo.length; i++) {
                    let upd = "insert into table (id, id_detail ,score, note) values (?,?,?,?)"
                    con.query(upd, [idcliente, detail[i], score[i], nore[i]], (err, rows) => {
                        callback(err, rows);
               }
May you help me? Thanks

**Comment by aearly** [comment]
`eachOf` over any of the arrays should work.
