### ISSUE TITLE
Throttle and Debounce

### ISSUE THREAD

**Issue by ccorcos** [caolan/async#1570]
Lodash has recommended this library for handling async throttle and debounce https://github.com/lodash/lodash/issues/3864

I am in need of throttle and debounce that actually await the async functions that are getting called. This is commonly needed when rate-limiting expensive apis.

**Comment by aearly** [comment]
I'd recommend [p-debouce](https://www.npmjs.com/package/p-debounce) for that

**Comment by ccorcos** [comment]
Yeah, I looked that up, but they don't drop requests as I would expect based on `_.throttle` for example. 

https://www.npmjs.com/package/p-throttle
https://www.npmjs.com/package/p-debounce

**Comment by ccorcos** [comment]
Here's a solution that I'm using:

```ts
/**
 * Similar to _.throttle but waits for the promise to resolve. There is no
 * wait time because you can simply await `Promise.timeout` inside `fn`
 * to wait some time before the next call.
 */
export default function asyncThrottle<I, O = void>(
	fn: (args: I) => Promise<O>
) {
	let runningPromise: Promise<O> | undefined
	let queuedPromise: Promise<O> | undefined
	let nextArgs!: I
	return async (args: I) => {
		if (runningPromise) {
			nextArgs = args
			if (queuedPromise) {
				return queuedPromise
			} else {
				queuedPromise = runningPromise.then(() => {
					queuedPromise = undefined
					runningPromise = fn(nextArgs)
					return runningPromise
				})
				return queuedPromise
			}
		} else {
			runningPromise = fn(args)
			return runningPromise
		}
	}
}
```

**Comment by aearly** [comment]
Cool, sounds like you found a good solution.

We've deliberately punted on implementing time-based throttling/debouncing in Async, there are a lot of hidden gotchas we don't want to have to support and maintain.
