### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by JFGHT** [caolan/async#1574]
Hello there.

I'd like to ask for a new release because there are nice changes in the code that could bring better performance of the Async library usage. I'm using Async in a serverless system but the current version it's using Lodash and since it's a heavy dependency it makes the execution really slow.

I saw in the commits that you already dropped it and it would be great if you make a new release.

Thank you.

**Comment by aearly** [comment]
There's one major feature I want to get out before 3.0 (https://github.com/caolan/async/pull/1572)  but I haven't had much time to work on it recently.

**Comment by aearly** [comment]
I've just published a pre-release that has all features currently on master!  Install it with `npm i async@next`!
