### ISSUE TITLE
Retryable issue 

### ISSUE THREAD

**Issue by bramses** [caolan/async#1575]
**What version of async are you using?**

2.6.1

**Which environment did the issue occur in (Node version/browser version)**

10.8.0

**What did you do? Please include a minimal reproducable case illustrating issue.**

```
let index = 0;
const someFunction = async (callback) => {
  try {
    console.log(`Running someFunction index: ${index}`)
    if (index < 3) {
      index++
      throw new Error('oops')
    }
    callback(null, 'success')
  } catch (error) {
    callback(error, null)
  }
}

async.retryable(5, someFunction)

someFunction((err, res) => {
  console.log(err)
  console.log(res)
})
```

EDIT: After rereading the documentation involving ES2017 async, I've rewritten the function to look like the one below:
```
let index = 0;
const someFunction = async () => {
  try {
    console.log(`Running someFunction index: ${index}`)
    if (index < 3) {
       index+= 1
      throw new Error('oops')
    }
    return 'success'
  } catch (error) {
    console.error(error)
  }
}

const someWrapper = async.retryable({ times: 5, interval: 1000 }, someFunction)

someWrapper((err, res) => {
  console.log(err)
  console.log(res)
})
```

however `someFunction` still only invokes once

**What did you expect to happen?**

I expected the function to invoke 4 times, throw 4 errors and then crop up a successful result

**What was the actual result?**

It only ran once, threw an error and then exited

**Comment by bramses** [comment]
I was able to get intended behavior by bubbling the error up again in the `catch` block

```
let index = 0;
const someFunction = async () => {
  try {
    console.log(`Running someFunction index: ${index}`)
    if (index < 2) {
      index += 1
      throw new Error('oops')
    }
    return 'success'
  } catch (error) {
    console.error(error)
    throw error
  }
}

const someWrapper = async.retryable({ times: 5, interval: 1000 }, someFunction)

someWrapper((err, res) => {
  console.log(err)
  console.log(res)
})
```

**Comment by aearly** [comment]
Yes, that makes sense, `async` functions don't get passed callbacks, instead the return values and thrown errors are handled.
