### ISSUE TITLE
error for async@latest No valid versions available for async

### ISSUE THREAD

**Issue by bradford1802** [caolan/async#1576]
async versio = async@latest

node version = 8.11.4

npm version = 6.4.1

OS = Microsoft Windows [Version 10.0.16299.611]

tried to install with npm:
  npm install aysnc --save

Error log received:
  0 info it worked if it ends with ok
  1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
  1 verbose cli   'C:\\Users\\name\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
  1 verbose cli   'install',
  1 verbose cli   'aysnc',
  1 verbose cli   '--save' ]
  2 info using npm@6.4.1
  3 info using node@v8.11.4
  4 verbose npm-session 1b665823338bc105
  5 silly install loadCurrentTree
  6 silly install readLocalPackageData
  7 http fetch GET 200 https://registry.npmjs.org/aysnc 914ms
  8 silly fetchPackageMetaData error for aysnc@latest No valid versions available for aysnc
  9 timing stage:rollbackFailedOptional Completed in 1ms
  10 timing stage:runTopLevelLifecycles Completed in 2958ms
  11 verbose type tag
  12 verbose stack aysnc: No valid versions available for aysnc
  12 verbose stack     at pickManifest (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\index.js:20:11)
  12 verbose stack     at fetchPackument.then.packument (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:39:14)
  12 verbose stack     at tryCatcher (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
  12 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
  12 verbose stack     at Promise._settlePromise (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
  12 verbose stack     at Promise._settlePromise0 (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
  12 verbose stack     at Promise._settlePromises (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
  12 verbose stack     at Async._drainQueue (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
  12 verbose stack     at Async._drainQueues (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
  12 verbose stack     at Immediate.Async.drainQueues (C:\Users\name\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
  12 verbose stack     at runCallback (timers.js:810:20)
  12 verbose stack     at tryOnImmediate (timers.js:768:5)
  12 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
  13 verbose cwd C:\Users\name\Development\express-locallibrary-tutorial
  14 verbose Windows_NT 10.0.16299
  15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\name\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "aysnc" "--save"
  16 verbose node v8.11.4
  17 verbose npm  v6.4.1
  18 error code ENOVERSIONS
  19 error No valid versions available for aysnc
  20 verbose exit [ 1, true ]

**Comment by aearly** [comment]
Okay, something is up.  This is not correct at all: https://registry.npmjs.org/aysnc

**Comment by aearly** [comment]
Wait, nevermind, `npm install aysnc --save`  -- misspelled a*ys*nc.

**Comment by bradford1802** [comment]
Wow I feel like a royal shite I stared at this for ages and didn’t see my typo.  Thanks for the quick response and sorry to waste your time.

**Comment by aearly** [comment]
Well, in all fairness I missed it too and sent a false alarm to npm's security team 😅
