### ISSUE TITLE
Await-able queues

### ISSUE THREAD

**Issue by aearly** [caolan/async#1586]
I've been thinking about how we might make queues work better with async/await.  It would be nice if certain operations returned promises, so they could be awaitable.  However, most of the callbacks used in queues are really more event-based, rather than a single task that resolves once.

For example, `q.push(task)` also accepts a callback.  We could make `push()` return a promise if you leave the callback off.  However, `push()` also accepts an array of items to push, in which case, the callback is called multiple times.  Promises can't resolve multiple times.

```js
const done = await q.push([foo, bar, baz]) // how should this resolve?
```

We could make it so it only resolves when all the tasks complete, but this complicates internal logic.

The handling of errors in this case would also be a bit strange.  The callback for `push()` is mainly useful for determining if an error occurred processing the item. If we return a Promise, suddenly that error becomes an unhandled rejection.  If we return a promise from `push()` suddenly a lot of existing code starts throwing unhandled rejections, as most people dont use the `push()` callback.  We could change it so the promise resolves with the error object in those cases.

There are several event callbacks you can register, `empty`, `saturated`, `error` etc.  It seems really difficult to make these awaitable in a useful way.  I've thought about changing the QueueObject API so that event  handlers are methods, rather than bare properties.

```js
q.error((err, task) => console.log(`Queue error: ${err.message} for ${task}`))

//rather than

q.error = (err, task) => console.log(`Queue error: ${err.message} for ${task}`)
```

In this case, we could make it so calling the method without passing a function returns a promise that resolves the next time the event triggers.

```js
const [err, task] = await q.error()
```

This is a bit clunky.  To repeatedly await errors, you'd have to use an infinite loop:

```js
var q = async.queue(taskFn)

const errorLoop = async () => {
  while(q.length) { // not a good condition to test for
    const [err, task] = await q.error()  // if no error occurs, this waits here forever
    console.log(err)
    q.push(task)
  }
}
errorLoop() // fire and forget, hopefully it exits when the queue drains.
```

It's also a bit complicated to implement internally.  We have to keep track of the  promises for each event, creating promise references for each and tracking them appropriately.

Returning a promise on the next firing of the event would be the most useful for the `drain` callback.  It makes the most common use of the queue work nicely in the context of an async function:

```js
async processItems(items) {
  const q = async.queue(processAsync, 5)
  q.push(items)
  await q.drain()
}
```

These changes add slightly  more utility to the queue in `async`/`await` but might be more trouble than they're worth.

-----

Another idea for the event-style callbacks is to return an Async Iterator:

```js
const iterator = q.error()

for await ([err, item] of iterator) {
  //...
}
```

These would still have to be wrapped in a fire-and-forget async function, unless you used one of the `for await` loops to drive the lifecycle of the queue within the main async function.  I think we would also have to assume that a `drain` event  means the queue has ended, thus also ending all the async iterators.

Lots of implementation complexity here as well.

**Comment by aearly** [comment]
Node is considering making `eventEmitter.once()` return a promise, so you can do things like:

```js
const data = await emitter.once('data')
```

This is similar to the first idea above, having the event-style methods return a promise for the next occurrence of the event.

**Comment by Morikko** [comment]
## For the push API

You could return an array of promises:
```javascript
const all_tasks_promise = await q.push([foo, bar, baz])

await Promise.all(all_tasks_promise) // Wait all

const [, task_2_promise] = all_tasks_promise

try {
  await task_2_promise // wait only one task
} catch (err) {
  // Do a specific error handling
}
```

Add an automatic error handler for each promise in the queue:
```javascript
// In the queue
task_promise.catch(() => {}) // avoid an unhandled rejection

// For the user
// optional try/catch
try {
  await q.push(task)
} catch(err) {
  // Do a specific error handling
}
```

## For the event based API
I definitely prefer the method style because you can pass more than one function at different time. It is more an observer pattern than just a single hard coded callback.

1. Using a method for adding observers is good => event programming
2. Adding an API for a one shot call to get a promise that resolves the next time something happened is useful especially for the `empty` and `drain` cases (like you showed)

However the API should differ in a more precise way than just omitting the callback. I think so because the behavior is not the same. In case 1, we do a recursive calling for each event. In case 2, only the next event is targeted.

Maybe:
1. Observers
```javascript
q.drain(() => console.log('Queue drained'))
q.empty(() => console.log('Queue empty'))
q.error(() => console.log('Queue error'))
```
2. Next event
```javascript
q.nextDrain() // return a promise
q.nextDrain(() => console.log('Queue drained')) // only the next event but with the callback style

// and so on...
q.nextEmpty()
q.nextError()
```

Adding an API to get an async generator sounds a bit overkill and complicated compared to use the event programming (doing a recursive task each time something happened).
But, if someone comes with a real use case, the iterator would make sense. In my opinion, it should be treated in another issue later on.

**Comment by ferdian26** [comment]
> Saya telah memikirkan bagaimana kita bisa membuat antrian bekerja lebih baik dengan async / menunggu. Alangkah baiknya jika operasi tertentu mengembalikan janji, sehingga bisa ditunggu. Namun, sebagian besar panggilan balik yang digunakan dalam antrian benar-benar lebih berdasarkan peristiwa, daripada satu tugas yang diselesaikan sekali.
> 
> Misalnya, `q.push(task)`juga menerima panggilan balik. Kami bisa membuat `push()`janji kembali jika Anda membatalkan panggilan balik. Namun, `push()`juga menerima berbagai item untuk ditekan, dalam hal ini, panggilan balik disebut beberapa kali. Janji tidak bisa diselesaikan berulang kali.
> 
> ```js
> const  selesai  =  menunggu  q . push ([foo, bar, baz]) // bagaimana cara mengatasi ini?
> ```
> 
> Kita dapat membuatnya sehingga hanya menyelesaikan ketika semua tugas selesai, tetapi ini menyulitkan logika internal.
> 
> Penanganan kesalahan dalam hal ini juga akan sedikit aneh. Panggilan balik untuk `push()`ini terutama berguna untuk menentukan apakah terjadi kesalahan saat memproses item. Jika kita mengembalikan Janji, tiba-tiba kesalahan itu menjadi penolakan yang tidak tertangani. Jika kami mengembalikan janji dari `push()`tiba-tiba banyak kode yang ada mulai melempar penolakan yang tidak ditangani, karena kebanyakan orang tidak menggunakan `push()`callback. Kita bisa mengubahnya sehingga janji terselesaikan dengan objek kesalahan dalam kasus tersebut.
> 
> Ada beberapa acara callback Anda dapat mendaftar, `empty`, `saturated`, `error`dll tampaknya benar-benar sulit untuk membuat ini awaitable dalam cara yang bermanfaat. Saya telah berpikir untuk mengubah API QueueObject sehingga event handler adalah metode, bukan properti kosong.
> 
> ```js
> q . error (( err , task ) =>  console . log ( ` Kesalahan antrian: $ { err . message } untuk $ { task } ` ))
> 
> // bukannya
> 
> q . error  = ( err , task ) =>  konsol . log ( ` Kesalahan antrian: $ { err . message } untuk $ { task } ` )
> ```
> 
> Dalam hal ini, kita bisa membuatnya begitu memanggil metode tanpa melewati fungsi mengembalikan janji yang diselesaikan saat acara berikutnya dipicu.
> 
> ```js
> const [ err , task ] =  menunggu  q . kesalahan ()
> ```
> 
> Ini agak kikuk. Untuk berulang kali menunggu kesalahan, Anda harus menggunakan loop tak terbatas:
> 
> ```js
> var q =  async . antrian (taskFn)
> 
> const  errorLoop  =  async () => {
>    while ( q . length ) { // bukan kondisi yang baik untuk menguji 
>     const [ err , task ] =  menunggu  q . error ()   // jika tidak ada kesalahan terjadi, ini menunggu di sini selamanya 
>     konsol . log (err)
>      q . push (tugas)
>   }
> }
> errorLoop () // jalankan dan lupakan, semoga keluar ketika antrian terkuras.
> ```
> 
> Ini juga agak rumit untuk diterapkan secara internal. Kita harus melacak janji untuk setiap acara, membuat referensi janji untuk masing-masing acara dan melacaknya dengan tepat.
> 
> Mengembalikan janji pada pemecatan acara berikutnya akan menjadi yang paling berguna untuk `drain`panggilan balik. Itu membuat penggunaan paling umum dari antrian bekerja dengan baik dalam konteks fungsi async:
> 
> ```js
> async  processItems ( items ) {
>    const  q  =  async . antrian (processAsync, 5 )
>    q . push (item)
>    menunggu  q . tiriskan ()
> }
> ```
> 
> Perubahan ini menambahkan sedikit lebih banyak utilitas ke antrian di `async`/ `await`tetapi mungkin lebih banyak masalah daripada nilainya.
> 
> Gagasan lain untuk panggilan balik gaya acara adalah mengembalikan Async Iterator:
> 
> ```js
> const  iterator  =  q . kesalahan ()
> 
> untuk  menunggu ([ err , item ] dari  iterator ) {
>    // ... 
> }
> ```
> 
> Ini masih harus dibungkus dengan fungsi async api-dan-lupa, kecuali jika Anda menggunakan salah satu `for await`loop untuk mendorong siklus hidup antrian dalam fungsi async utama. Saya pikir kita juga harus berasumsi bahwa suatu `drain`peristiwa berarti antrian telah berakhir, dengan demikian juga mengakhiri semua iterator async.
> 
> Banyak kerumitan implementasi di sini juga.

**Comment by ferdian26** [comment]
Check
