### ISSUE TITLE
Feature request: reflect() should return values even when there is error

### ISSUE THREAD

**Issue by jazanne** [caolan/async#1587]
I have a function that will always return a "fallback" value to the callback, even if there's an error. I would really like reflect() / reflectAll() to capture this value.

For example:

```
function myFunc(callback){
    return callback('my error, 'my fallback value')
}

async.parallel(reflectAll({
   myval: myFunc
}), function(err, r){
    // r.myval.error = 'my error'
    // r.myval.value = 'my fallback value'
});
```

**Comment by aearly** [comment]
Good point, we could easily return both the error and value in that case.
