### ISSUE TITLE
2 queues, one with concurrency 1 another with concurrency 3

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1588]
I have this situation with:

```js
const q1 = async.queue((task,cb) => task(cb), 1);
const q2 = async.queue((task,cb) => task(cb), 3);
```

basically, the situation is - if I can get a lock on q1, I can process up to 3 things concurrently in q2. Aka, most things in my program have to run serially, but certainly things can run in parallel, but only if they acquire a "lock" on q1 first. However, writing this turns out to be much harder than expected. I think it's akin to the reader/write locking problem.  https://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock

In other words, I can only process things in q2 if I have a lock on q1. One problem with implementing this, is if I always have to acquire a lock on q1, then I won't be able to use a higher concurrency level.

The only idea I have right now is to flip a boolean, something like this:

```js
let q2HasLock = false;

if(q2hasLock === true){
  q2.push(cb => ...);
}
else{
  q1.push(cb => ...);
}
```

then I can use this:

```js
q2.drain = () => {
   q2HasLock = false;
};
```

but the remaining part is I don't know how/when to flip `q2HasLock` to `true`. Hopefully you understand the problem/idea. Another problem with this implementation, is that requests to push to q2 could starve requests that are going to q1, so I could do this:

```js
let q2HasLock = false, count = 0 ;

if(q2hasLock === true && count < 3){
  count++;
  q2.push(cb => ...);
}
else{
  q1.push(cb => ...);
}

q2.drain = () => {
   count = 0;
   q2HasLock = false;
};
```

This is getting hairy - I would like to implement this as simply as possible!

**Comment by juergba** [comment]
I'm not sure wether I understand "lock on q1" correctly. Do you mean q1 should be idle, or with task waiting for processing?
You can check with q1.length the number of waiting items to be processed in queue q1.  If q1.length>0 you can switch easily to queue q2. You can even pause a queue with q1.pause.
With q1.idle and q2.saturated you get useful infos in order to switch back from q2 to q1.
