### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by JYF3721** [caolan/async#1589]
Hello, I'd like to ask about the 3.0 release and when the document will be released. I'm looking forward to the 3.0 release. Support for async await is a powerful feature.

**Comment by aearly** [comment]
Async 3.0 is already available as a prelease!  `npm i async@next`  should get you the first 3.0 RC.

I'm waiting for some wider feedback before making 3.0 `latest`.

**Comment by casret** [comment]
How can i see the docs for 3.0?

**Comment by casret** [comment]
Answering my own question: ```npx jsdoc -c ./support/jsdoc/jsdoc.json && node support/jsdoc/jsdoc-fix-html.js``` and it'll be in docs/index.html.

**Comment by JYF3721** [comment]
Hello, I'd like to ask when 3.0 will come out. Promise is very popular now. We are all looking forward to the release of 3.0. Do you have any plans for 3.0?

**Comment by aearly** [comment]
It's out!
