### ISSUE TITLE
How to catch javascript errors in async.waterfall ?

### ISSUE THREAD

**Issue by souuu** [caolan/async#1607]
Hello,
I'm running a function that contains an async.waterfall.
Is there a way to handle errors such as error parsing a JSON, reading a non existing attribute from an object ... without exiting the whole function.
I can make many try catch in every function in the async.waterfall, but i'm searching for an easier solution.
Thank you.

**Comment by applefreak** [comment]
On the part of not exiting the whole function take a look at [`reflect`](https://caolan.github.io/async/docs.html#reflect). But you still have to catch it manually in each tasks and call the callback function.

**Comment by aearly** [comment]
Using `async` functions in place of callback functions could help, but it's still best practice to `try`/`catch` things that could throw.

**Comment by souuu** [comment]
Hello,
Still no solution for this ? :(

**Comment by aearly** [comment]
The solution is the same:  use `async` functions, or 

```
fn task (val, cb) {
  try {
    result = doSomething(val)
  } catch (err) {
    return cb(err)
  }
  cb (null, result)
}
```

**Comment by souuu** [comment]
So for example, I have a big script that contains a main async.waterfall that contains a number of functions.
Example : 
script1.js
`func1 = (cb) => {
    //2000 lines
}
func2 = (cb) => {
    //2000 lines
}
func3 = (cb) => {
    //2000 lines
}
async.waterfall([
    func1,
    func2,
    func3
], (err) => {
    if (err) {
        console.log('error')
    } else {
        console.log("DONE")
    }
})`

Do you mean I have to put all this code in one function that contains a try catch ?

**Comment by souuu** [comment]
I will give another example:
`
var async = require('async')
var request = require('request')

  let func1 = (callback) => {
    var clientServerOptions = {
      uri: 'https://www.google.com',
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    };
    console.log("Requesting ..")
    request(clientServerOptions, (err) => {
      if (err) {
        console.log("Error while requesting")
        console.log(err)
        callback(err)
        return
      }
      else {
        console.log("Done requesting")
        callback()
      }
    })
  }

  let func2 = (callback) => {
    console.log("FUNCTION 2")
    let a = JSON.parse(undefined)
    callback()
  }


  try {
    async.waterfall([
      func1,
      func2
    ], (err) => {
      if (err) {
        console.log("ASYNC ERROR =>", err)
      }
    })
  }
  catch (e) {
    console.log("TRY ERROR")
  }
`
this script will stop executing due to : "SyntaxError: Unexpected token u in JSON at position 0"
but, if we comment the GET call and replace it by a callback(), the script is not aborted, and the error is catched in the catch block.
So the question is How to catch javascript errors in async.waterfall, so the script do not stop executing ..

**Comment by applefreak** [comment]
If the only concern is that `JSON.parse` will throw an error, just make a wrapper function around it and returns a distinctive value if it fails. Like this:

```js
function safeParse(str) {
  try {
    return JSON.parse(str);
  } catch (e) {
    console.log('Error parsing JSON', e);
    return {};
  }
}
```

The downside is that you're not able to tell if the JSON string is actually an empty object or not, you can change the failure return value to something more distinct I suppose.

**Comment by applefreak** [comment]
In your code, if you just don't want your waterfall to fail, just don't call the callback with err (`callback(err)`), instead provide some value to tell the next function that something wrong happened. You always have to think about what to do if the code fails...

**Comment by souuu** [comment]
Hello,
Thank you for your reply.
Let me explain more, when having an error due to asynchronous call ( like an api call ), it's correct to catch it and stop the waterfall chain, and for sure there is a part in the code logic that treat this asynchronous error.
In a simple express server that requires in his main server.js file some other js files that exports functions that have risks to throw javascript errors ( like the JSON.parse of undefined object ), this error will stop all the server from running ( it's like an application crash ). Imagine if other functions are running and making important changes to my database, so resetting the server is not a good solution ..
As a final solution for this, I changed the way that I call these functions, I have made them in seperate js files, and call them with child process fork. If the js process throws an error, the process.exit() will be called automatically in this js process, and the listening function in my server.js will catch it and callback an error. Like that, my server will not stop running or reset, also, I'm not obliged to review all my thousands of lines, detect which parts are synchronous and wrap them in try catch blocks ..

**Comment by iiiMaximus** [comment]
Hi, I've just recently published my ``await-waterfall``. It wraps the functions into a try-catch block in order to allow the use of ``throw`` whilst being asynchronous.

[https://www.npmjs.com/package/await-waterfall](https://www.npmjs.com/package/await-waterfall)
