### ISSUE TITLE
Question: async.parallel results order

### ISSUE THREAD

**Issue by AaronAcerboni** [caolan/async#161]
I understand that the `async.parallel` method run its task functions in parallel. However I am unsure about the order of the results.

Is the order of the results array dependant on:

---

When the parallel tasks callback. The first task to callback will have its results first in the final results array.

or

The order of the tasks were supplied in the `async.parrallel` method. The first task method will have its result first in the final results array.

**Comment by davisjam** [comment]
This should be explicitly stated in the async docs.

**Comment by davidcarma** [comment]
Another help would be possibility for a way to pass a key to use in the array lookup in the final results array.
