### ISSUE TITLE
Documentation does not mention if async.eachSeries processes the array in order

### ISSUE THREAD

**Issue by sam09** [caolan/async#1610]
I have a use case where I want to send a list of requests in order. I used async.eachSeries but one of my colleagues pointed out that the documentation does not mention if async.eachSeries processes the array in order or just one item at a time. 

After reading the code, my guess is it does. I maybe wrong, but the docs should mention this explicitly.

**Comment by aearly** [comment]
It does process in order.  A PR to fix the docs would be welcome.
