### ISSUE TITLE
waterfall Callback was already called.

### ISSUE THREAD

**Issue by 1nstinct** [caolan/async#1611]
async version **3.0.1-0**

**node v10.14.0**

**Run async waterfall method**

Expect to see Function without unhandled exceptions

Error happens

> (node:6039) UnhandledPromiseRejectionWarning: Error: Callback was already called.
    at /node_modules/async/dist/async.js:298:36
    at Promise.then.catch (/models/jobs.js:250:14)
(node:6039) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6039) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
const test = () => {
  return new Promise((resolve, reject) => {
    return async.waterfall([
      (cb) => {
        return new Promise((resolve) => {
          const i = setTimeout(() => {
            clearInterval(i);
            resolve();
          }, 1000);
        }).then(() => {
          return cb(null);
        }).catch((err) => {
          return cb(err);
        });
      },
      (cb) => {
        const a = undefined;
        const b = a.dummyData;
        return cb(null, b);
      },
    ], (err) => {
      if (err) return reject(err);
      return resolve();
    });
  });
};

test();
```

**Comment by aearly** [comment]
Thanks for the easily reproducible error case!

**Comment by 1nstinct** [comment]
> Thanks for the easily reproducible error case!

Yw

**Comment by liesislukas** [comment]
I have exactly the same error at `"async": "^2.6.1"`

**Comment by aearly** [comment]
Okay, I finally had a chance to look at this in depth.  I'm afraid there's nothing Async can do to guard against errors like this without reversing some deliberate design decisions.

The error occurs  due to how callbacks and promises are being mixed.

This line causes an error, since `a` is undefined.
```js
        const b = a.dummyData;
```

This is called as a result of
```js
        }).then(() => {
          return cb(null);
```
inside the waterfall.

The error is caught by the the `.catch()` immediately following,  since the `cb` is still within the call stack guarded by the promise.  The `cb(err)` on the following line triggers the `Callback was already called` error.

------

There are several ways to fix this, try/catch in the last waterfall function,  using more promises, or converting to `async` functions.


```js
      (cb) => {
        try {
          const a = undefined;
          const b = a.dummyData;
        } catch (err) { return cb (err) }
        return cb(null, b);
      },
```

or

```js
    return async.waterfall([
      (cb) => {
        return new Promise((resolve) => {
          const i = setTimeout(() => {
            clearInterval(i);
            resolve();
          }, 1000);
        }).then(() => {
          return cb(null);
        }).catch((err) => {
          return cb(err);
        });
      },
      async () => {// Async automatically handles `async` functions as of v2.5
        const a = undefined;
        const b = a.dummyData;
        return b
      }
    ]
```

or more simply:

```js
const test = () => {
  return async.waterfall([
      async () => {
        return new Promise((resolve) => {
          const i = setTimeout(() => {
            clearInterval(i);
            resolve();
          }, 1000);
        })
      },
      async () => {
        const a = undefined;
        const b = a.dummyData;
        return b
      },
    ]); // omitting the callback makes it return a promise as of v3.0
};

test();
```

**Comment by Runa-Redapple** [comment]
Hi I get this types  of issue and where my set time out interval Is create dynamically . Is it work ?
