### ISSUE TITLE
Create a pool that asynchronously watches pool for changes, then executes through eachlimit

### ISSUE THREAD

**Issue by rockyhuber** [caolan/async#1612]
I am trying to have it so that there is a pool, that sits on the server always waiting for a request from a client. Then when the client performs an action, add that action to the array pool and do the processing on the server and remove it from the pool once the processing has completed. Something like this:

let tasksPool = [];

let processTask = async function(task) {
  // await etc
}

eachLimit(tasksPool, 5, function(task, callback) {
  processTask(task).then(() => {
    callback();
  });
});

app.get('/some-url', (req, res) => {
  tasksPool.push(req.body.task);
});

But it does not re-fire the eachLimit process when I add something to the array. I want eachLimit to effectively watch the array for changes. I wished I could understand what was going on with your example enough to solve this on my own, though have not seen a lot of the syntax before. Any suggestions appreciated greatly?

**Comment by aearly** [comment]
`async.queue` is what you want to use here.  `eachLimit` wont iterate past the initial length of the array at the time it is passed to `eachLimit`.
