### ISSUE TITLE
Remove excess return statements

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1613]
Seems like to me we could remove some return statements like this one:

https://github.com/caolan/async/blob/master/lib/each.js#L65

```js
function eachLimit(coll, iteratee, callback) {
    return eachOf(coll, withoutIndex(wrapAsync(iteratee)), callback);
}
```

is there a good reason why it couldn't be:

```js
function eachLimit(coll, iteratee, callback) {
     eachOf(coll, withoutIndex(wrapAsync(iteratee)), callback);
}
```

I get the feeling it will save a tiny bit of perf...OR perhaps the return statements are necessary for async/await to work...dunno.

**Comment by hargasinski** [comment]
Hi @ORESoftware,

Thanks for the suggestion! You're right, not all of the `return` statements are required. The return of the promise, in the `eachLimit` case, is handled by the `awaitify` wrapper. However, maintaining a consistent style, i.e. always propagating the result, helps prevent subtle bugs from being introduced. For example, it is required in `mapValues`, `groupBy` and `compose`. Any performance gains from removing it would be negligible/if it does have any sort of impact, modern engines probably optimize it away in the cases it's not required.

**Comment by hargasinski** [comment]
I don't know, sorry. I'm sure there's something similar though.

**Comment by ORESoftware** [comment]
@hargasinski 
https://search.maven.org/artifact/org.webjars.bowergithub.caolan/async/2.6.1/jar

do you know what that JAR is about? Curious to see caolan/async in the Maven Central repo. It points to this git project so I doubt it's something in Java, so idk.
