### ISSUE TITLE
Make async even more composable

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1614]
Say I have this:

```js
const async = require('async');

async.parallel([
  cb => {
    async.series([
      cb => {
        process.nextTick(cb, null, 1);
      },
      cb => {
        process.nextTick(cb, null, 2);
      }
    ],cb);
  },
  cb => {
    process.nextTick(cb, null, 3);
  }
  
], (err, results) => {
   console.log({err,results});
});
```

it will log:

> { err: null, results: [ [ 1, 2 ], 3 ] }

I have always wondered if there was a way to make async even more composable, something like this:

```js
const async = require('async');

async.parallel([
  async.fseries([
    cb => {
      process.nextTick(cb, null, 1);
    },
    cb => {
      process.nextTick(cb, null, 2);
    }
  ]),
  cb => {
    process.nextTick(cb, null, 3);
  }

], (err, results) => {
  console.log({err, results});
});

```

that won't work, but basically I am looking to make async things even more composable. What we could do is add methods, so that async.fseries would look like:

```js
async.series = function(tasks, iterator, finalcb){

}
```
and then

```js
async.fseries = function(tasks, iterator){
  return finalcb => {
     
 }
}
```

I think async.apply currently can accomplish this? but I am not sure if async.apply can work with async.series or async.parallel?

**Comment by hargasinski** [comment]
Thanks for the question! Like you said, `apply` can be used to accomplish this:
```js
async.parallel([
  async.apply(async.series, [
    cb => {
      process.nextTick(cb, null, 1);
    },
    cb => {
      process.nextTick(cb, null, 2);
    }
  ]),
  cb => {
    process.nextTick(cb, null, 3);
  }
], (err, results) => {
   console.log({err,results});
});
```

Please see the [apply](https://caolan.github.io/async/docs.html#apply) docs for more info.

**Comment by ORESoftware** [comment]
nice yeah async.apply should suffice
