### ISSUE TITLE
Feature: Make call to nextTick if user doesn't

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1616]
This regards the common scenario where a user does something like:

```js
async.parallel([
   cb => cb(),
   cb => process.nextTick(cb)
]);
```

the user has broken a cardinal rule of Node.js - keep APIs always sync or always async. Here they mixed and matched.

However, the async lib could fix the problem if it could detect if the user fired the callback in the same tick of the event loop. I am thinking a feature like this:
https://github.com/nodejs/node/issues/25787

is it too late for something like this? Maybe in the next major version? I know that in older async versions, the library would always call process.nextTick. Here I am saying only call that if the user fired the cb in the same tick. It's just a matter of detecting it easily.

**Comment by hargasinski** [comment]
Thanks for the suggestion! Please see #1446. As you mentioned, we previously did have these guards in place, but decided to remove them for performance reasons.
