### ISSUE TITLE
Feature/question - boolean representing short-circuit

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1617]
This feature might exist, but I haven't seen it in my 3 years of using this lib. Say we have the common scenario of:

```js
async.parallel([
    cb => {
          setTimeout(() => {
             cb('this is an error');
          }, 100);
    },
    cb => {
         setTimeout() => {
            // this second settimeout will run, 
            // even though we passed an error to the callback in another task
            setTimeout(cb,150); 
        },200)
   }
], (err,results) =>{
    // fini
});
```

so what if there was something like this:

```js
async.parallel([
    cb => {
          // same as above
    },
    cb => {
         setTimeout() => {
           if(cb.isShortCircuited()){ 
               return;
           }
           // this won't run, because we short circuited
            setTimeout(cb,150);  
        },200)
   }
], (err,results) =>{
    // fini
});
```

so there'd be a method on the callbacks that could check if another task errored-out, and this would prevent us from doing no-longer-necessary processing, or cleanup things properly etc.

I suppose the user could handle this logic themselves, with their own booleans, like this:

```js
let shortCircuited = false;

async.parallel([
    cb => {
         setTimeout(() => {
             shortCircuited = true;
             cb('this is an error');
          }, 100);
    },
    cb => {
         setTimeout() => {
             if(shortCircuited) return;
            setTimeout(cb,150); 
        },200)
   }
], (err,results) =>{
    // fini
});
```

so I figure this last solution is probably good enough?

**Comment by hargasinski** [comment]
Hi @ORESoftware,

Thanks for the suggestion! This seems like a pretty niche use case, so I would prefer to let users handle it themselves for now.

**Comment by ORESoftware** [comment]
@hargasinski this one I think is more common - consider `async.race`, especially with many tasks?

**Comment by ORESoftware** [comment]
@aearly yes but I think you're not following this issue, think about async.race - all tasks start in the same tick, but if one short-circuits, we may want to allow the other tasks to know about that so they don't continue doing unnecessary work.
