### ISSUE TITLE
question - what is purpose of buffer in async queue

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1618]
re: https://github.com/caolan/async/blob/master/lib/internal/queue.js

the buffer property on the queue instance is the concurrency divided by 4?

just curious what that's about? i am implementing a clone of this lib in OCaml and trying to figure out how the queue works.

looks like the buffer property is used in the calc regarding when to call q.unsaturated()?

**Comment by ORESoftware** [comment]
on this topic, also trying to figure out what the "payload" property is as well

**Comment by aearly** [comment]
`buffer` is used in the saturated calculation, and `payload`  is the number of items to pass to the worker function, used by `cargo`.
