### ISSUE TITLE
saturated doesn't get called with queue?

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1619]
I have this:

```js
const q = async.queue((task,cb) => task(cb),3);

q.saturated = function(){
 console.log('saturated');
};

q.unsaturated = function(){
  console.log('unsaturated');
};

q.push(cb => {
  console.log('called 1.');
  cb(null);
});

q.push(cb => {
  console.log('called 2.');
  cb(null);
});

q.push(cb => {
  console.log('called 3.');
  cb(null);
});

```

I get:

```
called 1.
unsaturated
called 2.
unsaturated
called 3.
unsaturated

```

but if I change concurrency from 3 to 1, then I get:

```
saturated
called 1.
unsaturated
saturated
called 2.
unsaturated
saturated
called 3.
unsaturated
````

I guess I am confused - I would expect a saturated call to come before unsaturated, but maybe that's not always the case.

**Comment by aearly** [comment]
The queue never saturates at `concurrency: 3` because the tasks complete immediately.

**Comment by ORESoftware** [comment]
Yeah as an aside it's weird that unsaturated gets called 3 times when concurrency is 1. I would expect unsaturated to only be called once no more tasks are queued.
