### ISSUE TITLE
how to make async work with async/await

### ISSUE THREAD

**Issue by kazaff** [caolan/async#1622]
```javascript
var async = require('async');

var workPool = async.queue(async (task, taskComplete)=>{
  console.log(1, taskComplete);

  async.retry(3, async (retryComplete)=>{

    console.log(2, retryComplete);
    // retryComplete(null, task);

  });
});

workPool.push("test");
```

I wonder why i got this result:

```javascript
$ node test.js
1 undefined
2 undefined
```

**Comment by ex1st** [comment]
https://caolan.github.io/async/

> Async accepts async functions wherever we accept a Node-style callback function. However, we do not pass them a callback, and instead use the return value and handle any promise rejections or errors thrown.
> 
> ```javascript
> async.mapLimit(files, async file => { // <- no callback!
>     const text = await util.promisify(fs.readFile)(dir + file, 'utf8')
>     const body = JSON.parse(text) // <- a parse error herre will be caught automatically
>     if (!(await checkValidity(body))) {
>         throw new Error(`${file} has invalid contents`) // <- this error will also be caught
>     }
>     return body // <- return a value!
> }, (err, contents) => {
>     if (err) throw err
>     console.log(contents)
> })
> ```

**Comment by aearly** [comment]
Yep, Async doesn't pass callbacks to `async` functions -- just return when the task is complete.

**Comment by pawelotto** [comment]
And what about returning values from the final callback function (instead of console-log them like in this example)?

**Comment by aearly** [comment]
Just `return` ing values from `async` functions works in most cases.

**Comment by pawelotto** [comment]
Which `async` function exactly returns a value? From what I've checked they return void, e.g. 
[doUntil](http://oi66.tinypic.com/2jg788g.jpg)

**Comment by b4dnewz** [comment]
@pawelotto I think for that you can use node [promisify](https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original) util, I didn't test but since the main callback function signature is compatible I assume it will work.

So the example above will become (without handling error):

```js
import async from "async"
import {promisify} from "util"

const promiseMapLimit = promisify(async.mapLimit)
const results = await promiseMapLimit(files, async file => { // <- no callback!
    const text = await util.promisify(fs.readFile)(dir + file, 'utf8')
    const body = JSON.parse(text) // <- a parse error herre will be caught automatically
    if (!(await checkValidity(body))) {
        throw new Error(`${file} has invalid contents`) // <- this error will also be caught
    }
    return body // <- return a value!
})
```

**Comment by kazaff** [comment]
Maybe you can try [neo-async](https://github.com/suguru03/neo-async)

**Comment by b4dnewz** [comment]
@kazaff cool, I didn't know about it, thanks!

**Comment by pawelotto** [comment]
@kazaff Legend!

**Comment by superlbr** [comment]
@kazaff how to use neo-async in b4dnewz's answer, just fail to return reulst
