### ISSUE TITLE
is concat the same as flatmap?

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1625]
looks like concat in this lib is the same thing as flatMap?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

maybe alias concat as flatMap?

**Comment by Aqua-Dream** [comment]
The same question I want to ask yesterday. I was about to use `map` and `concat` to realize `flatMap`, until I saw the definition of `concat`. Therefore, I vote for your suggestion.

**Comment by ORESoftware** [comment]
that's good yeah I think it's the same as far as I can tell.

Also, on this note, I think it would be nice to also implement `filterAndMap` or `filterMap`. 

`filterMapConcat` or `filterMapFlatten` might be a little too much though.

**Comment by Aqua-Dream** [comment]
The main problem is that async does not return a promise, so we cannot write things like array.filter().map()...

**Comment by ORESoftware** [comment]
Promise type only has `then` and `catch` methods. Bluebird/Aigle libraries might have more methods than native promises. I have always preferred the async library to promises, more performant and easier to use imo.

**Comment by ORESoftware** [comment]
bump...does anyone know if the async concat functionality is equivalent to flatmap?

**Comment by aearly** [comment]
Yes, it is.  We could add an alias pretty easily.

**Comment by ORESoftware** [comment]
Yeah I recommend that, easily for users to get started quickly and know what's going on. Still waiting for filterMap functionality tho :)
