### ISSUE TITLE
eachOf vs. mapOf

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1631]
I noticed there is an `eachOf` method that will handle both _value_ and _index_.
Is there not a `mapOf` method that can do the same? I see `each/eachOf`, but I don't see `map/mapOf`, only `map`.

https://caolan.github.io/async/docs.html#map

**Comment by aearly** [comment]
I'd rather keep the simple `map`.  If you need the index you can do something like:

```js
async.map(items.map((val, idx) => [val, idx], ([val, idx], cb) => {
   //...
})
```

**Comment by ORESoftware** [comment]
Yeah I guess to be consistent then `filterOf` etc would also need to be implemented..I always thought that `eachOf` was confusing/superfluous, because `eachOf` could use the pre-map technique you use above. Looks like you're missing a paren after the first `[val,idx]` above.
