### ISSUE TITLE
QUESTION: Queue with retrys

### ISSUE THREAD

**Issue by marvinside** [caolan/async#1634]
I want to combine the features from a queue and retry/retryable, but could not manage to do so.

Scenario:
I need to make some calls to an REST api, wich sometimes fails with internal server errors (Shitty API...)
So if i do the request again a few seconds later, it probably succeeds.
As i also need to do about 11k requests, i need to use a queue.

I found this issue: https://github.com/caolan/async/issues/919, but there is no max Limit.

Are there any Examples/Snippets of an retryable queue? (Can also be cargo, i don't mind)

**Comment by aearly** [comment]
Using `retry` within the queue worker function should work.  Perhaps share a code snippet?

**Comment by marvinside** [comment]
For Anyone having the same Problem/Question:
Solved it by using a async.queue and just adding again if an error occours.
For this to have a maximum amount of tries for each task, i'm using and infoObject which stores the tries (see Line 3 and 10)

```typescript
this.articleQueue = async.queue((articleInfo: IArticleRequestInfo, callback: () => void) => {
	articleInfo.try++;
	this.requestArtikel(articleInfo.id, articleInfo.version, articleInfo.heft).then(
		() => {
			// success, call callback to inform the queue that we are finished
			callback();
		},
		(reason: unknown) => {
			// check if we have not reached the try-limit
			if (articleInfo.try < 10) {
				// Rescedule article
				this.articleQueue.push(articleInfo);
			} else {
				// Error handling after 10 tries are reached [code ommited]
			}
			callback();
		},
	);
}, 10); // Max 10 concurent requests
```

I'm dealing with about 3,000-10,000 requests, so directly adding them to the queue works for me.
You could improve this code by adding to the queue after a `setTimeout` with 3 seconds for example.
