### ISSUE TITLE
How to enlist all the pending tasks in a queue?

### ISSUE THREAD

**Issue by agarwalkartik** [caolan/async#1636]
How to enlist all the pending tasks in a queue?

**Comment by hargasinski** [comment]
Hi @agarwalkartik,

Thanks for the question. It depends on the version you're using. If you're using `v3`, `queue`s are iterable. Iterating over one will iterate over the pending tasks. So either

```js
for (const task of q) {
  // do something with task
}
```
or
```js
const pendingTasks = [...q];
```
depending on your requirements. If you're using `v2`, then your best bet is

```js
const pendingTasks = q._tasks.toArray();
```

See the [QueueObject](https://caolan.github.io/async/docs.html#QueueObject) docs for more info.

**Comment by agarwalkartik** [comment]
Hey Thanks a lot! It solves my query.

PS : is it just me who missed it or this is yet not added in the docs?

**Comment by hargasinski** [comment]
The `_tasks` list isn't documented and the `v3` docs (with iterable `queue`s) aren't out yet.
