### ISSUE TITLE
Using async from a node and browser library

### ISSUE THREAD

**Issue by kai670** [caolan/async#1639]
I'm using async in a library that is intended to be used both in node and the browser but I'm having some problems making it work as expected in both at the same time. If I use the "async" package, it works as expected in node but when the code is bundled using webpack the whole packet is included. On the other hand if I use "async-es" package tree-shaking works as expected but it doesn't work in nodejs at all as import and export are not recognised.

I think there are two possible solutions to fix this:

1. Include both builds in the same package (with the index property for cjs build and module property for esm build) instead of publishing them as two independent packages as it is currently done.
2. Create a new package for libraries that need to keep compatibility for both module syntaxes.

I have created a test package using the latter approach and it works as expected. Could make sense including in this repository the required code to automatically publish also this third package?

Here is the code I've created: https://github.com/kai670/async-universal-test

Thank you.

**Comment by hargasinski** [comment]
Hi @kai670,

Thanks for the question. Usually, when you're writing a package for both node and the browser, you build it with webpack or rollup before publishing and then point to that in your `package.json`. See the `Compatibility` section of the [rollup docs](https://rollupjs.org/guide/en). Would that work for you?

**Comment by kai670** [comment]
Thanks for the answer! I always thought bundling with rollup before publishing made sense for own code but not for dependencies. But maybe installing only `async-es` version and then using rollup to create a bundle for node version including `async-es` in the bundle as you suggest can be a reasonable solution. 

It doesn't seem like the ideal solution to me as package size will be increased and replicated code will exist in the case of being used from node but, anyway, I suppose the only disadvantage of this in node is a negligible increase in disk usage. And in fact the same disk usage increased (or even worse) will happen if both `async-es` and `async` are installed like I was suggesting.

Just curious, why is the reason of publishing two independent packages instead of including esm version also in the `async` package?

**Comment by aearly** [comment]
We keep them separate due to disk space concerns.  It might not seem like it matters much, but if you have multiple versions of Async and are building for docker images it can start to add up.

Also, three years ago, there wasn't a emerging standard for how to specify "this is the ESM entrypoint" and "this is the CJS entrypoint".  It might be worth revisiting now.  I can envision doing something like `"module": "async-full.mjs"` now, allowing you to `import mapLimit from 'async'`.
