### ISSUE TITLE
Confusing mismatch, release notes vs. documentation, browser support

### ISSUE THREAD

**Issue by bazineta** [caolan/async#1643]
In the release notes, there's this:

`We are now making heavy use of ES2015 features, this means we have dropped out-of-the-box support for Node 4 and earlier, and many old versions of browsers. (#1541, #1553)`

In contrast, in the documentation:

`In the Browser
Async should work in any ES5 environment (IE9 and above).`

Given the statement in the release notes, the documentation is surprising; I'd think there'd be no ability to support IE at all.

Which is correct?

**Comment by aearly** [comment]
Ah, the former.  It won't work out of the box in any version of IE (at least not without transpiling).
