### ISSUE TITLE
async.autoInject looks broken

### ISSUE THREAD

**Issue by pravichandran15** [caolan/async#1644]
async.autoInject seems to be broken with the latest 3.x version, Either I am getting non-dependency or it goes to the second function without waiting for the dependencies.

**Comment by runningman84** [comment]
We suffer from the same problem.

**Comment by aearly** [comment]
Would you mind sharing some some example code that breaks?

**Comment by aearly** [comment]
Please re-open this once you have a reproducible error example. As far as I can tell, `autoInject` is working as intended.
