### ISSUE TITLE
How to return error to results callback using async/await without premature exit

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1649]
Say I have this:

```javascript
async.autoInject({
  slack(cb){
     someCall((err, val) => {
        cb(null, {err,val});  // this works with callbacks, but what about async/await below?
    });
  },
  async bitbucket(){
    try{
       const val = await someCall();
       return {error: null, val};
    }
    catch(err){
        return {error: err, val: null}
    }
 }

}, (err, results) => {

    // how to pass errors to results instead of to err?
});

```

as you can see I am trying to pass errors from the async/await blocks to the results set not the first error argument - is it possible somehow?

**Comment by ORESoftware** [comment]
my guess rn is that the only way to get an error to show up in the first arg is to _throw_ the error in the async/await function?

**Comment by aearly** [comment]
Yeah, if you `throw` inside an `async` func, the error would show up ass the `err` arg in the callback.

**Comment by ORESoftware** [comment]
but only if you throw? I guess thats good enough

**Comment by aearly** [comment]
Yep, that's how async functions work.

http://caolan.github.io/async/v3/global.html
