### ISSUE TITLE
async.autoInject task has a non-existent dependency `this` in this, void0, void

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1650]
I have this:

```js
async.autoInject({

  async slack() {
      
     try {
        const v: any = await webClient.conversations.list();
      }
      catch(err){}
    }
  }
})
```

which got transpiled to this by TypeScript:

```js
 slack() {
         return __awaiter(this, void 0, void 0, function* () {});
       }
```

any idea why I got this error:

> async.auto task `slack` has a non-existent dependency `this` in this, void0, void

**Comment by aearly** [comment]
`autoInject` wouldn't work if you use TypeScript (or any form of transpiler).  It needs to have the original function signature at execution time in order to work.

**Comment by ORESoftware** [comment]
I fixed this by transpiling to ES7 instead of ES6, but still curious why it happens
