### ISSUE TITLE
typescript definition for v3.0.0

### ISSUE THREAD

**Issue by erossignon** [caolan/async#1651]
**What version of async are you using?**

version 3.0.1

**Which environment did the issue occur in (Node version/browser version)**
any

**What did you do? Please include a minimal reproducable case illustrating issue.**
async version is 3.0.1
@types/async version is still 2.4.2

**What did you expect to happen?**

I am expecting a definition file for async 3.0 
@types/async version is still 2.4.2

**What was the actual result?**
because of some breaking changes in 3.0.0 ( such as AsyncQueue drain etc ...) 
@types/async  2.4.2 causes typescript compilation error when trying to fix code to new API.

Also, I wonder if async would benefit of include its own definition file in this repo and publish in the npm package rather than defining it externely on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo ?

**Comment by aearly** [comment]
I don't maintain the `@types/async` module, and yeah, it would need updates after 3.0.   I don't use TS personally, so adding (and maintaining) a `.d.ts` hasn't been a priority.

**Comment by aearly** [comment]
I'd recommend making a PR to DefinitelyTyped.
