### ISSUE TITLE
Add browserify in package.json for ES6

### ISSUE THREAD

**Issue by binarykitchen** [caolan/async#1653]
Now that with v3.x my app is breaking since it's browserify + babelify configuration doesn't transform node_modules by default.

See https://github.com/babel/babelify#faq for background.

Suggestion is to add this in your package.json

```
{
  "browserify": {
    "transform": [["babelify", { "presets": ["@babel/preset-env"] }]]
  }
}
```

This will ensure that any app using async and building it with browserify + babelify gets transpiled correctly.

Thanks!

**Comment by aearly** [comment]
It seems a bit odd to have to configure browserify here for your project.  Shouldn't this type of config go in your project's bundler config?

**Comment by binarykitchen** [comment]
I hear you. Although some other modules do that so it's not unusual. And ultimately we all have to transpile to ES5. This is one solution to flag that package is ES6 and needs transpilation.

Don't want to tell browserify to babelify all node modules which would slow down build enormously.

**Comment by gabegorelick** [comment]
I'm glad this fixed someone's workflow, but this broke mine 😄. 

We run browserify but target Node.js (browserify is useful to generate single JS files). This change means we now get a `Cannot find module 'babelify' from '/node_modules/async` error. We can work around that by adding `ignoreTransform: ['babelify']` though. 

In general, I think this change means that anyone running browserify over `async` will need to either add `babelify` as a dependency or take steps to ignore the transform.

**Comment by alanshaw** [comment]
Broke ours too. If you need to babelify a particular node module can't it be configured in your project? Not everyone transpiles to ES5.

**Comment by aearly** [comment]
I'm considering removing the browserify-specific config.  I didn't like doing it in the first place.

**Comment by nappy** [comment]
What are you thinking? Why do I need to add "babelify" "@babel/core" and "@babel/preset-env" to my project. I do not want to use babel. I just want to bundle my dependencies.

Even if I would use a transpilerm, this whole concept does not work with devDependencies. Why should every library provide its own rollup/webpack/browserify config and then require downstream to include their dev dependencies manually?

This is madness.

A more resonable approach would be to target a specific node version, and if you want to use newer features in your source, then transpile it yourself.

This approach (sorry if I repeat mysdelf) is complete nonsense.
