### ISSUE TITLE
Code works with Node async v2.6.2 but not with v3.0.1

### ISSUE THREAD

**Issue by autumnus** [caolan/async#1654]
Hello.

The following example works with Node async v2.6.2 but not with v3.0.1

```js
var q = async.queue(function (task, callback) {
    console.log(task.task);
    callback();
}, 10);

q.drain = function() {
    console.log('all items have been processed');
};

for(var i = 0; i < 20; i++){
    q.push({task:"task"+i});
}
```
drain() is not entered.

Bug? Or am I missing something?

**Comment by aearly** [comment]
Check [the changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md#v300),  there was a breaking change to the `queue` api.

**Comment by aearly** [comment]
```js
q.drain(function() {
    console.log('all items have been processed');
});
```

**Comment by autumnus** [comment]
Thanks a lot!
Next time I will check the changelog!!
