### ISSUE TITLE
Create Release automatically as a part of CI

### ISSUE THREAD

**Issue by raiyanalam** [caolan/async#1655]
Hi,
   I observed that there are several tags in the release section which do not contain any information about what changes were incorporated in a release. Displaying this information in the release section really helps developers to be in sync with the latest development in this library.
![image](https://user-images.githubusercontent.com/7879476/58791446-d8b6c980-860f-11e9-8d44-4dcf08f0a39b.png)

  As the repo uses Azure pipelines for CI the solution here could be simple. Azure pipelines provides an [out of box task](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV0) that help create GitHub releases.  The task can be configured to create a release only when the pipeline is triggered for a matching tag. It can compute a list of changes, cross reference it with corresponding issues and can also take the contents of a file that's checked into repository and add it as the release notes. 

Here is a [sample repo](https://github.com/Microsoft/vscode-react-native/releases) that leverages this capability.
![image](https://user-images.githubusercontent.com/7879476/58791579-161b5700-8610-11e9-9911-25cf2f254d03.png)

PS: I am a PM for azure pipelines. I would be happy to help with the changes :)

**Comment by raiyanalam** [comment]
@megawac - i would be happy to raise a PR for this.

**Comment by aearly** [comment]
How does the input to the text of the release notes work?  We like maintaining a single `CHANGELOG.md`.

**Comment by raiyanalam** [comment]
The input field can either take:
1. A static content, eg link to release notes in some website. Variables can be used in the links to point each time at the correct version.
2. Path to file that contains the list changes or other release related information. In this case, it will copy all the contents of file as release notes

**Comment by aearly** [comment]
Hmnn, that is not something that fits our workflow.  I think we'll stick to the hand-maintained `CHANGELOG.md`.  Most people use npm to install Async, so I don't think having empty github release notes is that big of a deal.
