### ISSUE TITLE
 autoinject with async/await  - docs update

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1656]
Question -

```js
async.autoInject({

   async foo(){ return Promise.resolve(5)},
   async bar(foo){return foo + 3}

}, (err, results) => {
   // results => {foo: 5, bar: 8}
})
```

is the above supported?
If it is, I would be happy to update the docs with a working example

**Comment by ORESoftware** [comment]
looks like this works, would be happy to update the docs

**Comment by aearly** [comment]
It works, but I want to discourage that particular use case.  You really should:

```js
const results = await async.autoInject({
   async foo(){ return Promise.resolve(5)},
   async bar(foo){return foo + 3}
})
```

**Comment by ORESoftware** [comment]
mixing and matching async/await with callbacks is not a crime..in fact doing so means you know what you are doing. however it might make library implementation and maintenance harder.

```js
async foo cb => {
  const a = await p1()
  const b = await p2(a)
  doTheC(b, cb);
}
```

theres absolutely nothing wrong with that and to think there is, is defective thought, nor can you prevent your users from mixing and matching by mistake or purposefully.

Maybe I am just annoyed because I dont like promises.
