### ISSUE TITLE
Fix coveralls Token in Azure Pipelines builds

### ISSUE THREAD

**Issue by pablonete** [caolan/async#1657]
Looking at [recent build](https://dev.azure.com/caolanmcmahon/async/_build/results?buildId=5&view=results), we should not provide `run_coveralls` variable from outside:

![image](https://user-images.githubusercontent.com/579705/58968382-43a20500-87b6-11e9-9fc2-fa181be8ae39.png)

It is intended to be set on the strategy matrix for selected jobs, so passing it on queue time will overwrite the intended behavior of running coverage test on a limited number of jobs.

On the other hand, we're missing the `COVERALLS_REPO_TOKEN` that should be added on the [build definition](https://dev.azure.com/caolanmcmahon/async/_build?definitionId=1&_a=summary) (Edit > Settings > Variables), and uncheck "Settable at queue time" as nobody should know about or change this value.

![image](https://user-images.githubusercontent.com/579705/58968733-d5aa0d80-87b6-11e9-90bf-f612be83c048.png)

@caolan I can help out. Thanks!

**Comment by aearly** [comment]
I've added this env var, but it still seems to error out.  I've tried regenerating the token on Coveralls, but no luck.

**Comment by aearly** [comment]
I've decided to not run coveralls on azure, can't figure out why its not working.

**Comment by pablonete** [comment]
Sorry to hear that, @aearly. Definitely it worked for me on my own coveralls account:
https://dev.azure.com/pablo-nunez/Runner/_build/results?buildId=343

Leaving this capture here in case it helps for the variable I had to set, no other changes in yaml:
![image](https://user-images.githubusercontent.com/579705/60006627-205dcd80-9671-11e9-8b8c-f43fdf67b213.png)
Let me know how I can help any other way.

**Comment by aearly** [comment]
Ah, I made it not-a-secret, and it started working!

Now, Node on OSX is failing form some reason... 

https://dev.azure.com/caolanmcmahon/async/_build/results?buildId=65

**Comment by pablonete** [comment]
It's one test failing, see details on the [Tests tab](https://dev.azure.com/caolanmcmahon/async/_build/results?buildId=65&view=ms.vss-test-web.build-test-results-tab&runId=618&resultId=100525&paneView=debug).

Some tests like this are flaky as we discussed in #1630. They are more likely to fail in OSX and Windows, and even more in Web tests.

**Comment by aearly** [comment]
Ah, the tests tab is cool -- nice being able to see all tests that fail.

Anyway, the build seems to have stabilized!
