### ISSUE TITLE
I can't install Cordova on ubuntu 

### ISSUE THREAD

**Issue by abhirampjayan** [caolan/async#1660]
**I cant install cordova on ubuntu suing the command**
**$ sudo npm install -g cordova**
**it shows an warning**

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ECONNRESET: request to https://registry.npmjs.org/cordova failed, reason: read ECONNRESET
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
/usr/local/bin/cordova -> /usr/local/lib/node_modules/cordova/bin/cordova
+ cordova@9.0.0
added 451 packages from 357 contributors in 255.527s

**Comment by aearly** [comment]
Sorry, this is not the right place to troubleshoot npm installs.
