### ISSUE TITLE
ie11 async not defined

### ISSUE THREAD

**Issue by michael2043** [caolan/async#1661]
![asyncerr](https://user-images.githubusercontent.com/4134458/59319261-991d6b00-8cfc-11e9-8ae8-00f34bd8c997.jpg)
![async2err](https://user-images.githubusercontent.com/4134458/59319297-b8b49380-8cfc-11e9-8e34-896ade26f9f5.jpg)

**Comment by aearly** [comment]
Hard to tell what's going on here, but I think you're using v3, which doesn't support IE11.  Keep using v2.

**Comment by mattwelke** [comment]
@aearly  I looked at the NPM releases and it looks like there are some 3.x minor releases without corresponding 2.x minor releases. Is 2.x not receiving new features anymore? Is it still going to get patch updates, like for CVEs?

**Comment by aearly** [comment]
2.x won't be receiving new features, and will only be getting patches for major issues, like CVEs.
