### ISSUE TITLE
await queue.drain() does not reject promise if queue has an error.

### ISSUE THREAD

**Issue by tekmaven** [caolan/async#1662]
**What version of async are you using?**
3.0.1

**Which environment did the issue occur in (Node version/browser version)**
Node v10.15.3

**What did you do? Please include a minimal reproducible case illustrating issue.**
Example code:

```js
import async from "async";

(async () => {
  const q = async.queue(async task => {
    throw new Error("Bad thing");
  });

  try {
    q.push("test");
    await q.drain();
    console.log("this line should not execute");
  } catch (e) {
    console.log("this line should execute", e);
  }
})();
```
**What did you expect to happen?**
If an item in the queue errors (it's promise is rejected), the promise returned by `queue.drain()` should be rejected with the error.

**What was the actual result?**
The above code prints `this line should not execute`.  

**Workaround**
I have a workaround, to wrap the callback style code in a promise and await that:
```js
await new Promise((resolve, reject) => {
  queue.drain(resolve);
  queue.error(reject);
});
```

**Comment by aearly** [comment]
`q.drain()` rejecting on any error I think would be pretty surprising behavior.  The `drain` event is pretty decoupled from `error` events.

**Comment by tekmaven** [comment]
I understand your point here, closing the issue.  In the way I'm using the queue, I want to abort and stop processing the queue once I hit the first error.  The above Promise that I created above is working well in my use-case (I `try/catch` it and call `queue.kill` in the `catch`).
