### ISSUE TITLE
autoInject regex pattern contains error

### ISSUE THREAD

**Issue by freeart** [caolan/async#1663]
**What version of async are you using?**
3.0.1

**Which environment did the issue occur in (Node version/browser version)**
nodejs

**What did you do? Please include a minimal reproducable case illustrating issue.**
I found an error in autoInject when you use arrow function
https://regex101.com/r/RpedPY/1
regex doesn't work properly with "=>" symbol

**What did you expect to happen?**

**What was the actual result?**

**Comment by aearly** [comment]
Do you have code that breaks?  There is a secondary regex for arrow functions: https://github.com/caolan/async/blob/master/lib/autoInject.js#L6

**Comment by freeart** [comment]
```js
var FN_ARGS = /^(?:async\s+)?(?:function)?\s*[^(]*\(\s*([^)]+)\s*\)(?:\s*{)/m;
var ARROW_FN_ARGS = /^(?:async\s+)?(?:function\s+)?\(?\s*([^)^=]+)\s*\)?(?:\s*=>)/m;

...

const src = func.toString().replace(STRIP_COMMENTS, '');
let match = src.match(FN_ARGS);
if (!match) {
    match = src.match(ARROW_FN_ARGS);
}
```
It breaks on ```let match = src.match(FN_ARGS);```because match contains string ```!orderCache || !analysisCache``` for this function https://regex101.com/r/RpedPY/2

**Comment by aearly** [comment]
Figured this one out.  Thanks for the excellent example!
