### ISSUE TITLE
whilst and until type description differ from the documentation's examples in Typescript

### ISSUE THREAD

**Issue by genbaguettson** [caolan/async#1666]
**What version of async are you using?**
Async version 3.0.1

**Which environment did the issue occur in (Node version/browser version)**
Node v8.16.0 with Typescript v3.5.1

**What did you do? Please include a minimal reproducable case illustrating issue.**
Tried to use the example in [https://caolan.github.io/async/v3/docs.html#whilst](the documentation):
```
var count = 0;
async.whilst(
    function test(cb) { cb(null, count < 5;) },
    function iter(callback) {
        count++;
        setTimeout(function() {
            callback(null, count);
        }, 1000);
    },
    function (err, n) {
        // 5 seconds have passed, n = 5
    }
);
```

**What did you expect to happen?**
The program should pass 5 times through the `iter` function, then exit.

**What was the actual result?**
The function either does not transcompile from TS to JS because of wrong types, or when corrected (meaning the `test` function takes no callback and returns a boolean), just hangs after the first execution of `test`.

I think this comes from the types description, as `whilst` (and it seems `until`) is exported like so:
```
export function whilst<E = Error>(test: () => boolean, fn: AsyncVoidFunction<E>, callback: ErrorCallback<E>): void;
```

I don't know if Async is supposed to be used with Typescript, but I haven't found a resource stating otherwise on the internet.

**Comment by aearly** [comment]
We don't maintain the TS definitions, and yes, they are out of date as of v3.0.  You have to take the issue up with DefinitelyTyped.

**Comment by mattroot87** [comment]
@aearly , did you find a workaround for this? Using the latest async version and the TS definitions will not let me use the updated code below:

async.whilst(
      (cb) => { cb (null, true) }
      (callback) => { callback(); }
      (error) => { console.log('Done'); });

Thanks for any feedback you can give me!
