### ISSUE TITLE
.drain() not being reached on large list of file download tasks

### ISSUE THREAD

**Issue by joemanfoo** [caolan/async#1669]
**What version of async are you using?**
"async": "^3.0.1",

**Which environment did the issue occur in (Node version/browser version)**
v10.15.3 (testing on windows , but also see same issue on GAE environment)

**What did you do? Please include a minimal reproducable case illustrating issue.**
https://gist.github.com/joemanfoo/eeb617bfe43179ab3ce1907bca065a19

[Gist above requires: 
`const async = require('async');`
`const Axios = require('axios');`
]
[You'll want to have a `/tmp/test/` folder created before running the gist]
**What did you expect to happen?**
Expect that `await downloadQueue.drain();` would fire

**What was the actual result?**
Queue gets almost finished and then "hangs" with some `X` remaining number of remaining tasks to be completed.  `X` seems somewhat dependent on the size of the concurrence number.

With the concurrency set to 10 in the gist, my execution only reached to about 357 items left to be processed in the queue. When concurrency is 100 then the queue gets closer to zero. The number of files to download doesn't really matter unless we're looking at around 50 or so files, then the queue seems to complete A-OKAY...but bumping it down in half, still sees that the queue doesn't reach `.drain()`.

I'm 99.9999% sure this is likely something in my code because y'all are way smarter than I. I do know 100% there's a bug, just not sure where ;)

I would post this to SO for help but want to keep this on as much of a 'down low' as I can if at all possible. Thanks.

Here's some of the output from test:
```(10 / 374) downloaded: Standard-b--Leggings-TC-CuPjqiKJhR0mZQZkN4nGg.png
(10 / 373) downloaded: Standard-b--Leggings-TC-Ako4z0fX0jNoG8OIVyzOdw.png
(10 / 372) downloaded: Standard-b--Leggings-TC-77lIzkePap8lz8mUlciZw.png
(10 / 371) downloaded: Standard-b--Leggings-TC-5Tkix5r39tEa16Y9bAA.png
(10 / 370) downloaded: Standard-b--Leggings-TC-6eDHtcK1UA5vGydXgV1ecQ.png
(10 / 369) downloaded: Standard-b--Leggings-TC-jlO91IlYHOYJ0Q3MbqAA.png
(10 / 368) downloaded: Standard-b--Leggings-TC-g4bhciiEbbkIsE7RWDG3WA.png
(10 / 367) downloaded: Standard-b--Leggings-TC-rhQ6uS7QarIlIgew3XL3vQ.png
(10 / 366) downloaded: Standard-b--Leggings-TC-HRU7w08pShXSOxfFILD2fg.png
(10 / 365) downloaded: Standard-b--Leggings-TC-nYp8uhPwKdwTYQRYzOp2A.png
(10 / 364) downloaded: Standard-b--Leggings-TC-5AMHzvCrCKZpI1QVIOdqQ.png
(10 / 363) downloaded: Standard-b--Leggings-TC-LMELzzpJ6EwWflp4iXnMJQ.png
(10 / 362) downloaded: Standard-b--Leggings-TC-quou9I198dKReEdwAcHVlg.png
(10 / 361) downloaded: Standard-b--Leggings-TC-Zpl6AhUvPeTDYNTIPimMg.png
(10 / 360) downloaded: Standard-b--Leggings-TC-2McLOST49OSc73P19my0Ag.png
(10 / 359) downloaded: Standard-b--Leggings-TC-m9Al5puT4KRop0z5xZiYUQ.png
(10 / 358) downloaded: Standard-b--Leggings-TC-miWZ2F8LMOzHr04qm081QQ.png
(10 / 357) downloaded: Standard-b--Leggings-TC-OXWGOJrPHYfv79hGkAuA.png
```
Here's relevant part of code that's linked in the gist.
```
const fs = require('fs');
const async = require('async');
const Axios = require('axios');

const base = 'https://storage.googleapis.com/ezfficient.appspot.com/';
const downloadFile = (task, callback) => {
    
    const localFile = '/tmp/test/' + task.filePath.split('/')[3];
    const url = base + task.filePath;
    const writer = fs.createWriteStream(localFile);
    return Axios({
        url,
        method: 'GET',
        responseType: 'stream'
    })
    .then (response => {
        response.data.pipe(writer);
        console.log(`(${downloadQueue.running()} / ${downloadQueue.length()}) downloaded: ${task.filePath.split('/')[3]}`);
        writer.on('finish', callback);
        writer.on('error', callback);
    });
}

const downloadQueue = async.queue(downloadFile, 10);

(async () => {
    files.forEach(file => downloadQueue.push({filePath: file}));
    await downloadQueue.drain();
    console.log('downloadQueue is drained.');
})();
```

**Comment by aearly** [comment]
I think you need to handle errors in the Axios promise.

I'd also suggest that `eachLimit` might be a better method than `queue` for your use case.

**Comment by joemanfoo** [comment]
Hi @aearly - there were no errors in the Axios promise but I understand whatcha were saying. The gist was a minimal working example of the issue. And the issue likely was/is the `async` within the `forEach`. Per this write-up https://zellwk.com/blog/async-await-in-loops/, `async` doesn't work in loops that take a callback all that well.

I went a different route than to use `async` package so perhaps I'll look into the `eachLimit` next time. I thought I'd write this note and pass along the above link in case someone else walks into the `async in a loop` issue.

**Comment by fosteman** [comment]
Having similar problems with uploading a ~1500 tasks using `parallelLimit` set to 2. 
It just hangs somewhere in between 700-999. 

Looking for other threads in the repo that resemble the issue. Any ideas folks ?
