### ISSUE TITLE
async.queue callback is called before the async task is complete.

### ISSUE THREAD

**Issue by TOPSinfo** [caolan/async#1671]
```js
var que = async.queue(async function({id}, callback) {
   
  const res = await fetchData(id);
  callback(res);

}, 2);
```

`let res = await que.push({id});
// res is undefined here

With the latest update async@3.0.1 How this will work? Can you please provide some example for this?

**Comment by aearly** [comment]
You can't use callbacks with `async` functions  passed into Async.  Just return a value:

```js
var que = async.queue(async function({id}) {
   
  const res = await fetchData(id);
  return res;

}, 2);
```
