### ISSUE TITLE
handlePromise creates new Error object if it does not determine if the err passed to it is an error.

### ISSUE THREAD

**Issue by jongrubb** [caolan/async#1672]
**What version of async are you using?**
3.1.0

**Which environment did the issue occur in (Node version/browser version)**
node 8.9.3

**What did you do? Please include a minimal reproducable case illustrating issue.**
The way I handle errors in my project is like so...

```
throw {
  "err": new Error("This is my error.")
,"additionalInfo": "foo"
,"additionalInfo2": "bar"
}
```
I have been using the new async/await promise interface.  When throwing the above object, async does a couple checks on the err thrown to see if it's essentially a JS Error class object.  See async.js#169 for handlePromise() function. 

`invokeCallback(callback, err && err.message ? err : new Error(err));`

Reproduction Example:

```
const async = require('async');

let arr = [1,2,3];

async function myAsyncFunction(){
    await async.eachOf(arr, async function(a){
        throw {
            err: new Error("This is my error.")
            ,additionalInfo: "foo"
            ,additionalInfo2: "bar"
        }
    });
}

myAsyncFunction()
.then(function(){
    console.log("in then");
})
.catch(function(err){
    console.error(err);
});
```

**What did you expect to happen?**
I expected that my error object would bubble up and not be modified by the async library.

**What was the actual result?**
The async library ends up creating a new Error.  With the output to console.error() looking something like this.

```
Error: [object Object]
    at promise.then.err (/Users/jgrubb/WebstormProjects/test/node_modules/async/dist/async.js:173:65)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

***What have I done to fix this?***
I changed the way I handle errors now.  I create a custom class that extends built in js Error class.

**Comment by aearly** [comment]
It's really non-standard to throw with a non-Error object.  I'd recommend  doing something like: 

```js
const err = new Error("This is my error.")
err.additionalInfo = "foo"
err.additionalInfo2 = "bar"
throw err
```

or use a custom Error class, as you said.
