### ISSUE TITLE
v3.1.0 queue.push does nothing after no. of tasks are complete(defined concurrency) 

### ISSUE THREAD

**Issue by TOPSinfo** [caolan/async#1674]
```
var que = async.queue(async function({id}) {   
  const res = await fetchData(id);
  return res;
}, 2);
```

```
que.push({id}, function (err, res) {
console.log('handle res');
});
```

Here concurrency is set as 2. so after first two tasks are done and if I push a new task in the queue. nothing happens. No err, even the task in also not pushed.

If I update concurrency to 5, it will perform the first 5 tasks and then it fails for the 6th task.

Do we have to clear the queue after each task is done?

EDIT: This is working correctly when i run my react project locally. But when I create the build and deploy it to production it does not move forward after defined concurrency tasks are completed.

**Comment by aearly** [comment]
I would bet your `async` functions are being compiled away in production mode.  We can't detect `async` functions that have been transpiled -- wrap them with `asyncify` to prevent this.

**Comment by TOPSinfo** [comment]
Thanks for the help.
Yes wrapping them with asyncify solved the issue but now the tasks run one after the other. provided concurrency does not matter now.

```
var que = async.queue(asyncify(async function({id}) {   
  const res = await fetchData(id);
  return res;
}, 2));
```

**Comment by afladmark** [comment]
It looks like you have the second to last `)` in the wrong place. I believe it should be:

```
var que = async.queue(asyncify(async function({id}) {   
  const res = await fetchData(id);
  return res;
}), 2);
```

That way the `2` is part of the `queue` call and not the `asyncify` call.

**Comment by aearly** [comment]
:point_up:

**Comment by TOPSinfo** [comment]
@afladmark The concurrency issue gets fixed with your solution. Thanks for that.
But it again starts the initial issue.
After the first 2(provided concurrency)  tasks are complete, it does not start the next task.
Callback to any of the completed task is not called.

@aearly Can you please reopen this issue.

**Comment by aearly** [comment]
`async` functions shouldn't use callbacks.

**Comment by TOPSinfo** [comment]
@aearly Even if I don't rely on the callback. If the concurrency is 2 then the third push doesn't work. It only happens in the React production build. The local environment works all good.

**Comment by TOPSinfo** [comment]
Ok. This is works for me now.
The issue was the fetchData method was not returning any value in one of the many possible cases.
