### ISSUE TITLE
async.timesLimit returns undefined vs. the expected promise

### ISSUE THREAD

**Issue by AdamBD** [caolan/async#1676]
**What version of async are you using?**
Latest

**Which environment did the issue occur in (Node version/browser version)**
`v9.2.0`

**What did you do? Please include a minimal reproducable case illustrating issue.**
`let async = async.timesLimit(...,...,...)`

**What did you expect to happen?**
To receive the `promise` object.

**What was the actual result?**
This function call returns `undefined` instead of the expected `promise`

I had to switch back to `v3.1.0` to solve this.

Also FYI its weird that the latest version number is lower than previous ones. Why is that?

**Comment by aearly** [comment]
Ah, thanks for pointing this out!  I forgot to move the dist-tag after publishing a patch for 2.x.
