### ISSUE TITLE
Same JSDoc theme name but multiple templates

### ISSUE THREAD

**Issue by amruta-pani** [caolan/async#1677]
I wanted this template which is used in async docs but when I install this I get a different layout and apparently there exists another theme with same install instructions. What should I do to get your layout theme

**Comment by amruta-pani** [comment]
I guess I need to clone this and install it?

**Comment by aearly** [comment]
Our JSDoc theme is heavily customized -- you'd need to clone it and run the script that combines the generated output into one page.
