### ISSUE TITLE
Add documentation for thenables

### ISSUE THREAD

**Issue by BehindTheMath** [caolan/async#1683]
I discovered after some trial and error that while thenable objects are not supported out of the box, they are supported by `async.asyncify()`, since it checks for `.then()` instead of if it's an instance of a `Promise`. This is an example of a situation where you would need to use `async.asyncify()` even in an environment that natively supports async functions.

I came across this when using the [Knex QueryBuilder](http://knexjs.org/#Builder), which returns a thenable, not a `Promise`.

**Comment by aearly** [comment]
This is [already documented](http://caolan.github.io/async/v3/global.html), but the discoverability on the docs site isn't that great.

**Comment by aearly** [comment]
I added a link higher up in the intro docs.
