### ISSUE TITLE
Export variable in async.call functions

### ISSUE THREAD

**Issue by Wsine** [caolan/async#1691]
**What version of async are you using?**
3.1.0

**Which environment did the issue occur in (Node version/browser version)**
node 10.16.3

**What did you do? Please include a minimal reproducable case illustrating issue.**
```js
// file_a.js
var a = require('file_b.js');
console.log('str = ', a.str);
// file_b.js
const async = require('async');
async.waterfall([
...
], function(err, result) {
  exports.str = result;
});
```

**What did you expect to happen?**

I expect the output is `str = hello world`

**What was the actual result?**
It is `str = undefined`

I searched for so many solutions. But I could not find one workable.

**Comment by aearly** [comment]
This wouldn't work because require is synchronous.  `exports.str` isn't assigned until a later tick in the event loop.

**Comment by Wsine** [comment]
yep, i know that now. but sometimes we need a common module to export shared variables to other modules. how could we do that with async package?

Or the problem could be 

```js
async.waterfall([
...
], function(err, result) {
...
});

console.log('hello world');
```

how could we make sure that the console log will be executed after any async.call? except that all the code need to be put into async.call functions.

**Comment by aearly** [comment]
Look up how `async`/`await` works in JS.  You can't do that with a synchronous function, but you can with promises and async/await.
