### ISSUE TITLE
async.size()

### ISSUE THREAD

**Issue by LuisRodriguezLD** [caolan/async#1692]
### Hello. 
Looking into `undescore.js` they have a method that returns the number of objects in an list

```js
_.size(list)
Return the number of values in the list.

_.size([1, 2, 3, 4, 5]);
=> 5

_.size({one: 1, two: 2, three: 3});
=> 3
````

I can make a pull request implementing this, but what do you all think? worth a shot or you think this library is not for that?

or maybe, there's already a way to return the number of values (?)

**Comment by aearly** [comment]
Sorry, but I dont think this fits the library.  There's nothing really asynchronous about counting the elements in a collection.  You always can `const size = require('lodash.size')`.

**Comment by LuisRodriguezLD** [comment]
Makes sense. That’s ok. 
Thank you for this amazing library.
