### ISSUE TITLE
Missed callback detection

### ISSUE THREAD

**Issue by gregory-h** [caolan/async#1693]
This is a general question about methods to diagnose scenarios in which an async based waterfall or other control flow does not complete. 

Background is that we have a Job framework periodically running job definitions, which are just AMD modules exposing a method that executes an async based control flow, and over time we're noticing that some of these jobs sometimes do not complete - they do not crash or otherwise fail - they simply never report success or failure - and the circumstances are not directly repeatable but seem to depend on external factors like network or database load etc. 

Our working hypothesis is that there is some error pathway in our job definition in which a callback is never called etc, and I'm looking for techniques or any built in facilities that might help diagnose these scenarios, ie is there anything like a waterfall or other control flow timeout option etc?

**Comment by aearly** [comment]
The only way I've found to diagnose things like this is to use a timeout -- there is `async.timeout` which you can use to wrap steps that might never call callbacks.

**Comment by gregory-h** [comment]
ah I wasn't aware of async.timeout but that sounds like exactly what I need - thx.
