### ISSUE TITLE
applyEachSeries is not working since 3.0.0

### ISSUE THREAD

**Issue by axi92** [caolan/async#1694]
**What version of async are you using?**
3.1.0
**Which environment did the issue occur in (Node version/browser version)**
v8.16.2
v10.15.3
v10.15.1
**What did you do? Please include a minimal reproducable case illustrating issue.**
```js
const async = require('async');
function one(arg1, arg2, callback) {
  console.log('one');
  return callback();
}
function two(arg1, arg2, callback) {
  console.log('two');
  return callback();
}
async.applyEachSeries([one, two], 'argument 1', 'argument 2', function finalCallback(err) {
  console.log('done');
});
```
**What did you expect to happen?**
Output should be:
```
one
two
done
```
**What was the actual result?**
No output

Versions that did not work:
v3.1.0
v3.0.1
v3.0.0

Did work in:
v2.6.3
v2.6.2

**Comment by aearly** [comment]
The signature for `applyEach` changed a bit in v3.  Now you need to:

```js
async.applyEachSeries([one, two], 'argument 1', 'argument 2')(function finalCallback(err) {
  console.log('done');
});
```

**Comment by docteurzoidberg** [comment]
> 
> 
> The signature for `applyEach` changed a bit in v3. Now you need to:
> 
> ```js
> async.applyEachSeries([one, two], 'argument 1', 'argument 2')(function finalCallback(err) {
>   console.log('done');
> });
> ```

exemple code doesn't work either witch current 3.2.0. callback undefined
cool my stuff not work anymore and i don't find why
