### ISSUE TITLE
waterfall passes function onlyOnce on tasks calling callback()

### ISSUE THREAD

**Issue by pjbrinck** [caolan/async#1696]
**What version of async are you using?**
2.6.1

**Which environment did the issue occur in (Node version/browser version)**
Node.js 10.15.3

**What did you do? Please include a minimal reproducable case illustrating issue.**

```js
cradle.async.waterfall([(next) => {
		console.log(1);
		next(null, 2);  
	}, (a, next) => {
		console.log(a);
		next(null, 3);  
	}], (err, b) => {
		console.log(b);
	});
```
outputs
1
2
3

```js
cradle.async.waterfall([(next) => {
		console.log(1);
		next(null, 2); 
	}, (a, next) => {
		console.log(a);
		next(); 
	}], (err, b) => {
		console.log(b);
	});
```
outputs
1
2
undefined

```js
cradle.async.waterfall([(next) => {
		console.log(1);
		next(); 
	}, (a, next) => {
		console.log(a);
		next(null, 3);  
	}], (err, b) => {
		console.log(b);
	});
```
outputs
1
[Function]

and throws the error "TypeError: next is not a function"

**What did you expect to happen?**

On that last of three code examples, I expected output
1
undefined
3

In general, I expected that tasks can receive implicit undefined just as the finalCallback can receive implicit undefined.

Is this caused by the fact that we cannot read the next task prototype (list of params) and construct a series of undefined + callback?

**What was the actual result?**

as stated above

**Comment by aearly** [comment]
This is expected -- the arity of the next function in a waterfall is expected to match the number of non-error values passed to the previous function's callback.
