### ISSUE TITLE
Async Queue has issue and become slow after long run of tasks

### ISSUE THREAD

**Issue by lordlaw** [caolan/async#1698]
**What version of async are you using?**
Latest

**Which environment did the issue occur in (Node version/browser version)**
Node Version

**What did you do? Please include a minimal reproducable case illustrating issue.**
Generate huge task into Async Queue, with async type process function.
it somehow become slow down when processing.
1. running for 1440 job for first time, 20 minutes, reboot
2. running for 1440 job for second time, 20 minutes, no reboot
3. running for 1440 job for third time, 2 hours

**What did you expect to happen?**
it should took 20 minutes for 1440 jobs constantly

**What was the actual result?**
1. running for 1440 job for first time, 20 minutes, reboot
2. running for 1440 job for second time, 20 minutes, no reboot
3. running for 1440 job for third time, 2 hours

**Comment by aearly** [comment]
Is this using the same queue object, or are you calling `async.queue()` multiple times?  Really hard to diagnose with the info given here.

TBH, I'd recommend a different system if you need a durable, long-running queue system.
