### ISSUE TITLE
NEED ParameterizedQueue and user-friendly error handler

### ISSUE THREAD

**Issue by liesauer** [caolan/async#1699]
**What version of async are you using?**
`3.1.0`

**Which environment did the issue occur in (Node version/browser version)**
`v10.15.3`

**What did you do? Please include a minimal reproducable case illustrating issue.**
considering this
```js
const queue = require('async/queue');

var q = queue(function(task, callback) {
    console.log('executing ' + task.name);
    function doSomething() {
        return {
            status: 0,
            message: "success",
            others: {},
        };
    }
    var result = doSomething();
    callback(result);
}, 2);

q.error(function(error, task) {
    console.error(`error: ${task.name}: ${error}`);
});

q.push({name: 'foo'}, function(result) {
    console.log(`finished processing done, status: ${result.status}`);
});

```

**What did you expect to happen?**
1. can pass anything to callback
2. stop global error handler if i had handled in a specific callback
3. callback can handle error and result that are passed from worker

**What was the actual result?**
```
executing foo
finished processing done, status: 0
error: foo: [object Object]
```
worker can not pass result to callback, it will treat as an error! and once i create a global error handler, i cannot stop it in my callback like this
```js
q.error(function(error, task) {
    console.error(`unhandled error occur: ${error} in ${task.name} task.`);
});

q.push({name: 'foo'}, function(result, error) {
    if (error) {
        console.log("error");
        // return false or return error even throw new Error()
        // return false;
        // return error;
        throw new Error(`something unexpected happened: ${error}`);
    }
    console.log(`finished processing done, status: ${result.status}`);
    // return true means everything is ok, everything is handled.
    return true;
});
```

**Comment by aearly** [comment]
Sorry, but what you propose breaks the conventions of how callbacks are used.  The first argument to a callback is always an optional error, and return values in callback functions are typically ignored.

Calling `q.kill()` in your global error handler probably does 90% of what you want, if I understand correctly.
