### ISSUE TITLE
pause / resume / abort etc.

### ISSUE THREAD

**Issue by pnico** [caolan/async#17]
It would be nice to have a generalized way of controlling groups of async tasks, possibly using a return value from async api functions:

```
 var parallelController = async.parallel([  
    function(){ ... },
    function(){ ... }
 ], callback);

 var seriesController = async.series([  
    function(){ ... },
    function(){ ... }
 ]);

 var someEmitter = new SomeEmitter();

 someEmitter .on('stopEverything', function () {  
   parallelController .abort(); // if finished, does nothing
   seriesController .abort();
 }

 someEmitter .on('oneMoreThing', function () {  
   seriesController.append( [function(){..}, function(){..}] ) //if finished, start new tasks
 }
```

Might also be nice for such a value to be queueable like a function, like this:

```
 seriesController = async.series([  
    function(){ ... },
    function(){ ... }
 ]);

 seriesController.pause();

 someEmitter.on('okGo', function() {  
  async.parallel([
    function(){ ... },
    seriesController,
  ], callback);
  seriesController.resume();
 }
```

I realize this is all pretty vague, and appending etc. wouldn't work for some things like waterfall, but I've found these kinds of things useful in similar async frameworks in other environments.

**Comment by mderazon** [comment]
`abort()` might make sense with `retry()`

For example, if I try a 3rd party service and it responds with 404, there's no need to retry probably
