### ISSUE TITLE
Don't redefine property "name"

### ISSUE THREAD

**Issue by binarykitchen** [caolan/async#1700]
Happens in your latest version:

```
Uncaught TypeError: Cannot redefine property: name
```

Debugged it in the raw, compiled ES5 code and found the cause:

```
return Object.defineProperty(awaitable,"name",{value:"awaitable(".concat(asyncFn.name,")")})
```

The name property has been set without `configurable: true` and is being redefined again when another code requires the same file. I'd consider adding `configurable: true`. See: https://stackoverflow.com/questions/25517989/why-cant-i-redefine-a-property-in-a-javascript-object

(Sorry for not following the issue template but this is simple.)

**Comment by binarykitchen** [comment]
Can somebody look at this please? It's getting serious, happening every hour on my production site.

Or would you accept a PR of mine?

**Comment by binarykitchen** [comment]
Ping @karataev @aearly ???

**Comment by karataev** [comment]
@binarykitchen Sorry, I'm not a maintainer and can't help you

**Comment by binarykitchen** [comment]
@karataev but i see you made some recent commits?

**Comment by karataev** [comment]
@binarykitchen As far as I remember, it was just a pull request with documentation fix

**Comment by binarykitchen** [comment]
okay, i hope @aearly will comment

**Comment by binarykitchen** [comment]
Alright, here's a PR https://github.com/caolan/async/pull/1701

**Comment by aearly** [comment]
Published in `v3.1.1`

**Comment by binarykitchen** [comment]
@aearly Unfortunately it is still happening in the latest version. Can you reopen this ticket?

**Comment by binarykitchen** [comment]
I guess this happens with some exotic user agents like

```
"userAgent": "Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19"
```

**Comment by binarykitchen** [comment]
Also I do not recommend having code to rely on function names because of minifiers and obfuscators trying to reduce size of reoccuring strings.

**Comment by jpcodr** [comment]
Hi, i have the same issue.  Some workaround? @binarykitchen
In my case occurs on a cordova app with Android 5.0:
```json
"userAgent": "Mozilla/5.0 (Linux; Android 5.0; Google Nexus 5 - 5.0.0 - API 21 - 1080x1920 Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36"
```

**Comment by binarykitchen** [comment]
I dont have a workaround yet. Happens with Androids only and currently just ignoring these.
