### ISSUE TITLE
async api vice callback on waterfall do not seem to fire after first stage

### ISSUE THREAD

**Issue by jdmairs** [caolan/async#1706]
**What version of async are you using?**
3.2
**Which environment did the issue occur in (Node version/browser version)**
Node v12.14.1 on OS X
**What did you do? Please include a minimal reproducable case illustrating issue.**

export async function hello(): Promise<void> {
  console.info('hello');
}

export async function world(): Promise<void> {
  console.info('hello');
}

it('waterfall supports multiple calls to hello and world', () => {
    waterfall([
      hello,
      world,
    ]);
  });
**What did you expect to happen?**
hello prints on one line
then 
world

**What was the actual result?**

only hello prints

**Comment by aearly** [comment]
Make sure you're targeting ES2017 or higher in your `tsconfig`.

**Comment by jdmairs** [comment]
I modified target to ES2017 and our server code now prints but the Jest unit tests still do not.  Luckily I tested the node app itself.

I noticed your unit tests do not test es2017 async functions.  Any idea on why Jest wouldn't work?

I'm not using babel but we are using typescript v3.6.2

**Comment by aearly** [comment]
Jest might have its own TS configuration that is overriding your main config.
