### ISSUE TITLE
Await async.each with async function as parameter

### ISSUE THREAD

**Issue by Crodaycat** [caolan/async#1716]
I can't await async.each with async function as parameter.
Is there a way to achieve this?

**What version of async are you using?**

3.1.0

**Which environment did the issue occur in (Node version/browser version)**

Node v10.16.0

**What did you do? Please include a minimal reproducable case illustrating issue.**

```
console.log('Hello');

await async.each(array, async(item) => {
    await asyncFunction1(item);
    await asyncFunction2(item);
});

console.log('Hello 2')
```

**What did you expect to happen?**

```
Hello
Hello2
```

**What was the actual result?**

```
Hello
```

**Comment by aearly** [comment]
Are you using any sort of compiler, e.g. Babel, Typescript?

**Comment by Crodaycat** [comment]
Yes, i'm using react native with Expo, so i'm using Babel.

**Comment by aearly** [comment]
Make sure it's targeting at least ES2017 for the server code, and keeping `async` functions as-is.

**Comment by Crodaycat** [comment]
It seems to by a bad error catching. Thanks
