### ISSUE TITLE
callback function of asyn.each iteration is undefined

### ISSUE THREAD

**Issue by landoyjx** [caolan/async#1718]
my code is as follow.

```js
var transactions = ["1", "2", "3"]
async.each(transactions, async function(tx, callback) {
  console.dir(tx);
  console.dir(callback)
}, function(err) {})
```

the callback function is undefined

node v14.3.0
npm 6.14.5
ubuntu 18.04

**Comment by aearly** [comment]
`async` functions don't get passed a `callback` -- return a value, or throw an exception.
