### ISSUE TITLE
What to use to asyncify a for loop (and limiting the concurrent operations)?

### ISSUE THREAD

**Issue by skeddles** [caolan/async#1719]
I am trying to do an async version of a for loop which is looping through pixels (so lots of iterations), and skipping 3 each time (as pixels each have 4 values).

`for (var i - 0; i < pixels.length; i+=4) {}`

eachOfLimit almost works, but if I input the pixels array as the collection, it does i++ each time rather than i+=4.

I tried using timesLimit, which was perfect as it ran the right number of times (pixels.length/4), and limited how many ran at once, except that it accumulates the results (even when the result is undefined / null), and I need the result from the last loop.

So then I tried doing it with doUntil, which is perfect even at the end as it just returns the last result, except now I'm exceeding the maximum call stack size (which makes sense because it can be potentially millions of iterations). 

Am I missing a method that can do this, or does anyone have an idea of how to impliment it?

**Comment by aearly** [comment]
I'd avoid doing an async for loop over a pixel array -- it's going to be unusably slow.

`doUntil` seems like it would work, keeping track of the index yourself, but the call stack exception leads me to believe your processing is actually synchronous, in which case a basic for loop would work (and be way faster).
