### ISSUE TITLE
Lodash dependency causes prototype pollution issue: can you use another package instead of lodash?

### ISSUE THREAD

**Issue by marcoippolito** [caolan/async#1720]
Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ vue-cli-plugin-electron-builder                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ vue-cli-plugin-electron-builder > portfinder > async >       │
│               │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1523  

https://www.npmjs.com/advisories/1523

"No fix is currently available. Consider using an alternative package until a fix is made available."

So... can you use another package instead of lodash?

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
       Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm

    async@2.6.3

Marco

**Comment by moo1210** [comment]
A fix is now available, just update to version 4.17.19 or later

**Comment by aearly** [comment]
Upgrade, or ignore this warning.  We don't use the affected lodash methods.
