### ISSUE TITLE
It should push data even it is paused?

### ISSUE THREAD

**Issue by mherrera05** [caolan/async#1721]
**What version of async are you using?**
3.2.0

**Which environment did the issue occur in (Node version/browser version)**
v11.6.0

**What did you do? Please include a minimal reproducable case illustrating issue.**
I have a queue:
```javascript 
const queue = async.queue(async (task, callback) => {
  console.log('task name: ' + JSON.stringify(task.value.toString()));
  // call callback
}, 10)

// when queue is drain I want to pause it to let it load more data from kafka consumer
queue.drain(() => {
  queue.pause()
  consumer.consume(20)
})

//when queue has reached limit start to process
queue.saturated(() => {
  queue.resume()
})

// I give queue to kafka consumer to push data to it
consumer.on('data', async function (m) {
  console.log('message taken')
//flow get stuck here because a paused queue stops push data, it never get saturated to call queue.resume()
  queue.push(m, (error, result) => {
    console.log('message pushed')
    if (error) {
      // console.log('error pushing: '+ JSON.stringify(error))
    }
  })
})
```

**What did you expect to happen?**
I expect use resume() and pause() as control structure. I try to take message from kafka with a rate based on queue limitation and prevent it collapse.

**What was the actual result?**
The actual result does not let the queue push message to itself while it is stopped. I understand paused mode could refer to worker process. However, the behavior let the queue load one more message and dispatch it calling drain() again, which it is no efficient, because it starts calling drain per message.

**Comment by aearly** [comment]
There's no need to pause the queue once it drains.  It'd be empty and nothing processing to pause.
