### ISSUE TITLE
Async 3.2.0 queue.drain() is never invoked

### ISSUE THREAD

**Issue by pineshmenat** [caolan/async#1722]
I am facing this issue since last one week and banging my head on this. queue.drain() is never called even after all the tasks are completed for that queue. 

I tried the same code with async 2.6.0 and it worked amazingly, without any code change just version downgrade.

For security reason I cannot share my code but believe me this issue is there for sure.

**Comment by aearly** [comment]
I can't really help without some example code.

**Comment by Ndpnt** [comment]
I also have the a similar issue with the version `3.2.0`. 
When I use `await queue.drain()`, it is immediately resolved, whereas if I downgrade to `3.1.0`, `await queue.drain()` is properly waiting for my queue to be empty before resolving.

**Comment by Firas1993** [comment]
the same with me, async.eachLimit is no more executed ? os there any problem with the package

**Comment by aearly** [comment]
Please give an example of code that isn't working.  I can't help otherwise.

**Comment by Firas1993** [comment]
I downgrade the async version to 2.6.0 and it works, 
```
await async.eachLimit(
    productsList,
    (product) => {
       updateProductByDate(product);
    },
    (err) => {
      if (err) {
        console.log("err in product list refresh ");
        throw new Error({ err });
      }
    }
  );
```

**Comment by aearly** [comment]
Several issues here:

- Missing the `limit` parameter
- There's nothing asynchronous about that code -- the iterating function doesn't use a callback or isnt `async`.
- `async.eachLimit` now returns a Promise if there's 3 parameters (i.e. no callback), so you're actually `await`ing a promise that never resolves.

If `updateProductByDate` isn't asynchronous, you're better off just doing:

```js
productsList.map(product => updateProductByDate(product))
```

**Comment by szabi84** [comment]
> I am facing this issue since last one week and banging my head on this. queue.drain() is never called even after all the tasks are completed for that queue.
> 
> I tried the same code with async 2.6.0 and it worked amazingly, without any code change just version downgrade.
> 
> For security reason I cannot share my code but believe me this issue is there for sure.

For me the example in this documentation (for v3.2.0) works correctly. 
https://caolan.github.io/async/v3/docs.html#queue
