### ISSUE TITLE
Reduce Signature Should Match Javascript Reduce

### ISSUE THREAD

**Issue by machineghost** [caolan/async#1728]
**What version of async are you using?**

None; I chose not to use this library because re-inventing the wheel (in this case, the signature of "reduce") makes a library needlessly confusing, and that scared me away.

**What did you do? Please include a minimal reproducable case illustrating issue.**
(**NOTE:** You misspelled "reproducible" in your issue template.)

From the docs:

    async.reduce([1,2,3], 0, function(memo, item, callback) {

A Javascript reduce doesn't look like that; it looks like this (note that the initial value comes at the end):

    [1,2,3].reduce(function(memo, item, callback) {}, 0);

Of course you have to take the array as an argument ... but you could still do that and otherwise be consistent with the Javascript API:

    async.reduce([1,2,3], function(memo, item, callback) {}, 0);

Unless you're worried about people reducing with a function as an initial value, you could even fix this without breaking any code, by simply checking whether the 2nd arg is a function, and if it isn't only then treating it as the initial value.

**What did you expect to happen?**

I expect reduce in a library to work the same as reduce in Javascript, modulo any differences that *must* exist (ie. taking the array as an argument)..

**What was the actual result?**

If I use this library it's like going back to jQuery or something (which had $.forEach and $.map), where I had to memorize weird new ways to do basic things I already know how to do.

**Comment by aearly** [comment]
It's not worth doing a breaking change for this -- been this way for years.  Sorry that the documented call signature was confusing and scary.
