### ISSUE TITLE
queue.drain() invoked even when there are pending tasks

### ISSUE THREAD

**Issue by Heedster** [caolan/async#1729]
**What version of async are you using?**
3.2.0

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**
Babel. I used the async package, but the bug seems to exist in async-es as well. 

**What did you do? Please include a minimal reproducible case illustrating issue.**
push an empty array, and then array(s) with task, and then wait for queue to drain.

Here is a sample code:
```js
import { queue } from "async-es";

const createTask = () => {
  return {
    doIt: () => {
      return new Promise((r) => setTimeout(r, 2000));
    }
  };
};

const createQueueAndProcess = async () => {
  const q = queue(async (task, callback) => {
    await task.doIt();
    console.log("task done");
    callback();
  });

  //Comment the empty array push line below
  // and see the issue go away
  q.push([]);
  q.push([createTask()]);

  await q.drain();
  console.log("all tasks completed");
};

createQueueAndProcess();
```

Code sandbox link: https://codesandbox.io/s/async-queue-issue-mqxo5

**What did you expect to happen?**
Complete the one task that was pushed and then call drain. So the console will say

```
task done
all tasks completed
```

**What was the actual result?**
drain is exited (event emitted) before the task getting completed. 

```
all tasks completed
task done
```

If you remove that empty array, things get fixed. In real world, I got this issue when I was calling functions for getting tasks to upload any pending files to the server, and some of the functions returned empty arrays. 

I did some digging around the internal/queue.js, and I think the issue is because of _maybeDrain and the setImmediate inside it. I understand the reason behind the code, but this is what is likely happening
- pushed empty array
- we are not doing anything, we should emit drain, schedule it.
- actual things pushed. (setImmediate still have not emitted the drain)
- this time we are not emitting coz we have actual work. 
- waiting for drain. 
- setImmediate now sees next tick, and calls the drain, which was supposed to be emitted long before.

**Comment by der-kommissar** [comment]
I think I ran into something similar. In my case, it works when I run from source, but when I pack the module with `npm pack` and run the executable, it does not work.

Here's my test code:
```TypeScript
import * as Async from 'async';

class DriverQ {
    public async queueTasks (tasks: string[]): Promise<string[]> {
        const results: string[] = [];
        const queue = Async.queue(async (task: string, callback) => {
            console.log(`Queue driver for task ${task}`);
            const res = await this.runTask(task);
            results.push(res);
            callback();
        }, 2);
        queue.push(tasks);
        console.log("await queue");
        await queue.drain();
        console.log("after queue drain");
        return results;     
    }

    async runTask(task: string): Promise<string> {
        console.log(`run task ${task}`);
        const runTaskPromise = new Promise<string> ((resolve) => {
            setTimeout(() => {
                resolve(task ? "processed " + task : "task: " + task);
            }, 1500);
        });
        return runTaskPromise;        
    }
}

async function runDriver (items: string[]): Promise<string[]> {
    const driver = new DriverQ();
    return await driver.queueTasks(items);
}

async function main () {
    const items: string[] = [ "item1", "item2" ];
    console.log('start main');
    console.log(await runDriver(items));
    console.log('end main');
}

main();
```
Output when running from source (as expected):
```
start main
await queue
Queue driver for task item1
run task item1
Queue driver for task item2
run task item2
after queue drain
[ 'processed item1', 'processed item2' ]
end main
```
Output when running from packed executable:
```
start main
await queue
after queue drain
[]
end main
Queue driver for task item1
run task item1
Queue driver for task item2
run task item2
```

**Comment by aearly** [comment]
```js
const q = queue(async (task, callback) => {
```

You error is here.  You either use an `async` function, or a `callback`, not both at the same time.  I'd recommend

```js
const q = queue(async (task) => {
```
and simply `return`ing when you need to.

**Comment by Domiii** [comment]
@aearly That still does not fix the actual bug:

`q.push([])` is a special-case scenario that triggers an early `drain` event. But then there is more stuff added to the queue.

The problem arises because when `drain` event completes (in the `setImmediate` callback), it does not check again if the queue is indeed empty. That check should be added since there is always a chance for the queue to fill up between triggering and activating the event.

If you agree - here is a patch:

```diff
diff --git a/lib/internal/queue.js b/lib/internal/queue.js
index 2592a93..bb3e16b 100644
--- a/lib/internal/queue.js
+++ b/lib/internal/queue.js
@@ -124,7 +124,7 @@ export default function queue(worker, concurrency, payload) {
     function _maybeDrain(data) {
         if (data.length === 0 && q.idle()) {
             // call drain immediately if there are no tasks
-            setImmediate(() => trigger('drain'));
+            setImmediate(() => void q.idle() && trigger('drain'));
             return true
         }
         return false
```

**Comment by heartforit** [comment]
Hi,

just wanted to say, the patch fixes the problem very good. It´s in my eyes not an unwanted behavior, but I think it is a bug, since meantime changes on queue no evaluated correctly.
Is this fixed anyhow?

Best

**Comment by Domiii** [comment]
@heartforit @aearly I fixed my snippet. My original snippet, for some reason, had an unwanted `void` in it. I must have added that on a hunch or something. Either way. I fixed it, tested it and it works fine now.
Also, I'd strongly recommend adding a test that tests this particular scenario.

**Comment by Domiii** [comment]
Also @aearly if you cannot accept this fix in the near future quite yet, please at least open this issue again. It is a real problem and it is sadly NOT fixed

**Comment by heartforit** [comment]
Sadly the void did work on node.js side :) Broken by design i guess.

**Comment by Domiii** [comment]
> Sadly the void did work on node.js side :) Broken by design i guess.

Remove the `void`
