### ISSUE TITLE
What's the core difference of async.map from async.each ?

### ISSUE THREAD

**Issue by gkatsanos** [caolan/async#1731]
I'm experimenting with the library and I don't see the difference between `async.map` and `async.each`. 

they both:
- apply the iteratee to each item in parallel
- have a callback that can be run on success/failure
- If iteratee passes an error to its callback, the callback is immediately called with the error

I also made a small example to try to see potential differences: 

```js
const async = require("async");
const input = [1,2,3,4,5];
function asyncMultiply(num, callback) {
  return new Promise((resolve, reject) => {
    if (num < 10) {
      callback(null, num * 2);
      return resolve(num * 2);
    } else {
      callback('error');
      return reject('error');
    }
  });
}

async.each(input, asyncMultiply, function(err) {
  if (err) {
    console.log('asyncMultiply generated an error');
  }
});

async.map(input, asyncMultiply, function(err, results) {
  console.log(results);  
});
```

**Comment by justincounts** [comment]
I believe `async.each` doesn't return the cumulative results of the iteratee `asyncMultiply` to the final callback. so in your first example you don't have the result of the multiplication.

**Comment by gkatsanos** [comment]
That is true. So I guess the only difference is that the callback function has a second argument collecting the results. That would be good to point out in the documention (if this is really the only difference in how these two work..)

**Comment by aearly** [comment]
The docs do assume some familiarity with the built-in `[...].forEach()` and `[...].map()`.  The docs could be improved here.
