### ISSUE TITLE
Error passing for async functions

### ISSUE THREAD

**Issue by aryehb** [caolan/async#1732]
https://github.com/caolan/async/blob/d589a517534ad33e6cac92108f9be603814f0996/lib/asyncify.js#L90

When an error is thrown in an async function and `err.message` is falsy, why is it wrapped in an `Error` instance? Why isn't this code simply:
```javascript
invokeCallback(callback, err);
```

I see 2 issues with wrapping in a new `Error` instance:
1.  `Error` instances don't have to have a `message` property. E.g.:
```javascript
  const e = new Error();
  e.code = 1;
```
Wrapping it in a new `Error` instance causes the custom properties to be lost:
```javascript
  const e2 = new Error(e);
  // e2.code === undefined
```
2. If a non-string value is thrown, wrapping it in an `Error` will convert it to a string.
```javascript
  const err = {};
  const e = new Error(err);
  // e.message === '[Object object]'
```

**Comment by aearly** [comment]
We have to do some form of duck typing for that object, since we need an actual Error object.  (some people were passing an error string to the callback).  `message` is the most common property on Error objects, so that's what we went with.

Use a `message` with your custom errors and things will work as intended.

**Comment by aryehb** [comment]
Thank you for your response.

>since we need an actual Error object

I'm curious why that is. I believe JS allows throwing any value.

Regardless, if an actual `Error` object is needed, why not check if `err instanceof Error`? `err && err.message` doesn't assert it's an instance of `Error`, since it could be an object with a `message` property.

>Use a message with your custom errors and things will work as intended.

We often throw errors with only codes, and look up the messages later when they need to be displayed. This might not be common usage, but I'm trying to understand why the code was written this way.

**Comment by aryehb** [comment]
@aearly I'm not sure if you saw my last post.
