### ISSUE TITLE
Types not defined for async/cargoQueue

### ISSUE THREAD

**Issue by jancel** [caolan/async#1734]
**What version of async are you using?**

3.2.0

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**

Node/Typescript

**What did you do? Please include a minimal reproducible case illustrating issue.**

import cargoQueue from "async/cargoQueue"

**What did you expect to happen?**

It would work, and have type definitions.

**What was the actual result?**

Could not find a declaration file for module 'async/cargoQueue'. '/Users/{redacted}/node_modules/async/cargoQueue.js' implicitly has an 'any' type.
  Try `npm install @types/async` if it exists or add a new declaration (.d.ts) file containing `declare module 'async/cargoQueue';`

**Comment by jancel** [comment]
I will attempt a PR here if you'd like. I went through old issues and saw a previous one closed.

**Comment by aearly** [comment]
We don't maintain the types.  You'll have to take it up with the DefinitelyTyped project.
