### ISSUE TITLE
queue.error() does not resolve when there are no errors.

### ISSUE THREAD

**Issue by joshxyzhimself** [caolan/async#1736]
**What version of async are you using?** latest

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)** node

**What did you do? Please include a minimal reproducible case illustrating issue.**

```js
      console.log('awaiting error'); // reached
      await queue.error();
      console.log('error ok'); // not reached if there are no errors
      await queue.drain();
      console.log('drain ok'); // not reached, too
```

**What did you expect to happen?**

i was expecting for `queue.error()` to resolve when there are no errors

**What was the actual result?**

no resolve

**Comment by joshxyzhimself** [comment]
Current workaround is ff:

```js

      queue.error((error) => {
        assert(error instanceof Error);
        throw error;
      });

      await queue.drain();
```

**Comment by aearly** [comment]
This is expected behavior -- if you `await` `q.error()` with no callback, it'll block that function until an error occurs.  The callback form is generally better to use for the `error` event handler.
