### ISSUE TITLE
How 'async.each' is used in recursive structures?

### ISSUE THREAD

**Issue by ljg0230** [caolan/async#1737]
I am using async version 3.2.
I am in the process of downloading a zip file of objects in the folder structure from 'typescript'.
This is the file object to be used.

```
export class FileItem {
  name: string;
  isDirectory: boolean;
  dateModified? : string;
  fullName? : string;
  size? : number;
  items? : FileItem[];
}
```
All files should be explored in this directory structure.

I used 'async module' to proceed with the work after the foreach loop is finished.

Use recursive function because folders or files may exist within a folder.

I want to call 'zip.generateAsync' only once after all 'zip.file' courses, but it calls 'zip.generateAsync' as 'eachCallback' is called... What is the problem?

```
  getZipFileDownload(item: FileItem, rootName: string) {
    let zip = new JSZip();

    this.makeZipFile(item, zip, rootName);
  }

  makeZipFile(Item: FileItem, zip: JSZip, rootName: string) {
    async.each(Item.items, (item: FileItem, eachCallback) => {
      if (item.isDirectory) {
        this.makeZipFile(item, zip, rootName);
      } else {
        this.http.get(this.rootURL + item.fullName, { responseType: 'text' }).subscribe((res) => {
          zip.file(item.fullName.split(rootName)[1], res);
          eachCallback();
        });
      }
    }, (err) => {
      if (err) console.log(err);
      zip.generateAsync({ type: 'blob' }).then((resolve) => {
        let url = window.URL.createObjectURL(resolve);
        let anchor = document.createElement("a");
        anchor.download = rootName;
        anchor.href = url;
        anchor.click();
      });
    });
  }
```

**Comment by aearly** [comment]
`makeZipFile` has no callback, when it really should have one.

Decouple `generateAsync` from the process of recursion.

**Comment by ljg0230** [comment]
> `makeZipFile` has no callback, when it really should have one.
> 
> Decouple `generateAsync` from the process of recursion.

Thank you for your answer.
I'm sorry, but is there a way to separate 'generateAsync' in the recursive process and call it after all of Async.each's processes are over?

**Comment by ljg0230** [comment]
> `makeZipFile` has no callback, when it really should have one.
> 
> Decouple `generateAsync` from the process of recursion.

Is there any problem with using Async module as it is in Typescript?
