### ISSUE TITLE
How 'async.each' is used in recursive structures?

### ISSUE THREAD

**Issue by ljg0230** [caolan/async#1738]
I'm sorry to ask you a closed question again...(#1737)

I tried many things to find an answer, but I couldn't solve it.

```
  getZipFileDownload(item: FileItem, rootName: string) {
    let zip = new JSZip();

    this.makeZipFile(item, zip, rootName);
  }

  makeZipFile(Item: FileItem, zip: JSZip, rootName: string) {
    async.each(Item.items, (item: FileItem, eachCallback) => {
      if (item.isDirectory) {
        this.makeZipFile(item, zip, rootName);
      } else {
        this.http.get(this.rootURL + item.fullName, { responseType: 'text' }).subscribe((res) => {
          zip.file(item.fullName.split(rootName)[1], res);
          eachCallback();
        });
      }
    }, (err) => {
      if (err) console.log(err);
      zip.generateAsync({ type: 'blob' }).then((resolve) => {
        let url = window.URL.createObjectURL(resolve);
        let anchor = document.createElement("a");
        anchor.download = rootName;
        anchor.href = url;
        anchor.click();
      });
    });
  }
```

Use recursive function because folders or files may exist within a folder.

I want to call 'zip.generateAsync' only once after all 'zip.file' courses, but it calls 'zip.generateAsync' as 'eachCallback' is called... What is the problem?

You said "makeZipFile has no callback, when it really should have one." to this question. but I didn't understand the reason.

I apologize if these questions were rude...

I would really appreciate it if you could give me a more accurate answer.

**Comment by aearly** [comment]
This isn't the best forum for this kind of help.
