### ISSUE TITLE
async.queue with async arrow function without callback doesn't work

### ISSUE THREAD

**Issue by pgraham** [caolan/async#1741]
**What version of async are you using?** 3.2.0

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)** Node.js

**What did you do? Please include a minimal reproducible case illustrating issue.**

```javascript
// Some code has been abbreviated for legibility

// Cleanup lingering test data
before(async () => {
  const docs = await cosmosClient.queryAll(...);

  const q = async.queue(async (task) => {
    await cosmosClient.deleteItem(task.doc.id);
  }, 10);

  q.push(docs.map((doc, idx) => ({ doc, idx })));
  await q.drain();
});
```

**What did you expect to happen?**
all documents added to queue to be processed and for test suite to continue

**What was the actual result?**
only first 10 documents are processed and then Node.js exists after a bit of time.

**Comment by aearly** [comment]
Are you using any transpilers, like Babel or Typescript?

**Comment by pgraham** [comment]
yes, Typescript

**Comment by pgraham** [comment]
Ok, I see what you're getting at. The typescript compilation is replacing the native async function with a polyfill which is causing async.queue to not recognize the working as an async function... Is that right?

**Comment by aearly** [comment]
Yep, that's correct.  If you're using a recent version of Node (> 8.x), you can probably set TS's target to preserve `async` functions/

**Comment by pgraham** [comment]
I will try that, thanks so much. for your help!

**Comment by silveoj** [comment]
I set in `tsconfig.json` (or higher)
```
    "target": "es2017",
    "lib": ["es2017", "DOM"],
```

**Comment by JaosnHsieh** [comment]
> I set in `tsconfig.json` (or higher)
> 
> ```
>     "target": "es2017",
>     "lib": ["es2017", "DOM"],
> ```

`tsconfig.json` which without specifying `target` is default to `ES3` which `async.queue` will not work as expected.
it works after set to "target": "es2017"
