### ISSUE TITLE
build es modules package in the same way as async-es

### ISSUE THREAD

**Issue by raythurnevoid** [caolan/async#1742]
**What version of async are you using?**
3.2.0

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**
- Webpack 5.17.0
- Typescript 4.1.3

Actually the package contain a dist folder with a `async.mjs` file containing all the code as es modules. Unfortunately it seems that webpack have difficulty to correctly tree shake it. In these examples i'm importing only the cargo function but in 3 different ways getting 3 different bundle sizes at the end of the compilation:

## `import {cargo} from "async"` -> **11KB**
![image](https://user-images.githubusercontent.com/53383860/105656273-23124b80-5ec2-11eb-94c0-6755c13f4072.png)

## `import cargo from "async/cargo"` -> **6.5KB**
![image](https://user-images.githubusercontent.com/53383860/105656369-5654da80-5ec2-11eb-8686-6ec62dcbfa02.png)

## `import {cargo} from "async-es"` -> **4.33KB**
![image](https://user-images.githubusercontent.com/53383860/105656533-c4010680-5ec2-11eb-8606-70d6a8aa67c3.png)

**Solution**
Obviously the async-es gives the best result.
I would suggest to compile the es-modules version exactly as the `"async-es"` package instead of generating a single `async.mjs` file.
This would be helpful since the typescript typings actually, only exist for the `"async"` package, making it difficult to use the `"async-es"` package for Typescript users.

**Comment by aearly** [comment]
I'd recommend copying the async typings for async-es.  I also hope to support typescript directly in the next major release.

**Comment by jlarmstrongiv** [comment]
A workaround for now:

```ts
declare module "async-es" {
  export * from "async";
  const namespace: typeof import("async");
  export default namespace;
}
```
