### ISSUE TITLE
queue.drain is not a function

### ISSUE THREAD

**Issue by ashmortar** [caolan/async#1746]
**What version of async are you using?**
3.2.0
**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**
Electron 10.1.4 => Node 12.16.3 => typescript 3.9.7
**What did you do? Please include a minimal reproducible case illustrating issue.**
I have tried both:

```typescript
class SomeClass {
 constructor() { 
   this.doingThingsQueue = Async.queue(this.handleProcessQueueItem, 2);
   this.doingThingsQueue.drain(() => console.log('all done' ));  
   }
   
   handleProcessQueueItem(item, callback) {
     console.log(item);
     callback();
   }
   
   processThings(items) {
     this.doingThingsQueue.push(items);
     return { success: true }
   }
}

```

and:
```typescript
class SomeClass {
 constructor() { 
   this.doingThingsQueue = Async.queue(this.handleProcessQueueItem, 2);
   }
   
   handleProcessQueueItem(item, callback) {
     console.log(item);
     callback();
   }
   
   processThings(items) {
     this.doingThingsQueue.push(items);
     this.doingThingsQueue.drain(() => console.log('all done' ));  
     return { success: true }
   }
}
```

in addition to trying to assign the function `this.doingthingQueue.drain = () => console.log('all done');`

but all situations result in each item processing but then getting the error:

**What did you expect to happen?**
`all done` to be logged in the console when the queue is empty.

**What was the actual result?**

`TypeError: this.doingThingsQueue.drain is not a function`

**Comment by ashmortar** [comment]
just as a quick follow up, this does actually appear to missing in the [queue.js](https://github.com/caolan/async/blob/master/lib/queue.js) file.  a quick search of `drain` only turns of comments.

**Comment by aearly** [comment]
Closing old issues, hope you figured it out.
