### ISSUE TITLE
eachOf doesn't work async iteratee

### ISSUE THREAD

**Issue by wa1one** [caolan/async#1751]
I just did as simple as:
```
await eachOf(arr, async(item, i) => {
return 'success';
})
```

node 16.3.0
async 3.2.0

and this never ends. 👎🏻 
The eachOf should return a Promise which is resolved or rejected! 

Some annoying stuff. What I did wrong.

**Comment by aearly** [comment]
Are you using babel or typescript or any other transpiler?

Do your configs for either preserve `async` functions?

**Comment by Hoxni** [comment]
> Are you using babel or typescript or any other transpiler?

Are there any issues with babel compatibility?

**Comment by aearly** [comment]
Does your babel setup preserve `async` functions?

**Comment by Hoxni** [comment]
The problem was in babel config, it works fine without "@babel/plugin-transform-async-to-generator" and "@babel/plugin-transform-regenerator"
`[
      "@babel/preset-env",
      {
        "exclude": [
          "@babel/plugin-transform-async-to-generator",
          "@babel/plugin-transform-regenerator"
        ]
      }
    ],`
