### ISSUE TITLE
async.whilst do not call the callback function if test function returns false on the first iteration

### ISSUE THREAD

**Issue by belivo** [caolan/async#1753]
**What version of async are you using?** 3.2.0. this was working in version 2.6.1

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)** Node 14 using typescript)

**What did you do? Please include a minimal reproducible case illustrating issue.**
```js
       async.whilst(() => { 
            return false; 
        },
            (next) => { 
                setTimeout(next, 5); 
            },
            (_err) => {
              // this is not being called
            }
```
**What did you expect to happen?**

Should haved call the callback

**What was the actual result?**

Callback is not called.

**Comment by aearly** [comment]
In 3.0 the `test` callback changed to be an async function.  Pass `false` to a callback, or make it an `async` function.
