### ISSUE TITLE
Contributing Help

### ISSUE THREAD

**Issue by jensengar** [caolan/async#1759]
Hey guys, I'm working on a pr to work around some of the throttling issues with `setImmediate` which becomes `setTimeout` in the browser. I'm having a hard time building the lib for testing though, even from a vanilla repo. What I've done:
* Checkout the repo
* install deps
* run `make`
That results in the following:
```
make: *** No rule to make target `build/all.js', needed by `build-modules'.  Stop.
```
I didn't see a contributing guide or anything like that, am I missing some setup steps?
I'm on MacOS if that makes a difference.

**Comment by aearly** [comment]
Which platform?  You might need an updated Make.
