### ISSUE TITLE
async.queue sometime not end task

### ISSUE THREAD

**Issue by vtlong** [caolan/async#1778]
What version of async are you using?
^3.2.2
Which environment did the issue occur in (Node version/browser version)
Node: >=12
npm: 6.14.11

Hi ,
I have problem with async.queue.

my example:
```
var queue = async.queue((infos, callback) => {
      var task = new MyTask(infos);
      task.on('task_done', (error) => {
           console.log('Finish processing task: ', infos.ID);
           callback();
      });
  
     tart.start();
}, 5);
```

- sometimes task doesn't remove from the queue when finished.
  I see ''Finish processing task: 12345' is printed in console, 
   but when I check the items in queue.workersList() I see item.data.ID = 12345 still exists, and never remove from queue.

Anybody help me?

Thanks!

ps: sorry for my english.

**Comment by aearly** [comment]
Need more info on the implementation of `MyTask`.
