### ISSUE TITLE
Could author provide a option to choose if use queueMicrotask

### ISSUE THREAD

**Issue by Hooho** [caolan/async#1788]
sorrry to waste your time to read my probleam, and I know my english is not good, so maybe there are some express issues, hope you could understand

I got a problem since I  update async to v3.2.1，and I checked the CHNAGELOG and debug my project for  a long long long time，and I find the reaseon is that the  package use queueMicrotask

the detail is 

I use a pkg exceljs to , ant it requires a pkg [ Archiver ], and Archiver require this pkg [async]

![image](https://user-images.githubusercontent.com/18716647/149668101-a87ade7e-a0d4-460b-aca5-367e94bbd8cd.png)
![image](https://user-images.githubusercontent.com/18716647/149668112-34adc5c1-a892-44eb-8fb1-6a6e080a3f47.png)

when I use exceljs like this

``` javascript
const wb = ExcelJS.stream.xlsx.WorkbookWriter()

.... something

ctx.body = wb.stream

``` 

I find the stream is over before I  write into all data so that the excel file is error

because in the [koa] ,it use [koa-compose] to execute middleware 

![image](https://user-images.githubusercontent.com/18716647/149668604-d0691b90-c066-4e41-9e1f-d802018e9097.png)

![image](https://user-images.githubusercontent.com/18716647/149668408-7df9edd8-2034-4a77-a9ea-a86109ee443b.png)

![image](https://user-images.githubusercontent.com/18716647/149668876-841fe138-bce4-4ed0-8784-c0b6890ec949.png)

koa-compose use Promise.then to set pipe to response 

if async use queuMicrotask, it would async.queue execute tasks before koa set body ok , because queueMicrotask is quickly then promise 

if async use  setImmidate is ok 

like this demo

``` javascript
function compose(fn) {
  return Promise.resolve(fn());
}

function middleware() {
  console.log("excute middleware");

  setImmediate(() => {
    console.log("middleware  setImmediate");
  });
  queueMicrotask(() => {
    console.log("middleware  queueMicrotask");
  });
}

compose(middleware).then(() => {
  console.log("link stream");
})
```

the result is  

![image](https://user-images.githubusercontent.com/18716647/149668762-817e6ed6-ccdc-4e32-b8f9-c36e920f34fb.png)

**Comment by aearly** [comment]
Personally, I feel like this is a bug in ExcellJs or archiver, since this situation relies on the precise ordering of deferrals.  One workaround to try:

```js
const wb = ExcelJS.stream.xlsx.WorkbookWriter()

//.... something
const stream = wb.stream // I assume this is a getter
await Promise.resolve() // defer to let the stream begin
ctx.body = stream
``
Or set your async dep to `~3.1.0`.
