### ISSUE TITLE
callback is undefined when passing async iteratee to async.reduce

### ISSUE THREAD

**Issue by pranav-singhal** [caolan/async#1817]
**What version of async are you using?**

3.2.0

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**

Node v10.15.1

**What did you do? Please include a minimal reproducible case illustrating issue.**

```javascript
async () => {
        let result = await async.reduce(fileList, 0, async (memo, file, cb) => {
        
            console.log(cb); // logs undefined
        
        } );
}

```

**What did you expect to happen?**

`cb` function should have been defined

**What was the actual result?**

`cb` is logged as undefined

**Comment by hargasinski** [comment]
When you pass in an async function, a callback isn't given to the function, instead the return value is used. Please see the [docs](https://caolan.github.io/async/v3/) for more info:

> Async accepts async functions wherever we accept a Node-style callback function. However, we do not pass them a callback, and instead use the return value and handle any promise rejections or errors thrown.
