### ISSUE TITLE
functions called by `async.*` return values prematurely? 

### ISSUE THREAD

**Issue by movy** [caolan/async#1842]
Not 100% certain whether it's a bug or some behaviour I cannot grasp, but it boils down to: 

A basic async function works as expected with native ES6 (in node) but the same function exits/returns after first `await` in its code when used with `async.*` constructions. Example:

## async.* scenario (very similar to an example from the docs):

```js
let dirList = ['dir1', 'dir2']
let results = await async.map(dirList, async (dir) => {
        console.log(dir, 'Before await')
        const files = await fs.promises.readdir(dir)
        console.log(dir, 'After await')
        return files
      })
console.log('results: ', results) // will be 'undefined'
```

Output:

```js
dir1 Before await
dir2 Before await
results: undefined
dir1 After await
dir2 After await
```

As you can see, `async.map` considers return after first await, and `results` are not populated, yet the function itself continues running.

## Native scenario:

```js
let dirList = ['dir1', 'dir2']
let results = await Promise.all(
      dirList.map(async (dir) => {
        console.log(dir, 'Before await')
        const files = await fs.promises.readdir(dir)
        console.log(dir, 'After await')
        return files
      })
    )
console.log('results: ', results)
  ```

Output:

```js
dir1 Before await
dir2 Before await
dir1 After await
dir2 After await
results: [ [ 'file1' ], [ 'file2', 'file3' ] ]

```

Of course, the actual function is way more complicated with multiple awaits and reassignments on the way to final `return`, but behaviour is the same. I'm not using any transpliers, just pure node js code.

I have used `async.*` extensively before and had to use `Promise` wrappers everywhere to put 'resolve/reject' in desired places and to avoid uncertainty like above. All worked as expected but readability suffered and some compromises were necessary such as `await`s inside promises.. This time around I wanted to stick to plain async/await functions, but stumbled upon this behaviour and cannot figure out what's going on here.

**Comment by MaxG2395** [comment]
I am also facing this issue. 
Have you found out whether that is indeed a bug, or something else missing?

**Comment by movy** [comment]
@aearly , thanks for following up. I'm aware of transpilers drawbacks, so I don't use them. This is plain vanilla node js code run via node.

**Comment by hargasinski** [comment]
@movy could you provide more info about your environment (what version of node you're using, what version of async, etc...)? I just tried your example locally and it worked as expected (the same as the native example).

Here is an example of it working in the browser: https://runkit.com/embed/xo52ogrvm20h

**Comment by movy** [comment]
wow, that's so bizarre, I ran your example in my node environment and it worked correctly, I also used real `fs` just to make sure, and it also worked. I swear to god, I witnessed wrong behaviour with other `async.` modules (`limit` comes to mind, as I eneded up using `p-limit` instead), I just used `map` for this particular issue as it was easy to replicate with vanilla node and display difference in behaviour. 

At this point I have no idea what was wrong at that time, I haven't updated my node version (16.3.0) or async (3.2.3) recently, so really puzzled at what was happening. 

My faith in `async` kinda restored, but the fact that I (and @MaxG2395  seems also) observed incorrect behaviour makes me worried a bit. Will keep this in mind as I'm moving ahead with this project.

**Comment by hargasinski** [comment]
I'm not sure why you would see that behaviour unless you were transpiling. If an error was occurring or the process was exiting early, you probably wouldn't see the `after wait`s being printed, so that's unlikely. I'm glad everything is working as expected now.
