### ISSUE TITLE
Is it possible to support `AsyncGenerator`

### ISSUE THREAD

**Issue by shtse8** [caolan/async#1859]
Currently, it doesn't support `IterableCollection<T>` as stated in the doc.

https://caolan.github.io/async/v3/docs.html#eachOfLimit
```ts
coll | Array \| Iterable \| AsyncIterable \| Object | A collection to iterate over.
```

I have tried to put async generator into the arg, and it's working perfect without issue except the type error.

**Comment by hargasinski** [comment]
Thanks for the report @shtse8! Could you provide an example? It seems to be working with async generators: https://runkit.com/embed/j24jjj3sg3ws

**Comment by shtse8** [comment]
This is a super amazing project in js. Hope it will support full typing in the future!
