### ISSUE TITLE
use 'async/mapLimit' in Chrome 43 has error

### ISSUE THREAD

**Issue by TrevorYS** [caolan/async#1872]
**What version of async are you using?**
 "async": "^3.2.4"
**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**
Node 14.16.1 、Chrome Version 43.0.2357.2、VueCli3、   "@vue/cli-plugin-babel": "^3.11.0"
**What did you do? Please include a minimal reproducible case illustrating issue.**

**What did you expect to happen?**

**What was the actual result?**
![mapjs-谷歌43版本报错](https://user-images.githubusercontent.com/19200800/195033783-9dddba14-7ace-4070-b003-f5b9be472262.png)

**Comment by aearly** [comment]
Chrome 43 is 7 years old, and unsupported.  It doesn't support arrow functions, so you would have to compile down to ES5.

Why are you using Chrome 43?
