### ISSUE TITLE
How to call functions to execute sequentially?

### ISSUE THREAD

**Issue by ymmeng** [caolan/async#1875]
```js
        (async () => {
          const v = await this.downVideo(video, 137, p, "mp4");
          const m = await this.downVideo(video, 140, p, "mp3");
          this.mergeMV(v, m);
        })();
```
downVideo is a function for downloading video or audio in Vue. As shown in the above code, the audio and video should be downloaded first and then the merged function should be executed, but it is always executed in advance. How can I wait for the audio and video to be downloaded before executing it? Merge function?

**Comment by 0fuz** [comment]
Hello
`let [v,m] = await Promise.all([this.downVideo(video, 137, p, "mp4"), this.downVideo(video, 140, p, "mp3")])
or
https://caolan.github.io/async/v3/docs.html#waterfall
