### ISSUE TITLE
Add adaptive functions

### ISSUE THREAD

**Issue by AlexRMU** [caolan/async#1887]
I think it would be nice to add adaptive parallelism to existing functions or create new ones.

![image](https://user-images.githubusercontent.com/61969794/206848877-1350a1e7-2245-4156-a696-837600273cb4.png)
https://netflixtechblog.medium.com/performance-under-load-3e6fa9a60581

For example:
There is a maximum, minimum, initial and current limit. There is a callback that accepts an error that occurred during the call (for example, an error related to parallelism or another error) and returns a boolean (whether to reduce the limit or not).

**Comment by aearly** [comment]
This seems like the kind of thing that is hard to get right, and hard to generalize for a low-level library such as Async. I'd encourage you to experiment with this in your own project.
