### ISSUE TITLE
Is there a way to empty the queue workersList items?

### ISSUE THREAD

**Issue by sanketdhoble** [caolan/async#1944]
Version: v3.2.0
ENV: nodeJs

We are getting unhandled rejection in a third party module which is used to process items from the queue.
Due to which we are not able to call callback() even though we have try catch added.
So the item remains in the workersList as cb is not called.
Is there a way to empty the workersList ?

**Comment by aearly** [comment]
http://caolan.github.io/async/v3/docs.html#QueueObject

`q.kill()` and create then create a new queue.
