### ISSUE TITLE
Cargo minimum payload size

### ISSUE THREAD

**Issue by gsouf** [caolan/async#1976]
Hi,

I'm trying to use a cargo queue to batch my tasks in parallel, it works well but I noticed that the cargo will trigger the worker as soon as possible, even if the payload size is not reached.

Is there a way to wait for the payload to have reached a desired minimum size before triggering the worker, and the last batch will be triggered manually ?

Thanks

**Comment by aearly** [comment]
Cargo will only process multiple items if there are multiple items queued when it looks for new items.  If you need it to only ever process it's specified payload size, you'd need additional logic around `cargo` to handle that behavior, e.g. read the current queue size, and only push to it when it's empty if you have `payload` number of items buffered.
