### ISSUE TITLE
Can you add the index of array in async.forEach and async.forEachSeries?

### ISSUE THREAD

**Issue by llevkin** [caolan/async#213]
Now async.forEach and async.forEachSeries looks like this:

async.forEachSeries(array, iterator, callback);

iterator has two arguments:

function iterator(item, callback) {}

If I need find a key (index) of item in array by value, how i can get it?
For async.forEachSeries I can declare my own varable count and increment it in the end of iterator-function, I think it not quite right, but it's possible.. For async.forEach function it's not possible to detect a key (index) of array value...( For example, how I can remove some items from array with async, if i don't know a key of value?

Maybe it makes sense to add in iterator function a third argument key (index)? Somthing like this:

function iterator(item, callback, key) {} - it's not so beauty, but useful.

Great Regards! sorry for my English.

**Comment by Markkos89** [comment]
there is an issue where you have 2 identical rows and the indexOf will throw a wrong index.... 

would be so much usefull to have and index iterator in the function..

**Comment by aearly** [comment]
`async.eachOf` and `async.eachOfSeries` will include the array index.

**Comment by knoxcard** [comment]
I came across this today, which I think is absolutely brilliant...in case you are needing the ID.
If there is something more simple than this, please let me know.

```
async.each(Object.keys(arr), function(index, cb) {
  console.log('index: ' + index)
  var item = arr[index]
  console.log(item)
}, (err, ret) {
  console.log('done')
})
```
