### ISSUE TITLE
Main callback getting called before the second task is finished for async.parallel

### ISSUE THREAD

**Issue by pvsundarram** [caolan/async#27]
I am using async.parallel and i am running two db queries in each of the task. 
I find that the main callback gets called immediately when the first task gets finished.

I have pasted somewhat stripped down version of the code i am using.

<pre>
exports.validate = function (req, res, next) {
    async.parallel({
        domain : function (cb) {
            logr.info('domain');
                        //this method makes a query to db
            checkdomain(email, function (err, det) {
                logr.info('domain callback');
                if (err) {
                    return cb(err);
                }
                cb(null, det);
            });
        },
        checkmail : function (cb) {
            logr.info('checkmail');
                        //another call to db.
            getuser(email, function (err, det) {
                logr.info('checkmail callback');
                if (err) {
                    return cb(err);
                }
                cb(null, det);
            });
        }

    }, function (err, results) {
        if (err) {
            return next(err);
        }
        logr.info('parallel callback', err, results);
        res.send({
            mail : results.checkmail,
            domain : results.domain
        });
    });

};

</pre>

logs:

<pre>
[2011-05-03 16:27:06.390] [INFO] app - domain, 
[2011-05-03 16:27:06.449] [INFO] app - checkmail, 
[2011-05-03 16:27:06.459] [INFO] app - domain callback, 
[2011-05-03 16:27:06.463] [INFO] app - parallel callback, undefined, { domain: '/register/' }, 
[2011-05-03 16:27:06.483] [INFO] app - checkmail callback, 
</pre>

Am i missing anything? Is the main callback supposed to get called after all the tasks are finished?
Thanks.

**Comment by ardok** [comment]
@pvsundarram 
May I know what your problem was?
I'm facing the exact same issue and I cannot find where the problem is.

**Comment by ardok** [comment]
Never mind. Geez....
`If any of the functions pass an error to its callback, the main callback is immediately called with the value of the error`
