### ISSUE TITLE
async.series get result of the previous function?

### ISSUE THREAD

**Issue by jacobsologub** [caolan/async#292]
Is there a way to get the result of a previous function?

**Comment by zdila** [comment]
it is possible to use `series` with reading/writing results from/to the outer context.

**Comment by kootoopas** [comment]
@zdila You can, but things can get messy if you have many refs to outer contexts, especially if you don't know enough about async execution. (speaking from experience ✋)

**Comment by aearly** [comment]
Just use `waterfall` or `auto`.
