### ISSUE TITLE
applyEach callback not collecting results?

### ISSUE THREAD

**Issue by zzo** [caolan/async#343]
The applyEach final callback does NOT have all of the values from all of the callbacks from each of the called functions if there was no error.
For example in the first 'applyEach' test in the async test file its final callback:

```
async.applyEach([one, two, three], 5, function (err) {
    test.same(call_order, ['two', 'one', 'three']);
    test.done();
});
```

should accept a second value with the accumulated results?  And that value should be an array: [ 2, 1, 3] - the values from the callbacks of the 3 functions called by applyEach.
But there is no second argument...??  Should that work?

thanks!!

**Comment by sigxcpu76** [comment]
Is there a resolution or replacement to this functionality? I need to pass a single argument to a series of functions an get an array of results from the said functions.

**Comment by aearly** [comment]
If you need the results collected, you can use a combination of `async.parallel` and `bind`/`async.apply`.

```js
async.parallel([
  async.apply(arg, func1),
  async.apply(arg, func2),
  async.apply(arg, func3),
  //..
], function (err, results) {
  // results will be an array
});
```

**Comment by cyberjoac** [comment]
+1
