### ISSUE TITLE
Question: Does this leak resources?

### ISSUE THREAD

**Issue by mattlandis** [caolan/async#552]
Ran across a case in our code where someone had done this.   The correct thing would be to call callback instead of next. I was just curious if it leaked resources or if garbage collection would eventually clean this up?

```javascript

function func2(callback) {
  if (sometest()) {
     return next(new MyError());  // Should be callback here.
  }
  callback();
}

function handler(req, res, next) {
  async.waterfall([
    func1,
    func2,
    func3], next);
}
```

**Comment by petkaantonov** [comment]
I don't see how this wouldn't be a leak, the waterfall will wait indefinitely for `func2` to call it back and it cannot possibly know that it will never be called back.

**Comment by aearly** [comment]
Here's a test case that leaks about ~650k of memory:  http://requirebin.com/?gist=fe483795802d62f32013

Turn on profiling, trigger GC, click Run, then trigger GC again.

**Comment by petkaantonov** [comment]
Oh right, I think func2 is the only one holding the waterfall at that point so even though the waterfall is indefinitely pending, nothing will reference it because func2 doesn't save the reference anywhere.

**Comment by megawac** [comment]
This should be cleaned up by the GC pretty quickly in modern environments as callback is only accessible to `func2` which is called by `async` which won't hold its references to it anyway
