### ISSUE TITLE
async.each callback could be called more than once when array is modified

### ISSUE THREAD

**Issue by mingqi** [caolan/async#557]
```javascript
var async = require('async')

inputs = [1,2]
async.each(inputs,
	function (item, callback) {
		setTimeout(function(){callback()}, 1000)
	},
	function(err){
		console.log("async.each done")	
	})

inputs.splice(1,1)

/* output is:
async.each done
async.each done
*/
```

the problem is async use completed >= arr.length to check if call callback. however arr.length is less than async.each was called.

**Comment by aearly** [comment]
This was fixed as a side effect of other changes.

**Comment by ORESoftware** [comment]
Did async end up disallowing array modifications after the fact? I have a use case where it would be nice to modify the original array after the fact, so as to iterate on more elements than initially.

**Comment by aearly** [comment]
Modifying the array causes undefined behavior.  If you need to modify the array, use `async.queue`.

**Comment by ORESoftware** [comment]
ok cool thanks

**Comment by kamikazechaser** [comment]
What is the array is an endless stream (eg streaming data from Reddit) ?
