### ISSUE TITLE
Series does not defend against multiple callback calls

### ISSUE THREAD

**Issue by amv** [caolan/async#559]
var async = require('async')

    async.series(
        [function (callback) {
            callback();
            callback();
        }],
        function(err){
            console.log("async.series done")  
        })

    /* output is:
    async.series done
    async.series done
    */

The bug also causes last functions in the series to not be executed if preceding functions call the callback multiple times.

We could fix this by using the only_once() wrapper but I am a bit hesitant to do this as only_once actually throws an Error, which might cause some existing code to fail.

@caolan can you give your opinion on wether we should create a "silent_only_once" which would allow iterables to call the callback multiple times without throwing an Error, but would deactivate the callback after the first call, guard the actual series execution against multiple calls?

**Comment by smtlaissezfaire** [comment]
This bug seems like it's already fixed (as of HEAD - 993995145fe2adbfe5eb2cbc7651086636acd1a1).

Check out this behavior with async.series:

![screen shot 2015-06-15 at 4 17 15 pm](https://cloud.githubusercontent.com/assets/3690/8172846/21e7aaaa-137a-11e5-86fe-40cc9f3a8e97.png)

So it seems that async.series now guards against multiple calls to the same callback.

async.waterfall, on the other hand, allows callbacks to be called multiple times, but will only call the final (error or done) callback once.

![screen shot 2015-06-15 at 4 17 28 pm](https://cloud.githubusercontent.com/assets/3690/8172872/53d3a244-137a-11e5-81c7-82010fe42927.png)

This behavior seems inconsistent and should be documented, if intended.

How would one now use the old behavior of async.series if code depended on multiple calls to the same callback?  Consider this code:

https://gist.github.com/smtlaissezfaire/016b54bc906a2dc7df87

**Comment by amv** [comment]
@smtlaissezfaire I agree that this is inconsistent, although I personally would view the ability to call callbacks multiple times an bug in itself.

However I think it would be best to close this issue if the original "series" problem has been fixed in a new release (I believe this has indeed happened based on discussion in other threads), and create a new issue for this so that we can discuss the changes required to fix this in isolation.

Could you post a fresh bug issue about this, then post a comment here linking to that issue? Specifically I would like to see the title not containing the word "series", as it links to both the functions that have "series" in their names, and an internal series structure used within the library to implement these. The issue you describe does not relate to either of them, so it would be better to have a new, clean issue.

We could then close this one and keep the issue space in a bit more manageable state :)

**Comment by amv** [comment]
The most recent version throws an error with the code attached in the first comment:

    #  temp_test_async  node test.js 
    async.series done

    /Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:38
                if (called) throw new Error("Callback was already called.");
                                  ^
    Error: Callback was already called.
        at /Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:38:31
        at /Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:705:17
        at /Users/amv/Desktop/temp_test_async/test.js:6:9
        at /Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:699:13
        at iterate (/Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:256:13)
        at Object.async.forEachOfSeries.async.eachOfSeries (/Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:275:9)
        at Object.async.series (/Users/amv/Desktop/temp_test_async/node_modules/async/lib/async.js:698:15)
        at Object.<anonymous> (/Users/amv/Desktop/temp_test_async/test.js:3:7)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)

I would consider this bug fixed.

**Comment by aearly** [comment]
@smtlaissezfaire   `waterfall` had a specific test case geared to reproduce that kind of behavior -- running through the remaining tasks twice if a callback is called twice.  I'm actually going to remove it in 2.x -- only one callback per iteration across the board.

The example in your gist could be changed to separate the creation and adding of the event handler from the validation and submitting steps.  `async` isn't needed at all for the first two steps.

**Comment by aearly** [comment]
Series should defend against multiple callbacks now.
