### ISSUE TITLE
async.map runs through without any callback()

### ISSUE THREAD

**Issue by cruiser12** [caolan/async#577]
```
async.map([1,2,3],_runTest2, function(err, results)
{
  console.log(results);
});

function _runTest2(item,callback)
 {
   console.log(item);
}
```
is returning 
```
1
2
3
```

And i really thought map() is waiting for any callback to proceed. What can i use to achieve a behaviour like this, that the next item is processed after a ```callback(null,res)```

**Comment by jzapantis** [comment]
async.mapSeries() seems nice but it is so slow in my implementation. @cruiser12 did you figure out how to resolve this with async.map() ?
