### ISSUE TITLE
Allow to use generators

### ISSUE THREAD

**Issue by piranna** [caolan/async#579]
Allow to use EcmaScript 6 [iterators and generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) instead of Array objects.

**Comment by megawac** [comment]
Support could be added pretty easily to `keyIterator` and `iterator` I think

**Comment by aearly** [comment]
A quick workaround is `async.map([...iterable], doSomething, done)`, but iterating over a lazy iterator would open up some cool control flow options.

**Comment by aearly** [comment]
Closing this in favor of #839 -- I think supporting arbitrary ES6 iterators covers a lot of things -- Maps, Sets, Generators, etc...

**Comment by piranna** [comment]
Yes, both issues are similar.

**Comment by aearly** [comment]
I just realized that generators don't implement the iterator protocol, meaning we'll need separate support for them.  This will prove to be tricky, since there doesn't seem to be a bulletproof way to detect generator functions.

**Comment by megawac** [comment]
@jdalton any interest in adding `_.isGenerator` =)

**Comment by megawac** [comment]
Actually nevermind there's no reason for us to detect whether its a generator @aearly, if the iterable passed to `keyIterator` is a function we can just execute it and process the result as an iterator?

**Comment by aearly** [comment]
It's really tricky, since our iterator handling checks an object for a `[Symbol.iterator]` method, then calls `.next()` on the result of that method.  For a generator, it would call the function itself, then call `.next()` on the result.  I'm not sure if being "nextable" is sufficient enough.

**Comment by aearly** [comment]
Perhaps `internal/getIterator` could check to see if the function's prototype matches a generator function's prototype.  (Like in that stackoverflow question).  I don't know how portable that strategy would be across JS engines, though.

**Comment by megawac** [comment]
I'd say if item is a function, we call the function assuming it will follow
generator protocol. Does that not suffice for our use case?

**Comment by aearly** [comment]
The only pitfall I can think of is when someone accidentally passes a function as the wrong arg -- you'd get an error like "undefined has no property `next`".  Right now, I think it would try to iterate over the own properties of the function.

Can't think of any use case where passing a function would be a valid use case in the  future.

**Comment by 131** [comment]
meanwhile, i am in need of async's signatures with generator supports. So, i ended up writing a dedicated project for it [async-co](https://github.com/131/async-co).

**Comment by aearly** [comment]
I think our current support is sufficient.  You can do this today, and it works:

```js
function* gen() {
  for (var i = 0; i < 5; i++)
    yield i;
}

async.map(gen(), (val, cb) => {
  cb(null, val * 2)
}, (err, res) => {
  // res = [0, 2, 4, 6, 8]
})
```

The generator support was within us the whole time.  :princess: :stars: :high_heel:
