### ISSUE TITLE
Async tests hanging on Linux with node 10.30

### ISSUE THREAD

**Issue by scarino** [caolan/async#592]
When I attempt to run the tests provided with async on node 10.30 on Linux it hangs. This does not occur on Windows.

Output:
//snipped
✔ mapLimit
✔ mapLimit empty array
✔ mapLimit limit exceeds size
✔ mapLimit limit equal size
✔ mapLimit zero limit
✔ mapLimit error
✔ reduce
//hung

Steps to recreate:
git clone https://github.com/caolan/async
cd async
npm install
npm test

Any idea why this is happening?

**Comment by aearly** [comment]
Looks like there was a bug with non-integer `setTimeout`s, which a test was using.  This was fixed in 0.10.31: http://blog.nodejs.org/2014/08/19/node-v0-10-31-stable/
