### ISSUE TITLE
.queue() hides errors by default

### ISSUE THREAD

**Issue by Suor** [caolan/async#599]
When you don't specify callback to `queue.push()` it will just happily continue on a failed task. I suggest throw all errors if callback is not specified, this will ease debugging greatly. It's from my real practice - I wasted hours trying to find out why something wasn't saved to db, turns out it was tricky duplicate key that was ignored.

If you can't change this cause of backward compatibility than it's at least should be documented very visibly in `queue.push()` and `queue.unshift()`. And still I think changing this to more strict behavior at least in the next major release would be beneficial.

**Comment by aearly** [comment]
Clarified in 78a77f4
