### ISSUE TITLE
Remove job from `queue` possible?

### ISSUE THREAD

**Issue by matejkramny** [caolan/async#607]
Hi, don't see this in the documentation so i'm checking whether its possible to remove a task from the `queue`.

I can contribute such feature, if it is not deliberate to not be able to remove tasks.

There might be some concurrency problems where a task is removed when it is running, but i think that could be solved with
1. Pause queue
2. Remove the job
3. Resume queue

What do you think?

**Comment by kosssi** [comment]
it's possible with q._tasks.removeLink ;)
