### ISSUE TITLE
Is Async somehow dependent on timers ?

### ISSUE THREAD

**Issue by FredyC** [caolan/async#609]
I have run into rather weird issue. I am using SinonJS to write my unit tests. There is some neat utility to [fake timers](http://sinonjs.org/docs/#clock). Today I was totally stumbled when my tests became somewhat "stuck". I run them and nothing happened, process was just hanging there and doing nothing.

I started digging and find out that if I don't use fake timers, it works, but since I need to control time in my tests, I started digging more and found out that Async is probably forcing asynchronous behavior with real timers. Check out this [JSFiddle](http://jsfiddle.net/FredyCr/2tbyvvc4/2/).

It's rather innocent piece of code that is not even asynchronous and you can see resulting message in console. However once you remove comment on first line with fake timers, it doesn't finish.

For now I had to get rid of `waterfall` and it started working as expected. I suppose that nothing can be done about this :(

**Comment by aearly** [comment]
Sounds like the fix is to do `var tick = setImmediate` in our init, as the sinon devs recommend.

**Comment by FredyC** [comment]
Well it took quite a while to accept this solution. Thank you!
