### ISSUE TITLE
Breaking async series with the response values from the other executed functions 

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [caolan/async#625]
Lets say now , one wants execute 10 functions in series(which individually are asynchronous functions),as usual, now i store the references to these functions in an array and used it as an argument for async.series . Here is my objective , When one of the function doesnt return the expected value i want to break the execution of further functions(further functions in the list of functions ) in such a way that i get the values returned by the previous successful executions of the functions in an array (currently its clear that the async series callback contains the values returned by these functions in an array only on successful execution of all the functions in the list) . How to achieve it ?? In my current scenario i have list of strings which i test for its availability inside the redis hash in an order using async series , when a non existing key is found i want to end the execution of further functions in async series and return with the aggregated answers(aggregated in an array , which now happens only on successful execution of all functions) from successfully executed functions  .Is there a method to achieve it ??? it doesnt seem so ...If not how to achieve this ???

**Comment by kessler** [comment]
@Karthic-Hackintosh 
I ran into similar scenarios several times myself and decided to write something: 
https://github.com/kessler/if-async
check it out
