### ISSUE TITLE
async.each Misbehavior

### ISSUE THREAD

**Issue by basdag** [caolan/async#640]
Hello everyone,

I was working with `async.each` and when it receives for example an array `[1, 2, 3, , , 6]` the `iterator` function take into account `6` cycles in order to finish, which is ok. However the `iterator` function will never finish because it is not taking into account the empty positions (array index: 3 and 4) inside the function to apply to each item in arr. Therefore even though the `iterator` knows that there are `6` cycles at the beginning it will only do 4 and it will never execute the callback which is called when all iterator functions have finished.

Thanks in advance for your time and support.

**Comment by aearly** [comment]
This should be fixed as of 3ffbf2b, we're no longer using the internal `forEach`.
