### ISSUE TITLE
Wait for or force completion of async.* calls?

### ISSUE THREAD

**Issue by deitch** [caolan/async#645]
Is there any way to either wait for or force completion of async calls?

E.g. I might have a function I am testing that does:

````JavaScript
var foo = {};
function myFunc() {
  async.parallel([
    function(cb) {doSomeStuff().then(cb);},
    function(cb) {doOtherStuff().then(cb);},
    function(cb) {doDifferentStuff().then(cb);},
  ],function() {
    foo.done = true;
  });
}
````

My tests will always fail, because `beforeEach()` returns before all of the async stuff is done:

````JavaScript
describe('MyFunc', function(){
  beforeEach(function() {
    myFunc();
    // HERE: How do I set this to wait until all async functions are complete, or conversely flush all async callbacks?
   // something like async.flushAll() ??
  });
  it('should set foo.done to true', function() {
    foo.done.should.be.true; // WILL FAIL
  });
});
````

BTW, in Angular http mocking, there is a similar structure with `$httpBackend` where you can force it to flush all callbacks and then return using `$httpBackend.flush()`.

**Comment by aearly** [comment]
BTW, if you're using promises, you can chain them together without async:

```js
function my_ctrl_handler($scope,Service1,Service2,Service3) {
  return Promise.all([ // I think in angular this is $q.all
     Service1.get(param1),
     Service2.get(param2),
     Service3.get(param3),
  ]).then(function (err) {
    $scope.ready = true;
  });
}

// in your test
beforeEach(function (done) {
  my_ctrl_handler($scope,Service1,Service2,Service3).then(done);
})

```

Also, I know that at least in mocha, if you return a promise from a `beforeEach()`/`after()`/etc. hook or from an  `it()` function, it will pass/fail the test when the promise resolves, no need for the `.then(done)` business.
