### ISSUE TITLE
gather

### ISSUE THREAD

**Issue by pomke** [caolan/async#646]
I find this pattern fairly useful, especially combined with partials, thought it might be a nice addition to async. Happy to send a pull request if you agree. 
```javascript
/* gather([fn1, fn2, ...], callback);
 * gather calls each function in the array with a callback which takes err, res,
 * then calls apply on final callback with an error then each result from the 
 * array of functions.
 */
exports.gather = function(fns, finish) {
    async.map(fns, function(fn, cb) { return fn(cb); }, function(err, res) {
        return finish.apply(null, [err].concat(res));
    });
};
```

**Comment by aearly** [comment]
You can simplify this a bit with `parallel`:

```js
exports.gather = function(fns, finish) {
    async.parallel(fns, function(err, res) {
        return finish.apply(null, [err].concat(res));
    });
};
```

Seeing as all this does is spread the results of parallel across the callback's arguments, I'm going to :-1: this.  Also, take a look at `auto` for more free-form control flow.
