### ISSUE TITLE
Does `series` push it's parameter functions to the end of the event loop?

### ISSUE THREAD

**Issue by whmountains** [caolan/async#654]
Are each of the functions in the series automatically wrapped with something like `setImmediate`, or will they only be asynchronous if they contain async code?

```
async.series([
  function(callback) {
    //do some work
    callback(null, null);
  },
  function(callback) {
    //do some more work
    callback(null, null);
  }
]);
````

To explain by example, I want the functions in my series to get pushed to the end of the event loop and only get executed after everything else.  Will that happen automatically, or must I explicitly call `setImmediate`?

**Comment by binarykitchen** [comment]
i am curious too for the answer on the above question. and that link. which is supposed to answer it, gives a 404. so would be good to have it in writing here ... thx

**Comment by whmountains** [comment]
Answer is yes.
