### ISSUE TITLE
Feature: wrapper for async.auto tasks

### ISSUE THREAD

**Issue by ArcanisCz** [caolan/async#657]
Hello!
I love to use async.auto for easy controlling control flow even in situation, which does not strictly require parallel execution. But it has nice feature - easily manageable dependencies of each tasks.

But there is one thing, that bugs me. If i ever want to use results from previous tasks, the task function have to know exact string name of that previous task. Which is not good, because that function might be from another file. When someone change that string name, not-so-easily-spottable bug appears. 

Example (As you seee, inside function "bbb", i must know name "a"):
```javascript
async.auto({
    a: aaa,
    b: ["a", bbb],
    c: ["a", ccc]
});

function bbb(callback, results){
   var someResult = results.a;
}
```

My proposal for this use case is to have some wrapper, which turns dependency list into arguments, so you only need to know names in defining async.auto. 

Example of desired use and its equivalent:
```javascript
async.auto({
  a: async.wrapArgs(aaa),
  b: async.wrapArgs(bbb, "a"),
  c: async.wrapArgs(ccc, "b", "a")
}, function(error, results){
  console.log("done", results);
});

async.auto({
  a: aaa,
  b: ["a", function(callback, results){
      bbb(callback, results.a)
  }],
  c: ["b" ,"a", function(callback, results){
      ccc(callback, results.b, results.a)
  }]
});

function bbb(callback, a){};
function ccc(callback, b, a){};
```
In the end, i wrote some simple wrapper to demonstrate funcionality, which i am now offering for async, in case you decide its good pattern and practice for others :) (i will use it anyway).

```javascript
async.wrapArgs = function(){
    var args = Array.prototype.slice.call(arguments, 0);

    var oldFn = arguments[0];
    var requires = args.slice(1, args.length) || [];

    var newFn = function(callback, results){
        var newArgs = requires.map(function(key){
            return results[key];
        });
        newArgs.unshift(callback);
        oldFn.apply(null, newArgs);
    }

    return requires.concat([newFn]);
}
```

**Comment by aearly** [comment]
I've needed this kind of behavior mant times, so I added something similar to my acomb library: https://github.com/aearly/acomb#spreadoptionsfunc-option1-option2-

**Comment by aearly** [comment]
I think we're going to go with `autoInject` (#608) for this kind of behavior.
