### ISSUE TITLE
async.map item index

### ISSUE THREAD

**Issue by SamiSammour** [caolan/async#669]
in async.map function is there any way I can find the index of the current item in the main array when executing the iterator function?

**Comment by bertyhell** [comment]
For anyone else coming across this, a good solution I found was to just run over the indexes instead of over the original array.

```javascript
let myArray = ['a', 'b', 'c', 'd'];
let myIndexes = Object.keys(myArray);

async.map(myIndexes, function (myIndex, callback) {
  setTimeout(function() { // Emulating an async function using setTimeout
    callback(null, myArray[myIndex].toUpperCase());
  })
}, function(err, results) {
  console.log(results.join(', '))
});
```

Codepen of the above code snipplet: https://codepen.io/bertyhell/pen/opJqwx

**Comment by suguru03** [comment]
In this case, you can also use [`async.times`](http://caolan.github.io/async/docs.html#times).

```js
async.times(myArray.length, function(index, callback) {
  setTimeout(function() {
    callback(null, myArray[index].toUpperCase());
  }) ;
}, function(err, results) {
  console.log(results.join(', '))
});

```
