### ISSUE TITLE
New async.sync like async.apply for sync functions.

### ISSUE THREAD

**Issue by reggi** [caolan/async#671]
I came up with an `async.sync` call that's like `async.apply` except for synchronous functions. Checkout the bottom example that uses `path.join`  `async.sync(path.join, "/hello", "world", "awesome")`.

```
var path = require("path");
var async = require("async");
var _ = require("underscore");

async.sync = function() {
  var args = arguments;
  args = Array.prototype.slice.call(args);
  var fn =  args.shift();
  return function(callback) {
    var exe = fn.apply(null, args);
    return callback(exe);
  }
}

async.waterfall([
  async.sync(path.join, "/hello", "world", "awesome")
], function(err, results) {
  console.log(err);
  console.log(results);
});
```

**Comment by aearly** [comment]
I've added [`acomb.asyncify`](https://github.com/aearly/acomb#asyncify) with this functionality to my helper library.  It might be worth adding to async, but I'll wait for more opinions.

**Comment by aearly** [comment]
And ideas for what to name this?

- `async.asyncify`
- `async.ify`
- `async.sync`
- `async.fromSync`
- `async.toAsync`
- `async.wrapSync`
- …

**Comment by reggi** [comment]
@aearly From my example above, I personally like like `sync`.

**Comment by aearly** [comment]
I'm not a fan of `async.sync`, because it's not really "syncing" anything -- it's shorthand for an adjective, not a verb. It's also too generic for what it's doing.

Whats your second choice?  :smile:

**Comment by reggi** [comment]
@aearly Makes sense. 

I like `async.wrapSync` because that is more inline with what is being done, and it's easy to read the whole way through without your head wanting to explode.
