### ISSUE TITLE
Kapeli Dash for Mac

### ISSUE THREAD

**Issue by mathieug** [caolan/async#676]
A documentation for Dash would be awesome.
https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

**Comment by mathieug** [comment]
Still not?

**Comment by eighteyes** [comment]
If only Dash would let us import npm module github readme's

**Comment by beaugunderson** [comment]
I'm interested in converting to tmcw's documentation project--it uses JSDoc to render markdown, html, and Dash so might be a good fit for us :)

**Comment by mathieug** [comment]
What do we need to get started?

**Comment by beaugunderson** [comment]
@mathieug a branch that moves the README.md documentation to JSDoc would be a good start I think; with the examples using the @example JSDoc tag; then we'll need a tiny script to update the README markdown from the JSDoc

**Comment by mathieug** [comment]
So we have to document the code (like Lodash https://github.com/lodash/lodash/blob/master/lodash.js#L4456)?

**Comment by aearly** [comment]
I'd prefer to not have to do JSDoc-style comments everywhere to accommodate this.  We're reaching a point where we'll be able to generate many `async` methods programmatically, so there might not be a clear line where a given method is written.  `async.js` will end up being more docs than code.

**Comment by megawac** [comment]
JSDoc can be used with helper functions generating the methods pretty easily, you just include the documents wherever a method is defined (ala lodash)

```js
/**
 * Whatever does something
 *
 * @param smt array something
 */
async.whatver = createWhatever()
```

**Comment by aearly** [comment]
Closing this in favor of #859 .  Once we migrate to JSDoc, we should be able to support Dash and other doc aggregators.

**Comment by raszi** [comment]
Any update on this? It seems that you've already moved to JSDoc, but I could not find the Dash version of it.
