### ISSUE TITLE
mutli-threading 

### ISSUE THREAD

**Issue by h0ru5** [caolan/async#688]
After some brief experiments and a look in the code, it seems to be single-threaded.
Some (clearly not all)  applications could additionally benefit from multi-threading.
As async.js is the de-facto standard API, it could offer an ease-of-use entry to parallelization.

In the browser you have a lightweight multi-threading API by using webworkers, which can at lease be easily polyfilled into a single-threaded fallback.
for node, I've seen some implementations encapsulating the node threading API into webworkers API.

What do you think of adding possibilities for multi-threaded operation?
Would you consider webworkers API as a fitting API?

**Comment by h0ru5** [comment]
Agreed, thats why I wanted to go for an existing API.  I've seen ports of the Webworker API onto node (using `child_process` and another one using Threads a GoGo) so I thought of calling webworkers from async and providing functions like each_parallel.

 When I have some time on the hands I can fork and hack together a first shot.

**Comment by aearly** [comment]
There's a lot of prior art you might want to consider:  https://www.npmjs.com/search?q=webworker

**Comment by h0ru5** [comment]
yes, I used the ``webworker-threads`` npm. However, after poking around he main remaining problem is that the worker has an own js context, therefore passing in a function pointer is a not simple possible.
It seems one need to marshal out a function into js so that the worker can eval it.

**Comment by aearly** [comment]
Sorry, this would open a huge can of worms that is way out of scope.
