### ISSUE TITLE
async series doubt

### ISSUE THREAD

**Issue by imane-jym** [caolan/async#694]
code:
a = require('async');
function test(err, results) {
    console.log('The solution is: ', results);
}
a.series([
        function (cb)
        {
            console.log(typeof cb);
            pool.query('SELECT * FROM account', function(err, results) {cb(err, results);});
        },
        function (cb)
        {
            pool.query('SELECT * FROM account', cb);
        },
        ],
        test);

=====output=======
function
The solution is:  [ { str: 'asdf' } ]
The solution is:  [ [ { str: 'asdf' } ], [ [ [Object] ], [ [Object] ] ] ]

Why I can not find result[1] obj that is like this "[{str: 'asdf'}]"?

**Comment by aearly** [comment]
Your `pool.query` function looks like it calls-back twice.  It also calls-back with multiple results, it seems.

**Comment by imane-jym** [comment]
The first pool.query return  "[ { str: 'asdf' } ]",  then the second pool.query return "[ [ [Object] ], [ [Object] ] ]". If  call back twice. I think  them should calls-back twice.
PS: The solution is: [ { str: 'asdf' } ]  is not other code's output.
