### ISSUE TITLE
Update NPM Module

### ISSUE THREAD

**Issue by alanjames1987** [caolan/async#695]
I noticed async was updated to 0.9.2 last month but the NPM module is still at 0.9.0.

There is obviously no rush as the module is working fine, but I was wondering when it might be updated.

**Comment by aearly** [comment]
Yeah, @caolan is the only one who can update NPM.  @beaugunderson is the one who tagged it.

**Comment by beaugunderson** [comment]
Yup, @caolan will have to be the one to `npm publish` or `npm owner add async beaugunderson`. :)

**Comment by alanjames1987** [comment]
Understood, just wanted to report it. Thanks.

**Comment by beaugunderson** [comment]
@alanjames1987 No worries, thanks for reporting! Just wanted to use that comment to ping him and detail the commands if he's interested in adding me to `owners`. (Background: I've only been helping to maintain the library for a couple of months and he seems like a busy dude these days)

**Comment by bausmeier** [comment]
+1. I'm waiting for https://github.com/caolan/async/commit/66ca10e52795707ca436154bddc38c560864e91c.

**Comment by PiotrWpl** [comment]
+1 It's half of march now, and there is still no update in NPM :/

**Comment by mwoc** [comment]
+1

**Comment by NAlexandrov** [comment]
+1

**Comment by beaugunderson** [comment]
@caolan how do you feel about publishing a new version or adding me to owners on npm?

**Comment by aearly** [comment]
@beaugunderson and I are now official collaborators!  0.9.2 was pushed earlier today!
