### ISSUE TITLE
async.series just freeze

### ISSUE THREAD

**Issue by kfirufk** [caolan/async#697]
the code works fine on my osx, but on my gentoo linux it just freeze the request sent by the browser and completes with timeout
             async.series([
                       function (callback) {
                           callback(null,null);
                       }
                   ],
                    function(err,result) {
                        console.log(inspect("error: " + err));
                        console.log(inspect("result: " + inspect(result)));
                        res.send({"status":"done"});
                    }

**Comment by aearly** [comment]
It's very doubtful async is to blame here. It's impossible to debug without more context, but that context is outside of the scope of this library.



![](http://cdn2.hubspot.net/hub/228391/file-745508197-jpg/blog-files/devopsevil.jpg)

**Comment by kfirufk** [comment]
you are right :) it wasn't async's fault.
