### ISSUE TITLE
eachSeries - stack size limitation

### ISSUE THREAD

**Issue by ghominejad** [caolan/async#700]
```JAVASCRIPT

var arr = [];
for (var i=0; i <= 5000; i++ ) {
    arr.push( i );
}
async.eachSeries(arr, function (i, cb){
    cb();
});

```
RangeError: Maximum call stack size exceeded

**Comment by aearly** [comment]
See #66, #75, #110, #117, #133, #296, #413, #510, #573, #588, #590, #604, #622, #696 .

Your iterator is synchronous.  You need to:

```js
async.eachSeries(arr, function (i, cb){
    setImmediate(cb);
});
```

**Comment by ghominejad** [comment]
Thank you

**Comment by wilywork** [comment]
`
async.eachSeries(arr, function (i, cb){
    setImmediate(cb);
});
//Uncaught ReferenceError: setImmediate is not defined(…)
`

**Comment by hargasinski** [comment]
@wilywork see https://developer.mozilla.org/en/docs/Web/API/Window/setImmediate. If you're running this in a browser, you'll need to change it to:
```js
async.eachSeries(arr, function (i, cb){
    async.setImmediate(cb);
});
```

**Comment by wilywork** [comment]
Thank you
