### ISSUE TITLE
Would you consider adding a time logging option?

### ISSUE THREAD

**Issue by flyswatter** [caolan/async#701]
Hi, I frequently end up using `console.time` and `console.timeEnd` to help diagnose steps in my async flow that are going slowly.  I was thinking it would be pretty sweet to build logging into async.

Would you hypothetically pull in a PR that added optional time logging around the async methods?

An example would be:

```javascript
async.timeLogging = true
async.parallel({ 
  firstThing: aMethod,
  secondThing: bMethod
}, callback)
```
Would print to the console something like:
```
Async parallel calling firstThing: 26ms
Async parallel calling secondThing: 523ms
```

**Comment by kumavis** [comment]
Not a bad suggestion, though if its determined to be undesired feature bloat you could publish a wrapper module `async-timer` that just passes through to `async` after injecting the timing functions

**Comment by flyswatter** [comment]
I agree, an async-timer module could play this part as a module, but loses some of the convenience of casually checking the timing of your functions.

I would totally concede that it adds bloat, which is why I asked here before implementing any of it myself.

**Comment by kumavis** [comment]
re "casually checking the timing of your functions". This was the usage I was thinking of:
```js
var async = require('async')
//var async = require('async-timer')
async.parallel({ 
  firstThing: aMethod,
  secondThing: bMethod
}, callback)
```
vs
```js
var async = require('async')
//async.timeLogging = true
async.parallel({ 
  firstThing: aMethod,
  secondThing: bMethod
}, callback)
```

**Comment by aearly** [comment]
Something like that already exists: https://www.npmjs.com/package/async-time

**Comment by flyswatter** [comment]
@kumavis:  That is pretty simple, and will probably be my fallback if this is rejected.

@aearly: Looks like the `async-time` module only works with event-emitters, so it isn't really what I'm talking about here.

**Comment by aearly** [comment]
The EE is used for reporting -- could easily adapt the wrapper to automatically log the elapsed time for any function.
