### ISSUE TITLE
New feature suggestion, possibility to stop running iterators 

### ISSUE THREAD

**Issue by gabrieldodan** [caolan/async#703]
For the collection functions that run iterators in parallel like each, eachLimit, map etc, if the iterator return error the global callback is called but the iterator continue to run for the others items. For example
```
function iterator (item, cb) {
	var timer = setTimeout(function(){
		console.log('done for item ' + item);
		return cb(item === 1 ? true : false);
	}, item*1000);
}

async.each([1,2,3], iterator, function() {
	console.log("done async.each");
});

The output
done for item 1
done async.each
done for item 2
done for item 3

```
async.each completed but iterator(2) and iterator(3) are still running ... imagine the iterator fork a child process or make extensive processing, it's not good to let iterator(2/3) running as long as we don't need their results anymore. Would be very good to stop somehow the running iterators. 

A possible solution that is simple an elegant is to make iterator to return a stop closure, for example the iterator and async.each will become
```
function iterator (item, cb) {
	var timer = setTimeout(function(){
		console.log('done for item ' + item);
		return cb(item === 1 ? true : false);
	}, item*1000);
	
	return function () { // the stop closure
		console.log('stop for item ' + item);
		// stop the iterator somehow, clean up etc. in this case stop the timer
		clearTimeout(timer);
	}
}

async.eachWithStop = function (arr, iterator, callback) {
    callback = callback || function () {};
    if (!arr.length) {
        return callback();
    }
    var completed = 0, stopFunctions = [];
    _each(arr, function (x) {
        stopFunctions.push(iterator(x, only_once(done) ));
    });
    function done(err) {
      if (err) {
          for(var i=0; i<stopFunctions.length; i++) {
            if(i !== completed) {
                stopFunctions[i]();
            }
          }	

          callback(err);
          callback = function () {};
      }
      else {
          completed += 1;
          if (completed >= arr.length) {
              callback();
          }
      }
    }
};
```

```
async.eachWithStop([1,2,3], iterator, function() {
	console.log("done async.eachWithStop");
})

The output
done for item 1
stop for item 2
stop for item 3
done async.eachWithStop
```

Much better, robust and predictable behavior in my opinion.

**Comment by aearly** [comment]
This is a feature that has been requested a couple times before.  It's tricky to get the API right.  I'm not a fan of returning things from an async function -- it's a bit unorthodox.  Perhaps a `iterator.stop = function () { ... }` property added?  I'd want other people's opinions.

Also, not every async function is cancellable.  Timers and streams, yes, but I'm not sure how you would cancel something like `fs.readFile`.

**Comment by gabrieldodan** [comment]
I haven't know this feature has been already requested. If it was requested by other people too then I think it should be implemented somehow. 

```fs.readFile``` can't be canceled but we can stop processing the data returned by ```fs.readFile```  e.g. 
```
function iterator() {
    var stopped = false;

    fs.readFile('file', function(err, data) {
        if(stopped) {
            // do not process the data
        } else {
            // process the data
        }
    });
    
    return stop() {
        stopped = true;
    }
}
```

The stop functionality will be optional, if the iterator returns a ```close()``` function then ```async.each``` will call that function, if not ```async.each``` will work as it works now. 

Another solution could be to define an interface/class for iterators, the interface/class will have two methods: run() and stop(), each iterator must implement those two methods. But this solution is much complicate than closure solution in my opinion.

The ```iterator.stop=function(){ .. }``` solution I don't think will works. From what I understand it create a static property/function. But the stop/cleanup actions depends by the item the iterator was called. Each ```iterator(item)``` call create their own resources: files descriptions, streams, child processes, timers etc that need be closed/cleanup/stopped.

**Comment by aearly** [comment]
I don't think there's a good solution here.  I think the best we can do is have results from other tasks be discarded.  Unfortunately, there's no standard way that I see that allows us to cancel arbitrary tasks.

**Comment by ypresto** [comment]
:+1: I want to use this feature to kill running child process. [RxJS also uses `return function` technique](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/create.md).
