### ISSUE TITLE
Iterating tasks on a queue or referencing the queue from tasks

### ISSUE THREAD

**Issue by klivin** [caolan/async#706]
Looking to support cancellation in tasks on a queue in a sensible way - I would like to access all the tasks currently running on a queue or have the tasks be able to reference the queue's state.

Is there a built-in way to reference the queue from a task?

Conversely, is there a built-in way to access all running tasks on a queue?

Thanks for the awesome library!

**Comment by aearly** [comment]
There are `q.pause()` and `q.kill()` to stop the queue from processing, but there is currently no way to cancel currently running tasks, unless you manage it yourself.  I can definitely see how it would be useful. 

How would you cancel an async function?  Queue uses a single worker function with a queue of data.  If we provided a list of running *somethings* what would that list contain?

Somewhat related: #703
