### ISSUE TITLE
Option b (video bitrate (please use -b:v)) cannot be applied to input file 

### ISSUE THREAD

**Issue by jBachalo** [caolan/async#708]
Get the following error when trying to run example1

Option b (video bitrate (please use -b:v)) cannot be applied to input file /Users/foo/Documents/node-simple-ffmpeg-master/examples/videos/input1.mp4 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
Error parsing options for input file /Users/foo/Documents/node-simple-ffmpeg-master/examples/videos/input1.mp4.
Error opening input files: Invalid argument

**Comment by beaugunderson** [comment]
Hi @jBachalo, this looks like an issue with `node-simple-ffmpeg`; you'll probably want to report this bug [at their GitHub repo](https://github.com/scopely/node-simple-ffmpeg). :)
