### ISSUE TITLE
Developed Neo-async, an improved version of async

### ISSUE THREAD

**Issue by suguru03** [caolan/async#709]
Hi. I have developed [Neo-async](https://github.com/suguru03/neo-async), basically it is an improved version of the original async module. It keeps all the original functions, so it is thought to be a drop-in replacement.  At the moment it only includes just a small extra functionality. Neo-async offers better overall performance and almost 100% code coverage.

We are using Async for managing asynchronous operations in our project since it offers a straightforward solution and has the source code well organized. We use it very often in our code, but we have detected some perfomance problems, this is our motivation to create a version with these perfomance problems solved.

I would really appreciate your feedback or any comments. Thank you.

**Comment by thammin** [comment]
Impressive! :+1:

**Comment by martinheidegger** [comment]
If it truly is a "drop-in-replacement" then I wonder why you not just created a PR here to improve the quality of async? I assume that there are some "incompatibilities". Would love to know what they are about.

**Comment by suguru03** [comment]
@thammin @martinheidegger 
Thanks for replies!  
I have been using Async in production, and an error occured due to a bug. I sent a [PR](https://github.com/caolan/async/pull/578) at that time but it has not been merged yet. That is my main motivation to develop Neo-Async as a separate project. In order to achieve a better performance Neo-Async has been built from scratch. The code structure of Neo-Async is far from Async now, so it could not be merged anymore.  
I think the relation between async and Neo-Async could be similar to the one between Underscore and lodash. I am also planning to implement more methods to improve the usability.

**Comment by ralgara** [comment]
@suguru03 

Great job on Neo-Async. Also here trying to find a fix for #508/#512 -- there is a similarly pending [PR](https://github.com/caolan/async/pull/512). Any chance it can be addressed in Neo-Async?

**Comment by suguru03** [comment]
@ralgara 

Thank you for your comment.
OK, I try to fix it ASAP.

**Comment by aearly** [comment]
BTW, since we have a couple more maintainers now, PRs will start getting merged again. :smile:

**Comment by suguru03** [comment]
Thank your very much for your contribution.
I’m very happy for published new version and want to improve async :)
