### ISSUE TITLE
async.queue: throw error if called with a concurrency of 0

### ISSUE THREAD

**Issue by LinusU** [caolan/async#714]
I recently had this code:

```javascript
var concurrency = os.cpus.length;

function doWork(opts, cb) {
  cb(null);
}

var queue = async.queue(doWork, concurrency);
```

Things queued never called the callback because `os.cpus` is a function that takes 0 arguments. Thus `os.cpus.length` returns 0 and the queue never does anything. The correct code would be `os.cpus().length`, notice the **`()`**.

Maybe it would be a good idea to throw an error to alert the user that the queue was initialised with 0 concurrency and thus never will run anything.

**Comment by VitoNordloh** [comment]
#762

**Comment by VitoNordloh** [comment]
PR #762

**Comment by VitoNordloh** [comment]
Ah, i see that it is possible to change the concurrency after the initalisation.
I will update my PR later.

**Comment by aearly** [comment]
Thanks!
