### ISSUE TITLE
Proposal to add async.when to dynamically decide whether to execute a function on a waterfall or series workflow

### ISSUE THREAD

**Issue by carpasse** [caolan/async#717]
Hi guys 

I have started to use async a couple months ago and I love it. 
I think it could be cool for some situations to be able to dynamically decide whether to execute one of the steps in a workflow.

For Example:

```
async.waterfall([    
    step1,
    step2,
    async.when(env == 'production', sendResponseToProdServer),
    step3,
    async.when(step3ReturnsBla, step4forFoo),
    async.when(step3ReturnsFoo, step4forFoo)
  ], function (error, response) {
    ...
  });

 function step3ReturnsBla(response){
    return response.type === 'bla'
}

 function step3ReturnsFoo(response){
    return response.type === 'foo'
}
```

I am pretty new to async so maybe there is a way of doing this already and I just couldn't find it. If not, I have a working async.when implementation and I would like to do a pull request with it.

What do you think???

**Comment by aearly** [comment]
Caolan has historically been against features like this in async -- he prefers plain `if`-statements in functions.

I've added a `provided` function that is very similar to your proposal here to my `acomb` library:

https://github.com/aearly/acomb#provided

**Comment by carpasse** [comment]
@aearly Thanks for the response. 

```provided``` is indeed very similar. If I ever need this functionality again I will use your library in companion with async.
