### ISSUE TITLE
async series data along the way?

### ISSUE THREAD

**Issue by sgarbesi** [caolan/async#722]
So I have a series of functions which need to run but I need to grab the data a long the way.

Originally I tried doing this with waterfall, but it's a lot of excess code and far from ideal.

Along with that premise, you can't pass an Object to a waterfall, so the nice mapping set of callback data that you get from a `series` is thrown out the window.

**Example:**

```javascript
async.series({
	test1: function(callback) {
		// do something
		callback(null, 'all good');
	},

	test2: function(data, callback) {
		// do something

		// logs `all good`
		console.log(data.test1);

		callback(null, 'test2 passed');
	},

	test3: function(data, callback) {
		// do something

		// logs `all good` and `test2 passed`
		console.log(data.test1);
		console.log(data.test2);

		callback(null, 'test3 passed');
	},
}, callback);
```

Now this is obviously a very simple example. I have dozens of series of functions running which need to gain access to the data that's being populated along the way, and it's not always necessarily in order.

For instance the 5th function that is invoked in a series, may need the data for the 1st function which was invoked.

So my current alternatives are either start nesting series (which is nasty and definitely not the way to go) or send a pass through Object, in which case I have to manually write out each of the callback functions. It works, it's hacky, it's not ideal though.

If I could somehow get the series Object that is returned for the final callback along the way, this would not only save a a lot of time but also prevent code duplication.

**So what I'm currently doing is this:**

```javascript
var data = {};

var test1 = function(data, callback) {
	// do something
	data.test1 = 'all good';
	callback(null, data);
};

var test2 = function(data, callback) {
	// do something

	// logs `all good`
	console.log(data.test1);

	data.test1 = 'test2 passed';
	callback(null, data);
};

var test3 = function(data, callback) {
	// do something

	// logs `all good` and `test2 passed`
	console.log(data.test1);
	console.log(data.test2);

	data.test3 = 'test3 passed';
	callback(null, data);
};

async.series({
	async.apply(test1, data),
	async.apply(test2, data),
	async.apply(test3, data)
}, callback);
```

**Any ideas here? Went diving through the docs and couldn't find anything that solved this problem.**

**Comment by aearly** [comment]
Take a second look at async.auto -- it does precisely what you want.

**Comment by sgarbesi** [comment]
@aearly I've actually tried that function before making this post but couldn't get it to work as I illustrated with the example above. Might transforming my example above for how it should work with the `autio` Function?

**Comment by aearly** [comment]
```js
async.auto({
  test1: function(cb) {
    cb(null, "all good")
  }
  test2: ["test1", function (cb, data) {
    // data.test1 is set
    cb(null, "test2 passed")
  }]
  test3: ["test1", "test2", function (cb, data) {
    //data.test1, data.test2 are set
    cb(null, "test3 passed");
  }]
}, function done(err, data) { 
  // data.test1, test2, test3 are valid
})
```

**Comment by sgarbesi** [comment]
@aearly Thanks for the example. Is there a way to specify the whole payload or you have to manually specify each key every time?

**Comment by aearly** [comment]
You have to manually specify the steps each following step is dependent upon.  It can be tedious if a step has a lot of dependencies, but the benefit is that `async.auto` will automatically determine the calling order, and automatically parallelize what it can.  For example, if `test2` wasn't actually dependent on `test1`, `auto` would call both `test1` and `test2` in parallel, and then call  `test3` when both are done.

**Comment by sgarbesi** [comment]
@aearly Interesting. In my case I need this to be a series (meaning it has to run it order or the whole thing breaks down). I might just wind up doing something like _.keys() on the series payload. Thanks for the help.
