### ISSUE TITLE
async.queue emits "saturated" event at wrong point

### ISSUE THREAD

**Issue by glenjamin** [caolan/async#724]
In the https://github.com/caolan/async#queue docs it says:

> saturated - a callback that is called when the queue length hits the concurrency limit, and further tasks will be queued.

This is both correct & incorrect.

A queue has both a number of `running()` functions, and a queue of functions to run `length()`. The event is emitted when `.length() === concurrency` - whereas it should really be emitted when `running() === concurrency`.

Example:

```js
var q = async.queue(function(){}, 2);
q.saturated = console.log.bind(console, "full");
q.push(1);
q.push(2);
// would expect "full" here
q.push(3);
q.push(4);
// but actually get "full" here
```

**Comment by aearly** [comment]
You are correct, this is misleading. I fixed this as a side effect of other changes in #704
