### ISSUE TITLE
[Discussion] How to test async tasks functions separately

### ISSUE THREAD

**Issue by hellboy81** [caolan/async#725]
In `async.waterfall` I need to test the only step that has global parameter dependency:

```js
var inputParameter = ...

async.waterfall([
function taskToTest(cb) {
   // We are using  inputParameter
  ...
  cb(err, firstTaskResult)
}
,
// Tisk task cannot/ should not be testsed
function taskShouldNotTest(firstTaskResult, cb) {
    // external hard-to-test dependencies are used
}
])
```

How? I don't know how to refactor this code to make first task function accepting inputParameter.

I can not test whole function / all steps due on hard-to-test dependencies.

**Comment by aearly** [comment]
Just change `taskToTest` so  you can partially apply it with `bind`

```
function taskToTest(inputParameter, cb) {
  ...
  cb(err, firstTaskResult)
}
```

Then you do:

```
async.waterfall([
  taskToTest.bind(null, inputParameter),
  function taskToNotTest (firstTaskResult, cb) {
  ...
```

Should be easy to test that single function now.

**Comment by hellboy81** [comment]
In public method of module there is the only code:

```js
async.waterfall([
m_func1,
m_func2,
...
]
], function(err){
   if(err) return callback(err)
   return callback()
})
```

All `m_func1`, `m_func2` are private and unit tested (with using `rewire`)

Should I write unit tests for this public method?

**Comment by aearly** [comment]
It's up to you to determine if you get value out of a test like that -- an "integration" test with all the tasks together.  Without knowing your use case here, it's impossible to determine.

**Comment by hellboy81** [comment]
OK, now  we have also infinite Nested Matrix from the Matrix: Reloaded!

**Comment by hellboy81** [comment]
```js
var m_secondStep = function m_secondStep(...) {
  // Both myFuncParam1 and firstStepResult should be available
  ...
}

mod.myFunc = function (myFuncParam1, ...) {
  async.waterfall([
    function firstStep() {
      cb(null, firstStepResult)
    }
    // null -> this - ??
    m_secondStep.bind(null, myFuncParam1),
    ...
  ])
}
```

**Comment by aearly** [comment]
If you define `m_secondStep` as:

```js
function m_secondStep(myFuncParam1, firstStepResult, callback) {
  ...
}
```

And then do what you did above, you should be able to test `m_secondStep` by itself.  Any parameters from the surrounding closure scope will have to be passed as arguments, so it's not coupled to that closure scope.

**Comment by hellboy81** [comment]
I have function as a async step:
```js
var m_asyncStepFunction = functionm_asyncStepFunction (item, cb) {
    item.myProp =  ....
   return cb()
}
```
This function should have `testable design`. Should I *ALWAYS* refactor it to allow to make `yields ` for stub?
```js
var m_asyncStepFunction = functionm_asyncStepFunction (item, cb) {
    item.myProp =  ....
   return cb(null, item)
}
```

**Comment by aearly** [comment]
I'm not sure what you're asking.
