### ISSUE TITLE
series and eachSeries won't work without callback

### ISSUE THREAD

**Issue by khanh-nguyen** [caolan/async#728]
## First try without callback:
```
function task1() {
    fs.readFile('foo.txt', function() {
        console.log('Task 1: long task');
    }); 
}

function task2() { console.log('Task 2: very quick'); }

var arr = [task1, task2];
async.series(arr, function() {
    console.log('All done');
});
```
Result: only task 1 was executed. 
```
$ node test.js
Task 1: long task
```

## Second try, with callbak
```
function task1(cb) {
    fs.readFile('foo.txt', function() {
        console.log('Task 1: long task');
        cb();
    }); 
}

function task2(cb) {
    console.log('Task 2: very quick');
    cb();
}

var arr = [task1, task2];

async.series(arr, function() {
    console.log('All done');
});
```
Result: everything is fine
```
$ node test.js
Task 1: long task
Task 2: very quick
All done
```
The same thing happens with `eachSeries`.
Why do I need that `cb`? What if I don't want to change my existing tasks? Is there any other way to make it work?
Thanks,

**Comment by khanh-nguyen** [comment]
Ah, I see that `series` uses `eachSeries`, which requires `iterator` to take a callback function. The index is incremented inside callback as shown [here](https://github.com/caolan/async/blob/master/lib/async.js#L152), so it won't work unless my tasks take a callback. 
Is there anyway to work around without adding callback to my tasks, @caolan ?

**Comment by khanh-nguyen** [comment]
Wow, I guess we need a way to tell when a task is done, so callback is not avoidable. I'd love to be proved incorrect though.

**Comment by mcasteller** [comment]
Hi, on the caolan main page there is a "Using ES2017 async functions" section, we can then understand that "all" async functions can use those. 
Can we update documentation in series section and others that do not work without callbacks? There might be people like me struggling with series in no-callback mode, until this post is found.

**Comment by aearly** [comment]
Anywhere were we accept a callback-style function, an `async` function should also work.  Just make sure that if you're using a compiler (e.g. TypeScript, Babel), it's set to preserve `async` functions.
