### ISSUE TITLE
`done` function gets reused between calls to async.parallel and fails

### ISSUE THREAD

**Issue by gabrielecirulli** [caolan/async#730]
I'm encountering this very weird error in my code:

```js
  load(callback) {
    // Reset the skills adapter before loading
    skills._reset();

    // Load sets and contents from the adapter
    async.parallel([
      // Load the sets
      (done) => {
        skills.getSets([], (sets) => {
          this.setState({ sets });
          done();
        });
      },

      // Load the contents
      (done) => {
        skills.getContents([], (contents) => {
          this.setState({ contents });
          done();
        });
      },
    ], callback);
  }
```

My `skills` object can load two types of resources `sets` and `contents`. The `load` function gets called at the start of the lifecycle of my component and also at specific points throughout its lifecycle when the values of `sets` and `contents` are known to have changed and needs to be reloaded.

On the first run, everything seems fine.

When it gets run the second time, however, it fails with this cryptic error:

```
Uncaught Error: Callback was already called.
```

I really couldn't understand what's going on. The error seems to be triggered when `done()` is called in the first "task", the one that loads the sets.

Scouring through the source code I found that the error itself happens because `async.each` uses `only_once` around each of the callbacks it passes to its iterators, and `async.parallel` makes use of `async.map` which in turn loops back to `each`.

That tells a bit about where the error comes from, but doesn't explain *how* it's happening.

Unless I'm really missing something big, between two different executions of `load` there should be nothing in common: `async.parallel` would be called with a different array of different task functions that run and call different `done` functions.

However, if I change the first task as such:

```js
      // Load the sets
      (done) => {
        skills.getSets([], (sets) => {
          this.setState({ sets });
          if (window.done) {
            window.done2 = done;
          } else {
            window.done = done;
          }
          done();
        });
      },
```

and then check whether `window.done === window.done2`, I get `true`!

Now, that condition would easily happen if `skills.getSets` would somehow be calling the callback twice, but I extensively made sure that that's not the case, even just by having a counter that gets increased every time before `done` is called and checking that, when I use it for the second time and it fails, the counter has counted to 2.

Am I missing something REALLY big, or is there something weird going on?

**Comment by aearly** [comment]
Your last paragraph doesn't make sense.  It sounds like you conclusively verified that `skills.getSets()`  *is* calling its callback twice.

**Comment by gabrielecirulli** [comment]
Sorry for being unclear, what I meant is that I verified it does not call twice. The counter I was talking about goes to 1 when the `load` method is called at the start of my component's lifecycle, and goes to 2 only after my interaction. This means that the callback is not being accidentally called multiple times, or else the count would be 4.

Also, I'm guessing here but might this be related to #535?

**Comment by aearly** [comment]
When you run 

```js
        skills.getSets([], (sets) => {
          if (window.done) {
            window.done2 = done;
          } else {
            window.done = done;
          }
          done();
        });
      },
```

in isolation (outside of async) what happens?

**Comment by gabrielecirulli** [comment]
I couldn't run the exact same code since `done` comes from async but I ran this

```
    skills.getSets([], (sets) => {
      this.setState({ sets });
      if (window.done) {
        window.done2 = 2;
      } else {
        window.done = 1;
      }
    });
```

And when I check, only `window.done` is set.

**Comment by gabrielecirulli** [comment]
I really cannot tell what or where it's happening, but the symptoms seem to allude to the fact that something might be leaking between the two executions of `async.parallel`.

**Comment by aearly** [comment]
Maybe something odd happens when both `skills.getSets()` and `skills.getContents()` are called in parallel.

**Comment by gabrielecirulli** [comment]
I've been trying to figure that out but everything seems to happen unrelated to each other. Th first time, both `getSets` and `getContents` get called and go to completion. The second time only `getSets` gets called and everything crashes when it calls `done()`, without the corresponding result body in `getContents` being run and getting a chance to call `done()`.

I'm really clueless on this one, it's very weird.

**Comment by gabrielecirulli** [comment]
The weird thing is that the anonymous function that gets the `done` callback passed as argument is not influenced at all by `getSets` and `getContents` (as in they are unaware and don't affect `done()`), so it seems like the same `done()` function as the previous cycle is coming in to the anonymous function twice somehow.

**Comment by gabrielecirulli** [comment]
Ok it does seem to be something in the way `getSets` and `getContents` will work.

**Comment by gabrielecirulli** [comment]
Ok, you were right, I had events accidentally firing multiple times inside of `getSets` and `getContents`. Async was not accidentally recycling callbacks, but my thing was covertly keeping track of them and on the second load it would call both the original and the new callback.

Sorry for the hassle. It turns out it was a problem on my end! Thanks for the help!

**Comment by charlierudolph** [comment]
Please close this, if this has been resolved
