### ISSUE TITLE
.each issue

### ISSUE THREAD

**Issue by ecabrera1** [caolan/async#737]
So I'm using each and I can't .push a new item to the returned doc.

async.each(array, function(returnedDocs, callback) {
     Model1.BuildDocIntoMongo(returnedDocs, function(err, newDoc) {
          Model2.UseNewDocDataToAddToMongo(newDoc, function(err, ReturnedArrayOfOBJIds) {
               newDoc.newList.push(ReturnedArrayOfOBJIds); //Returns an error "TypeError: Cannot call method 'push' of undefined"
          })
     })
})

I can't figure out why this is not working. I can console out ReturnedArrayOfOBJIds, and newDoc but I can't push a new object to newDoc. Any help would be fantastic.

**Comment by aearly** [comment]
What does `newDoc.newList` evaluate to?

**Comment by ecabrera1** [comment]
An array of objectIds ('XXXXX..', 'YYYYYY...')

**Comment by ecabrera1** [comment]
I figured it out. I was being mental. Thank you for the quick response.

**Comment by charlierudolph** [comment]
Please close this if this is no longer an issue
