### ISSUE TITLE
async.waterfall is showing unexpected behaviour

### ISSUE THREAD

**Issue by deepaksisodiya** [caolan/async#742]
I am using
var obj = {};
async.waterfall([
    function(callback) {
        fetching data from database and set it to 'obj'
        callback(null, obj);
    },
    function(obj, callback) {
      fetching data from database and set it to 'obj'
      callback(null, obj);
    },
    function(obj, callback)) {
        fetching data from database and set it to 'obj'
        callback(null, obj);
    }
], function (err, obj {
    res.json(obj);    
});

but last two block of async function is not working , it is working like last two bloack of function does not exist. so i did this

var obj = {};
async.waterfall([
    function(callback) {
        fetching data from database and set it to 'obj'
        callback(null, obj);
    },
    function(obj, callback) {
      fetching data from database and set it to 'obj'
      callback(null, obj);
    },
    function(obj, callback)) {
        fetching data from database and set it to 'obj'
        callback(null, obj);
    },
   function(obj, callback)) {
        doing nothing
        callback(null, obj);
    },
    function(obj, callback)) {
        doing nothing
        callback(null, obj);
    }
], function (err, obj {
    res.json(obj);    
});

this is working fine but the first one should work.
if i am doing something wrong, let me know.

**Comment by aearly** [comment]
The problem must be in your `fetching data from database and set it to 'obj'` code you're omitting.   It's probably calling-back twice.
