### ISSUE TITLE
Explain your currying logic

### ISSUE THREAD

**Issue by vevo-kurt-snyder** [caolan/async#745]
The library works well so far, but some functions are quite hard to get running because it's not clear what currying logic to follow when invoking something composed from your library.  Some work after many guesses, some still don't work -- any more details available on this?  Thanks.

**Comment by aearly** [comment]
I'm not sure what you mean by "currying logic" -- which functions can be easily curried?  Which take optional params, are variadic etc.?

**Comment by ilinkuo** [comment]
Chiming in here. I'd really like async.js to consider following Ramdajs's API as an example:
* Callback as the first argument, object to be operated on as the first argument
* partial functions are automatically curried by returning a function

**Comment by aearly** [comment]
@ilinkuo If you want that kind of stuff, check out what has been done with [lodash-fp](https://github.com/lodash/lodash-fp).  You can do a lot with `_.curry` and `_.rearg`, but it won't work with variadic functions or functions with optional parameters.

Also note that having the end callback as the first argument breaks with node.js conventions, and curried/re-arged functions are a tad slower.

**Comment by aearly** [comment]
I recently update the docs to denote which functions take optional callbacks.

With most functions you can `_.curry(_.rearg(async.each[1, 0,  2]), 3)` (like lodash-fp)  to get something like what @ilinkuo describes.  Doing this by default is a performance hit I'd like people to be able to opt in to.

Open a new issue if you want something more specific clarified.
