### ISSUE TITLE
Is there a reason that parameters expected from functions passed in async.series are different from convention of nodejs?

### ISSUE THREAD

**Issue by techsin** [caolan/async#746]
I believe the convention in nodejs is like this

function abc (err, callback) {...}

however, async.series expect functions to take callback as their first argument.like so..

function abc (callback, err ) {...}

I'm new to asyncjs and learning about it, and wasn't able to find it mentioned anywhere. For example in other libraries like bluebird this convention is followed.

**Comment by aearly** [comment]
I think you're  getting the functions mixed up.  `series` expects the functions in the list to only take in a *single* argument -- the callback.  The callback  function `series` will pass will be of the form `function (err, data, ...) {`.

**Comment by techsin** [comment]
http://stackoverflow.com/questions/29595449/how-promisifyall-works-or-what-are-the-requirements-for-it-work

http://stackoverflow.com/questions/29594383/how-do-you-handle-error-in-asyncjs
