### ISSUE TITLE
Add observability (i.e., like vasync).

### ISSUE THREAD

**Issue by djensen47** [caolan/async#749]
vasync has some great features, especially for debugging
- observability
- ~~dtrace support~~

However, async is much more feature rich and actively worked on. Async is also intended to be used in the browser, which makes adding these features questionable.

What if there were some sort of plugin system to add this type of support to async?

Maybe @davepacheco can chime in about vasync.

**Comment by djensen47** [comment]
:jeopardy theme song:

**Comment by aearly** [comment]
vasync has a slightly different design philosophy -- return an object from each of the methods, and incrementally update it.  This comes with a slight performance cost.  I also feel you could accomplish observability in a layer on-top of async by wrapping your iterating functions with a decorator that reports results.  That way you could get observability when you need it, but have maximum performance otherwise.

Also, what does vasync do differently that allows it to support dtrace?

Merging a completely different library is also non-trivial.

**Comment by djensen47** [comment]
Turns out I was mistaken on the dtrace-provider support in vasync. It's actually an open issue on vasync to include it. So, nevermind that,

I mostly meant "merging" in the sense of merging ideas. Specifically on observability and I like this idea of wrapping the iterating functions.

It might be interesting if there were a flag to enable/disable observability in async.

**Comment by jclulow** [comment]
As a long-time user of, and occasional contributor to, {{vasync}}, I cannot say I've ever noticed a measurable performance difference between the two libraries.

I would be exceptionally keen to see quantified the performance impact that building instrumentable, debuggable, software has in practice.  Where are the benchmarks and analysis that demonstrate the performance impact? I am especially curious about real-world workloads where the completion delay for asynchronous operations generally dwarfs the time spent on the processor.

**Comment by jpattisoninc** [comment]
You can create a higher level scope array/object and push success/error values before each individual function callback is executed, then do whatever you want with the report/result object when the async function completes. That's as long as you're functions actually return success or error. 
 
```javascript
var async = require('async');

var report = [];

function step_1(callback) {
    var fake_func_result_1 = { function_name: 'STEP_1', status: 'SUCCESS' };
    report.push( fake_func_result_1 );
    callback( null, fake_func_result_1 );
}

function step_2(callback) {
    var fake_func_result_2 = { function_name: 'STEP_2', status: 'SUCCESS' };
    report.push( fake_func_result_2 );
    callback( null, fake_func_result_2 );
}

function step_3(callback) {
    var err = { function_name: 'STEP_3', status: 'SOME ERROR OCCURED'};
    report.push( err );
    callback( new Error({ function_name: 'STEP_3', status: 'SOME ERROR OCCURED'}) );
}

async.series([

        function(callback) {
            step_1(callback);
        },

        function(callback) {
            step_2(callback);
        },

        function(callback) {
            step_3(callback);
        }

    ],
    function(err, results) {
        if (err) {
            //////////////////////////////////////////////
            // ON ASYNC PROCESS ERROR
            //////////////////////////////////////////////
            report.push( { 'PROCESS_ERROR': results } );
            console.log('[PROCESS REPORT] ' + JSON.stringify(report, null, 4));

        } else {
            //////////////////////////////////////////////
            // ON ASYNC PROCESS SUCCESS
            //////////////////////////////////////////////
            report.push( { 'PROCESS_SUCCESS': results } );
            console.log('[PROCESS REPORT] ' + JSON.stringify(report, null, 4));;

        }
    });
```
