### ISSUE TITLE
0.9.2 version vs 0.9.0 version ?

### ISSUE THREAD

**Issue by smartmouse** [caolan/async#752]
Hello, the official version in your website is 0.9.0, but if we git clone , it has 0.9.2 version.
Are you going to publish the 0.9.2 version soon? What are major differences between the two versions?
I found that your packaged tests works well on 0.9.2 but there are some failures on 0.9.0.

Thanks in advance for your help.

**Comment by aearly** [comment]
0.9.2 was published today!
