### ISSUE TITLE
iterator counter issue

### ISSUE THREAD

**Issue by martingg88** [caolan/async#757]
any idea how to solve the following issue?

var index = 1;
var parallel = [];

for(i=0; i < 3; i++){
    
  parallel.push(function(callback){
        console.log(index); -> here should give me 1, 2, 3, but it give me only 3 instead. Any idea?
   }); 

index++;
}

async.parallel(parallel, callback);

**Comment by aearly** [comment]
It's a common closure scope problem.  The `index` variable is shared by all the parallel functions.

You'll have to capture it:

```
for(i=0; i < 3; i++){
  (function (index) 
    parallel.push(function(callback){
      console.log(index);
    });

  }(i));
}
```

or do something else:

```
var parallel = _.range(3).map(function (index) {
  return function (callback) {
    console.log(index);
  }
});
```

**Comment by martingg88** [comment]
thanks.
