### ISSUE TITLE
Minor performance issue

### ISSUE THREAD

**Issue by DotsElshad** [caolan/async#758]
Hello,

when going from 0.9.0 to 0.9.2 I noticed the following change: f5d804f068e9950a38e34c050842cf2400cc1c00

The problem here, is that q.process() is called "q.concurrency" times. But it should suffice to call it Math.min(q.tasks.length, q.concurrency) times.

OK, this is a minor performance problem. But if q.concurrency happens to be Infinity then it actually produces an endless loop. Which it didn't before. Arguably, "concurrency = Infinity" is not a very sensible case.

**Comment by aearly** [comment]
Thanks for the code review.

**Comment by DotsElshad** [comment]
Thank you very much!
It lead to a bug in our software, but it was wrong usage of "async" on our side ("concurrency = Infinity" really makes not much of a sense).
