### ISSUE TITLE
forEachOf from npm

### ISSUE THREAD

**Issue by jordonias** [caolan/async#760]
`forEachOf` is mentioned in the documentation but is not included in the code I am getting from `npm install async`.

It does not seem to be in the 0.9.2 zip release.

Edit: looks like this is in 0.10, when will this be published to `npm`?

**Comment by aearly** [comment]
Yep, it was merged yesterday, might do a 0.10.0 release today.

**Comment by jmls** [comment]
please ;) I just spent some time trying to figure out why forEachOf wasn't working ;)

**Comment by beaugunderson** [comment]
@aearly tangential, but if we release can we bump to 1.0 so we're semver-friendly too? :)

**Comment by aearly** [comment]
Hmnn, it might be time for 1.0!  There are some breaking PRs and features that make sense to add (#696, #118, using _once() on all callbacks, optional callbacks, all the queue stuff) that I wanted to save for 1.0, but I suppose those could go into a 2.0 release later.

**Comment by aearly** [comment]
1.0.0  published!
