### ISSUE TITLE
async.each array modification after iteration

### ISSUE THREAD

**Issue by jnam** [caolan/async#761]
Hi,

I believe I found a behaviour in async.each that is a tad bit counter-intuitive in 0.9.2.

I call async.each on an array (call it "arr") with 2 items. When async finishes iterating through the 2 items, I add more items in the callback. Since it is after async has FINISHED iterating through the array, I do not expect further action from async, least of all process the newly added item. However, async moves on to the newly added item and processes it, calling the callback again. The effect can vary from an infinite loop to "Callback was already called" depending on how async is used, but this means I have to remember to preserve the array as it is, if it is ever used in an async.each call. And since arrays seem to be passed around as pointers in Javascript, this can be tricky.

I believe this behaviour can be prevented in the "_each" function if, instead of checking the array length on each iteration, store the length of the array at the time of invocation and use that as loop-termination condition, like so:

    var _each = function (arr, iterator) {
        var arrLength = arr.length;
        for (var i = 0; i < arrLength; i += 1) { 
            iterator(arr[i], i, arr);
        }    
    };

I believe this is faster, as well. This behaviour is not seen in 0.9.0, probaby because for arrays, _each function uses Array.prototype.forEach.

Please let me know what you think.

Thank you.

**Comment by aearly** [comment]
Should be fixed as of 3ffbf2b, the length is set once at the beginning of the iteration.
