### ISSUE TITLE
bug async.series

### ISSUE THREAD

**Issue by flybaby** [caolan/async#773]
hello

I stand Julien Mutzenhardt, async I use for my project and following resettlement my async nodes modules, function async.series no longer works.

The function launches the first function defined in tasks and then stops without starting the callback function and there is no error. With async.parallel function function works again?

I effecuté a git revert to commit 1b258fb79db17ea94e2f6af2372b85f9fef37258 and functions series works again, the following commits the bug returns if it can help.

Sincerely,

Julien Mutzenhardt

**Comment by aearly** [comment]
Do you have some example code that reproduces the bug?  `series` was made more strict in the last release.

**Comment by flybaby** [comment]
YEs, here's the piece of code (be indulgent I started in nodejs lol)

 async.series([
            // load config JARVIS
            function (callback) {
                callback(load_config(), 'load config JARVIS : OK');
            },
            // load LIB JARVIS
            function (callback) {
                callback(load_lib(), 'load lib JARVIS : OK');
            },
            // initialization ERROR
            function (callback) {
                callback(JARVIS.lib.error.init(), 'initialization ERROR : OK');
            }],
        //callback
        function (err, msg) {
            if (err) {
                throw new Error(err);
            }
            for (var id in msg) {
                if (msg.hasOwnProperty(id)) {
                    console.log(msg[id]);
                }
            }
            console.log('Initialisation OK');
            return null;
        });

FYI, I code in "use strict" and I'm on Mac OS X and I installed the latest version of node (v0.12.4).

**Comment by aearly** [comment]
What do `load_config()`, `load_lib()` and `JAVRIS.lib.error.init()`  return?   If they return anything they will cause the series to end because it will be considered an error (the first param of a callback).

**Comment by flybaby** [comment]
excuse me

load_config (), load lib () and JARVIS.lib.error.init ()
return null if no error otherwise an error message {string}
But in the bug, the callback function is never called someting be returning functions.

**Comment by aearly** [comment]
Which callback is never called?

I also realize that your code doesn't really need `async.series`.  Nothing you are doing is actually asynchronous.   Before it was roughly equivalent to:

```
load_config();
load_lib();
JARVIS.lib.error.init();
console.log('Initialisation OK');
```

One of the changes made was automatic deferral of tasks passed to things like `series` and `eachSeries`.  If you were relying on that callback being called on the same tick, it will now break.

**Comment by flybaby** [comment]
thank you for your reply, actually I know my code is not really asynchronous equivalent to:

load_config ();
load_lib ();
JARVIS.lib.error.init ();
console.log (Initialization OK ');

What I want to do is that it stops the call of each function (load_config ()
load_lib () JARVIS.lib.error.init ()) if one of the functions references an error

**Comment by aearly** [comment]
I that case I would just have your functions throw errors and do:

```
try {
  load_config();
  load_lib();
  JARVIS.lib.error.init();
} catch (e) {
  console.log(e.message);
} finally {
  console.log('Initialisation OK');
}
```

No need to over-complicate things with `async.series`.
