### ISSUE TITLE
async.waterfall context parameter

### ISSUE THREAD

**Issue by yuklai** [caolan/async#776]
Is there anyway we can pass down the context in async.waterfall currently?
For instance:

    function TestObjectClass() {}
    TestObjectClass.prototype.test = function(callback) {
        assert(this); // this is null
    };
   
    var async = require('async');
    var testObject = new TestObjectClass();
    async.waterfall([
        testObject.test
    ]);

I'd like to be able to the `testObject` as the context so when `TestObjectClass.test` is `applied`, we can get a valid `this`. Right now the workaround is to create anonymous function for each waterfall function. What do you think?

**Comment by aearly** [comment]
[You can use Function.bind](https://github.com/caolan/async#binding-a-context-to-an-iterator) as another way to pass a context, in addition to creating an anonymous function.

You can also use `_.bindAll()` from lodash/underscore.

```
_.bindAll(testObject, "test", "test1", "test3", ...)
```

**Comment by yuklai** [comment]
Thanks, I read that section before but didn't click when I was looking into this particular problem.
