### ISSUE TITLE
Feature Request: Stateful series flow control making common flow situations easier

### ISSUE THREAD

**Issue by owenallenaz** [caolan/async#780]
At my job we've created a stateful flow object to help assist with some common flow control problems we run into. We've already written this and think this could be useful in async core. If you're interested I can submit a pull request with unit tests.

Here's a rundown of what it does:

* Provides mechanism to short-circuit a series with non-error conditions. Sometimes we want to jump to the end without an error.
* Allow access to data returned by the series from any previous function. This is similar to waterfall, but using waterfall requires us to continually pass along everything and that gets quite cumbersome.
* Provides a mechanism to access the data of whatever the "last" function returned. If the last function was a short-circuit return, it returns that, otherwise it returns the last function in the series' return.
* Preserves all async semantics: handles array of functions or object of functions, if the first argument of a cb is non-null it skips all further series functions and proceeds to the final CB, final callback recieves `err, results` and the structure of those is identical to what async returns out of the box. In practice this means that switching a native `async.series` with our `async.Flow` will immediately work with no change in behaviors.

Semantics:

* `flow.data` is an object that stores the data of the returns. It is structurally identical to the `results` object that the final callback in `async.series` gets, but it's accessible at each step along the way.
* `flow.last` is whatever the return was from the last function executed. If you're mid-way through a series, it's the previous functions return. If you're at the end of the series, it may a short-circuit methods return or the final callback's return depending on the flow worked out.
* `flow.halt(optional_arg1, optional_arg2, cb)` halts the flow and skips to the final callback function. `flow.last` will be set to the values returned. The final cb will still recieve `err, results` with whatever data it was able to get so far.
* `flow.lastCb(cb)` - Wraps the final callback, instructing it to pass along the return value of the last return, in normal situations this is the return of the last series function. In short-circuit, it's the return from the short-circuit. This makes it easy to keep all of our logic within our async series functions, using the final callback simply for piping and control flow. This helps with readability and refactoring.

Here's an example showing some of the values along the way using array syntax:

```
var flow = async.Flow();

flow.series([
	function(cb) {
		cb(null, "foo");
	},
	function(cb) {
		// flow.last === "foo"
		// flow.data === ["foo"]
		cb(null, "bar", "baz");
	},
	function(cb) {
		// flow.last === ["bar", "baz"]
		// flow.data === ["foo", ["bar", baz"]]
		cb(null, "qux");
	}
], function(err, results) {
	// err === null
	// flow.last === "qux"
	// results === ["foo", ["bar", "baz"], "qux"]
	// flow.data === results
});
```

Here's the same example with object syntax:

```
var flow = async.Flow();

flow.series({
	"first" : function(cb) {
		cb(null, "foo");
	},
	"second" : function(cb) {
		// flow.last === "foo"
		// flow.data === { first : "foo" }
		cb(null, "bar", "baz");
	},
	"third" : function(cb) {
		// flow.last === ["bar", "baz"]
		// flow.data === { first : "foo", second : ["bar", baz"] }
		cb(null, "qux");
	}
}, function(err, results) {
	// err === null
	// flow.last === "qux"
	// results === { first : "foo", second : ["bar", "baz"], third : "qux" }
	// flow.data === results
});
```

Here's an example simulating rendering a blog page:

```
var getPostHtml = function(id, cb) {
	var flow = new async.Flow();
	
	flow.series({
		"post" : function(cb) {
			api.posts.findById(id, function(err, post) {
				if (err) { return cb(err); }
				
				if (post === null) {
					return flow.halt({ success : false, message : "Post does not exist" }, cb);
				}
				
				cb(null, post);
			});
		}
		"author" : function(cb) {
			api.authors.findById(flow.data.post._id, function(err, author) {
				if (err) { return cb(err); }
				
				if (author === null) {
					return flow.halt({ success : false, message : "Author does not exist." }, cb);
				}
				
				cb(null, author);
			});
		},
		"template" : fs.readFile.bind(null, __dirname + "/templates/post.html", { encoding : "utf8" }),
		"result" : function(cb) {
			var html = goatee.fill(flow.data.template, {
				author : flow.data.author,
				post : flow.data.post
			});
			
			cb(null, { success : true, html : html });
		}
	}, flow.cbLast(cb));
}

app.get("/post/", function(req, res) {
	getPostHtml(req.query.id, function(err, result) {
		if (err) { // do stuff with errors }
		
		if (result.success === false) {
			return res.send(result.message);
		}
		
		res.send(result.html);
	});
});
```

Here's another example authenticating a user-login. Here we can see common short-circuiting decisions that are made such as if the e-mail doesn't exist or the password is invalid.

```
var flow = async.Flow();

flow.series({
	"user" : function(cb) {
		apis.users.find({ email : req.email }, function(err, user) {
			if (err) { return cb(err); }
			
			if (user === null) { return flow.halt({ success : false, message : "No user registered with that e-mail" }, cb) }
			
			cb(null, user);
		});
	},
	"checkPass" : function(cb) {
		bcrypt.compare(req.password, flow.data.user.passwordHash, function(err, match) {
			if (err) { return cb(err); }
			
			if (match !== true) {
				return flow.halt({ success : false, message : "Incorrect e-mail or password." }, cb);
			}
			
			cb(null);
		});
	},
	"history" : function(cb) {
		api.loginHistory.insert({ user : flow.data.user._id, date : new Date() }, cb)
	},
	"result" : function(cb) {
		req.session.user_id = flow.data.user._id.toString();
		
		cb(null, { success : true, redirectUrl : req.redirectUrl || "/" });
	}
}, flow.cbLast(cb));
```

Let me know if you think this would be useful in core.

**Comment by aearly** [comment]
I feel like this isn't unique enough from  `auto` to be worth adding.  I like that you can exit the flow early, but I dislike that each task function has to be defined in the scope of the `flow` instance to use its features.

I think `flow` would be worthy of its own npm module, though.
