### ISSUE TITLE
Breaking change in v1.1.0

### ISSUE THREAD

**Issue by ljharb** [caolan/async#782]
[caolan/forms](https://github.com/caolan/forms)’ tests pass on `v1.0.0`, but break on `v1.1.0` and `v1.2.0`.

I'm still digging for the bug, but this means that `v1.1.0` should instead have been `v2.0.0` - once we find the fix, both the 1.1 and 1.2 branches will need a patch release to revert the breakage.

**Comment by ljharb** [comment]
Using `git bisect`, bf71c8c417dea9c1fd1f6836cc573b26a572e9ce appears to be the commit that broke it.

**Comment by aearly** [comment]
Do you have an isolated test case for what is breaking?  I'm apprehensive there's a widely used corner case in async that async's tests don't cover...

**Comment by ljharb** [comment]
If you clone the forms repo, and run `npm install && npm install async@1.1.0 && node test/test-render.js` you'll see the 4 tests that fail.

The gist seems to be "expected 4 assertions, got 0" which is implying that a previous async.forEach/forEachSeries call would iterate 4 times whereas now it doesn't iterate.

**Comment by aearly** [comment]
The issue is that the forms tests are relying on `async.eachSeries` calling its callback on the same tick if there is a single synchronous validator in `field.bind`.

**Comment by ljharb** [comment]
OK - I'll certainly correct that, but "same tick" and "next tick" changes are definitely a breaking change.

**Comment by ljharb** [comment]
Thanks!

**Comment by aearly** [comment]
Sure thing.  v1.1.1 and v1.2.1 published
