### ISSUE TITLE
async.cargo does not expose payload anymore

### ISSUE THREAD

**Issue by pierre-elie** [caolan/async#783]
It seems an `async.cargo` does not expose its `payload` property anymore (probably due to its refactor with queue).
`payload` was not only readable but could also be used to resize the cargo on the fly.

Any chance to get it back? Or at least remove it from documentation, it’s a breaking change.

Thanks

**Comment by aearly** [comment]
Related to #740,  #744

**Comment by aearly** [comment]
Fixed in 7b3c5c2
