### ISSUE TITLE
final callback for async.each is never fired

### ISSUE THREAD

**Issue by ken860622** [caolan/async#784]
Hi,

I am writing a program which read all the files in a folder and rename them and copy to another folder.
My code is like:

```js
async.waterfall([
			function(next){
				fs.readdir(tmpPath, function(err, files){
					next(err, files)
				});
			},
			function(files, next){
				async.each(files, 
                                function(file){
					fileRetrieverFS.renameFiles(tmpPath, file, region);
				}, 
				function(err){
					console.log('done');
					next(err);
				});
			},
			function(next){
				console.log('read');
				fs.readdir(tmpPath, function(err, files){
					next(err, files)
				});
			}],
			function(err, results){
				if (err) console.log(err);
			}
		);
```

The console.log('done'); and next(err) is never called after all files are successfully renamed.
How can I trigger the final callback for this case?

Thanks!

**Comment by aearly** [comment]
You're not calling the callback passed to the iterator function of `async.each`.

```js
async.each(files, function(file){
// needs to be
async.each(files, function(file, callbabk){
```

If you don't need asynchronous iteration, just use something like `Array.forEach` or `Array.map`.
