### ISSUE TITLE
how to do a simple for loop

### ISSUE THREAD

**Issue by perrin4869** [caolan/async#787]
I've been trying to figure out how to do a simple for loop, say, from 1 to 10, and have a callback when the loop is done. For example:

```
for(i=1; i<=10;i++) {
    User.insert({ username: "user" + i }, callback)
}

runWhenDoneInserting();
```

I figured that it could be done using the `async.each` method, but that would mean building an array with all the elements I wanna loop, and that seems both wasteful (what if I want to execute a loop 1M times?), and also the array building code is quite declarative...

```
var i = [];
for(var j = 1; j<=10;j++) {
   i.push(j);
}

async.each(i,foo,callback);
```

 Is there any way to accomplish the above without having to manually create the iteration array?
Thanks!

**Comment by aearly** [comment]
`async.times` will do what you want.  Just make sure to call the passed callback for each iteration.

**Comment by perrin4869** [comment]
Oh I see! Thanks! Should have read the docs a bit more carefully ^^;;
