### ISSUE TITLE
series/waterfall callback is added to stack of last fn's done() call

### ISSUE THREAD

**Issue by mattfysh** [caolan/async#788]
Can't seem to find this problem in the docs/issues, it seems the last fn's call to done() sits beneath the callback function in the stack, meaning its able to try/catch any errors encountered in the callback. Simple example:
```
async.series([function(done) {
	try {
		done();
	} catch(e) {
		console.log('caught error from callback')
	}
}], function(err, result) {
	throw new Error('callback threw');
});
```
In my case, I'm using the "wd" library and my last fn in the series array is:
```
browser.init({browserName: 'chrome'}).then(done);
```
In my callback, I'm calling mocha.run() which throws an error if the coffeescript modules cannot compile. With the async + wd/q stack, the error is being swallowed.
Is there another way I can use the async lib to prevent this, and ensure that all thrown errors in the callback function always bubble up to the process? thanks!

**Comment by aearly** [comment]
This is a tricky problem because `q` and other promise implementations wrap the `onResolved` handler in try/catch, which is a bad idea if you call a callback in the handler, for the exact problem you're running in to.

One thing to do would be to defer the actual `done()` call:

```js
browser.init({browserName: 'chrome'}).then(function ()  {
  setTimeout(done, 0);
});
```

That way, the `mocha.run()` call gets a new call stack and the error will bubble all the way up.

**Comment by mattfysh** [comment]
Thanks :) I ended up adding the setTimeout to get around this issue, though I wonder if this should be baked into the async lib itself? so as to prevent async functions from being able to capture callback errors this way.

**Comment by aearly** [comment]
I'd rather not do that -- it adds an unnecessary deferral, and I've been trying to minimize those.  Also, `try`/`catch`ing your callback call is bad practice.  I'm always trying to weigh ease of use with disallowing bad practices, but this one comes with a performance hit....

You can easily define a decorator to apply the deferral workaround more broadly:

```js
function newStack(fn) {
  return function () {
    setImmediate(fn);
  };
}

//...
browser.init({browserName: 'chrome'}).then(newStack(done));
```
