### ISSUE TITLE
async.queue does not have a function that means end when all tasks are drain

### ISSUE THREAD

**Issue by yuklai** [caolan/async#795]
Hi, 
I'm using the queue a lot and notice that in the case when no task is added, drain doesn't get called, so I ended up having to write a wrapper to check if the queue's length is 0 then exit right away. All the functions are implemented according to the spec, but I feel such a function that waits for all tasks are finished or when no task is pushed is convenient. Any thoughts on adding this to the default implementation of queue? Thanks! 

    ProcessQueue.prototype.endWhenAllTasksDone = function(err) {
        if (this.queue.length() === 0) {
            // when the queue's length is 0, drain is not called.
            // hence, we simply exit here.
            this.callback(err);
        } else {
            this.hasEnded = true;
            this.error = err;
        }
    };

**Comment by aearly** [comment]
`drain()` should be called when you push an empty array to an empty queue:

https://github.com/caolan/async/blob/master/test/test-async.js#L3286

Do you have some example code that is not working?
