### ISSUE TITLE
async.parallel - allowing all functions to finish even if error is thrown

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#798]
Hello, thanks for your wonderful lib !!

One question I have - is it possible to pass async.parallel a parameter to tell it to not immediately call the final callback when there is an error passed ```callback(err,null)``` by one of the parallel functions?

I want to be able to put all the errors in an array + I also want to allow all the functions to complete, even in the case of an error in one or more of them.

Does this make sense? is it already possible?

**Comment by aearly** [comment]
Very similar to #531 and  #675.  We're still deciding on the best way to do this, and what the API should look like...

**Comment by ORESoftware** [comment]
all you need is optional boolean as first arg!!

:)

that's my thinking after thinking about it for 3 seconds
