### ISSUE TITLE
async.auto specify a specific result be passed to the callback.

### ISSUE THREAD

**Issue by charlierudolph** [caolan/async#799]
I'd like the ability to specify that the callback receive a specific task's result instead of the object that holds the results of all tasks. 

Currently I would need something like
```js
function performTasks(done) {
    async.auto({
        task1: function(callback){
            callback(null, 'task1 result');
        },
        task2: function(callback){
            callback(null, 'task2 result');
        },
        task3: ['task1', 'task2', function(callback, results){
            callback(null, 'task3 result');
        }]
    }, function(err, results) {
        if (err) {
            done(err)
        } else {
            done(null, results.task2)
        }
    });
}
```

I would like to have an easier way to do this.
Maybe have a reserved task name the allows me to specify what result gets passed to the callback
```js
function performTasks(done) {
    async.auto({
        task1: function(callback){
            callback(null, 'task1 result');
        },
        task2: function(callback){
            callback(null, 'task2 result');
        },
        task3: ['task1', 'task2', function(callback, results){
            callback(null, 'task3 result');
        }],
        return: 'task2'
    }, done);
}
```

Alternatively I would be good with creating a new async helper method that aids in this process something like
```js
async.extractFromResult(key, callback) {
  return function(err, result) {
    if(err) {
      callback(err);
    } else {
      callback(null, result[key]);
    }
  };
}


function performTasks(done) {
    async.auto({
        task1: function(callback){
            callback(null, 'task1 result');
        },
        task2: function(callback){
            callback(null, 'task2 result');
        },
        task3: ['task1', 'task2', function(callback, results){
            callback(null, 'task3 result');
        }],
        return: 'task2'
    }, async.extractFromResult('task2', done));
}
```

**Comment by aearly** [comment]
I like the idea -- oftentimes I find myself only wanting a single result from an `auto` invocation.  I think the `return:` task is a bit odd -- I think `extractFromResult(key, callback)` is cleaner, and more re-usable.

I'm somewhat against adding this to the mainline async library (the kitchen sink is getting a bit full), but this would be a perfect addition to [acomb](https://github.com/aearly/acomb), which already has a few helpers that make using `auto` easier.

**Comment by aearly** [comment]
In fact, you can do this today with `acomb.after`:

```js
function performTasks(done) {
    acomb.after(_.partial(async.auto, {
        task1: function(callback){
            callback(null, 'task1 result');
        },
        task2: function(callback){
            callback(null, 'task2 result');
        },
        task3: ['task1', 'task2', function(callback, results){
            callback(null, 'task3 result');
        }]
    }, _.property("task2"))(done);
}
```

... but `extractFromResult()` is more straightforward...

**Comment by charlierudolph** [comment]
Okay. I'm fine having this somewhere else. I may start a new repo thats just dedicated to this type of error handling. Something else that I've found myself to need a couple times is 

```js
resultNotEmpty(callback) {
  return function(err, result) {
    if(err) {
      callback(err);
    } else {
      callback(null, result.length > 0);
    }
  };
}
```

**Comment by charlierudolph** [comment]
Just put these into https://github.com/charlierudolph/async-handlers. Work well in certain cases.
