### ISSUE TITLE
async.auto tasks *will* complete, eventually, if they pass an error to their callback

### ISSUE THREAD

**Issue by mhobbs-8B** [caolan/async#811]
The docs for async.auto states that
> If any of the functions pass an error to their callback, it will not complete (so any other functions depending on it will not run), and the main callback is immediately called with the error.

However, that would only be true if the main callback throws an exception as a result of the error. If no exception is ever thrown, then the remainder of the task *will* execute when the main callback returns. For example, this test case:
```javascript
var async = require("async");

var tasks = {
  taskA: function taskA(callback) {
    var err = true;
    if (err) {
      console.log("taskA sending error");
      callback(new Error("taskA error"));
    } 
    console.log("taskA continuing after error");
    callback(null, "taskA result");
  },
  taskB: ["taskA", function taskB(callback, results) {
    console.log("in taskB: %j", results);
    callback(null, "taskB result");
  }]
};

async.auto(tasks, function finalCallback(err, results) {
  if (err) {
    console.log("finalCallback err:", err);
    return;
  } 
  console.log("finalCallback results: %j", results);
});
```
generates the following output:
```
taskA sending error
finalCallback err: [Error: taskA error]
taskA continuing after error
in taskB: {"taskA":"taskA result"}
```

**Comment by aearly** [comment]
You need a `return` in the `if (err) {` block in blockA.  The error will stop `auto` from kicking off further tasks, but it won't stop a function from executing unless you return.

**Comment by mhobbs-8B** [comment]
Sorry, I should have been more specific. The point of this issue is the wording of the documentation. It implies that by calling `callback(err)`, the task "will not complete".

**Comment by aearly** [comment]
You're right, the docs could be more clear.
