### ISSUE TITLE
New util function - async.spread

### ISSUE THREAD

**Issue by kobezzza** [caolan/async#816]
I have the function:

```js
function diff(file1, file2, cb) {
  // ...
}
```

And i want to use amasing async functions such each/map/reduce etc. But i can't do it simple, because all this methods provide only two argument: `arg` and `callback`.

For example:

```js
async.map([
  ['f1.txt', 'f2.txt'],
  ['f1.txt', 'f3.txt']
], diff, function (err, res) { /* Error, file2 is undefined */ })
```

But if we have simple helper function, like

```js
async.spread = function (fn) {
	return function (args, cb) {
		fn.apply(null, [].concat(args, cb));
	}
};
```

We can do it easily

```js
async.map([
  ['f1.txt', 'f2.txt'],
  ['f1.txt', 'f3.txt']
], async.spread(diff), function (err, res) { /* All fine! */ })
```

**Comment by aearly** [comment]
[Lodash has this already](https://lodash.com/docs/#spread).  Lodash and async are best buds -- `_.partial`, `_.rearg`, `_.spread`...

**Comment by aearly** [comment]
I also have something similar from my experimental `acomb` library: [`spreadOptions`](https://github.com/aearly/acomb#spreadOptions).  `acomb.spreadOptions(diff, 0, 1)` would do exactly what you want.

If this gets a few more +1's i'll consider adding it to async proper.

**Comment by kobezzza** [comment]
@aearly Thanks!

**Comment by jdalton** [comment]
<img src="http://img.pandawhale.com/117376-step-brothers-did-we-just-beco-RjAf.gif" height=50% width=50%>
