### ISSUE TITLE
Live help hangouts for async users?

### ISSUE THREAD

**Issue by cmrnh** [caolan/async#830]
What do you all think about setting up regularly-scheduled, live hangouts for helping async users work through integration issues?

The goal would to create an extra layer of support for users who otherwise might open up issues for questions that could be better solved by jumping into a short pair-programming / screenshare session.

We did an open group hangout on Node yesterday and ended up talking through questions around basics for integrating async. We're doing another hangout tomorrow at 11am ([rsvp here](http://start.thinkful.com/node/)) and should have a few more open sessions next week too

The only reason these hangouts work is that people show up, though. So especially if async keeps coming up — would it make sense to add a link to the sessions to the README or in the docs somewhere to get the word out?

**Comment by aearly** [comment]
Sounds like a good idea!  I'd recommend checking out out our Gitter room.  Ideally if you needed more real-time help you would coordinate through there.  Your weekly/daily/etc. hangout would be good to advertise there.

https://gitter.im/caolan/async

**Comment by cmrnh** [comment]
Cool, thanks @aearly! Will post there as well — we're doing another group hangout tomorrow at 11am ET!
