### ISSUE TITLE
Drop aliases in v2

### ISSUE THREAD

**Issue by megawac** [caolan/async#835]
There are plenty of aliases at the moment (some not consistently applied, e.g. `any` & `all`). I think all aliases should be dropped.

**Comment by aearly** [comment]
I think there's no harm in keeping them in there, we should just apply them consistently.

**Comment by aearly** [comment]
`any` -> `some`, `all` -> `every`, what about `detect` -> `find` ?

**Comment by megawac** [comment]
Definitely `detect`->`find`

**Comment by aearly** [comment]
What is the motivation behind removing aliases?  Doesn't seem to be too much hassle to keep them in.  All we have to do is `assert(async.any === async.some)`.

**Comment by mreinstein** [comment]
agreed, breaking change for the sake of breaking things seems like putting up arbitrary barriers and making the new 2.x that much harder to adopt.
