### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by guotie** [caolan/async#841]
var async = require('async');
     var a = [];
     for (var i = 0; i < 3000; i ++) 
          a.push(i);
     var q = new aysnc.queue(function(item, cb) {
            cb()
     }, 10);

     q.push(a)

will result in:
RangeError: Maximum call stack size exceeded

**Comment by aearly** [comment]
Check this out:

https://github.com/caolan/async#synchronous-iteration-functions

**Comment by guotie** [comment]
Thanks very much.
