### ISSUE TITLE
eachParallel instead of eachSeries

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#843]
I have this absolutely fine Node.js module that reads from Redis and responds with data to a request to an Express server.

However, I would like to know if there was a way to convert the eachSeries to some sort of "eachParallel". For the purpose of the code below, there is no necessary reason each function has to run in series. But according to the async API I don't think there is an eachParallel function. And I don't believe async.parallel can do what I want below, because I need to pass each function the value from the each array.

```javascript
//core
var async = require('async');
var sentinel = require('redis-sentinel');

//redis
var Sentinel = sentinel.Sentinel(endpoints);
var client = Sentinel.createClient(REDIS_SENTINEL_MASTER_NAME, {});

function get(req, res, next) {

    var ret = {}; 

    client.keys('*', function (err, keys) {

        if (err) {
            log.error(err);
        }
        else {
            async.eachSeries(keys, function iterator(item, cb) {
                createLocalDataMap(item, cb);
            }, function done() {
                res.json(ret);  //respond with JSON
            });
        }
    });

    function createLocalDataMap(redisKey, cb) {
        client.get(redisKey, function (err, data) {
            if (err) {
                log.error('Getting data for ' + redisKey + ' Error: ', err);
                cb(err); //1
            }
            else if (data) {
                var data = JSON.parse(data);
                ret[redisKey] = data;
                cb();  //2
            }
            else {
                log.error('no error yet no data either, in redis client get query.');
                cb(); //3
            }
        });
    }
}


function post(req, res, next) {
}
function del(req, res, next) {
}
function put(req, res, next) {
}

module.exports = {
    GET: get,
    POST: post,
    DEL: del,
    PUT: put
};
```

there's a couple of imperfections with the code. Having to place 3 callbacks (cb) in the createLocalDataMap function is one.

Is it possible to create some sort of async.eachParallel functionality? The problem that I see with async.parallel, as it is now, is that I need to pass each function in async.parallel the redis keyname (redisKey), I don't think that's possible with async.parallel?

**Comment by megawac** [comment]
See [`each`](https://github.com/caolan/async#each)

**Comment by ORESoftware** [comment]
please alias 'each' with 'eachParallel' and we are GOLDEN, thanks. I love your lib, but you already have so many aliases, so please add this one. Otherwise I will take it personally :)
