### ISSUE TITLE
splitting up async into independent modules?

### ISSUE THREAD

**Issue by mreinstein** [caolan/async#845]
this would be really nice because it's moving away from cargo cult programming and offering specific functions that are needed. I frequently find that I'm using 2-3 functions from async over and over; the rest is dead weight.

@jdalton has set a great precedent with lodash, which ships it's functions as individual modules:

https://www.npmjs.com/package/lodash.assign

https://www.npmjs.com/package/lodash.filter

etc...

**Comment by aearly** [comment]
Yes.  #720 #796
