### ISSUE TITLE
Drop es5 shims in v2

### ISSUE THREAD

**Issue by megawac** [caolan/async#857]
Lodash is currently suggesting users use `es5-shim` & `es5-sham` to cherry patch older environments (for lodash v4). I think we should take the same route and drop es5 shims in the next major bump

**Comment by aearly** [comment]
:+1:  We accidentally released a version using an ES5-only function, and no-one complained, so... :new_moon_with_face:

**Comment by jdalton** [comment]
LOL yes! :full_moon_with_face:

**Comment by aearly** [comment]
We're using lodash instead!

**Comment by megawac** [comment]
@aearly we should still recommend users use `ES5-shim` if they need to support older browsers. Lodash doesn't support ES5 natively (though I don't recall if it'll be an issue for any of the method's we're using currently)

**Comment by jdalton** [comment]
Yep. You use `lodash/isArray`.

**Comment by aearly** [comment]
Okay. We should add a note to the readme.

**Comment by jdalton** [comment]
Good news is lodash is made with support for es5-shim in mind and if they're wanting older enviro support chances are es5-shim is already in their toolbox.
