### ISSUE TITLE
Breakup readme

### ISSUE THREAD

**Issue by charlierudolph** [caolan/async#859]
Thoughts on breaking it up into a documentation folder or a wiki with a page for each function?

**Comment by aearly** [comment]
I'm thinking of what our goals are for the docs:

- Easily accessible from the readme
- `Ctrl+F`-able
- Parse-able, so we can support Kapeli and other doc tools #676 

A doc folder full of markdown that we build into the readme (or some documentation page we link from the readme) might fit the bill.   I'm not really experienced with GH's wiki tools, so I don't know if it supports the Kapeli use case.

**Comment by megawac** [comment]
I think porting the current docs to jsdoc would offer the best of all worlds (soooooooooo many tools can parse jsdoc)

**Comment by aearly** [comment]
Where would we put the introductory stuff and common pitfalls in the jsdoc case?

**Comment by megawac** [comment]
I figure we'd move it to a landing page ala http://danieltao.com/lazy.js/

**Comment by ecasilla** [comment]
I can help port the docs to jsdocs if no one has started yet :smile:

**Comment by megawac** [comment]
If you're interested in helping with that it'd be awesome!

**Comment by ecasilla** [comment]
I would love to help, but I also don't want to go off into a corner, and implement this all in the dark. I would like the idea of incremental changes. Maybe lets start with a roadmap of how we want to tackle this. It will allow for less friction when it's PR time.

**Comment by aearly** [comment]
Closing this, we've already moved to JSDoc, and are working on generating the docs site in other issues.
