### ISSUE TITLE
File sync-package-managers.js breaks with uglify.js

### ISSUE THREAD

**Issue by Bertuzb** [caolan/async#861]
I'm using a different environment for javascript, and it uglifies all node_modules. Sadly I cant use this module because it fails at the file `support/sync-package-managers.js`. Line 1 contains `#!/usr/bin/env node` which isnt vaild javascript

**Comment by megawac** [comment]
That file shouldn't be on npm anyway

**Comment by Bertuzb** [comment]
thx ily
