### ISSUE TITLE
waterfall etc. - add thisArg to all functions.

### ISSUE THREAD

**Issue by Izhaki** [caolan/async#862]
I find myself writing a lot of code like this:

        async.waterfall([
            getRunningJobs.bind( this ),
            updateRunningCount.bind( this ),
            startInterval.bind( this )
        ], function ( aError ) {
        });

And so I wrote a wrapper:

    function main( aFunctions, aFinalCallback, aScope ) {
        aBoundFunctions = [];
    
        aFunctions.forEach( function( aFunction ) {
            aBoundFunctions.push( aFunction.bind( aScope ) );
        });
    
        async.waterfall( aBoundFunctions, aFinalCallback )
    };

Which means we can now call:

        main([
            getRunningJobs,
            updateRunningCount,
            startInterval
        ], function ( aError ) {
        }, this);

I might be doing something wrong, but wouldn't it be useful to have `thisArg` as the last parameter to `waterfall` etc.?

**Comment by megawac** [comment]
I'm -1 for this. I'd suggest you use a helper like `_.bindAll`

```
async.waterfall(_.bindAll([
        getRunningJobs,
        updateRunningCount,
        startInterval
    ], this), function ( aError ) {
    });
```
