### ISSUE TITLE
'Undefined' async window variable.

### ISSUE THREAD

**Issue by G3E9** [caolan/async#870]
The device is an Android (2.3.5) using its stock browser (2.3.5).
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <script src="async.js"></script>
    <script>
      alert(window.async);
    </script>
  </body>
</html>
```
```
async.js:1198
Uncaught SyntaxError: Unexpected token catch
```
I copied @yourfriendgerasim's code from #864 and I could not make it to the **.each** and got the same error as just above.

**Comment by megawac** [comment]
What version of async are you using?

**Comment by G3E9** [comment]
I've hosted 1.4.0 along-side the .html example above and have also tried referencing via https://cdnjs.com/libraries/async
Both approaches result the same. All my current devices ran the .html and async fine, it has just been my old Android with this problem.

**Comment by aearly** [comment]
Looks like Android 2.3 is balking at the use of `Promise.catch`.
