### ISSUE TITLE
Request for "soft start" of parallel tasks 

### ISSUE THREAD

**Issue by brosenquist** [caolan/async#874]
I have several cases where I run a bunch of tasks in parallel and all the tasks repeated call the same service on an interval. When I start the tasks all of the request are send at almost the same time  and they continue to be called more or less in sync with each other until complete. This results in a spikes in the traffic on the service. I would like to a way to automatically spread out the start of the parallel tasks. This would spread out the traffic generated by the parallel tasks resolving the spiky traffic problem I'm seeing. I can always solve this by implementing the soft start logic in the parallel tasks themselves, but it would be nice if async.parallel supported it directly. 

Thanks for your consideration.

**Comment by aearly** [comment]
It sounds like `async.queue` might be a better fit for what you're trying to do.  You can specify the concurrency of the queue, and even create a simple buffer to stagger calls to `queue.push()`.

`parallelLimit` also might be worth exploring, to see if it helps fix the behaviour you're seeing.
