### ISSUE TITLE
Ensure the callback fn is always the last parameter of waterfall functions

### ISSUE THREAD

**Issue by boblauer** [caolan/async#877]
Currently, in a `waterfall`, the current function needs to know exactly how many parameters the next function is expecting.  Something like this:

```javascript
async.waterfall([
  function first(next) {
    if (someCondition()) next(null, 'value 1', 'value 2');
    else next(null, 'value 1', null); // must pass in null as the last parameter
  },
  function second(param1, optionalParam, next) {
    ...
  }
], cb);
```

In our `else` condition, if we don't pass in `null`, then in the `second` function, `optionalParam` will be our callback function, and `next` will be undefined.

---

In a similar vein, if we pass in too many parameters, we screw things up:

```javascript
async.waterfall([
  function A(next) {
    myMongooseDocument.save(next);
  },
  function B(savedDocument, next) {
    // next will not be our callback function, because
    // mongoose passes 3 arguments to the save callback.
    // (err, savedDocument, countOfDocumentsSaved)
  }
], cb);
```

It would be extremely handy if `waterfall` checked the next functions `length` property to see how many arguments it was expecting, and then made sure the last argument was always the `next` function.

This would mean both trimming arguments when necessary, as well as inserting `undefined` arguments when applicable.  With this change, the above two scenarios would now look like this:

```javascript
async.waterfall([
  function first(next) {
    next(null, 'value1');
  },
  function second(param1, optionalParam, next) {
    // param1 === 'value1'
    // optionaParam === undefined
    // next === callback function
  }
], cb);
```

```javascript
async.waterfall([
  function A(next) {
    myMongooseDocument.save(function(err, document, affectedCount) {
      next(err, document, affectedCount);
    });
  },
  function B(savedDocument, next) {
    // savedDocument === document
    // next === callback function
    // even though affectedCount was passed in, it is ignored,
    // and next is still our callback function.
  }
], cb);
```

I haven't thought through every possible scenario, but I don't believe this would be a breaking change.  Well, there is one scenario currently that would break with this change:

```
async.waterfall([
  function first(next) {
    next(null, 'value1');
  },
  function second(param) {
    // we don't care about next, which would be very strange.
  }
], cb);
```

As it stands today, `param` would be `'value 1'`.  If you were to implement this change, `param` would be the `next` callback function.  But this seems like an extremely edge-case scenario.

**Comment by aearly** [comment]
You can't rely on `Function.length` to know which arg the callback is.  It doesn't work with variadic functions or partially-applied functions (or any function created with a higher-order function).  This has been brought up before:  #519 #492 .

An easy way to get the callback is to do something like this in your waterfall functions:

```js
async.waterfall([
  step1Func,
  function (/*args... next*/) {
     var next = _.last(arguments);
     //...
  }
], done);
```

...but there's no reliable way for async to do this for you.

**Comment by boblauer** [comment]
Thanks for the explanation, hadn't considered variadic and partially-applied functions.
