### ISSUE TITLE
async.each returns with 'undefined' when err = 0 in callback(err)

### ISSUE THREAD

**Issue by AdamMroz** [caolan/async#884]
Why do async.each return undefined whet it gets 0 (zero) in callback(err)?

Test code:

```javascript
var array = [
	{"_id":123}, // array[0]
	{"_id":124}, // array[1]
	// etc. // array[N]
];

var neededId = 123;
async.each(array, function(arrayElement, callback){
	if(arrayElement._id == neededId){
		callback(array.indexOf(arrayElement));
	} else {
		callback();
	}
},function(key){
	console.log("KEY IS => "+key);
});
```
RESULT : KEY IS => undefined

Is it right behavior or just a bug?

Async updated to newest ver.

**Comment by teoking** [comment]
It's right behavior.
Look at here: https://github.com/caolan/async/blob/master/lib/async.js#L230

the callback would not pass any other arguments than a error/null, so you cannot get any arguments because they're discarded.

**Comment by aearly** [comment]
@teoking is right -- the first parameter to a callback should be an Error or null.  Anything truthy is considered an error.
