### ISSUE TITLE
"Callback was already called" error firing inapropriately

### ISSUE THREAD

**Issue by benjamincarp** [caolan/async#885]
I am still trying to isolate exactly how this is happening/carve out our erroring code so I can reasonably paste an example in here but I have some code that worked great before the multiple callback protection that now throws this error. Any tips on what might cause this (in my code or async) would be greatly appreciated.  I have traced through our code and I can't find any problems with our callbacks other than that we get this error.

To keep track of series being initialized and their final callback being called I I added the following to async.js:
- a counter at the top of the file initialized to 0
- add cod to  async.series() to:
 - increment the counter 
 - use that counter in console logs to see when a new series is initialized and when we hit the final callback for that series.

When I run my code I see:
initializing series 1
initializing series 2
Series Callback 2
Series Callback 1
initializing series 3
initializing series 4
Series Callback 4
Series Callback 3
initializing series 5
[callback already called error]

Series 1 & 2 are nested inside a function and series 5 is the start of that same function being called again with different params.  When we enter series 5 with these new parameters the first function just gets in an if statement then calls it's callback and this is when the error fires.

```
    async.series(
                [
                    function(series_cb){
                        if (size === null || action === 'delete') {
                            //this next line causes the error
                            return series_cb();
                        }
                        ...
```

**Comment by aearly** [comment]
Your example code doesn't provide enough context to know what's going wrong.  You need to verify that there's no way any of your series steps could call a callback twice.

**Comment by benjamincarp** [comment]
This error should only appear if a single step of a series calls its callback more than once correct?

If so, there is something going wrong because the point where we get the error is a callback at the top of the first step in the series (we want to skip that step because of the parameters passed in).  Since there are no callbacks in the series before this one, nothing could have previously called it unless the previous async.series calls (which have all finished and already called their final callback) are somehow interfering.

I did step through all of our code line by line this morning to confirm that no steps called a callback twice and everything looks correct to me.  Do you have any tips on something else to look for?

**Comment by aearly** [comment]
I cant tell without seeing more  of your  code.  See if you can isolate what is going wrong to a smaller code example.

**Comment by AndrewBarba** [comment]
Just to add to this, we are having the exact same problem. Really difficult to track down the exact issue or come up with an example but will keep at it.

**Comment by AndrewBarba** [comment]
And 5 minutes later I found what was wrong on our end... Example if it helps
```
function doSomething(list, next) {
  var result = ...
  _.each(list, function(item) {
    if (falis(item)) return next(new Error(...))
  });
  next(null, result)
}
```
It's pretty common pattern for us to check for an error and then return near the top of the function. In this case we did that in an underscore each which returns from the context of underscore but does not return from the enclosing function, and thus the callback was being called twice. Hope that helps someone else out there.

**Comment by benjamincarp** [comment]
In the end, this was a problem on our end that just exhibited itself in a very odd fashion.  Sorry for the false alarm.  I would like to provide more info on exactly what was happening but I have since changed jobs and no longer have access to their repo to reference for describing it.

**Comment by samuelgoldenbaum** [comment]
@AndrewBarba could you perhaps add some more code showing the problem and fix? If did you deal with the guard clauses at the top of the function?
