### ISSUE TITLE
async.each final callback not called

### ISSUE THREAD

**Issue by ildella** [caolan/async#886]
hi, I would expect that

```javascript
async.each(['one', 'two'], fake, function(err){
    console.log("end");
  });
  function fake(source) {
    console.log("fake");
  } 
```
would log "fake" twice, which it does, and log "end" as last thing. But that is not happening, the final callback function is never called, "end" is never printed. What am I doing wrong?

**Comment by tolgaek** [comment]
In your callback you define, you need to call a callback to indicate that you are done. Right now each doesn't know if any of those tasks finished. If you modify your `fake` function to be something like 
```
function fake(source, callback) {
  console.log('fake');
  callback();
}
```

It will work

**Comment by ildella** [comment]
thanks a lot! sorry for the naive question..

**Comment by tolgaek** [comment]
No worries, you can go ahead and close this ticket

**Comment by tolgaek** [comment]
Also a quick tip, look into [Error First Callbacks](http://thenodeway.io/posts/understanding-error-first-callbacks/), and if you ever see callbacks defined in any library, make sure you understand why they are there and you call them once. Don't ignore the callbacks basically
