### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by osherx** [caolan/async#887]
wouldn't it be lovely if we could express our codes like this:

```
async.waterfall( [
    async.parallel( [
        paralel_task1_1,
        paralel_task1_2,
        paralel_task1_3,
     ]),
     process_sync_point1,
     async.parallel( [
        paralel_task2_1,
        paralel_task2_2,
        paralel_task2_3,
     ])
], function(err) { 
     console[ err ? "error" : "info" ]("process complete with " , err || "SUCCESS" )
})
```

now it's not possible, because async.parallel, and async.waterfall (and their synonyms) return 'undefined'.

What I propose - is that if they don't accept a finalling callback - they should not exectute, but return a function, representing the given flow-unit

so now the current form requires some scaffold which does not really have any semantic meaning to the reader:

```
async.waterfall( [
    function (next) { 
        async.parallel( [
            paralel_task1_1,
            paralel_task1_2,
            paralel_task1_3
        ], next);
     },
     process_sync_point1,
     function (result, next) {
         async.parallel( [
             paralel_task2_1,
             paralel_task2_2,
             paralel_task2_3
         ], next);
    }
], function(err) { 
     console[ err ? "error" : "info" ]("process complete with " , err || "SUCCESS" )
})
```

**Comment by aearly** [comment]
Sounds like you want currying. If you're using lodash, you can do something like:

```js
var parallel = _.curry(async.parallel, 2);
```

Then `parallel` will work like your first example.  We're thinking of doing this, but it doesn't work for functions with optional parameters, and there are slight performance implications.  `async.apply` also is something to explore -- it does partial application.

(somewhat related: #745 )

**Comment by osherx** [comment]
got it, thanks.

BTW - async.apply looks a form of Function#bind for old browsers, am I right?

and lodash - it would be great to makedo without it... 

So first step would be:

```
function parallelStep(stack) {
     return function(next) {
          async.parallel(stack, next)
     }
}
```
but still need to resolve passing of arguments accepted from previous stage

so I guess something like:

```
function parallelStep(stack) {
     return function() {
          var next = Array.prototype.pop.apply(arguments)
              , args = arguments
              ;
          async.parallel(stack.map( function(f) { return f.bind(null, args) }), next)
     }
}
```

ah, and then - there's compatibility between handling of Array-Stack and Object-Stack.

```
function parallelStep(stack) {
     return function() {
          var next = Array.prototype.pop.apply(arguments)
              , args = arguments
              ;
          async.parallel(
             Array.isArray(stack)
               ?  stack.map( function(f) { return f.bind(null, args) } )
               :  Object.keys(stack).reduce( function(m, k) { m[k] = stack[k].bind(null, args); return m }, {} ) } )
         , next)
     }
}
```

worths a PR?
(assuming I use browser compatibility and add tests to that)

**Comment by aearly** [comment]
I'd want to solve this more broadly than just with `parallel`, and without creating more methods.  I think auto-currying methods makes the most sense in most cases, but I'd save it for a major release.  In the meantime you can do `async.apply(async.parallel, stack)`, but that doesn't solve the case where you want to pass an additional arg to each function.

**Comment by osherx** [comment]
clear.
keep us posted for the new major... ;)
