### ISSUE TITLE
Async.map calling its own callback function and ignoring my defined callback

### ISSUE THREAD

**Issue by leonaburime** [caolan/async#888]
I have something like this

```js
var async = require('async');
var request = require('request');//request urls

var urls = ['url1','url2', 'url3' ];

function requestUrl( url, callback){
  request(url, function(err, resp, body){
    callback(null, body)
 }
}

function cb(err, results){ console.log(results); }
```

then I call it via

```js
async.map(urls, requestUrl, cb);
```

My 'cb' never gets called. I am printing out the 'callback' function in the second parameter and it looks like this.

```js
function (err, v) {
  results[index] = v;
  callback(err);
}
```

Why is it ignoring my callback and putting it in its own?

**Comment by aearly** [comment]
You're not handling the `err` in the `request` callback.  That might  be masking what the real issue is.

**Comment by leonaburime** [comment]
This was my fault. Bad  code configuration

**Comment by leonaburime** [comment]
Ill delete this if possible
