### ISSUE TITLE
waterfall tasks should take callback first

### ISSUE THREAD

**Issue by devinus** [caolan/async#895]
This would make it so you don't have weird errors where the callback is not where you expected it to be because you got the argument list wrong. Would also allow you to completely ignore arguments for some tasks. Will also allow you to use `async.apply` in the middle of a waterfall.

**Comment by aearly** [comment]
I've wanted to make this change for a while.  I'm not sure if we should make this change in a major release, or create another `auto`-like method with the callback in the "correct" position.

**Comment by aearly** [comment]
Nevermind, i was confusing `waterfall` with `auto`. I want to keep things so the callback is always the last argument to a function.
