### ISSUE TITLE
feature request - async.minimum

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#899]
I am looking for the functionality described here:

http://stackoverflow.com/questions/32323611/node-js-async-but-with-minimum-priority

the question is:
What is the best way to create parallel asynchronous HTTP requests and take the first result that comes back positive?

//something like this, where one call goes to some API and a parallel call goes to our Redis store to see if we already have the value:

```javascript 
async.minimum([

function apiRequest(cb){
   request(opts,function(err,response,body){
         cb(err,body.result.hit);
    }
},
function redisRequest(cb){
   client.get("some_key", function(err, reply) {
          cb(err,reply.result.hit);
     });
}], 

  function minimumCompleted(err,result){

   // this mimimumCompleted final callback function will be only fired once, 
   // and would be fired by one of the above functions - 
   // whichever one had a value for body.result.hit that was defined


 });
```

**Comment by megawac** [comment]
Take a look at async.find, which I believe is what you want

**Comment by megawac** [comment]
Sorry, I meant detect

**Comment by aearly** [comment]
I think they mean  something more like `async.first` from #568 .  But `async.detect` should work until we sort that one out.

**Comment by aearly** [comment]
Closing this in favor of #568 .  I'll add `minimum` to the list of potential names. :P

**Comment by ORESoftware** [comment]
I think "first" is actually better than "minimum". The only problem with "first", is that the result I want is not just the first result, it is the first result that has a defined value for the second callback parameter, the first being a potential error.

This is something that could be easily generified for popular use.

**Comment by aearly** [comment]
Yeah, "first" is not without its problems.  I think coming up with a good name is most of the work remaining for that feature.  "Cache invalidation and naming things" as the saying goes.

**Comment by ORESoftware** [comment]
http://www.thesaurus.com/browse/pristine  async.pristine haha, pristine seems to mean both earliest and immaculate
