### ISSUE TITLE
Async.retry executes immediately before waiting for interval

### ISSUE THREAD

**Issue by v1k4s** [caolan/async#908]
async.retry({times : 5,interval : 30000},myFunction.bind(functionData),function(err,results){
                            console.log("===================================")
                            console.log("Async function finished processing")
                            return;
                        })

**Comment by aearly** [comment]
Are you talking about the first execution, or the second?

**Comment by rpallas** [comment]
relates to: http://stackoverflow.com/questions/32537483/async-retry-executes-immediately-before-waiting-for-interval

**Comment by stonephp** [comment]
Upgrade async to 1.4.0.
