### ISSUE TITLE
[DOC] Common PITFALL

### ISSUE THREAD

**Issue by sdnetwork** [caolan/async#911]
hi,

in the doc we can read that if our callback is sync, we can get an *RangeError: Maximum call stack size exceeded*.

    async.eachSeries(hugeArray, function iterator(item, callback) {
      if (inCache(item)) {
         callback(null, cache[item]); // if many items are cached, you'll overflow
      } else {
         doSomeIO(item, callback);
      }
    }, function done() {
      //...
    });

Maybe the async lib has changed since this exemple because if i understand today is not the case with this exemple because in async.js in async.forEachOfSeries you test if the callback is sync and if yes you call it with async.nextTick so we can't get a *RangeError: Maximum call stack size exceeded*, isn't it ?

    iterator(obj[key], key, only_once(function (err) {
                if (err) {
                    callback(err);
                }
                else {
                    key = nextKey();
                    if (key === null) {
                        return callback(null);
                    } else {
                        if (sync) {
                            async.nextTick(iterate);
                        } else {
                            iterate();
                        }
                    }
                }
            }));
or maybe i don't understand something

**Comment by aearly** [comment]
The nextTick call was added after writing that note in the README.  We're going to remove it in 2.0.

**Comment by sdnetwork** [comment]
ok thanks
