### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by squirrelsRduck** [caolan/async#913]
I try doing npm install async --save
yet, it gives this error:  

npm ERR! Failed to parse json
npm ERR! Unexpected token 'h' at 17:6
npm ERR!     "https": "^1.0.0",
npm ERR!      ^
npm ERR! File: /Users/myUserAccount/Desktop/myProjectFolder/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by aearly** [comment]
Looks like a parse error in `/Users/myUserAccount/Desktop/myProjectFolder/package.json`

**Comment by squirrelsRduck** [comment]
good call, just noticed that.  thanks
