### ISSUE TITLE
npm test fails on windows - jshinit does not recognize lib/*.js

### ISSUE THREAD

**Issue by smartmouse** [caolan/async#916]
On a command prompt windows , with node 0.12.7
When I invoke npm test,   jshinit cannot find lib/*.js

However, if I modify  lib/*.js to lib/async.js without the wildcard, it works.
Are you aware of this behaviour on windows.
Is this jshint issue on windows?
On linux , this is working fine.

 "scripts": {
    "mocha-node-test": "mocha mocha_test/",
    "mocha-browser-test": "karma start",
    "mocha-test": "npm run mocha-node-test && npm run mocha-browser-test",
    "nodeunit-test": "nodeunit test/test-async.js",
    "test": "npm run-script lint && npm run nodeunit-test && npm run mocha-test",
    "lint": "jshint lib/async.js test/test-async.js perf/benchmark.js && jscs lib/async.js test/test-async.js perf/benchmark.js",
    "coverage": "nyc npm test && nyc report",
    "coveralls": "nyc npm test && nyc report --reporter=text-lcov | coveralls"
  },

**Comment by megawac** [comment]
Feel free to send a PR changing this. This is a long time issue on windows

**Comment by aearly** [comment]
Closed by #1003
