### ISSUE TITLE
Can't use with PhantomJS phantom.injectJs

### ISSUE THREAD

**Issue by justin-hackin** [caolan/async#920]
I've tried to follow the advice of this post : http://stackoverflow.com/a/22007457/2780052 in using async.js to sequentially load pages in PhantomJS but when I try to use phantom.injectJs (http://phantomjs.org/api/phantom/method/inject-js.html) the code into the PhantomJS I get an error:
```
ReferenceError: Can't find variable: exports
  /home/cosmo/Web/xmeasures/svgPlay/floorplan-viewer/bower_components/asyncjs/lib/async.js:7
```

Any idea what might be going on here, or how to make this work with PhantomJS ?

**Comment by aearly** [comment]
What version of async are you injecting?

**Comment by justin-hackin** [comment]
most recent, 1.4.2

**Comment by aearly** [comment]
Looks like you're injecting the wrong async: https://github.com/fjakobs/async.js/blob/master/lib/async.js

`asyncjs` vs. `async`

**Comment by justin-hackin** [comment]
Wow, that was a silly mistake, thanks kindly for correcting me
