### ISSUE TITLE
performance loss

### ISSUE THREAD

**Issue by thanhthang20** [caolan/async#921]
My synchronous code is near thousand of lines. I want to divide them to some groups and put it in async.auto (one group is one function in async.auto). Each function has the name. I do that because I want to make it easy for other people to do maintain in the future. Code is divide to group so they will easy to understand. I want to know does async.auto cause performance loss comparing with when I don't use it. My question on stackoverflow: http://stackoverflow.com/questions/32860503/use-async-auto-as-wrapper

**Comment by aearly** [comment]
There is a minimal performance hit with using  `async.auto` -- for example, it checks for unmet dependencies or circular dependencies.

Although, if your code is sync, then using `async.auto` is probably overkill.  Well-factored functions and parameters should be good enough.

**Comment by thanhthang20** [comment]
thanks you so much!. So I will use async.auto because sometime I need to do something with MongoDB and It will be very easy to manage input/output of every function with a minimal performance hit
