### ISSUE TITLE
async.forEachOf

### ISSUE THREAD

**Issue by the1mills** [caolan/async#925]
async.forEachOf(dbs, function (client, key, cb) {})

async.forEachOf is not a function, can you remove from your docs? or correct me?

**Comment by ex1st** [comment]
@the1mills https://github.com/caolan/async/blob/master/lib/async.js#L229

**Comment by paglias** [comment]
Just found this

**Comment by paglias** [comment]
sorry my fault, I was using a version prior to 1 

@the1mills make sure you're using at least version 1

**Comment by the1mills** [comment]
yeah thanks

**Comment by megawac** [comment]
Yep, duplicate of https://github.com/caolan/async/issues/878
