### ISSUE TITLE
optional callback never called in async.each when finished with no errors

### ISSUE THREAD

**Issue by ayinger1** [caolan/async#926]
i do not see the optional callback called after all items processed, if there are no errors.

for example:

function iterator(item, callback) { if (item==4) callback('oops!'); else console.log(item); }
function callback(err) { if (err) console.log('there was an error: ' + err); else console.log('all done, no errors'); }
async.each([1,2,3], iterator, callback);

i would expect to see 'all done, no errors' logged to console.  but callback(err) functioned passed to async.each never seems to be called.

**Comment by deeply** [comment]
@ayinger1 you need run callback without arguments or with an explicit null argument, see https://github.com/caolan/async#eacharr-iterator-callback. 

``` javascript
function iterator(item, callback) { 
  if (item==4) 
    callback('oops!'); 
  else 
    console.log(item); 
    callback(); // <--- you need run callback without arguments or with an explicit null argument
}
...
```
