### ISSUE TITLE
whilst with async fn

### ISSUE THREAD

**Issue by kynwu** [caolan/async#927]
when using async.whilst(test, fn, callback),
if I have another async function inside fn ( ex: mongoDB find() ),
how can I let fn wait for the callback of this function to be finished...

sample code below:

async.whilst(test, function(cb) { mongoDB.find() }, cb(err) } 

where mongoDB.find() is an async function which return callback(err, result),
and I need the result to further determine code execution flow....

the real case is that the code is for generating token for an account, and the whilst is applied to make sure the token isn't duplicated, if it is duplicated then re-generate another token and call mongoDB.find()....till the result shows that the token is not duplicated then move forward....

**Comment by ex1st** [comment]
```javascript
async.whilst(test, function(cb) { mongoDB.find(cb); }, callback(err) }
```

**Comment by kynwu** [comment]
@ex1st 

Full code sample below:

findToken function has callback(err, results), how can I modify it in order to put
fn callback into it?

PrimaryAccount.findToken = function(token, callback) {
  var query = {
    "token.value": token
  };
  this.find(query, callback);
}

PrimaryAccount.findToken(token_value, function(err, results) {              
  if (results!='') {
    // token duplicated 
    console.log('token duplicated');
    token_value = PrimaryAccount.generateToken();
  } else {
      condition = false;                
  }
});

**Comment by ex1st** [comment]
@kynwu 

```javascript
var token_value;
async.whilst(function () { return !token_value; }, function(cb) {
  token_value = PrimaryAccount.generateToken();
  PrimaryAccount.findToken(token_value, function(err, results) {
    if (err || results.length) // results are array?
      token_value = null;
    cb(err);
  }); 
}, callback);
```

**Comment by kynwu** [comment]
@ex1st  thanks you ex1st
after refer your code...I found out that I forgot to put another cb within the if / else block...
I did put one cb within "else" block (token is not duplicated) but I miss the one within "if" block...
that's why the async.whilst doesn't work (the loop doesn't carry on)....
so very appreciated about your sample code!!! :)
```javascript
var condition = true;
    async.auto({
      // step1: generate token
      // step2: check if token is duplicated
      // step3: YES: go to step1 or go to next part
      generate_token: function(callback) {        
        var token_value;
        async.whilst(
          function() {
            return !token_value;
          },
          function(cb) {
            token_value = PrimaryAccount.generateToken();
            PrimaryAccount.findToken(token_value, function(err, results) {
              if (err || results.length) {
                console.log('token duplicated');
                token_value = null;
                cb(err);
              } else {
                cb()
                callback(null, token_value);
              }
            });
          },
          function(err) {
            console.log('err:', err);
          }
        );
      },
```
