### ISSUE TITLE
Async.Parallel doesnt work in Node 4.2.1 

### ISSUE THREAD

**Issue by codeapps** [caolan/async#930]
Using Express 4.13.3 
Don`t Execute the both Object Functions Only One.
Sometimes, I get the PONG Response from Mandrill Server but not the user data JSON or sometimes only get the User Data but not the PONG Response. I tried too use Async.Series or changing the Objects to only Functions but don't work.

```javascript
exports.getMandrill = function(req, res, next) {
  mandrill = require('mandrill-api');
  var M = new mandrill.Mandrill(secrets.mandrill.key);
  async.parallel({
    getPing: function(done) {
      M.users.ping2({}, function(err, ping) {
        done(err, ping);
      });
    },
    getInfo: function(done) {
      M.users.info({}, function(err, info) {
        done(err, info);
      });
    }
  },
  function(err, results) {
    if (err) return next(err);
    res.render('mandrill', {
      title: 'Mandrill API',
      ping: results.getPing,
      info: results.getInfo
    });
  });
};
```

**Comment by megawac** [comment]
What version of async are you using... Can you elaborate on the issue you face..

**Comment by codeapps** [comment]
```
Async@1.4.2 
```

**Comment by aearly** [comment]
There likely is a bug in mandrill in 4.2.1 -- especially if it  breaks with both `parallel` and `series`.
