### ISSUE TITLE
Async.each[Series] not allows provide additional arguments to iterator

### ISSUE THREAD

**Issue by Cherviakov** [caolan/async#931]
Hello. I'm using async quite often in my code, especially async.each[Series] to process arrays of data. I have need to use several nest async.each[Series] to process data in categories (for instance: for each day, for each user, for each action for each currency do smth) and need to pass more global variables to the bottom of this chain for database query. But I can do that only making nested functions, and as you can see from example above, nesting degree is about 4, which make code looks awful and each time make some more fancy names for callbacks. 

So the problem is that it is not possible to pass anything into iterator function arguments but target array. Is it possible to change this? Or maybe there is some way to avoid that, and therefore avoid high nesting degree?

**Comment by aearly** [comment]
You can pass additional args to function using partial application using `Function.bind` or `_.partial`.  It also might be worth investigating if your tasks are suitable for  `async.map[Series]` or another array processing function.  Also check out  `auto` -- its really handy for complicated async flows.
