### ISSUE TITLE
async.each callback called multiple times if result is unshifted

### ISSUE THREAD

**Issue by guyellis** [caolan/async#932]
I expect this issue is closely related to #557 and #572

```javascript
var async = require('async');

function func(done) {
  var arr = ['a'];
  async.each(arr, function(item, callback){
    return callback();
  }, function() {
    console.log('done');
    return done(arr);
  });
}

func(function(arr) {
  arr.unshift('a');
  // arr.shift('a') => no problem
});
```

"done" is printed an infinite number of times.

async version: 0.9.2

node version 0.12.7

**Comment by aearly** [comment]
Thanks for the bug report! :bug:   I think i know what's going on here.

**Comment by youqingkui** [comment]
I have not found this to be a bug

**Comment by guyellis** [comment]
I should have mentioned that my workaround is to clone `arr` in `func()` before calling `done()`. Not sure if that helps.

**Comment by guyellis** [comment]
@youqingkui You ran the snippet I posted and did not see "done" printed an infinite number of times? If so, what versions of node and async are you using?

**Comment by youqingkui** [comment]
@guyellis I use node is v4.0.0, async is 1.4.2

```js
var async = require('async');
function func(done) {
  var arr = ['a'];
  async.each(arr, function(item, callback){
    return callback();
  }, function() {
    console.log('done');
    return done(arr);
  });
}

func(function(arr) {
  console.log(arr);
  arr.unshift('a');
  //arr.shift('a');nod
  console.log(arr);
});

// done
// [ 'a' ]
// [ 'a', 'a' ]
```

**Comment by guyellis** [comment]
@youqingkui You're right. The project that I'm working on has a very out-of-date version of async. Looks like it's my problem. Thanks for pointing this out! :)
