### ISSUE TITLE
eachLimit can't invoke final callback

### ISSUE THREAD

**Issue by zhuping** [caolan/async#933]
i use eachLimit to download a photo array,but sometime it's can't invoke final callback.
<pre>
async.eachLimit(photos, 50, function(photo, callback) {
  if (photo.image) {
    var filename = path.basename(photo.image);
    var filepath = './public/download/' + id + '/' + filename;

    require('request')
      .get(photo.image)
      .on('error', function() {
        console.log(error);
      })
      .pipe(fs.createWriteStream(filepath))
      .on('error', function(err) {
        console.log(err);
      })
      .on('close', function() {
        callback();
      });
  }
}, function(err) {
  if (err) {
    console.log(err);
  } else {
    console.log('============== all images have been downloaded. =============');
    // me.archiveAlbum(id);
  }
});
</pre>

**Comment by aearly** [comment]
Make sure you `callback` in the error handlers.

**Comment by zhuping** [comment]
@aearly there's no prompt error

**Comment by zhuping** [comment]
@aearly i write a example for this question.sometimes it can't invoke final callback.
see here https://github.com/zhuping/async-example

**Comment by aearly** [comment]
Do you have a simpler example?  That's an entire koa app.
