### ISSUE TITLE
exit async.retry early

### ISSUE THREAD

**Issue by michAtEl** [caolan/async#934]
Hi,

as far as I understand,  `async.retry(5, apiMethod, resultHandler);`
will try to execute apiMethod 5 times if apiMethod returns an error. My program might run into situations, where it doesn't make sense to try apiMethod again after the first try. In other situations, a second try might be necessary.

Is the following code safe?
```
async.retry(5, function() {
  if (...) {
    // no error
    callback(null);
    return;
  } else {
    // error
    if(...) {
      // another try might work
      callback(err);
      return;
    } else {
      // another try will not work
      // break without calling callback()!
      anotherResultHandler();
      return;
    }
  }
}, resultHandler);
```

Is there another way to break async.retry early?

Thanks
Michael

**Comment by aearly** [comment]
`doWhilst` might be a better use case for what you're trying to do -- you have better control over the exit condition.

**Comment by michAtEl** [comment]
aearly,
Thank you very much, this helps. 

But I still wonder if it is possible to break async.retry (or other Control Flow patterns) early. Caolan proposed a similar way to break a waterfall early in pull #85 ("... just use a named function for the final callback and call that instead of the task callback passed into the successful task function."). Does this work for other Control Flow patternsas well? If yes: I think, this should be added to the documentation.

Michael

**Comment by aearly** [comment]
It does work, but it causes a memory leak.  The context for the waterfall is never cleaned up because it waits forever for the function you exit early from to call the waterfall callback.  There's more discussion in #552  and #880
