### ISSUE TITLE
Failed assert is not propagated out of async.

### ISSUE THREAD

**Issue by mpetrak** [caolan/async#935]
Hi,
starting in async 1.1.0 (also reproducible in 1.4.2) I have a problem in this block of my testing nodeJS code:

```javascript
'test step': function(done) {
    async.waterfall([
        function (next) {
            query('SELECT Id, Name, FROM Contact WHERE Email = \'' + email + '\'', next);
	},
	function (result, next) {
	    assert.strictEqual(result.totalSize, 1, 'Expecting exactly 1 record in Salesforce Contact');
            next();
        }
    ], function(err) {
           done(err);
   });
     
```

Using latest Mocha (2.3.3) for executing this test step.

In async 1.0.0 when assert fail, error is thrown, Mocha catch it immediately.
But starting async 1.1.0 if assert fail, nothing is done - looks like no throw, no callback call. Reaching Mocha timeouts.
Reproducible with chai.assert and nodeJS assert.

Can you please look at it and say, what is wrong?
Thank you!

**Comment by aearly** [comment]
What happens when you test without `waterfall`? e.g.

```js
'test step': function(done) {
    query('SELECT Id, Name, FROM Contact WHERE Email = \'' + email + '\'', function (err, result) {
        assert.strictEqual(result.totalSize, 1, 'Expecting exactly 1 record in Salesforce Contact');         
        done(err);
   });
}
```

**Comment by mpetrak** [comment]
Ohh, same without `waterfall`.
Seems, it is not an async issue, but something is wrong with Salesforce query library / my usage.

Apologies and thank you.
