### ISSUE TITLE
Async parallel not calling final callback

### ISSUE THREAD

**Issue by MrDHat** [caolan/async#937]
I am adding functions dynamically to an array to process them parallely (I/O wise).

Here is what the code looks like:

```js
var parallelFn = function (i, callback) {
  _someInternalFunction(arg, arg1, [], function (err, res) {
    if (err) {
      return callback(err);
    } else {
      if (res && res.length > 0) {
        var items = res;
        for (var j = 0; j < items.length; j++) {
          // Do something
        }
        console.log(res.length);
        return callback(null, res);
      } else {
        return callback('Error');
      }
    }
  });
};

var parallelFns = [];

for (var i=0; i<arr.length; i++) {
  parallelFns = parallelFns.concat(
    parallelFn.bind(null, i)
  );
}

async.parallel(parallelFns, function (err, results) {
  console.log(err, results);

});

```

All the functions are called and `res.length` is logged, but the log in the callback is not called. What am I doing wrong here?

**Comment by aearly** [comment]
Are all your `parallelFns` completing?

**Comment by MrDHat** [comment]
Yes. All the functions complete.

Akshay Katyal
Co-founder, CTO
Strike | Know People Better
https://getstrike.co

**Comment by aearly** [comment]
It's impossible to debug further without knowing what your internal function is  doing.  I would guess there is something going wrong there.

**Comment by MrDHat** [comment]
The function is simple, it sends request to a third party api and returns the results.
That function works fine as I can successfully log the values of `res`
Everything works as expected till `console.log(res.length);` Only the callback is not called.

**Comment by aearly** [comment]
So you see the results of `console.log(res.length)` for each item in `arr`?  No more, no less?

**Comment by MrDHat** [comment]
Yes, exactly.

**Comment by aearly** [comment]
I tried this with the latest version of async:

```js
var async = require("async");

function _someInternalFunction(arg, callback) {
    setTimeout(function () {
        callback(null, [arg]);
    });
}

var arr = new Array(10);

var parallelFn = function (i, callback) {
    _someInternalFunction(i, function (err, res) {
        if (err) {
            return callback(err);
        } else {
            if (res && res.length > 0) {
                var items = res;
                for (var j = 0; j < items.length; j++) {
                    // Do something
                }
                console.log(res.length);
                return callback(null, res);
            } else {
                return callback('Error');
            }
        }
    });
};

var parallelFns = [];

for (var i=0; i<arr.length; i++) {
    parallelFns = parallelFns.concat(
        parallelFn.bind(null, i)
    );
}

async.parallel(parallelFns, function (err, results) {
    console.log(err, results);

});
```

It logged:

```
1
1
1
1
1
1
1
1
1
1
null [ [ 0 ], [ 1 ], [ 2 ], [ 3 ], [ 4 ], [ 5 ], [ 6 ], [ 7 ], [ 8 ], [ 9 ] ]
```

Seems to be working.  I bet the issue is in the implementation of `_someInternalFunction`.  It might be calling-back twice.

**Comment by kafka-tamura** [comment]
@MrDHat Were you able to solve this? If yes, how? Was the issue in the internal function as @aearly pointed out.

**Comment by MrDHat** [comment]
@kafka-tamura I don't remember the exact issue, but, as far as I remember, the issue was in the internal function.
