### ISSUE TITLE
Does the async.each() method return the array in the same order?

### ISSUE THREAD

**Issue by DaddyWarbucks** [caolan/async#939]
This may seem like a silly question but I want to ensure I understand it correctly. I understand that the iterator will obviously take a different amount of time per function in the array. But, is the returned array mapped in the initial order, or in the order in which the async callbacks were returned?

Thank you!!

**Comment by aearly** [comment]
`async.each` and family don't return arrays at all -- just an error if one occurred.  If you want to ensure the order of results a parallel fashion, use `async.map`.

**Comment by DaddyWarbucks** [comment]
Duh. Thank you. Sorry for the stupid question.
