### ISSUE TITLE
Make queue behavior easier to customize

### ISSUE THREAD

**Issue by adam-26** [caolan/async#947]
Hi, I have a use case with a queue where I check a condition in the queue task, and if the condition is not met I put the task back in the queue (this is a simplification). 

From a performance perspective, it would be much better if the tasks that failed the condition were not processed. However, currently it's very difficult to modify the behavior of the queue without accessing the async source.

I will submit a pull request that allows the queue behavior to be customized without needing to copy/paste snippets from the async source.

Let me know if you have any comments.

**Comment by aearly** [comment]
Would this accomplish what you want?

```js
var q = async.queue(function (task, callback) {
  if (matchesFailureCondition(task)) {
    requeue(task);
    return callback();
  }
  // process as normal...
}, concurrency);

function requeue(task) {
  q.push(task);
}
```

**Comment by adam-26** [comment]
No, I'm trying to avoid having to requeue items, it adds unecessary delay to pending tasks. For an example of what I'm wanting to do, see https://github.com/adam-26/async/commit/6ba827d757416ea6dbde21e501511140c400e7fb
