### ISSUE TITLE
move async-if-else to be part of async utils

### ISSUE THREAD

**Issue by diasdavid** [caolan/async#949]
Would there be interest to make [async-if-else](https://www.npmjs.com/package/async-if-else) one of the available async utils? @tdantas would be available to submit that PR :) //cc @alanshaw

**Comment by megawac** [comment]
If we decide to add something like t this, is prefer if we use the semantics of cond in scheme or ifElse in ramda

**Comment by aearly** [comment]
Historically, async (i.e. caolan) has been against adding conditional logic helpers.  In most cases, a basic `if`/`else` in the right place is good enough.

I've experimented with a `provided` method: https://www.npmjs.com/package/acomb#provided
Truth be told, I've never actually used it in production code, as `if`/`else` was good enough and more clear.

Using keywords as identifiers (e.g. `foo.if()`) also causes some JS engines to barf.

**Comment by aearly** [comment]
I think I'm happy keeping this in plugin-land.

**Comment by tdantas** [comment]
that would be great @aearly :) :+1:

**Comment by megawac** [comment]
Do we document plugins @aearly?

**Comment by aearly** [comment]
Nope, but we could create a list in the README of other async utils.

**Comment by diasdavid** [comment]
That would be great!
