### ISSUE TITLE
async-series failing on last function (prior to finish call)

### ISSUE THREAD

**Issue by xhh2a** [caolan/async#951]
```
async.series(
    [
      function(cb) {
        MX.register_super(MX.Core, 'DataManager_isDatabaseLoaded', DataManager.isDatabaseLoaded, cb);
      },
      function(cb) {
        MX.Core.override_load(cb);
      },
      function(cb) {
        MX.Core.load_classes(cb);
      }
    ],
    function(err) {
      if (err) {
        log.trace();
        log.error('An error occurred setting up MX Core System:', err);
      } else {
        log.info('MX Core: Loaded MX Core System. Initializing dependents');
        log.dir(MX.Core.Dependents);
        async.each(MX.Core.Dependents, function(mod, cb) {console.dir(mod); mod.setup(cb)});
      }
    }
  );
```
It runs through things fine until it returns from load_classes and calls the cb() and goes into:
```
// Similar to ES6's rest param (http://ariya.ofilabs.com/2013/03/es6-and-rest-parameter.html)
    // This accumulates the arguments passed into an array, after a given index.
    // From underscore.js (https://github.com/jashkenas/underscore/pull/2140).
    function _restParam(func, startIndex) {
        startIndex = startIndex == null ? func.length - 1 : +startIndex;
        return function() {
            var length = Math.max(arguments.length - startIndex, 0);
            var rest = Array(length);
            for (var index = 0; index < length; index++) {
                rest[index] = arguments[index + startIndex];
            }
            switch (startIndex) {
                case 0: return func.call(this, rest);
                case 1: return func.call(this, arguments[0], rest);
            }
            // Currently unused but handle cases outside of the switch statement:
            // var args = Array(startIndex + 1);
            // for (index = 0; index < startIndex; index++) {
            //     args[index] = arguments[index];
            // }
            // args[startIndex] = rest;
            // return func.apply(this, args);
        };
    }
```
It crashes in case 1 because arguments[0] is null.
```
arguments = Arguments[2], 0: null, 1: null, length:1 index: 1
rest = array[1]
```

What's weird is that if I move the order of functions around, async doesn't crash anymore (load_classes isn't dependent on override_load)

**Comment by aearly** [comment]
What environment are you running in?  `func.call(this, null, [])` should not crash.

**Comment by xhh2a** [comment]
Frontend browser ECMA5 js game engine running in Chromium.

**Comment by aearly** [comment]
Are you sure it's ES5?  The MX namespaces and `log.trace` seem like AS3/ES4.

Does it work if you nest your callbacks (e.g. don't use async.series)?

**Comment by xhh2a** [comment]
MX is the 'module' name (really global namespace since it's frontend and I haven't browserified that code yet). log.trace is from a library I'm using (it's a wrapper around console with the ability to set logging level). And yes I'm pretty sure unless node doesn't use ES5 (the core library the framework uses is pixi.js)

Async.each, eachSeries, and changing the ordering of the .series call works. It's a really weird bug that I have no idea what the root cause is.
```
    [
      function(cb) {
        MX.Core.load_classes(cb);
      },
      function(cb) {
        MX.register_super(MX.Core, 'DataManager_isDatabaseLoaded', DataManager.isDatabaseLoaded, cb);
      },
      function(cb) {
        MX.Core.override_load(cb);
      }
    ]
```

**Comment by aearly** [comment]
The problem is likely with one of those functions, especially if changing the order works.  It might be calling a callback twice or something similar.

**Comment by xhh2a** [comment]
That's what I first thought but I stepped with breakpoints (and there are many many trace statements in the functions) and the function finished without calling callback twice. Anyhow it works so I suppose it's not that important.

It might be some weirdness with the framework.

**Comment by rclayton-the-terrible** [comment]
Callback is being invoked more than once because the Newman is a singleton and it's state checks the number of iterations.  I too am getting a "callback executed more than once error" from Caolan's Async library, because on the second time running a collection, the internal state of Newman thinks it's already reached the max number of iterations.

**Comment by aearly** [comment]
In the next major release, we're going to warn on multiple callbacks.  We're not doing it now because it breaks some of our tests.
