### ISSUE TITLE
Final callback is called before all functions have completed

### ISSUE THREAD

**Issue by emmettnicholas** [caolan/async#953]
The docs for `parallel` state:

> callback(err, results) - An optional callback to run once all the functions have completed

But this is violated in the following example:

```javascript
var async = require('async');

async.parallel([
    function(next) {
        console.log('begin step 1');
        setTimeout(function() {
            console.log('end step 1');
            next();
        }, 1000);
    },
    function(next) {
        next(new Error('step 2 error'));
    }
], function(err, results) {
    console.log('final callback');
});
```

The log output is:

    begin step 1
    final callback
    end step 1

whereas I would expect:

    begin step 1
    end step 1
    final callback

**Comment by aearly** [comment]
Errors cause `parallel` to exit as soon as they are encountered.  This is expected behavior.

**Comment by emmettnicholas** [comment]
I realize the docs also state:

> If any of the functions pass an error to its callback, the main callback is immediately called with the value of the error.

But the above statement seems inconsistent with

> callback(err, results) - An optional callback to run once all the functions have completed

So it's likely a bug in the docs, not the code.

**Comment by emmettnicholas** [comment]
@aearly Thanks for the making the change so quickly, but https://github.com/caolan/async/commit/b0797ca40b102012b582d17e1825ae81731b15da is not adequate:

1. "An optional callback to run once all the functions have completed successfully." is not correct. Better would be: "An optional callback to run once all the functions have completed successfully _or_ any function passes an error to its callback".
2. `parallel` was just an example. This same docs fix should apply to all methods which run functions in parallel, e.g. `auto`, `each`, etc.

**Comment by emmettnicholas** [comment]
Also, perhaps we should consider re-opening this issue and labelling it as a feature request.

I think async control flow would be much easier to reason about if the final callback were always called _after_ all functions have completed, successfully or unsuccessfully. (No new functions would begin, but any already-started functions would have a chance to finish.)
