### ISSUE TITLE
Async queue empty vs drain

### ISSUE THREAD

**Issue by lucaswxp** [caolan/async#958]
Hey guys.

I read the docs, but don't quite get what "empty" actually means, what is the practical difference with drain?

I have a queue that I must be notified when it gets "satured" and also when it becomes "unsatured", is "empty" event what I'm looking for?

**Comment by aearly** [comment]
`empty` is called when the last item in the queue starts processing, whereas `drain` is called when that last item finishes processing.

There is also a proposal to add `unsaturated` callback when the queue goes from saturated to not-saturated: #869

**Comment by lucaswxp** [comment]
Got it, thanks!
