### ISSUE TITLE
Setting default final callback

### ISSUE THREAD

**Issue by peecky** [caolan/async#960]
Would you add a feature of overridable default final callback?

It is tired to specify same callback function whenever I use async.* functions, and sometimes I forget it.

I wish to change this kind of code

	function handleError(err) {
		if (err) logError(err);
	}

	async.waterfall([
	function(cb) {
		doSomething(cb);
	},
	function(result, cb) {
		doAnother(result, cb);
	}
	], errorHandling);

	async.eachSeries(arr, function(item, next) {
		doSomething2(item, next);
	}, errorHandling);

to this form.

	async.defaultCallback = function handleError(err) {
		if (err) logError(err);
	}

	async.waterfall([
	function(cb) {
		doSomething(cb);
	},
	function(result, cb) {
		doAnother(result, cb);
	}
	]);

	async.eachSeries(arr, function(item, next) {
		doSomething2(item, next);
	});

`function noop() {}` is used as a default final callback. But this cannot be overridden from outside of the library.

**Comment by aearly** [comment]
I don't really like this because it adds global state to async. For example, if a library used this feature, and then a project that used that library also used that feature, the default callback would conflict, causing the library to break.
