### ISSUE TITLE
What do you think `async.auto` order?

### ISSUE THREAD

**Issue by suguru03** [caolan/async#961]
The `addListener` which is in `async.auto` calls `Array#unshift` when the worker is not ready yet. So the waiting listeners are registered in reverse order. That's why the calling order is as follow.

```js
var delay = 10;
var order = [];
var tasks = {
  task1: function(callback) {
    order.push('task1');
    callback();
  },
  task2: ['task1', function(callback) {
    setTimeout(function() {
      order.push('task2');
      callback();
    }, delay * 2);
  }],
  task3: ['task1', function(callback) {
    setTimeout(function() {
      order.push('task3');
      callback();
    }, delay * 2);
  }],
  task4: ['task1', function(callback) {
    setTimeout(function() {
      order.push('task4');
      callback();
    }, delay * 1);
  }],
  task5: ['task1', function(callback) {
    setTimeout(function() {
      order.push('task5');
      callback();
    }, delay * 1);
  }],
  task6: ['task1', function(callback) {
    setTimeout(function() {
      order.push('task6');
      callback();
    }, delay * 1);
  }]
};
async.auto(tasks, 2, function(err) {
  if (err) {
    return done(err);
  }
  assert.deepEqual(order, [
    'task1',
    'task2',
    'task3',
    'task6',
    'task5',
    'task4'
  ]);
  done();
});
```
I think that the order should be `['task1', 'task2', 'task3', 'task4', 'task5', 'task6']`;
I know that the order is not guaranteed by ECMAScript but I think it should have same order of `Object.keys` order.
What do you think about it?

**Comment by aearly** [comment]
I'm not too concerned by this.  One of the reasons to use `auto` is when you don't care about the exact order, just that dependent tasks start after their dependencies.  On the other hand, `push` seems more logical than `unshift`, but there might be some bugs that arise from changing it, after a quick glance at the code.

**Comment by suguru03** [comment]
> I'm not too concerned by this. One of the reasons to use auto is when you don't care about the exact order, just that dependent tasks start after their dependencies.

That's right! I agree.

> On the other hand, push seems more logical than unshift, but there might be some bugs that arise from changing it

If I find something which might be bugs, I'll submit a issue.

Thanks.
