### ISSUE TITLE
wait for 2 callback to move on

### ISSUE THREAD

**Issue by guypaskar** [caolan/async#965]
consider the following scenario:
Async that calls a function that has 2 async functions inside.
I want to move on only when both functions return the callback. Is it possible?

```
async.each([arr,function(report,callback){
  foo();
},endCallback);

function foo(){

  FunctionA() //does something async we need to wait for
  FunctionB() //does something async we need to wait for

}
```

**Comment by aearly** [comment]
You can use `async.series` inside `foo()` to combine the two  together.  Just make sure that `foo` takes in and calls a callback.  You also might be able to use `waterfall` or `seq` depending on how related `FunctionA` and `FunctionB` are.
