### ISSUE TITLE
whilst not calling callback with extra parameters

### ISSUE THREAD

**Issue by dmorrow** [caolan/async#967]
The sample code for whilst seems to state that you can add extra params to the callback.  However, that sample code no longer seems to work, and the method being called seems to be `callback(null)`
https://github.com/caolan/async#whilst
```
function (err, n) {
   // 5 seconds have passed, n = 5
}
```

**Comment by aearly** [comment]
Sorry, we just added this in #963, but haven't published a new version.

**Comment by tiffanyandco** [comment]
Thanks @aearly - when do you expect that you'll publish the updates to npm?

**Comment by aearly** [comment]
Within a week.

**Comment by vsinha** [comment]
any updates on this? :speak_no_evil:

**Comment by shaikatzir** [comment]
+1

**Comment by aearly** [comment]
Sorry, been really busy.  It'll be at least another week :(

**Comment by shaikatzir** [comment]
Maybe Just update the Readme for now?

**Comment by lionvs** [comment]
+1

**Comment by garas1** [comment]
+1

**Comment by xQuai** [comment]
+1

**Comment by aearly** [comment]
1.5.1 released!
