### ISSUE TITLE
each and eachSeries not passing back values to results array - why?

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#969]
This is probably my misunderstanding, but there's a small chance of a bug

```javascript

async.each([1,2,3], function(value,cb){
    setTimeout(function(){
        cb(null,value);
    },200);

},function complete(err, results) {
    console.log(err,results);  //results is undefined here, err is null
});


async.eachSeries([1,2,3], function(value,cb){
    setTimeout(function(){
        cb(null,value);
    },200);

},function complete(err, results) {
    console.log(err,results); //results is undefined here, err is null as expected
});
```

for the async.series and async.parallel apis, we have the results argument being populated as an array, but with async.each and async.eachSeries, this does not seem to be the case.

is there something I am missing?

thanks!

**Comment by ex1st** [comment]
> is there something I am missing?
Yes - async.map

**Comment by ex1st** [comment]
You need use async.map for passing result

**Comment by aearly** [comment]
:arrow_up: What he said.  `each` is just for control flow, `map` is for gathering the results.

**Comment by ORESoftware** [comment]
thanks

async.mapSeries is working for me
