### ISSUE TITLE
fs.exists is bad example for docs

### ISSUE THREAD

**Issue by ex1st** [caolan/async#972]
> https://nodejs.org/dist/v4.2.2/docs/api/fs.html#fs_fs_exists_path_callback
> Stability: 0 - Deprecated: Use fs.stat or fs.access instead.

Now all async functions without error in callback are deprecated (node.js). Need to change examples.
I also suggest change methods like `filter` and `reject` in `2.0` for consistency with node.js practics.

```javascript
async.filter(['file1','file2','file3'], function (file, cb) { 
    fs.stat(file, function(err, stat){
        cb(null, !err);
    });
}, function (err, results) {
    // results now equals an array of the existing files
});
```

What do you think?

**Comment by aearly** [comment]
We're going to change how these functions work in the next major release: #118 .  As they exist today, `fs.exists` is just about the only function that's useful for these methods.

**Comment by ex1st** [comment]
Ok, thanks.
