### ISSUE TITLE
.series() or any async type function gives weird warning with RethinkDB

### ISSUE THREAD

**Issue by ChrisCates** [caolan/async#974]
```
Warning: a promise was created in a  handler but was not returned from it
    at Term.run (/Users/chriscates/projects/CodeMedium/node_modules/rethinkdbdash/lib/term.js:142:15)
    at /Users/chriscates/projects/CodeMedium/backend/init_db.js:23:10
    at /Users/chriscates/projects/CodeMedium/node_modules/async/lib/async.js:713:13
    at iterate (/Users/chriscates/projects/CodeMedium/node_modules/async/lib/async.js:262:13)
    at /Users/chriscates/projects/CodeMedium/node_modules/async/lib/async.js:274:29
    at /Users/chriscates/projects/CodeMedium/node_modules/async/lib/async.js:44:16
    at /Users/chriscates/projects/CodeMedium/node_modules/async/lib/async.js:718:17
    at /Users/chriscates/projects/CodeMedium/node_modules/async/lib/async.js:167:37
    at /Users/chriscates/projects/CodeMedium/backend/init_db.js:17:13
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Any clue as to what's happening?
This is the function  running in `init_db.js`
```
async.series([
    function(finished) {
      r.dbList().contains('codemedium')
        .run()
        .then(function(dbExists) {
          if (dbExists == false) {
            r.dbCreate('codemedium')
              .run()
              .then(function() {
                finished(null, 'success');
              })
              .error(function(err) {
                finished(err);
              });
          } else {
            finished(null, 'success');
          }
        })
    },
```

**Comment by Chris-Cates** [comment]
Packages involved:
`rethinkdbdash`
`async`

**Comment by aearly** [comment]
Hard to say, without knowing how the rethinkDB module works.  Does that function work properly outside of `async.series`?

One wierd thing I see is `.then(...).error(...)`.  Usually with promises, isn't it `.then(...).catch(...)`?

**Comment by Chris-Cates** [comment]
@aearly Works like a charm without `async.series`... Would like some feedback ASAP. :8ball:

**Comment by Chris-Cates** [comment]
@aearly Also, the `async.series` function seems to run perfectly fine. But gives that funky error anyway.

**Comment by daamdaam** [comment]
@ChrisCates Any joy on that one, as i too face a similar issue with an async.series..

cheers

**Comment by aearly** [comment]
I think the error is telling you all you need to know.  Just add a `return` to the  `r.dbCreate('codemedium')` line and the warning should go away.  It doesn't matter (i.e. still works) because the promise is handled through the series callback.

**Comment by ChrisCates** [comment]
Uhh @aearly I've tried that and it still didn't work.

I've semi-resolved the issue by setting `process.env.BLUEBIRD_DEBUG` to `0`... I would prefer to not emit these issues though.

**Comment by aearly** [comment]
Any particular reason you're using async.series?  You could just use bluebird to chain a series of promises.

**Comment by ChrisCates** [comment]
Once again, it doesn't matter if it's bluebird or async... The issue still arises...

I've posted tickets in RethinkDBDash... But not yet Bluebird.

I did make one in Bluebird... But I can easily refactor this same code to Bluebird.

**Comment by ex1st** [comment]
https://github.com/neumino/rethinkdbdash/commit/961853f0a4c61b635d82412bf8dbb23fca6798be

May be this fix need to apply to https://github.com/neumino/rethinkdbdash/blob/master/lib/term.js#L142
