### ISSUE TITLE
Need a logo!

### ISSUE THREAD

**Issue by Kikobeats** [caolan/async#975]
I was checking [nodejs logo issue](https://github.com/nodejs/node/issues/37) that have very nice ideas from the community.

Why not create a logo that identify async library? 💪

**Comment by aearly** [comment]
It's hard to say, async is  such an abstract concept.

Through years of exposure, I've come to subconsciously associate async with @caolan 's face. :smile:

**Comment by jdalton** [comment]
Async started as a branch of Underscore. And both Underscore and Lodash have `_` in their logos:
<table>
<tr>
<td>
<img width=50% src=https://cloud.githubusercontent.com/assets/4303/13719504/7f43914a-e7ab-11e5-8697-24785259ec89.png>
</td>
<td>
<img width=50% src=https://cloud.githubusercontent.com/assets/4303/13719511/acc55a4a-e7ab-11e5-8cba-7760bd0f957e.png>
</td>
<tr>
</table>
Maybe async could be an ellipsis `…`

**Comment by aearly** [comment]
I think of something like a sequence diagram.  Maybe this could be stylized more:

![async](https://cloud.githubusercontent.com/assets/558190/13720016/b267da10-e7b3-11e5-8963-6e3d74983af5.png)

**Comment by Kikobeats** [comment]
Please artists contributors check this :-)

**Comment by crispen-smith** [comment]
Didn't we all agree (I mean the community at large) that logos are basically the worst type of bike shedding?   It's Asynch, it does exactly what it says on the tin and it does it well. Does it need a logo to represent that?

If it really does, then a nice jpg of the name set in Helvetica is probably sufficient, maybe underscore it.

**Comment by aearly** [comment]
I liked the old iojs logo thread strategy last year.  Just create a thread with a bajillion logo ideas, and see which one ends up printed on the most stickers.

**Comment by olizilla** [comment]
https://github.com/substack/hex-grid/blob/master/example/images/async.png

**Comment by jjhesk** [comment]
![iscp_icon_staged_routing_information_flow](https://cloud.githubusercontent.com/assets/629338/14675941/f16e2350-073d-11e6-92b4-2881362a6e65.png)
![iscp_icon_partitioned_routing_information_flow](https://cloud.githubusercontent.com/assets/629338/14675942/f1773f44-073d-11e6-8749-7d1b8760c0e1.png)
![iscp_icon_buffered_routing_flow](https://cloud.githubusercontent.com/assets/629338/14675943/f1777950-073d-11e6-8079-9d71d2ee227f.png)

**Comment by jjhesk** [comment]
![advanced_power_machines](https://cloud.githubusercontent.com/assets/629338/14675979/14b415e0-073e-11e6-844a-23133e7c14d3.png)
![seat_flow](https://cloud.githubusercontent.com/assets/629338/14675978/14b3ff24-073e-11e6-9de5-cd15e7435add.png)
![subflowreuse](https://cloud.githubusercontent.com/assets/629338/14675980/14b557ac-073e-11e6-8934-7c967b608d41.png)

some more ideas.

**Comment by bOvOd** [comment]
why not something like

`>|`

because you can straighten your callbacks with async, you could visualize nested callbacks `>` and your straightened ones `|`. If you like, you can also interpret it as "going simple".

**Comment by ivanseidel** [comment]
![async-01](https://cloud.githubusercontent.com/assets/3102127/16169755/ef740b1e-350f-11e6-9aff-ac943a14915d.png)

I did some sketches.. Is it something like this?

**Comment by Kikobeats** [comment]
@ivanseidel awesome

**Comment by megawac** [comment]
Sweet, I really like the 3rd one

**Comment by ivanseidel** [comment]
Thanks! If you guys like it, I can work on improving the 3rd a bit more

**Comment by Gorzas** [comment]
Great logos @ivanseidel. I prefer the third one, it's great :D

**Comment by aearly** [comment]
The 3rd one is great.  I also like the first square logo -- would be good for a favicon or other smaller logo.

The only critique I have is that the "a" looks a bit weird.  The perfect circle looks odd compared to the square shape.

**Comment by piranna** [comment]
Third one for me too :-D

> The only critique I have is that the "a" looks a bit weird. The perfect circle looks odd compared to the square shape.

Yes, maybe better replace the circle in the `a` with a semicicle, so it could mimic better conditional `if` as they are shown in flowcharts :-)

**Comment by ivanseidel** [comment]
A few A's options...
![async_as](https://cloud.githubusercontent.com/assets/3102127/16269429/965ff07c-3868-11e6-8e3a-d8c1ccfcd6da.png)

**Comment by piranna** [comment]
I was thinking about 2D with an open or closed horizontal termination, similat to the ones of 3A and 3B.

**Comment by aearly** [comment]
I like 2A and 2C the best.  What does the logo look like at smaller sizes?  Might need thicker lines when it is smaller.

**Comment by megawac** [comment]
I think 2a/2b with 3c's gap would look great. Otherwise I like 2b-2d.

**Comment by ivanseidel** [comment]
So, here is the final version (I took 2A as "a" by some sort of voting from the comments). 

About the Icon, depending on the size (for generating an Favicon), we can tick the line a bit more of the outer-box, that shouldn't be a problem...

Should I change the `README` and also include the graphics in EPS in the github so that everyone can use/modify it later?
![async_final](https://cloud.githubusercontent.com/assets/3102127/16458457/8305c6ea-3df5-11e6-9591-e4a20aa65ed8.png)

**Comment by megawac** [comment]
> Should I change the README?

Yeah, send a pull request adding the logo and icons. put them in a `/logo` folder

 and also include the graphics in EPS in the github so that everyone can use/modify it later?

How big is the EPS? might make sense to keep separate depending on size

**Comment by piranna** [comment]
> How big is the EPS? might make sense to keep separate depending on size

It would be just enough by adding it to the `.npmignore` file, so they don't get uploaded to npm repository (nor downloaded when doing `npm install` afterwards...)..

**Comment by ivanseidel** [comment]
[ ] Put both `.AI` and `.EPS` in `/logo`.
[ ] Add logo to the `Readme`
[ ] Add `.npmignore` to `/logo` folder/files
[ ] Generate Favicon for the site ( #1202 )
[ ] Be happy

**Comment by ivanseidel** [comment]
There we go: [ivanseidel/async](https://github.com/ivanseidel/async)

If all is ok, I will swap the readme header url to `caolan`. @piranna @megawac

**Comment by megawac** [comment]
Looks good to me, send a pull request and lets be happy

**Comment by ivanseidel** [comment]
@megawac Everything is just fine to merge: #1203
