### ISSUE TITLE
semi-awkward API for async.waterfall

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#981]
Been using this API for awhile and I have a junior developer who is working with an old project that I wrote original. In looking at the old code I realize that async.waterfall is kind of awkward:

the API as is:
```js
async.waterfall([
    function(callback) {
        callback(null, 'one', 'two');
    },
    function(arg1, arg2, callback) {
      // arg1 now equals 'one' and arg2 now equals 'two'
        callback(null, 'three');
    },
    function(arg1, callback) {
        // arg1 now equals 'three'
        callback(null, 'done');
    }
], function (err, result) {
 
});
```

would it not be much easier to use like so:

```js
async.waterfall([
    function(callback) {
        callback(null, {
          one:'one',
          two:'two'
       });
    },
    function(arg, callback) {
        callback(null, 'three');
    },
    function(arg, callback) {
        callback(null, 'done');
    }
], function (err, result) {
   
});
```

is there something like this in the async API?

async.waterfall_defunk ?

**Comment by aearly** [comment]
It's entirely up to you, the user or waterfall, whether or not to callback with one or multiple values.  You can wrap them in an object, or pass them individually, but the next step in waterfall will always be passed-in the same number of arguments as the number previous function passes to the callback.

This is a pretty key feature, I don't think it needs changing.

**Comment by ORESoftware** [comment]
yeah you're right, I was being stupid, you can just pass in one argument, it's up to you as the user of the lib, my bad
