### ISSUE TITLE
strongly request add interval setting for all Api

### ISSUE THREAD

**Issue by xxxman2008** [caolan/async#982]
Hi,

 I know Async is so popular, so famous.
But many Async's api  have no interval between function calls .. Last two days ,i spend whole time to find  why "max call stack size exceeded" .

I used  Async.until to check some conditions  satisfied function running. And used it much times in my code. And then ....process crashed with "max call stack size exceeded".

Finally ,i changed  to Async.retry ,..Then without any crash.

I strongly advised add "interval" setting for all other Api for stable running.

Raymond

**Comment by ex1st** [comment]
Please read https://github.com/caolan/async#synchronous-iteration-functions

**Comment by xxxman2008** [comment]
Ok ,thank you ...my mistake ..:-)
