### ISSUE TITLE
Async parallel max tasks

### ISSUE THREAD

**Issue by nvartolomei** [caolan/async#985]
Is there any limit on how many async tasks can run at the same time? What if I kick 10 000 tasks at the same time?

Regards

**Comment by gr2m** [comment]
@nvartolomei yes, there is the `concurrency` option for [async.auto](https://github.com/caolan/async#autotasks-concurrency-callback)

and for most of the other methods, there are the `<name>Limit` methods. It says it right on top of [Documentation](https://github.com/caolan/async#documentation):

> <name>Limit - the same as <name> but runs a maximum of limit async operations at a time

**Comment by nvartolomei** [comment]
The question was if there is any technical limits on maximum parallel task, can I throw in 10 000 tasks?

**Comment by gr2m** [comment]
yes you can, JavaScript is decent with concurrency

**Comment by ex1st** [comment]
@nvartolomei

4,294,967,295 (4.29 billion) - max size of Array in javascript (need for accumulation of results). The only one limit (except memory).

**Comment by aearly** [comment]
There's no official limit, but realize that the set up for each task (before any async I/O) is still processed sequentially.  I wouldn't want to kick off 10,000  tasks simultaneously.
