### ISSUE TITLE
queue drain

### ISSUE THREAD

**Issue by KevinBurton** [caolan/async#986]
I am pushing items onto a queue like:

    self.q.push(tables, function(err) {

and then defining 

    self.q.drain = function(err) {
        callback(err);
    };

But it seems that drain is never called. What do you think I am doing wrong? Under what conditions will drain get called?

Thank you.

**Comment by KevinBurton** [comment]
One more piece of information. I am using Node.js fs to write to a file. I am using asychronous methods in the 'worker'. Is that not allowed? Could this be contributing to my problem?

Thanks again.

**Comment by aearly** [comment]
Drain is called when the last item in the queue finishes processing. E.g. when a worker finishes and the queue size is 0.

asyncronous methods are totally allowed.  It's hard to say what's going wrong without seeing more code.

**Comment by KevinBurton** [comment]
That is what I was expecting, but it doesn't seem to be happening. I will post a full listing of code tomorrow. I was also expecting a callback for each processed task and that is also not happening. Is the decision that the task is "done" based on the calls to the callback or the return? If I have asynchronous methods in "queue" method and they don't call their callback right away won't the just fall through and eventually cause a return from the "queue" function? Thank you for helping me understand this library.

**Comment by KevinBurton** [comment]
As promised here is the code I am using. The idea is to pass in an array of strings representing the names of tables. The first part of the process is to query the database regarding schema information on the table then write the information out to a file. So as  you can see from the source there are several points that are asynchronous. One, when making the query. Two, when opening the file. Three, when writing to the file. And finally when the file is closed.

function writeSchema(tables, callback) {
    var self = this;
    self.q = async.queue(function(item, schemaCallback) {
        var query = 'select \'' + item + '\' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH,' +
            'NUMERIC_PRECISION, DATETIME_PRECISION,' +
            'IS_NULLABLE' +
            ' from EForms.INFORMATION_SCHEMA.COLUMNS' +
            ' where TABLE_NAME=\'' + item + '\'';
        self.request = new sql.Request();
        self.request.query(query, function(err, recordsets) {
            if(err) {
                return schemaCallback(err);
            } else if(recordsets && recordsets.length > 0) {
                fs.open(recordsets[0].TableName + '.txt', 'w', function(err, fd) {
                    if(!err) {
                        recordsets.forEach(function(e, i, a) {
                            fs.write(fd, 'var ' + e.COLUMN_NAME + ' = \'\';\r\n', function(err, written, buffer) {
                                if(err) {
                                    return console.log(err);
                                }
                            });
                        });
                        fs.close(fd, function(err) {
                            return schemaCallback(err);
                        });
                    } else {
                        return schemaCallback(err);
                    }
                });
            }
        });
    }, 4);
    self.q.drain = function(err) {
        callback(err);
    };
    self.q.push(tables, function(err) {
        if(err) {
            console.error(('Schema: ' + err.message));
            //console.error(err.stack)
            if(!self.q.paused) {
                self.q.pause();
                callback(err);
            }
        }
    });
}

To manage the 'this' the routine is called like:

    writeSchema.call(writeSchema, tables, function(err) {
        if(err) console.log(err);
    });

Ideas as to why when I set a breakpoint either on the 'push' or in the drain it is never hit?

Thank you.

**Comment by aearly** [comment]
There's no plain `else` clause after `} else if(recordsets && recordsets.length > 0) {`.  If you get an empty result, the no callback will be called, and the task will never be considered complete.

**Comment by KevinBurton** [comment]
One more question. I have the following code for handling the queue.
```
    var q = async.queue(function(item, callback) {
        db.query(item, params, function(err, results) {
            if(err) {
                return callback(err);
            } else {
                return callback();
            }
        });
    }, 4);
```
It doesn't seem that return circumvents every item being processed. If there is an error I would like to flush the items in the queue avoiding having the same error hundreds of times. Is that possible?

**Comment by aearly** [comment]
`q.kill()` will empty the queue and stop execution of further tasks.

**Comment by amitdhawan** [comment]
return callback(); should be callback();  only. No return

**Comment by olragon** [comment]
Spend >2 hours debug this issues,  if it's happen to you, just add

```js
// magic here
q.empty = function () {
  // don't known why it's work
}
q.drain = function () {
  // it's work!
}
```

**Comment by onkea** [comment]
I've having a different issue. For me, the drain is running too soon, almost as soon as the code starts to execute:

var dnsQueue = async.queue(function(domain, lookupAgain) {
  setTimeout(
    function() {
        
        dns.resolve(domain, function (err, address) 
        {
            dnsArray.push({domain: domain, address: address});
            console.log('domain: ' + domain + " address: " + address)

        }
        
        );
        lookupAgain();


    }, MaxWait);
}, MaxConcurrent);


// All results are now finished?
dnsQueue.drain = function() {
    console.log('done??');
//
}

**Comment by olragon** [comment]
@onkea your code call `lookupAgain()` immediately after first queue execute.

**Comment by onkea** [comment]
Thanks @olragon, I just tried moving the lookupAgain() call to the top 
var dnsQueue = async.queue(function(domain, lookupAgain) {
    lookupAgain();
But it still seems to be running the drain function right away.
