### ISSUE TITLE
add version to library that try catch errors

### ISSUE THREAD

**Issue by lugog** [caolan/async#995]
It would be cool if there was a version of functions in this library that supported try catch for the error callback. When a javascript exception happens instead of crashing node it calls the callback with the error. Maybe seriesEx, parallelEx.   

Ex.
```javascript
asyncLib.series([
        //new feature -- in the library before calling this wrap with try/catch, call callback with exception
        function(asyncCallback) { 
            console.log( arrayDoesntExist[0] );  // <--- error takes down server!
        },
    ],
    function(err) {
        if ( err ) {
            callback( err );
        }

        callback(null);
    });
```

**Comment by aearly** [comment]
This would be nice, if it were possible.  There's no good way to catch asynchronous errors.  There is `process.on("uncaughtException")`, but it is global, making it hard to link to the source, especially  when there are parallel tasks running.

**Comment by lugog** [comment]
I think it is possible. Global exception handlers are terrible! You might as well restart your node app if you are going to trap a global exception handler. Here is how I think it would work. 
```javascript
async.iterator = function (tasks) {
        function makeCallback(index) {
            function fn() {
                if (tasks.length) {
                    try { //catch exceptions in steps in any loop type in the library because this is in iterator!
                         tasks[index].apply(null, arguments); 
                   } catch ( err ) {
                          //do the default callback here!
                          arguments( err ); //this may or may not work in every situation, but the jist is it is calling the error callback on behalf of the function that crashed
                    }
                }
                return fn.next();
            }
            fn.next = function () {
                return (index < tasks.length - 1) ? makeCallback(index + 1): null;
            };
            return fn;
        }
        return makeCallback(0);
    };
```

**Comment by aearly** [comment]
That was discussed in #396 in depth.  The general gist of it is that errors thrown in the callback chain will be caught by the wrong task.

Unfortunately, it means you have to architect your node apps such that they can handle a crashed process due to an unforeseen exception.

**Comment by lugog** [comment]
@aearly  I read through a lot of that thread. I believe it is possible and I'd still vote for the work to be done, but understand there are some challenges to get it to work. Thanks for your response!
